### ISSUE TITLE
"Members" page can't open 

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2434] opened 2019-06-07 18:03 UTC
### Reproduction Steps: ###

1.Open https://test-community-app.topcoder-dev.com/challenges
2. Login with account: dan_developer/dantopcoder123
2. Try to open Me page with url: https://test-community-app.topcoder-dev.com/settings/profile
3. Click on arrow beside avatar 
4. Click on "Image avatar" and observe page

### Expected Result: ###
"Members" page open correctly.

### Actual Result: ###
URL is changed to "Members" but Content still stay "Settings" page.

### Screenshots or screencast: ###

See comment

### Browser Information: ###

Google Chrome 74.0 on desktop window 10

**Comment by HongHT** [comment] 2019-06-07 18:47
![4](https://user-images.githubusercontent.com/26895101/59126450-558ad000-898f-11e9-8531-a1b41e4b3855.png)

**Comment by nithyaasworld** [comment] 2019-06-10 19:06
@luizrrodrigues Please confirm if we are covering this as part of any other bug. Thanks.

**Comment by luizrrodrigues** [comment] 2019-06-10 19:32
@nithyaasworld this is duplication of #2395

**Comment by luizrrodrigues** [comment] 2019-06-10 19:33
Duplicate of #2395

**Closed** 2019-06-10 19:38 UTC
Labels: Bug Hunt, Navigation
