### ISSUE TITLE
Topcoder icon(logo) is clickable but user is not redirected on clicking

### ISSUE THREAD

**Issue by VaishaliSanthosh** [topcoder-platform/community-app#2577] opened 2019-06-08 09:25 UTC
**Describe the bug**
Topcoder icon(logo) is clickable but user is not redirected on clicking

**To Reproduce**
1. Go to https://test-community-app.topcoder-dev.com/challenges
2. Click on topcoder icon on the top left corner
3. No redirection

**Expected behavior**
Either the icon should not be clickable or user should be redirected on click.

**Screenshots**
![image](https://user-images.githubusercontent.com/29533254/59145134-6eca6580-89fd-11e9-8445-595aaf2c81e5.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser Chrome
Version 75.0.3770.80

**Additional context**

**Comment by nithyaasworld** [comment] 2019-06-10 18:00
Duplicate of https://github.com/topcoder-platform/community-app/issues/2496

**Closed by nithyaasworld** 2019-06-10 18:00 UTC
Labels: Bug Hunt, Navigation
