### ISSUE TITLE
[$25]My Dashboard: My communities -  challenge count and Purse cash is not displayed

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4461] opened 2020-06-03 13:47 UTC
v4 url: https://www.topcoder.com/my-dashboard
v5 url: https://beta-community-app.topcoder.com/my-dashboard

Challenge count and Purse cash is not retrieved for sub communities. Please compare comcast community data in the screenshots.

<img width="1440" alt="Screenshot 2020-06-03 at 7 10 05 PM" src="https://user-images.githubusercontent.com/58783823/83643910-46545780-a5ce-11ea-843b-51a14017966d.png">

<img width="1440" alt="Screenshot 2020-06
-03 at 7 09 59 PM" src="https://user-images.githubusercontent.com/58783823/83643888-3ccaef80-a5ce-11ea-8037-e0fc5b8404e9.png">

@sushilshinde, user will need to be added to comcast/topgear community on prod to view this. We are not able to see communities in dev backend (as groups api updates are in dev)

**Comment by sushilshinde** [comment] 2020-06-06 10:16
@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup

Submit in 8 hours and PR to

https://github.com/topcoder-platform/community-app/tree/integration-v5-challenge-api
https://github.com/topcoder-platform/topcoder-react-lib/tree/integration-v5-challenge-api

run `npm run test` before PR

**Comment by crazyk07** [comment] 2020-06-06 10:17
Contest https://www.topcoder.com/challenges/30128535 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-06-06 10:41
Contest https://www.topcoder.com/challenges/30128535 has been updated - it has been assigned to Narekvar90.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by narekcat** [comment] 2020-06-06 18:50
@SathyaJayabal @sushilshinde I have tried to fix issue using develop beck-end, but couldn't, because I am not a member of comcast/topgear community. How can I connect to that community ?

**Comment by narekcat** [comment] 2020-06-07 08:05
@SathyaJayabal @sushilshinde Can you add me to the comcast/topgear community ?

**Comment by sushilshinde** [comment] 2020-06-07 08:06
Use dan developer user on dev

**Comment by narekcat** [comment] 2020-06-07 08:26
@sushilshinde I have tried to use dan_developer on dev, but the problem is that there are no challenges in groups, where dan_developer is a member.

**Comment by sushilshinde** [comment] 2020-06-07 08:27
Ok let me get approval to add you to the Comcast group

**Comment by narekcat** [comment] 2020-06-07 08:28
@sushilshinde Ok, my topcoder handle is Narekvar90.

**Comment by sushilshinde** [comment] 2020-06-07 08:29
Ok thanks

**Comment by Oanh-and-only-Oanh** [comment] 2020-06-07 14:01
Is dan developer not part of Comcast group? We can add that user to the group.

**Comment by narekcat** [comment] 2020-06-07 14:05
@Oanh-and-only-Oanh No, dan_developer isn't Comcast group member. If we add dan_developer to Comcast group, then we also need to create new challenges in that group in dev beck-end.

**Comment by mtwomey** [comment] 2020-06-07 20:50
@sushilshinde It's fine to add him to that group. It's also fine to add Dan_Developer.

**Comment by narekcat** [comment] 2020-06-08 07:42
@sushilshinde Can you add me or dan_developer to comcast group ?

**Comment by sushilshinde** [comment] 2020-06-08 07:53
@narekcat please test, you should be part of the group.

You if you are running in the prod mode

1. go to localhost:3000
2.  Search for `Comcast Community` link
3. Navigate from here for each change.

**Comment by narekcat** [comment] 2020-06-08 07:54
@sushilshinde Ok, thank you.

**Comment by sushilshinde** [comment] 2020-06-08 07:55
and on dev dan_developer is already for Comcast group (dev env)

**Comment by narekcat** [comment] 2020-06-08 08:01
Ok, thanks.

**Comment by sushilshinde** [comment] 2020-06-09 08:47
Update on this @narekcat ?

**Comment by narekcat** [comment] 2020-06-09 11:13
@sushilshinde I have spend more then 8 hours, yesterday, but still can't fix it. The problem is with groups api. If you give me more time, I'll try fix it in next 4 hours.

**Comment by sushilshinde** [comment] 2020-06-09 11:15
Sure

In cases please add status in the issue comments

Communication is important

Find me on Topcoder community slack

**Comment by narekcat** [comment] 2020-06-09 11:19
@sushilshinde Ok. Thank you.

**Comment by narekcat** [comment] 2020-06-09 17:53
@sushilshinde I need to do change api version from v3 to v5, when getting user groups (https://github.com/topcoder-platform/topcoder-react-lib/blob/integration-v5-challenge-api/src/actions/auth.js#L19). There are pull request https://github.com/topcoder-platform/topcoder-react-lib/pull/152, this pull request contains the changes that I need. Can you merge this pull request ? Need I create new pull request with api version changes ?

**Comment by narekcat** [comment] 2020-06-11 17:39
@sushilshinde @SathyaJayabal I have a problem with this request community-app.topcoder-dev.com/community-app-assets/api/tc-communities?groups%5B0%5D=c7fcf1b8-a0f7-4efe-8aba-e6337eec85b4&groups%5B1%5D=72a0b8a0-aa45-44f7-86c2-bf9de6321e5b&groups%5B2%5D=32ff09a8-ffcd-438c-91c5-1e3423519549&groups%5B3%5D=b42e4f94-c168-4fa6-8ac7-08e33a7d9f41&groups%5B4%5D=b8fe66cc-935f-4986-a1cf-5e1dee943e8a&groups%5B5%5D=53eddd4a-e554-48e9-8fd4-b57406008b76&groups%5B6%5D=cadc4f45-ecc6-46dc-ae99-ee37418e1e89&groups%5B7%5D=713a5be0-48b1-44dd-94fe-f3d9a94209f1&groups%5B8%5D=96855169-cf5e-46f1-979e-de5175ae9b2d&groups%5B9%5D=717f514d-f375-4e25-aff9-07d2af3052e2&groups%5B10%5D=b487df20-afab-406a-a474-97d538b0cb34&groups%5B11%5D=45d364b0-136f-4be3-9a2f-3538b52ac89b&groups%5B12%5D=b467e239-ed75-4719-9f8b-97014e08a730&groups%5B13%5D=5cb8e5cd-a4b5-4c3f-97a6-8be6304b7c64&groups%5B14%5D=b4a704a2-14bf-42ae-97ee-eeb51049a3ad&groups%5B15%5D=a391c9ae-66a0-4e02-af6a-970c8b6cb290&groups%5B16%5D=f07038c8-c860-45ea-a2b9-e21c08e816f0
It returns group filters with old group ids. How can I get new V5 groups filters ?

**Comment by sushilshinde** [comment] 2020-06-14 09:00
@rootelement need help here

Groups API doesn't support UUIDs and resources API doesn't return legacy IDS. It will be very latent to call for each.

**Comment by sushilshinde** [comment] 2020-06-14 10:24
@narekcat please include changes from the https://github.com/topcoder-platform/topcoder-react-lib/pull/152 in your work.

**Comment by narekcat** [comment] 2020-06-14 10:29
@sushilshinde Ok.

**Comment by narekcat** [comment] 2020-08-31 13:21
@SathyaJayabal @sushilshinde I have tested this issue again and it works as expected. See screanshot:
![image](https://user-images.githubusercontent.com/11549629/91724405-55877900-ebae-11ea-8629-56d5cbe710a7.png)

**Comment by SathyaJayabal** [comment] 2020-09-01 11:21
verified on staging (develop branch)
<img width="1440" alt="Screenshot 2020-09-01 at 4 50 53 PM" src="https://user-images.githubusercontent.com/58783823/91843454-62ba6b80-ec73-11ea-9bf5-cd4650e2db1b.png">

**Comment by SathyaJayabal** [comment] 2020-09-01 12:07
The challenge count and purse cash only includes challenges the user is registered to. It should include all challenges

**Comment by SathyaJayabal** [comment] 2020-09-03 04:18
This issue seems to be fixed on production
<img width="1440" alt="Screenshot 2020-09-03 at 9 45 10 AM" src="https://user-images.githubusercontent.com/58783823/92070709-73312a00-edca-11ea-97df-0f65b6d4a1d3.png">

**Comment by crazyk07** [comment] 2020-09-03 04:18
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-09-03 04:19
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30128535<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed** 2020-09-03 04:18 UTC
Labels: Beta Env, Dashboard, P3, QA Pass, tcx_Assigned, tcx_FixAccepted, v5-intgration-sub-code
