### ISSUE TITLE
[$50]Submission Page issue

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/community-app#1775] opened 2018-11-30 10:14 UTC
**Describe the bug**
Community specific users when land to public domain topcoder.com for submission, the submission page keeps on showing a revolving circle instead of space for uploading the .zip submission.

**To Reproduce**
1. Go to 'https://www.topcoder.com/challenges/30074795/submit'
2. You'll see a revolving circle in place of space for browsing the .zip file for submission.
Note : This is specific to users from private community when they try to land on the submission page via public domain.

**Expected behavior**
Since the system knows weather the user is a private community member or public community member , the submission page should either redirect the user to community specific submission page or allow him to upload the submission from public domain as well.

**Screenshots**
![submissionerror](https://user-images.githubusercontent.com/45197181/49283044-af797d00-f4b6-11e8-8d6e-14044d0eb384.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Google Chrome]
 - Version [70.0.3538.102]

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by RiteshTC** [comment] 2018-11-30 10:15
@cwdcwd @sushilshinde

**Comment by sushilshinde** [comment] 2018-12-03 15:50
@RiteshTC this challenge isn't visible to me

![screen shot 2018-12-03 at 9 19 09 pm](https://user-images.githubusercontent.com/683231/49384499-232eba80-f741-11e8-97f7-821c1ea82a98.png)


@ajefts @cwdcwd are you able to see

**Comment by RiteshTC** [comment] 2018-12-04 15:02
@sushilshinde 
The issue is applicable to all challenges of private community accessed by the topcoder URL. Pick any challenge from any private community to reproduce the issue

**Comment by ThomasKranitsas** [comment] 2018-12-06 16:45
Contest https://www.topcoder.com/challenges/30076272 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-12-06 16:45
Contest https://www.topcoder.com/challenges/30076272 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2018-12-06 16:45
@topcoder-platform/topcodercompetitors this one is open for pickup

**Comment by ThomasKranitsas** [comment] 2018-12-06 16:48
Contest https://www.topcoder.com/challenges/30076272 has been updated - it has been assigned to rashmi73.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2018-12-06 16:49
PR on 
https://github.com/topcoder-platform/community-app/tree/hot-fixes

**Comment by cwdcwd** [comment] 2018-12-06 18:48
![](https://github.trello.services/images/mini-trello-icon.png) [File attachments not showing on challenge page.](https://trello.com/c/F62jkdYA/17-file-attachments-not-showing-on-challenge-page)

**Comment by sushilshinde** [comment] 2018-12-07 12:08
@topcoder-platform/topcodercompetitors this one is open for pickup

PR on https://github.com/topcoder-platform/community-app/tree/hot-fixes

**Comment by ThomasKranitsas** [comment] 2018-12-07 12:14
Contest https://www.topcoder.com/challenges/30076272 has been updated - it has been assigned to gauravseta.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by gurmeetb** [comment] 2018-12-10 11:45
@sushilshinde it has been 3 days and no MR, should this be opened for pickup ?

**Comment by Gauravseta** [comment] 2018-12-10 12:01
@gurmeetb I am alreayd working and it willl be completed todya evening. same has been conveyed to sushil

**Comment by Gauravseta** [comment] 2018-12-10 18:38
@sushilshinde PR #1798

**Comment by sushilshinde** [comment] 2018-12-11 09:01
testing...

**Comment by sushilshinde** [comment] 2018-12-11 10:30
Deployed on prod

**Comment by ThomasKranitsas** [comment] 2018-12-11 10:31
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30076272<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed by sushilshinde** 2018-12-11 10:30 UTC
Labels: Blocker, Submission Page, tcx_Assigned, tcx_FixAccepted, tcx_ReadyForReview
