### ISSUE TITLE
Author names are inconsistent in search results

### ISSUE THREAD

**Issue by InfinityToP** [topcoder-platform/community-app#3867] opened 2020-02-07 11:37 UTC
**Describe the bug**
Author names appear to be inconsistent in the article filter results.

**To Reproduce**
1. Go to 'https://www.topcoder.com/thrive/search?author=Mariia%20Mykhailova'
2. Scroll down to 'search results'
3. Find the authors name to be "Mariia Mykhailova" in 'Articles'
4. Click on 'Forum posts'
5. Find the authors name to be "Nickolas" in 'Forum posts'

**Expected behavior**
The author's name remain consistent. Not be interchangeably used with their Topcoder handle, if that is the case.

**Screenshots**
![image](https://user-images.githubusercontent.com/32297688/74026317-ec4ed700-49cb-11ea-87fd-e87475ab5039.png)
_Articles_

![image](https://user-images.githubusercontent.com/32297688/74026376-0ee0f000-49cc-11ea-90ef-be425468242a.png)
_Forum posts_

**Desktop: **
 OS: Windows
Browser: chrome
Version: 79.0.3945.130

**Additional context**
Functional Issue

**Comment by kkartunov** [comment] 2020-10-16 12:24
duplicate of https://github.com/topcoder-platform/thrive-code/issues/20

**Closed by kkartunov** 2020-10-16 12:24 UTC
Labels: Functional, Thrive
