### ISSUE TITLE
[Common] Error message displayed when user close the login popup

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1310] opened 2018-09-13 20:43 UTC
## Steps to Reproduce

1. Open the Application and Login as a valid user
2. Go to Settings > Account > Linked Account
3. Click on Github
4. Close the popup
5. Observe

## Actual Result(s)

- Error message displayed when user close the login popup

## Expected Result(s)

- Must not display an error

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** Google Chrome 69.0.3497.92 (Official Build) (64-bit)

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment] 2018-09-14 02:36
```
main-1536762026959.js:83 Uncaught (in promise) Error: server error
    at new o (main-1536762026959.js:83)
    at main-1536762026959.js:88
    at main-1536762026959.js:83
o @ main-1536762026959.js:83
(anonymous) @ main-1536762026959.js:88
(anonymous) @ main-1536762026959.js:83
setInterval (async)
open @ main-1536762026959.js:83
A.loginWithPopup @ main-1536762026959.js:88
A.login.A.signin @ main-1536762026959.js:88
(anonymous) @ main-1536762026959.js:83
t @ main-1536762026959.js:9
(anonymous) @ main-1536762026959.js:83
g @ main-1536762026959.js:96
(anonymous) @ main-1536762026959.js:96
e.(anonymous function) @ main-1536762026959.js:96
o @ main-1536762026959.js:9
(anonymous) @ main-1536762026959.js:9
t @ main-1536762026959.js:9
(anonymous) @ main-1536762026959.js:9
(anonymous) @ main-1536762026959.js:83
LINK_EXTERNAL_ACCOUNT_DONE @ main-1536762026959.js:83
r @ main-1536762026959.js:9
i @ main-1536762026959.js:9
linkExternalAccount @ chunk-1536762026959.js:1
value @ chunk-1536762026959.js:1
onClick @ chunk-1536762026959.js:1
(anonymous) @ main-1536762026959.js:83
invokeGuardedCallback @ main-1536762026959.js:83
invokeGuardedCallbackAndCatchFirstError @ main-1536762026959.js:83
S @ main-1536762026959.js:83
D @ main-1536762026959.js:83
x @ main-1536762026959.js:83
z @ main-1536762026959.js:83
I @ main-1536762026959.js:83
j @ main-1536762026959.js:83
Sn @ main-1536762026959.js:83
$i @ main-1536762026959.js:83
Qe @ main-1536762026959.js:83
xn @ main-1536762026959.js:83
tu @ main-1536762026959.js:83
Cn @ main-1536762026959.js:83
```

![2018-09-13_21-35-34](https://user-images.githubusercontent.com/4592712/45526523-15e6dd00-b79d-11e8-988c-4b05c3fbc112.png)

**Comment by ThomasKranitsas** [comment] 2018-09-19 15:20
Duplicate of #1306

**Closed by ThomasKranitsas** 2018-09-19 15:20 UTC
