### ISSUE TITLE
[$150] - Use terms from v3 to display terms on a challenge

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#602] opened 2017-11-22 14:11 UTC
endpoint is ready in dev.  Terms are added to the challenge response:

http://api.topcoder-dev.com/v3/challenges/30028553

**Comment by nauhil** [comment] 2017-11-28 16:47
getChallengeTerms get from v3,  getCommunityTerms keeps use v2

right ?

**Comment by kondakovdmitry** [comment] 2017-12-02 21:04
`terms` in the v3 challenge response contains many duplicated items with the same `termsOfUseId` but with different `role`. Is it ok to show only terms with the `role` `Submitter` for a challenge?

**Comment by birdofpreyru** [comment] 2017-12-02 21:12
@kondakovdmitry yes, on challenge details page we need to show only `Submitter` terms, and only they are used to protect `Register` button.

**Comment by kondakovdmitry** [comment] 2017-12-02 21:50
The v3 challenge response does not contain `agreed` property which is required to check protection for `Register` button. How should we obtain whether user already agreed with the terms or not?

**Comment by birdofpreyru** [comment] 2017-12-02 22:07
@ajefts @skyhit can we add `agreed` property into terms included inside challenge details, if they were fetched with auth token?

**Comment by kondakovdmitry** [comment] 2017-12-03 12:53
PR: #632
hash: f40aa9f

This should work when `agreed` is added into terms inside challenge details.

**Comment by kondakovdmitry** [comment] 2018-01-08 14:07
@birdofpreyru Cannot test with DocuSign terms. When getting term details via v3 api, the following error response is always returned:
Response:
```json
{
    "id": "5daf7796:160bf4aaf4f:-7fcd",
    "result": {
        "success": true,
        "status": 500,
        "content": "Exception thrown while attempting to traverse the result set [statement:\" SELECT \ttou.terms_of_use_id as termsOfUseId,  tou.title,  tou.url,  touat.name as agreeabilityType,  tou.terms_text as text,  touat.terms_of_use_agreeability_type_id as agreeabilityTypeId,  toudtx.docusign_template_id as docusignTemplateId,  (utuox.user_id IS NOT NULL) as agreed  FROM common_oltp\\:terms_of_use tou  INNER JOIN common_oltp\\:terms_of_use_agreeability_type_lu touat ON touat.terms_of_use_agreeability_type_id = tou.terms_of_use_agreeability_type_id  LEFT JOIN common_oltp\\:terms_of_use_docusign_template_xref toudtx ON toudtx.terms_of_use_id = tou.terms_of_use_id  LEFT JOIN common_oltp\\:user_terms_of_use_xref utuox ON utuox.terms_of_use_id = tou.terms_of_use_id AND utuox.user_id = :userId  WHERE tou.terms_of_use_id = :termsOfUseId \", located:\" SELECT \ttou.terms_of_use_id as termsOfUseId,  tou.title,  tou.url,  touat.name as agreeabilityType,  tou.terms_text as text,  touat.terms_of_use_agreeability_type_id as agreeabilityTypeId,  toudtx.docusign_template_id as docusignTemplateId,  (utuox.user_id IS NOT NULL) as agreed  FROM common_oltp\\:terms_of_use tou  INNER JOIN common_oltp\\:terms_of_use_agreeability_type_lu touat ON touat.terms_of_use_agreeability_type_id = tou.terms_of_use_agreeability_type_id  LEFT JOIN common_oltp\\:terms_of_use_docusign_template_xref toudtx ON toudtx.terms_of_use_id = tou.terms_of_use_id  LEFT JOIN common_oltp\\:user_terms_of_use_xref utuox ON utuox.terms_of_use_id = tou.terms_of_use_id AND utuox.user_id = :userId  WHERE tou.terms_of_use_id = :termsOfUseId \", rewritten:\" SELECT \ttou.terms_of_use_id as termsOfUseId,  tou.title,  tou.url,  touat.name as agreeabilityType,  tou.terms_text as text,  touat.terms_of_use_agreeability_type_id as agreeabilityTypeId,  toudtx.docusign_template_id as docusignTemplateId,  (utuox.user_id IS NOT NULL) as agreed  FROM common_oltp:terms_of_use tou  INNER JOIN common_oltp:terms_of_use_agreeability_type_lu touat ON touat.terms_of_use_agreeability_type_id = tou.terms_of_use_agreeability_type_id  LEFT JOIN common_oltp:terms_of_use_docusign_template_xref toudtx ON toudtx.terms_of_use_id = tou.terms_of_use_id  LEFT JOIN common_oltp:user_terms_of_use_xref utuox ON utuox.terms_of_use_id = tou.terms_of_use_id AND utuox.user_id = ?  WHERE tou.terms_of_use_id = ? \", arguments:{ positional:{}, named:{termsOfUseId:21153,userId:40154274}, finder:[]}]"
    },
    "version": "v3"
}
```
Request:
GET https://api.topcoder-dev.com/v3/terms/detail/21153?nocache=1515419490437

At the same time v2 api works well.

**Comment by birdofpreyru** [comment] 2018-01-08 16:14
@kondakovdmitry ok, we'll have to wait for @skyhit to check this issue at the backend side

**Comment by skyhit** [comment] 2018-01-09 01:12
@ajefts @birdofpreyru this is a configuration issue for dev environment, I am checking with Tony about the right configurations, for /terms/details/<termsid>, and terms accept endpoints, they are working properly, right?

**Comment by birdofpreyru** [comment] 2018-01-09 17:16
@skyhit I am not sure whether term accept endpoints work. @kondakovdmitry do you know about it?

**Comment by kondakovdmitry** [comment] 2018-01-09 23:46
@birdofpreyru @skyhit The terms 'agree' endpoint works (could only test it with non-DocuSign terms, e.g. id 21193). The problem is that with DocuSign terms (e.g. id 21153) the 'detail' endpoint does not work in v3. Please also note that in production environment, the terms v3 api does not work at all for me - it always returns 404 Not Found errors.

Here is a summary of what works/not works currently:
**Dev environment v3:**
`GET https://api.topcoder-dev.com/v3/terms/detail/21193` - **works** 
`POST https://api.topcoder-dev.com/v3/terms/21193/agree` - **works** 
`GET https://api.topcoder-dev.com/v3/terms/detail/21153` - **does not work** (see exception above)
**Dev environment v2:**
`GET https://api.topcoder-dev.com/v2/terms/detail/21193` - **works**
`GET https://api.topcoder-dev.com/v2/terms/detail/21153` - **works**

**Prod environment v3:**
`GET https://api.topcoder.com/v3/terms/detail/21193` - **does not work** (404 error)
`GET https://api.topcoder.com/v3/terms/detail/21153` - **does not work** (404 error)
**Prod environment v2:**
`GET https://api.topcoder.com/v2/terms/detail/21193` - **works**
`GET https://api.topcoder.com/v2/terms/detail/21153` - **works**

**Comment by birdofpreyru** [comment] 2018-01-13 00:31
@kondakovdmitry, @skyhit told me that backend configuration that prevented DocuSign terms from working is fixed. I have rapidly tested the latest version of your PR, and I see the following problems:

- It seems that your code looks into a wrong place to check whether the simple terms have been agreed or not: in dev I try to register to NDA 3 challenge as TonyJ, and the simple terms there is shown up as not-agreed, even though the backend returns `true` in the `agreed` field (which is correct).

- DocuSign terms for the same challenge now falls at the call to https://api.topcoder-dev.com/v3/terms/docusign/viewURL with the error `"status":400,"content":"Please provide the post body."` I have not looked into details, but it seems to be an error at Community App side.

- In prod an attempt to register for the Bug Bash challenge with my main user fails with 405 error at the call to https://api.topcoder.com/v3/terms/detail/21193?nocache=1515802913968. I am not sure, whether it is TC backend or Community App error.

Please look into these.

**Comment by kondakovdmitry** [comment] 2018-01-13 14:29
@birdofpreyru 
* To check whether the terms have been agreed or not, the code looks into the `terms` array received from v3 challenge details api. You can check the response from https://api.topcoder-dev.com/v3/challenges/30050950 in POSTMAN with correct auth token - it still returns response without `agreed` property. You asked ajefts and skyhit about that in [this comment](https://github.com/topcoder-platform/community-app/issues/602#issuecomment-348723651), but it still has not been resolved. I also noted about that in my comment for #632 PR. I can make a workaround for this and call 'term details' api (to get the value for `agreed` property) for all terms of a challenge when registering for a challenge, but this will mean all term details with their full texts will be retrieved each time you register, which is not very efficient and also will complicate the code, so it would be better to fix that on the TC backend side.
* DocuSign terms view is now fixed. Please check the updated PR.
* For prod environment, are you sure it is 405 error? For me it always returns 404 error, I wrote about that in the [above comment](https://github.com/topcoder-platform/community-app/issues/602#issuecomment-356451485). I do not see any problem from the Community App side - it just gets the `termsOfUseId` from the v3 challenge details response and tries to get term details - all the same as in dev environment. It is better to check this api call in prod on the TC backend side.

**Comment by skyhit** [comment] 2018-03-03 02:15
@birdofpreyru @kondakovdmitry the `agreed` field is added in challenge detail api (deployed in dev), please check if that is fine

**Comment by sushilshinde** [comment] 2018-03-19 08:26
@skyhit this is not yet fixed, please have a look.

**Comment by ThomasKranitsas** [comment] 2019-06-21 05:12
[500]: Challenge for the updated issue 602 is creating, rescheduling this event<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-06-21 05:12
Contest https://www.topcoder.com/challenges/30093976 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-07-11 16:38
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed by ThomasKranitsas** 2019-07-11 16:38 UTC
Labels: P2
