### ISSUE TITLE
[$50]Challenge Details: Checkpoint prize details missing for design contests

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4448] opened 2020-06-01 05:06 UTC
Checkpoint prize details missing for design contests
user: not logged in
V4 URL:https://www.topcoder.com/challenges/30126014
V5 URL:https://beta-community-app.topcoder.com/challenges/fbd47239-43dc-4f50-8d0d-739dfe82191a
<img width="1440" alt="Screenshot 2020-06-01 at 10 34 21 AM" src="https://user-images.githubusercontent.com/58783823/83377605-af33a800-a3f3-11ea-9a24-6dde3c7095e3.png">

**Comment by SathyaJayabal** [comment] 2020-06-01 12:07
https://github.com/topcoder-platform/challenge-api/issues/145

**Comment by crazyk07** [comment] 2020-06-02 09:47
Contest https://www.topcoder.com/challenges/30127613 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by sushilshinde** [comment] 2020-06-02 09:58
To fix this issue 
Use details API call - 
http://api.topcoder-dev.com/v5/challenges/741f427e-9f4c-4735-9448-45afaf21455e

(call with legacy challenge id for ref, don't use it http://api.topcoder-dev.com/v5/challenges?legacyId=30047827)

Context: 
```
The only data point that changed from how it was previously is prizeSets. To accommodate the checkpoint prizes, I cleaned up the object a little bit. You’ll notice in this object:
http://api.topcoder-dev.com/v5/challenges?legacyId=30047827
Prize Sets now looks like this:
"prizeSets": [
{
"type": "placement",
"description": "Challenge Prizes",
"prizes": [
{
"value": 1500,
"type": "USD"
},
{
"value": 500,
"type": "USD"
}
]
},
{
"type": "checkpoint",
"description": "Checkpoint Prizes",
"prizes": [
{
"value": 100,
"type": "USD"
},
{
"value": 100,
"type": "USD"
},
{
"value": 100,
"type": "USD"
},
{
"value": 100,
"type": "USD"
},
{
"value": 100,
"type": "USD"
}
]
}
],
The change is that before this migration, the “type” for the Challenge Prizes was Challenge Prizes. I’ve changed that type to be placement. That allows for the addition of checkpoint type which is more logical.
```

**Comment by sushilshinde** [comment] 2020-06-02 09:58
@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup

Submit in 8 hours and PR to

https://github.com/topcoder-platform/community-app/tree/integration-v5-challenge-api
https://github.com/topcoder-platform/topcoder-react-lib/tree/integration-v5-challenge-api

run `npm run test` before PR

**Comment by crazyk07** [comment] 2020-06-02 10:02
Contest https://www.topcoder.com/challenges/30127613 has been updated - it has been assigned to Narekvar90.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by narekcat** [comment] 2020-06-02 20:44
@SathyaJayabal @sushilshinde Something wrong with beck end. I can't reproduce the issue.
![image](https://user-images.githubusercontent.com/11549629/83567473-ad243300-a532-11ea-9b84-16c9cbf7e184.png)
![image](https://user-images.githubusercontent.com/11549629/83567540-c5944d80-a532-11ea-8c44-35d6977e2221.png)

**Comment by rootelement** [comment] 2020-06-02 22:55
Challenges were re-migrated. They all got new UUIDs. You can use this one:
http://api.topcoder-dev.com/v5/challenges?legacyId=30048648
http://api.topcoder-dev.com/v5/challenges/8e48e825-1f82-48d6-9c99-de2671fd3302

**Comment by narekcat** [comment] 2020-06-03 00:55
@rootelement Ok. Thanks.

**Comment by narekcat** [comment] 2020-06-03 08:56
@SathyaJayabal @sushilshinde  The checkpoint prizes can have different values. Need I display each of them, like challenge prizes ? What about reliability bonus ? I have checked challenge-api repository and there are nothing about reliability bonus.

**Comment by sushilshinde** [comment] 2020-06-03 09:17
@Oanh-and-only-Oanh @SathyaJayabal please help

**Comment by SathyaJayabal** [comment] 2020-06-03 09:26
@narekcat , as far as I know checkpoint prizes have the same values, example either 5 prizes of $100, or 10 prizes of $50 etc. If you did see an example where there were different amounts for checkpoint prizes, please share the link.

**Comment by narekcat** [comment] 2020-06-03 09:28
@SathyaJayabal Ok. Does `prizeSets` include reliability bonus ?

**Comment by SathyaJayabal** [comment] 2020-06-03 09:37
@Oanh-and-only-Oanh can  you help with reliability bonus? Do we still offer reliability bonus? @narecat, do you have any example of an existing challenge with reliability bonus.

**Comment by narekcat** [comment] 2020-06-03 09:40
@SathyaJayabal No I haven't. I have check all active challenges, but there is no reliability bonus. Actually I can remove code associated with reliability bonus.

**Comment by SathyaJayabal** [comment] 2020-06-03 09:42
@narekcat , lets wait for @Oanh-and-only-Oanh 's reply regarding reliability bonus.

**Comment by narekcat** [comment] 2020-06-03 09:43
@SathyaJayabal Ok.

**Comment by Oanh-and-only-Oanh** [comment] 2020-06-03 14:42
Can we keep reliability bonus as an option feature that copilots can decided to add or remove?

**Comment by narekcat** [comment] 2020-06-03 15:05
@Oanh-and-only-Oanh If you asking my opinion, then we can.

**Comment by Oanh-and-only-Oanh** [comment] 2020-06-03 15:22
I meant, don't remove code associated with reliability bonus. keep it as option.

**Comment by narekcat** [comment] 2020-06-03 15:24
@Oanh-and-only-Oanh Ok. I understand.

**Comment by sushilshinde** [comment] 2020-06-03 16:34
@narekcat please PR in 12 hours

**Comment by narekcat** [comment] 2020-06-03 16:35
@sushilshinde I'll finish this issue in an hours.

**Comment by narekcat** [comment] 2020-06-03 17:29
@sushilshinde I have fixed this issue. Please see pull request https://github.com/topcoder-platform/community-app/pull/4462.

**Comment by SathyaJayabal** [comment] 2020-06-04 08:14
Verified on beta and test. Checkpoint prizes displayed  as expected.
<img width="1440" alt="Screenshot 2020-06-04 at 1 40 43 PM" src="https://user-images.githubusercontent.com/58783823/83732226-5b31f900-a669-11ea-9cf2-e6bb7e60211c.png">
<img width="1440" alt="Screenshot 2020-06-04 at 1 41 11 PM" src="https://user-images.githubusercontent.com/58783823/83732291-73a21380-a669-11ea-95e9-2c6e4b195682.png">

**Comment by SathyaJayabal** [comment] 2020-06-04 14:31
Reverified on beta and test after data model update
(https://topcoder.slack.com/archives/G012CL5GF71/p1591254930370200)
v5 prod url :https://beta-community-app.topcoder.com/challenges/6a92af4d-328d-430b-a3a2-d8397513ffe8
v4 prod url: https://www.topcoder.com/challenges/30126014
v5 dev url: https://test-community-app.topcoder-dev.com/challenges/bec3ff26-5369-4bcf-9556-813bad5ab8ca
v4 dev url:https://qa-community-app.topcoder-dev.com/challenges/30048869
<img width="1440" alt="Screenshot 2020-06-04 at 7 59 02 PM" src="https://user-images.githubusercontent.com/58783823/83769882-06f53c00-a69e-11ea-8b96-82d5c644390b.png">

<img width="1440" alt="Screenshot 2020-06-04 at 7 56 35 PM" src="https://user-images.githubusercontent.com/58783823/83769865-0197f180-a69e-11ea-82b7-583096badc05.png">

**Comment by crazyk07** [comment] 2020-06-06 09:27
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30127613<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed** 2020-06-06 09:26 UTC
Labels: Beta Env, Challenge Details Screen, P1, QA Pass, Test Env, tcx_FixAccepted, v5-intgration-sub-code
