### ISSUE TITLE
No back button to return from user menu

### ISSUE THREAD

**Issue by alexandreeva** [topcoder-platform/community-app#2447] opened 2019-06-07 18:16 UTC
**Reproduction steps:**

1.  Open the test URL and log in
2. Click on the user drop down menu at the top right corner
3. Observe

**Expected result:** 
After opening the user menu, the user is able to go back by clicking on a go back button

**Actual result:** 
After opening the user menu, there is no go back button to return to the previous page

**Frequency:** 
5/5

**Device/Browser/OS:** 

Device: Axon ZTE A20170

OS: Android 7.1.1

Browser: Chrome

**Screenshot:**
![screenshot2](https://user-images.githubusercontent.com/45698232/59124828-9219e580-8915-11e9-9cc3-8bbfd2607c92.jpg)

**Comment by alexandreeva** [comment] 2019-06-07 21:19
Chrome version: 74.0.3729.157

**Comment by nithyaasworld** [comment] 2019-06-09 20:21
Duplicate of https://github.com/topcoder-platform/community-app/issues/2445

**Closed by nithyaasworld** 2019-06-09 20:21 UTC
Labels: Bug Hunt, Functional, Navigation, P2
