### ISSUE TITLE
[$200] Settings > Tools: "Your Information has been updated' shown when switching the tabs after deleting a Devices/Software/Service Providers/Subscriptions

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2096] opened 2019-03-16 03:42 UTC
1. Open the application and login as TonyJ
2. Hover over the profile avatar > Click Settings
3. Click Tools Tab > Devices/Software/Service Providers/Subscriptions
4. Delete an item
5. Go to the Profile tab; "Your Information has been updated' shown

**Actual:** "Your Information has been updated' shown when switching the tabs after deleting a Devices/Software/Service Providers/Subscriptions

**Expected:** Should not show messages on the profile page

**Reproducibility Rate:** 3/3

**Environment:** Google Pixel XL, Android 9.0 | Browser: Google Chrome 73.0.3683.75

**Comment by ThomasKranitsas** [comment] 2019-03-18 20:27
The notifications don't seem to work properly

**Comment by ThomasKranitsas** [comment] 2019-04-08 20:11
@topcoder-platform/topcodercompetitors this is open for pickup and needs to be checked and fixed in all subpages in the settings page

**Comment by ThomasKranitsas** [comment] 2019-04-08 20:13
Contest https://www.topcoder.com/challenges/30088204 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-04-08 20:13
Contest https://www.topcoder.com/challenges/30088204 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-04-08 20:14
Contest https://www.topcoder.com/challenges/30088204 has been updated - it has been assigned to applehit16.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by Gauravseta** [comment] 2019-04-08 20:35
@ThomasKranitsas any more open for pickup soon?

**Comment by ThomasKranitsas** [comment] 2019-04-08 20:36
Yes, I'll open more tomorrow. Stay tuned!

**Comment by liqiang372** [comment] 2019-04-09 06:47
@ThomasKranitsas can you please verify the validity of ticket? https://drive.google.com/file/d/1_p7XdcDOfgosnK_BAkyP7VeZm8GD2lxC/view?usp=sharing

The notification doesn't show up for me.

But I found there is a `delete` button in profile page, desktop webpage however doesn't have this
https://ibb.co/pKj37tm

**Comment by ThomasKranitsas** [comment] 2019-04-09 06:50
@liqiang372 ignore the `delete` button for now.

The notifications seem to have many issues. Can you please fix them across the settings page?
The notifications should be properly shown when the data gets updated and should be dismissed when you change tab/page.

Let me know if the effort is too much for this.
I may have to run a challenge for this if it needs a lot of effort.

**Comment by applehit16** [comment] 2019-04-09 07:08
@ThomasKranitsas To fix them, I need to first understand what the issue is... I tried to follow the op's instruction, and nothing happens to me. https://drive.google.com/open?id=1_p7XdcDOfgosnK_BAkyP7VeZm8GD2lxC

So to my understanding now, the issue has become that notification doesn't show up when you delete an item. I'll look into this first, and see if It will be dismissed when switching tabs

**Comment by ThomasKranitsas** [comment] 2019-04-09 07:12
Correct, the notification should show up when you edit anything in your settings/traits.

Again, let me know if the effort is too much for this ticket

**Comment by applehit16** [comment] 2019-04-09 07:14
@ThomasKranitsas looking into it, will keep you updated

**Comment by liqiang372** [comment] 2019-04-11 03:06
@ThomasKranitsas this is ready for review https://github.com/topcoder-platform/community-app/pull/2303

**Comment by ThomasKranitsas** [comment] 2019-04-18 09:45
Contest https://www.topcoder.com/challenges/30088204 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-04-18 09:46
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30088204<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed** 2019-04-18 09:45 UTC
Labels: Major, tcx_FixAccepted, tcx_ReadyForReview
