### ISSUE TITLE
All Challenges Page Does Not Display After Viewing Member Profile

### ISSUE THREAD

**Issue by VanitaW** [topcoder-platform/community-app#2532] opened 2019-06-07 23:13 UTC
**Describe the bug**
The challenges will not display after viewing the member profile.

**To Reproduce**

1. Open safari browser on iOS mobile device.
2. Go to https://test-community-app.topcoder-dev.com/challenges .
3. Click on 'Login'
4. Sign in using username: dan_developer password: dantopcoder123 . If you are redirected to to the Topcoder live site, go to https://test-community-app.topcoder-dev.com/challenges
5. Click on the profile picture in the upper right hand corner.
6. Click on 'Settings'.
7.  Refresh the browser.  The member profile information is displayed.
8.  Click on the hamburger menu in the upper left-hand corner.  
9.  Click on 'Work'
10.  Click on 'Compete'
11.  Click on 'Compete' located below the Topcoder logo.
12. Click on 'All challenges'

**Expected behavior**
All current Topcoder challenges should display.

**Actual behavior**
The dropdown menu closed with the member profile information displayed.

**Screenshots**

![BeforeClickingOnAllChallenges](https://user-images.githubusercontent.com/12702517/59137763-f6a56680-894e-11e9-8f33-0392f0505622.png)

![AfterClickingOnAllChallenges](https://user-images.githubusercontent.com/12702517/59137765-f86f2a00-894e-11e9-9a1e-6dbd133f11fd.png)

**Smartphone:**
 - Device: iPhone SE
 - OS: iOS12.2
 - Browser: Safari
 - Version: 12

**Comment by nithyaasworld** [comment] 2019-06-09 18:37
Duplicate of https://github.com/topcoder-platform/community-app/issues/2401

**Comment by nithyaasworld** [comment] 2019-06-09 18:42
Duplicate of https://github.com/topcoder-platform/community-app/issues/2433

**Closed by nithyaasworld** 2019-06-09 18:42 UTC
Labels: Bug Hunt, Functional, Navigation, mobile
