### ISSUE TITLE
specification track - no challenges found

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#987] opened 2018-06-09 03:19 UTC
### Reported URL ###
https://www.topcoder-dev.com/members/MIG-29/details/?track=DEVELOP&subTrack=specification&tab=statistics

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/members/MIG-29/details/?track=DEVELOP&subTrack=specification&tab=challenges

3. observe 

### Expected Result ###
should display successful challenges for specification track

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment] 2018-06-11 06:05
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Blocker

**Comment by ThomasKranitsas** [comment] 2018-06-14 12:07
duplicate of https://github.com/topcoder-platform/community-app/issues/925

**Closed by ThomasKranitsas** 2018-06-14 12:07 UTC
Labels: Blocker, PD - Member - Migration
