### ISSUE TITLE
[$50] Don't display the bucket if there are zero items 

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#4962] opened 2020-09-21 07:08 UTC
![image](https://user-images.githubusercontent.com/683231/93739963-2f7e5300-fc07-11ea-8a9e-756fe7226316.png)

**Comment by SathyaJayabal** [comment] 2020-09-21 14:26
Related: display "No challenges found" message when search returns no results. See prod for expected behaviour.
<img width="1440" alt="Screenshot 2020-09-21 at 7 55 46 PM" src="https://user-images.githubusercontent.com/58783823/93779341-7ccce580-fc44-11ea-8dd4-5baf3cc386b9.png">

<img width="1440" alt="Screenshot 2020-09-21 at 7 55 37 PM" src="https://user-images.githubusercontent.com/58783823/93779323-776f9b00-fc44-11ea-9f9b-1183b36adb1b.png">

**Comment by luizrrodrigues** [comment] 2020-09-22 15:07
@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup

Submit in 8 hours and PR to

https://github.com/topcoder-platform/community-app/tree/feature-refactor-challengelist
https://github.com/topcoder-platform/topcoder-react-lib/tree/feature-refactor-challengelist

run `npm run` test before PR

**Comment by crazyk07** [comment] 2020-09-22 15:07
Contest https://www.topcoder.com/challenges/30143197 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-09-23 10:02
Contest https://www.topcoder.com/challenges/30143197 has been updated - it has been assigned to cagdas001.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by SathyaJayabal** [comment] 2020-09-24 06:18
@cagdas001 , We need to display the `No challenges found in bucket name` when there are no challenges found. 

1. When "All Challenges" is selected and no challenges found in any of the buckets display message `No challenges found in All Challenges`. But if any of the buckets have data, then simply hide the other buckets and display only the the bucket(s) with the data. No need for message here.
2. Any specific bucket is selected and no data is returned, we need to display the message `No challenges found in bucket name`

Please see production for expected behaviour.

<img width="1440" alt="Screenshot 2020-09-24 at 11 41 28 AM" src="https://user-images.githubusercontent.com/58783823/94107837-dd823b00-fe5b-11ea-9e12-8d3acdbd0cf9.png">

**Comment by cagdas001** [comment] 2020-09-24 14:38
Done in #5001

**Comment by luizrrodrigues** [comment] 2020-09-29 01:48
@cagdas001 Looks like now we loose loading animation:
https://i.gyazo.com/e177fca8a4653c3613fa7fd681620b04.mp4

This not from latest PR, but form first one: https://github.com/topcoder-platform/community-app/pull/4992

Expected;
https://i.gyazo.com/1432ce908e53a7bc68a29f0456de0249.mp4

**Comment by sushilshinde** [comment] 2020-09-30 08:04
@cagdas001 any update on this

**Comment by cagdas001** [comment] 2020-09-30 10:33
I'll push a new commit in open PR (#5001), don't merge it for now. I'm making it Draft

**Comment by Oanh-and-only-Oanh** [comment] 2020-10-01 03:10
@cagdas001 any updates?

**Comment by luizrrodrigues** [comment] 2020-10-01 13:03
@cagdas001 Please PR next few hours or open for pickup.

**Comment by cagdas001** [comment] 2020-10-01 16:07
ready

**Comment by luizrrodrigues** [comment] 2020-10-02 01:28
@cagdas001 Thanks

**Comment by SathyaJayabal** [comment] 2020-10-02 07:50
verified on test
<img width="1440" alt="Screenshot 2020-10-02 at 1 07 54 PM" src="https://user-images.githubusercontent.com/58783823/94900022-eef9c180-04b1-11eb-8111-d7c7bc9bcc3a.png">
<img width="1440" alt="Screenshot 2020-10-02 at 1 08 02 PM" src="https://user-images.githubusercontent.com/58783823/94900045-f4efa280-04b1-11eb-9561-6cbc17d570a8.png">
<img width="1440" alt="Screenshot 2020-10-02 at 1 09 07 PM" src="https://user-images.githubusercontent.com/58783823/94900057-f751fc80-04b1-11eb-833f-8c6ddf8fa37d.png">

**Comment by SathyaJayabal** [comment] 2020-10-05 09:42
verified on staging
<img width="1440" alt="Screenshot 2020-10-05 at 3 09 10 PM" src="https://user-images.githubusercontent.com/58783823/95064273-1bfddc80-071d-11eb-9144-4c7796a09999.png">
<img width="1440" alt="Screenshot 2020-10-05 at 3 09 12 PM" src="https://user-images.githubusercontent.com/58783823/95064290-215b2700-071d-11eb-9c1b-164f743074d1.png">
<img width="1440" alt="Screenshot 2020-10-05 at 3 11 23 PM" src="https://user-images.githubusercontent.com/58783823/95064293-23bd8100-071d-11eb-99f6-b2826ff453f3.png">

**Comment by luizrrodrigues** [comment] 2020-10-07 12:26
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30143197<br/><br/>```This is an automated message for luizrrodrigues via Topcoder X```

**Closed** 2020-10-07 12:25 UTC
Labels: P3, QA Pass in Staging, listing:re-implementation, tcx_Assigned, tcx_FixAccepted
