### ISSUE TITLE
[$30] should not show "Sorry, no rated SRM found" before loading data

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#986] opened 2018-06-09 03:12 UTC
### Reported URL ###
https://www.topcoder-dev.com/members/petr/details/?track=DATA_SCIENCE&subTrack=SRM&tab=Past%20srm

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/members/petr/details/?track=DATA_SCIENCE&subTrack=SRM&tab=Past%20srm

3. observe 

### Expected Result ###
should not show "Sorry, no rated SRM found" before loading data.

### Actual Result ###

See screenshot, it first shows the message, then starts loading SRM data.

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment] 2018-06-09 03:12
<img width="1199" alt="sorry" src="https://user-images.githubusercontent.com/4590317/41187134-f58400d2-6bd5-11e8-9036-05b4f66251d4.png">

**Comment by winterflame** [comment] 2018-06-11 06:05
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment] 2018-08-13 21:03
You should show the existing loading indicator while the data is being loaded instead of the "Not found.." message.

**Comment by ThomasKranitsas** [comment] 2018-08-13 21:03
This should be fixed for all types of challenges and not just SRMs

**Comment by ThomasKranitsas** [comment] 2018-08-13 21:06
Contest https://www.topcoder.com/challenges/30069371 has been created for this ticket.

**Comment by ThomasKranitsas** [comment] 2018-08-13 21:06
Contest https://www.topcoder.com/challenges/30069371 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment] 2018-08-13 21:07
Contest https://www.topcoder.com/challenges/30069371 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment] 2018-08-13 21:08
Contest https://www.topcoder.com/challenges/30069371 has been updated - it has been assigned to kevin.crain.

**Comment by ThomasKranitsas** [comment] 2018-08-13 21:08
@KevinLeigh it's yours

**Comment by KevinLeigh** [comment] 2018-08-13 21:11
@ThomasKranitsas Thank you Thomas!

**Comment by KevinLeigh** [comment] 2018-08-13 21:38
I have forked and cloned repo. I am now installing the correct node version and fetching dependencies. After that I will run solution to to reproduce issue and fix accordingly. This should not take too long from what I read in the description. 

I just want to verify is it 'develop-new' branch that I need to work off of ?

**Comment by ThomasKranitsas** [comment] 2018-08-13 21:41
Correct, the work is to be done based on the `new-develop` branch.
You may want to take a look here https://github.com/topcoder-platform/community-app/issues/1150#issuecomment-412354461

**Comment by KevinLeigh** [comment] 2018-08-13 21:47
Please could you tell me the endpoint to use to login as well as password for username pshah_manager ?

**Comment by ThomasKranitsas** [comment] 2018-08-13 21:50
The password should be: `topcoder123`.

The login URL should be: https://accounts.topcoder-dev.com/member?retUrl=http:%2F%2Flocal.topcoder-dev.com:3000%2Fmy-dashboard%2F&utm_source=community-app-main

**Comment by KevinLeigh** [comment] 2018-08-13 21:53
Perfect it works and I have managed to reproduce issue :)

**Comment by KevinLeigh** [comment] 2018-08-13 22:30
Is there another repo that has a deployment script that is generating server side javascript code and deploying code to AWS which is being used by community-app repo?

**Comment by ThomasKranitsas** [comment] 2018-08-13 22:37
Maybe 
https://github.com/topcoder-platform/topcoder-react-lib but I’m not sure.

I’m on mobile now so I can’t check.

What needs to be fixed here is that the app should show the loading indicator while the data is being loaded instead of the error message.

It should not show “sorry, no rated srms found” and then (after the API call was made render the data.

**Comment by ThomasKranitsas** [comment] 2018-08-13 22:38
I’ll look for more details tomorrow as it’s late here.

**Comment by KevinLeigh** [comment] 2018-08-13 22:43
All good, I will investigate further into where “Sorry, no rated srms found” is coming from.

**Comment by KevinLeigh** [comment] 2018-08-13 23:06
So I was using  `https://www.topcoder-dev.com/members/petr/details/...` link to test because `local.topcoder-dev.com:3000` fails with HTTP status code `500` with error message `Unauthorized`. I cannot test properly locally because of this error.  Please see screenshots below:

<img width="529" alt="screen shot 2018-08-14 at 00 57 36" src="https://user-images.githubusercontent.com/32452072/44062665-a4083faa-9f5d-11e8-9b17-f81b6be4afb1.png">

<img width="941" alt="screen shot 2018-08-14 at 00 57 57" src="https://user-images.githubusercontent.com/32452072/44062672-a7ae89e8-9f5d-11e8-8e65-542116c87ab7.png">

I have tried both production and development environments which throw the same error.

**Comment by ThomasKranitsas** [comment] 2018-08-13 23:11
Check the forum of this challenge 
https://www.topcoder.com/challenges/30069264 to see how to get rid of this error

**Comment by KevinLeigh** [comment] 2018-08-13 23:28
Perfect it works, it was because of Contentful environment variables not being set. Thank you.

**Comment by KevinLeigh** [comment] 2018-08-13 23:39
@ThomasKranitsas 

I am not able to reproduce issue locally and can only reproduce via url `https://www.topcoder-dev.com/members/petr/details/...`. Which leads me to suspect that a `redeploy` to `https://www.topcoder-dev.com` should fix this issue because no where in the code can I find a reference to 'Sorry, no rated SRM found' message and the message may have been removed in previous changes/commits.

Please see local verification video here: https://youtu.be/lej7W19AbTg

**Comment by ThomasKranitsas** [comment] 2018-08-14 07:56
Contest https://www.topcoder.com/challenges/30069371 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment] 2018-08-14 07:57
Hmm... Ok, thanks for looking at this. I'll make a $30 payment for your effort

**Comment by ThomasKranitsas** [comment] 2018-08-14 07:57
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069371

**Closed by ThomasKranitsas** 2018-08-14 07:57 UTC
Labels: Assigned, Fix accepted, Minor, PD - Member - Migration
