### ISSUE TITLE
Unable to open any challenge 

### ISSUE THREAD

**Issue by binit92** [topcoder-platform/community-app#592] opened 2017-11-15 15:58 UTC
![capture](https://user-images.githubusercontent.com/6235165/32845873-e395d80e-ca4b-11e7-8a32-fbe4f44e053a.PNG)

**Comment by birdofpreyru** [comment] 2017-11-23 14:46
I believe, it was a temporary problem, caused by instability of the backend API, and should not be an issue anymore; thus closing this ticket for now.

**Closed by birdofpreyru** 2017-11-23 14:46 UTC
