### ISSUE TITLE
Unable to Unregister from the challenge

### ISSUE THREAD

**Issue by jsundarr** [topcoder-platform/community-app#589] opened 2017-11-15 11:55 UTC
when trying to unregister from the  challenge, its giving the below error - 

![image](https://user-images.githubusercontent.com/33688522/32834820-de956176-c9fb-11e7-8147-4861c0201373.png)

**Comment by birdofpreyru** [comment] 2017-11-23 14:46
I believe, it was a temporary problem, caused by instability of the backend API, and should not be an issue anymore; thus closing this ticket for now.

**Closed by birdofpreyru** 2017-11-23 14:46 UTC
