### ISSUE TITLE
mm-feature-experiment branch : Past MM not showing up

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1126] opened 2018-07-16 09:16 UTC
For this filter, nothing shows up

`https://test-community-app.topcoder-dev.com/challenges/?filter[tracks][data_science]=true&bucket=past`

**Comment by birdofpreyru** [comment] 2018-07-16 10:00
@a-lowe, please check & fix

**Comment by a-lowe** [comment] 2018-07-16 21:24
@sushilshinde 
This is caused by the api responding with a '429 Too Many Requests' error.  This also affects code and design challenges, but because they are more plentiful than data science challenges, the listing is filled (or partially filled) before this error occurs.

I don't believe that the code for the track filters has changed.  Does the threshold for the 429 error need to adjusted for the test api?

**Comment by sushilshinde** [comment] 2018-07-17 13:06
@skyhit this is weird?

**Comment by sushilshinde** [comment] 2018-07-17 13:10
@a-lowe 
Same code on beta prod not showing past MMs

https://beta-community-app.topcoder.com/challenges?filter[tracks][data_science]=true&bucket=past

**Comment by skyhit** [comment] 2018-07-17 13:11
@a-lowe which request is send for past challenges?

**Comment by birdofpreyru** [comment] 2018-07-17 13:51
@sushilshinde have you tried to call the API? https://api.topcoder.com/v4/challenges/?filter=status%3DCOMPLETED&limit=50&offset=0 , and further offsets, do not return any MMs, as far as I can see.

**Comment by birdofpreyru** [comment] 2018-07-17 14:30
@skyhit ok, but the current logic of _Data Science_ filter is not to show only MMs, it also shows any challenges tagged with _Data Science_ tag, etc. Thus frontend does not add `subTrack=MARATHON_MATCH` to its API calls.

**Comment by a-lowe** [comment] 2018-07-17 22:38
@sushilshinde @birdofpreyru @skyhit 
Some more information on the problem, it looks like there have been a few issues affecting MMs in the Challenge Listing:

1. For past challenges we're using this query: (https://api.topcoder.com/v4/challenges/?filter=status%3DCOMPLETED).  There are very few legacy MMs being returning by this.  The reason for this may be that most legacy MMs appear to have ```currentStatus: "Draft"``` (including MMs that are currently shown on production using the old mm endpoint.)
2. (https://api.topcoder.com/v4/challenges/?filter=status%3DCOMPLETED%26subTrack%3DMARATHON_MATCH) does return legacy MMs, but these are all from 2012 or earlier.
3. There are some challenges categorized as ```DEVELOP_MARATHON_MATCH``` which were created years ago. Ex. (api.topcoder.com/v4/challenges/30053152) which is from 2016. But, it also has a legacy page at (https://community.topcoder.com/tc?module=MatchDetails&rd=16676).  Would this be expected to have the legacy MM subTrack of ```MARATHON_MATCH```?

**Comment by sushilshinde** [comment] 2018-07-18 12:46
@a-lowe where is the code committed for this fix.

**Comment by sushilshinde** [comment] 2018-07-18 12:48
@skyhit please comment on the issues that @a-lowe mentioned.

I think we had a discussion before about DRAFT challenges, they shouldn't be there even in ES.

**Comment by skyhit** [comment] 2018-07-18 14:03
@sushilshinde 

1. probably, you are right, https://api.topcoder.com/v4/challenges/?filter=subTrack%3DMARATHON_MATCH, there are 630 matches. I am looking into.
2. right.
3. DEVELOP_MARATHON_MATCH are banner marathon matches

**Comment by skyhit** [comment] 2018-07-18 15:57
@a-lowe @sushilshinde  @birdofpreyru  the problem should be fixed, can you help double check

**Comment by a-lowe** [comment] 2018-07-18 16:21
@skyhit Looks good, thanks.

**Closed** 2018-11-15 10:32 UTC
Labels: MM-INTEGRATION
