### ISSUE TITLE
Submission tab is showing the user_id instead of the handle for the logged in user

### ISSUE THREAD

**Issue by dushyantb** [topcoder-platform/community-app#3257] opened 2019-08-22 13:19 UTC
`Submission` tab is showing the `user_id` instead of the `handle` for the `logged in` user
<img width="1319" alt="Screenshot 2019-08-22 at 6 47 03 PM" src="https://user-images.githubusercontent.com/1861713/63517903-81890c80-c50d-11e9-887f-7c3198b88b30.png">

**Comment by crazyk07** [comment] 2019-08-22 13:29
Contest https://www.topcoder.com/challenges/30100093 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2019-08-22 13:29
Contest https://www.topcoder.com/challenges/30100093 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2019-08-22 13:30
Contest https://www.topcoder.com/challenges/30100093 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2019-08-22 13:30
Contest https://www.topcoder.com/challenges/30100093 has been updated - it has been assigned to thomaskranitsas.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2019-08-22 13:30
Contest https://www.topcoder.com/challenges/30100093 has been updated - it has been assigned to thomaskranitsas.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by PrakashDurlabhji** [comment] 2019-08-23 20:05
@ThomasKranitsas if you agree then can I try this if you are busy with some other challenge? thanks

**Comment by ThomasKranitsas** [comment] 2019-08-28 06:58
I'm putting this on a challenge.

**Comment by ThomasKranitsas** [comment] 2019-08-28 07:01
The problem is that we're getting the user IDs from the `challenge.submissions` property which is coming from v4 (which is not updated properly).

https://github.com/topcoder-platform/community-app/blob/c87f5837a2af5a0e33dcc357844d2f9d158fd986/src/shared/components/challenge-detail/Submissions/index.jsx#L35

This should happen on the react lib and the `submitterIds` should be populated based on the `userId` property of each submission (from the v5 API response).

**Comment by PrakashDurlabhji** [comment] 2019-08-28 07:10
F2F?

**Comment by nithyaasworld** [comment] 2019-09-01 16:38
The Challenge in the screenshot provided is not opening up. So I am not able to verify for that challenge.

However, I verified for all the available MM challenges on the platform and I find only topcoder handle and no IDs. 

**@ThomasKranitsas I think we can close this issue. But we need to know why some challenges are not opening up.**

Below are the two challenges that are currently not opening. Both of them are dummy challenges I think.

https://beta-community-app.topcoder.com/challenges/30098582
https://beta-community-app.topcoder.com/challenges/30098568

These challenges are not opening in Production environment too.


![image](https://user-images.githubusercontent.com/5114190/64079395-ad25a700-cd04-11e9-9f20-8fae26ec6232.png)

CC: @dushyantb @cwdcwd @sushilshinde

**Comment by nithyaasworld** [comment] 2019-09-01 19:10
Verification Screenshot:

![image](https://user-images.githubusercontent.com/5114190/64081129-46ab8380-cd1a-11e9-8633-cab5fd26b9fa.png)

**Comment by nithyaasworld** [comment] 2019-09-10 08:51
Production Verification Screenshot:

![image](https://user-images.githubusercontent.com/5114190/64598986-4411f380-d3d6-11e9-8f55-a374caad9899.png)

**Closed by nithyaasworld** 2019-09-10 08:51 UTC
Labels: Ready for Prod QA
