### ISSUE TITLE
[$20] - Start and End Date filtering will give wrong results

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#230] opened 2017-08-24 23:28 UTC
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges?

- Click 'Filters'

- Set 'Date range' as Aug 01, 2017 - Aug 21, 2017

- Check the 'Predix - Integration with Alexa Voice Service' in Open for registration

- Start Aug 24, 2017 - Sept 7, 2017

Actual Result(s)
-----------------------------------------------------------------
- Start and End Date filtering will give wrong results

Expected Result(s)
-----------------------------------------------------------------
- Must display the challenges that falls within the date range

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment] 2017-08-24 23:28
![29](https://user-images.githubusercontent.com/4592712/29693242-0e7b602e-8952-11e7-9183-bdb83dec9f0b.jpg)

**Comment by birdofpreyru** [comment] 2017-08-25 12:22
Accepted, 3 points. I believe, the problem is that now the search looks at the date of specification creation (when the challenge was first drafted, and not when it was actually started). This Predix Alexa challenge was drafted like a week before we got the green light to launch. This should be fixed.

Othewise, it is fine that the end does not fit into the search range. I believe, we should find a challenge if at least some of its dates intersect with the search range.

**Closed** 2017-09-07 14:15 UTC
Labels: Bug Hunt - PAID
