### ISSUE TITLE
Calendar also moves when user scroll up/down the page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1365] opened 2018-09-13 23:49 UTC
## Steps to Reproduce

1. Open the Application and Login as a valid user
2. Go to Settings > Profile > Basic Info
3. Click on the 'Birth Date'
4. Scroll the page up/down

## Actual Result(s)

- Calendar also moves when user scroll up/down the page

## Expected Result(s)

- This is not happening in the Chrome browser
- Must not move the Calendar when user scrolls down the page

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** FF 62

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment] 2018-09-13 23:49
![2018-09-13_18-49-17](https://user-images.githubusercontent.com/4592712/45521906-c5b05080-b785-11e8-9861-9a9464dc5d63.png)

**Comment by ThomasKranitsas** [comment] 2018-09-19 16:53
duplicate of #1305

**Closed by ThomasKranitsas** 2018-09-19 16:53 UTC
