### ISSUE TITLE
[$80] Performance issue while pulling up challenges from listing page

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/community-app#3548] opened 2020-01-08 05:32 UTC
**Describe the bug**

1. The user tried to access the below URL to search for salesforce challenges ran but nothing loaded on the screen for around 30 seconds.

https://www.topcoder.com/challenges/?bucket=past&tab=details&filter[text]=salesforce

Please improve performance to reduce loading time.

**Comment by m-yadav** [comment] 2020-01-08 05:33
cc  @Oanh-and-only-Oanh

**Comment by kkartunov** [comment] 2020-01-16 20:15
@topcoder-platform/topcodercompetitors this one is now open for pickup. Please PR against the branch https://github.com/topcoder-platform/community-app/tree/feature-member-profiles

**Comment by crazyk07** [comment] 2020-01-16 20:15
Contest https://www.topcoder.com/challenges/30112906 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by gets0ul** [comment] 2020-01-20 05:16
@kkartunov is this still open? do you have the screen recording for this issue? Thanks

**Comment by LieutenantRoger** [comment] 2020-01-20 16:51
Hi @topcoder-platform/topcodercompetitors 

This ticket is open for pick up.  

Try to reproduce it on current production page: www.topcoder.com/challenges, you could easily spot the issues will show up.  

Please let me know if you can't reproduce this or have some questions about this.

**Comment by LieutenantRoger** [comment] 2020-01-20 16:55
The fix should be based on branch `hot-fix-performance`

**Comment by gets0ul** [comment] 2020-01-20 17:50
@LieutenantRoger the issue is with pulling up Past challenges with search keyword, right?

**Comment by LieutenantRoger** [comment] 2020-01-21 02:11
Hi @gets0ul  

Yes , it is.

**Comment by crazyk07** [comment] 2020-01-21 08:44
Contest https://www.topcoder.com/challenges/30112906 has been updated - it has been assigned to gets0ul.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by LieutenantRoger** [comment] 2020-01-22 06:41
Per my testing: with the fix, it will show the result in 17s for now. 

We will accept this for now.

**Comment by Oanh-and-only-Oanh** [comment] 2020-01-22 06:42
QA note: This ticket should pass QA if performance is under 18 secs. Thank you.

**Comment by SathyaJayabal** [comment] 2020-01-22 08:56
The time to show the results is based on the keyword that is being searched. For example if you have some recently completed challenges with the searched keyword, the results show up faster. If you do not have any recently completed challenges with the searched keyword, then the search takes longer. 

Also the page becomes more and more unresponsive as we keep searching

**Comment by SathyaJayabal** [comment] 2020-01-22 09:15
please check the video here
https://drive.google.com/open?id=1btecsA2_FqXDooMWLcDUPw345Q4C0ZAe

**Comment by SathyaJayabal** [comment] 2020-01-22 10:14
comment from dev: Hey @picachui thanks for testing, but it seems you are testing not the correct area.  It looks if we use Keyword in the filter panel, it will be searched as a 'tag', but the ticket is trying to fix the 'Search challenges' box when we open up the www.topcoder.com/challenges page.

After retesting as per above comment, search is displaying results below 18 secs . Verified in dev.

**Comment by SathyaJayabal** [comment] 2020-01-23 10:51
@LieutenantRoger , when the user searches for a keyword that is not present in the past challenges, the search results (No Past Challenges found") must be displayed at a reasonable amount of time. At present the search keeps going on for more than a few  minutes.

Please see video

**Comment by SathyaJayabal** [comment] 2020-01-23 10:54
@LieutenantRoger , when the user searches for a keyword that is not present in the past challenges, the search results (Message "No Past Challenges found") must be displayed at a reasonable amount of time. At present the search keeps going on for more than a few minutes.

Please see video
https://drive.google.com/open?id=1jwq43QZpOgPzeR1lv-1b0oi_ErqeBOax
For other examples, the results is displayed within 18 seconds
Please see video
https://drive.google.com/open?id=1rtWNdpDim5mStAYvUVEaBlV7_Ib-qTBu

**Comment by LieutenantRoger** [comment] 2020-01-24 02:24
Hi, @Oanh-and-only-Oanh 

Please take a look above raised issue

**Comment by Oanh-and-only-Oanh** [comment] 2020-01-24 03:48
@LieutenantRoger, what @SathyaJayabal noticed can be logged as a separate issue. Let's accept this fix and close out this ticket. Please open another separate ticket for:
 
"when the user searches for a keyword that is not present in the past challenges, the search results (Message "No Past Challenges found") must be displayed at a reasonable amount of time. At present the search keeps going on for more than a few minutes.

Please see video
https://drive.google.com/open?id=1jwq43QZpOgPzeR1lv-1b0oi_ErqeBOax

**Comment by LieutenantRoger** [comment] 2020-01-24 04:30
Sure. 

Hi @SathyaJayabal  please accept this fix and mark it pass.

**Comment by SathyaJayabal** [comment] 2020-01-29 07:17
Verified in beta
[past search.mov.zip](https://github.com/topcoder-platform/community-app/files/4126638/past.search.mov.zip)

**Comment by SathyaJayabal** [comment] 2020-01-29 11:54
Verified in prod
[past serach prod.mov.zip](https://github.com/topcoder-platform/community-app/files/4127759/past.serach.prod.mov.zip)

**Comment by crazyk07** [comment] 2020-01-29 11:54
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30112906<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed by SathyaJayabal** 2020-01-29 11:54 UTC
Labels: Challenge Listing, P3, Prod Env, QA Pass, tcx_Assigned, tcx_FixAccepted
