### ISSUE TITLE
New nav: when moving from one page to another, first level menu gets collapsed

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2408] opened 2019-06-04 19:35 UTC
**To Reproduce**
1. Go to https://test-community-app.topcoder-dev.com/
2. Login
3. Go to Work -> Compete -> All Challenges
4. Click on one of the challenges
5. Observe that the section "Work" is collapsed in the First Level Nav bar
6. Click on the Work and expand it
7. Click back button present in the challenge details page
7. Observe that the section "Work" is collapsed again

**Expected behavior**
The Collapsed and expanded state of the First Level Nav should be preserved, even if the user navigates to different pages.

**Screenshots**
![image](https://user-images.githubusercontent.com/5114190/58908341-ebbfbb80-872d-11e9-9aa3-b6cf2b6744fd.png)

**Comment by luizrrodrigues** [comment] 2019-06-07 17:29
@Oanh-and-only-Oanh this related to #2397

**Comment by luizrrodrigues** [comment] 2019-06-07 17:51
Duplicate of #2397

**Closed by luizrrodrigues** 2019-06-07 17:51 UTC
Labels: Navigation, P3
