### ISSUE TITLE
non image files should be filtered out (in disabled state) when adding a new image

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#971] opened 2018-06-09 00:43 UTC
### Reported URL ###
https://www.topcoder-dev.com/settings/profile/

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/settings/profile/, delete the profile image if necessary

3. click the ADD IMAGE button, select a folder with many files, observe

### Expected Result ###
non image files should be filtered out (in disabled state) when adding a new image

### Actual Result ###

See screenshot, all files are in enabled state and can be chosen

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment] 2018-06-09 00:43
<img width="1260" alt="non" src="https://user-images.githubusercontent.com/4590317/41185974-2ded5e88-6bc1-11e8-8980-09c786df3cd4.png">

**Comment by winterflame** [comment] 2018-06-11 05:18
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Critical

**Comment by ThomasKranitsas** [comment] 2018-06-13 22:21
duplicate of #1005 it's the same thing actually

**Closed by ThomasKranitsas** 2018-06-13 22:21 UTC
