### ISSUE TITLE
'Link Your Account' is not getting completed- PD - Member - Migration - BLOCKER

### ISSUE THREAD

**Issue by psharneja** [topcoder-platform/community-app#1019] opened 2018-06-10 18:42 UTC
@ThomasKranitsas 
'Link Your Account' is not getting completed, Once the Login Window closes, it gives error, PFA
![screenshot from 2018-06-10 19-26-05](https://user-images.githubusercontent.com/18382400/41205183-23ae5e94-6d0c-11e8-8430-076599267845.png)

**Comment by ThomasKranitsas** [comment] 2018-06-13 21:55
@ajefts @cwdcwd was that fixed on your end? I remember that was a config issue and not related to the code itself.

**Comment by ThomasKranitsas** [comment] 2018-06-13 22:07
Duplicate of https://github.com/topcoder-platform/community-app/issues/1006

**Closed by ThomasKranitsas** 2018-06-13 22:07 UTC
Labels: Blocker, PD - Member - Migration
