### ISSUE TITLE
Date picker is missing for Birth Date on Safari

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1376] opened 2018-09-14 00:53 UTC
**Describe the bug**
There is no date picker for the Birth Date on Safari

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/profile'
2. Click on 'Basic Info'
3. Scroll down to 'Birth Date'
4. Click into the textbox.
5. See error

**Expected behavior**
There should be a date picker, like in other browsers.

**Screenshots**  What you can see there is just the auto fill option icon.
<img width="1280" alt="screenshot 2018-09-14 02 52 53" src="https://user-images.githubusercontent.com/35376779/45523379-4fcdd880-b7c9-11e8-8aa8-acd1bed4059a.png">

**Desktop: MacBook Pro**
 - OS: Mac OS High Sierra
 - Browser: Safari
 - Version: 11.1.2

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment] 2018-09-19 17:03
duplicate of #1305

**Closed by ThomasKranitsas** 2018-09-19 17:03 UTC
