### ISSUE TITLE
Detail page not loading

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#854] opened 2018-05-17 08:33 UTC
@birdofpreyru
With this branch on `mm-features-experiment`

If I hit `http://local.topcoder-dev.com:3000/challenges/30051910` requests stalls for long period of time, and the request doesn't complete. The same challenge is viewable if I navigate from challenge listing click

But I'm on this branch `develop`, it works well.

A similar problem occurred on dev env when I deployed `mm-features-experiment` on dev env

I did try to debug the issue, but I didn't find any errors in console.

similar issue was mentioned by @tonyj yesterday

**Comment by ajefts** [comment] 2018-05-17 11:10
The issue is when you hit the page directly.  If you nav to the page from another page in the app then it loads ok.

**Comment by birdofpreyru** [comment] 2018-05-17 12:12
@sushilshinde @ajefts try now, I have merged latest **develop** into **mm-features-experment**. The fix for the error you saw was just one commit after the fork point for **mm-features-experiment**.

**Closed** 2018-11-15 10:31 UTC
