### ISSUE TITLE
[$50] Challenge prizes are showing wrong

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#5193] opened 2020-11-17 01:54 UTC
**Describe the bug**
The community app is reading the prizes wrongly from the v5 API response. It's reading the first entry in the `prizeSets` array when it should find the one where the `type` is equal to `placement`

**Expected behavior**
The community app should find the correct prize set based on the `type` property.

**Screenshots**
<img width="1708" alt="Screenshot 2020-11-17 at 3 07 07 AM" src="https://user-images.githubusercontent.com/4612921/99330937-70ea5200-2888-11eb-8ba8-c4e9d82656dc.png">

In the above screenshot, it's showing the copilot payment instead of the prizes as the copilot prize set appears first in the array.

See the following two API responses for comparison:
<img width="1101" alt="Screenshot 2020-11-17 at 3 05 53 AM" src="https://user-images.githubusercontent.com/4612921/99331453-970ff200-2888-11eb-8572-2863df998975.png">

**Comment by SathyaJayabal** [comment] 2020-11-17 07:27
cc @luizrrodrigues @Oanh-and-only-Oanh

**Comment by SathyaJayabal** [comment] 2020-11-17 07:32
@ThomasKranitsas , prizes seem good now
<img width="1440" alt="Screenshot 2020-11-17 at 1 01 53 PM" src="https://user-images.githubusercontent.com/58783823/99359443-16c3ae00-28d5-11eb-8faa-a6fd3cffb96a.png">

**Comment by rootelement** [comment] 2020-11-17 14:28
It seems random. I've refreshed a couple times, and it goes back and forth. Not sure why.

**Comment by ThomasKranitsas** [comment] 2020-11-17 15:28
This should be fixed regardless. The `prizeSets` array may contain multiple objects and the frontend can’t just pick the first one blindly assuming it's going to be the placement prizes.

**Comment by luizrrodrigues** [comment] 2020-11-17 15:51
@ThomasKranitsas Yep, agree. I'll as frontend getting the prize.

**Comment by Oanh-and-only-Oanh** [comment] 2020-11-17 17:29
I added prize amount. @luizrrodrigues you can decide how you want to get it fixed.

**Comment by luizrrodrigues** [comment] 2020-11-19 22:12
Contest https://www.topcoder.com/challenges/30152317 has been created for this ticket.<br/><br/>```This is an automated message for luizrrodrigues via Topcoder X```

**Comment by luizrrodrigues** [comment] 2020-11-19 22:13
Contest https://www.topcoder.com/challenges/30152317 has been updated - it has been assigned to luizrrodrigues.<br/><br/>```This is an automated message for luizrrodrigues via Topcoder X```

**Comment by luizrrodrigues** [comment] 2020-11-19 22:35
@SathyaJayabal Deployed in Stag env `tcx-202011` branch.

**Comment by SathyaJayabal** [comment] 2020-11-20 04:23
Verified.
<img width="1440" alt="Screenshot 2020-11-20 at 9 49 50 AM" src="https://user-images.githubusercontent.com/58783823/99757810-2ed64000-2b16-11eb-997d-36db1fc9e6a0.png">

note: @luizrrodrigues , i was not able to reproduce the issue on production too, even after refreshing the challenge details links for many times.
Example links
https://www.topcoder.com/challenges/1df9351c-d027-4a0b-8793-975fda252de9
https://www.topcoder.com/challenges/996f3425-1723-45c2-afea-29a7b0b4e8a0

**Comment by SathyaJayabal** [comment] 2020-11-24 11:06
verified on staging (develop)
<img width="1440" alt="Screenshot 2020-11-24 at 4 35 39 PM" src="https://user-images.githubusercontent.com/58783823/100086256-2f067080-2e73-11eb-85ea-5c349f58e4f5.png">
<img width="1440" alt="Screenshot 2020-11-24 at 4 35 58 PM" src="https://user-images.githubusercontent.com/58783823/100086273-3463bb00-2e73-11eb-82ce-a80d45697938.png">

**Comment by SathyaJayabal** [comment] 2020-11-24 14:15
<img width="1440" alt="Screenshot 2020-11-24 at 7 44 30 PM" src="https://user-images.githubusercontent.com/58783823/100105551-81548b00-2e8d-11eb-98d3-58918176a3b6.png">
<img width="1440" alt="Screenshot 2020-11-24 at 7 44 33 PM" src="https://user-images.githubusercontent.com/58783823/100105576-87e30280-2e8d-11eb-80c2-4a976ffd3e42.png">

**Comment by luizrrodrigues** [comment] 2020-11-24 14:15
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for luizrrodrigues via Topcoder X```

**Comment by luizrrodrigues** [comment] 2020-11-24 14:18
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30152317<br/><br/>```This is an automated message for luizrrodrigues via Topcoder X```

**Closed** 2020-11-24 14:18 UTC
Labels: Challenge Details Screen, Prod QA Pass, tcx_Assigned, tcx_FixAccepted
