### ISSUE TITLE
unable to view user profile from menu

### ISSUE THREAD

**Issue by VaishaliSanthosh** [topcoder-platform/community-app#2578] opened 2019-06-08 09:32 UTC
**Describe the bug**
User is not redirected to user profile when clicked on the user name/avatar
**To Reproduce**
1. Go to  https://test-community-app.topcoder-dev.com/challenges?
2. Click on drop down that is displayed near user name
3. Click on user name/Settings/Payments
4. Noticed that user is not redirected to corresponding page.

**Expected behavior**
User should be redirected on single click

**Screenshots**
![image](https://user-images.githubusercontent.com/29533254/59145224-5e66ba80-89fe-11e9-90b9-c34d14289e9d.png)

**Desktop (please complete the following information):**
OS: Windows 10
Browser Chrome
Version 75.0.3770.80

**Comment by nithyaasworld** [comment] 2019-06-09 18:35
Duplicate of #2402

Please always check for duplicates before logging a new defect!

**Closed by nithyaasworld** 2019-06-09 18:35 UTC
Labels: Bug Hunt, Navigation
