### ISSUE TITLE
[$60]Challenge listings: Recommended challenges must not include challenges the user is registered to

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4438] opened 2020-05-29 08:30 UTC
Challenge listings: Recommended challenges must not include challenges the user is registered to
If you compare V4 and V5 (user:dan_developer/dantopcoder123), you can see the two challenges that show up in V5 must not show up.
V4 Url: https://qa-community-app.topcoder-dev.com/challenges/30051825
V5 Url: https://test-community-app.topcoder-dev.com/challenges/8d5dd850-d275-4948-8678-793c1f4a6925
<img width="1440" alt="Screenshot 2020-05-29 at 11 06 31 AM" src="https://user-images.githubusercontent.com/58783823/83238834-a0ab7d80-a1b4-11ea-9134-db2046d0a324.png">
<img width="1440" alt="Screenshot 2020-05-29 at 11 09 23 AM" src="https://user-images.githubusercontent.com/58783823/83238888-b4ef7a80-a1b4-11ea-9b64-093b29726dd1.png">

**Comment by sushilshinde** [comment] 2020-05-29 08:47
Exclude these challenges

https://github.com/topcoder-platform/challenge-api/blob/3be96fea0fb23480747272434b73be3d846f7ed9/docs/swagger.yaml#L206

**Comment by crazyk07** [comment] 2020-05-29 09:24
Contest https://www.topcoder.com/challenges/30127102 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-05-29 09:28
Contest https://www.topcoder.com/challenges/30127102 has been updated - it has been assigned to Narekvar90.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by narekcat** [comment] 2020-05-29 14:19
@SathyaJayabal @sushilshinde - The member dan_developer registered to one challenge, to see list of challenges go to [here](https://api.topcoder-dev.com/v5/challenges?perPage=50&page=1&memberId=40152905).
![image](https://user-images.githubusercontent.com/11549629/83269876-c0ed3380-a1d8-11ea-91e1-b15b303a9a4c.png)
That challenge is non of shown above. I have tested in my local machine and it works as expected:
![image](https://user-images.githubusercontent.com/11549629/83269736-93a08580-a1d8-11ea-9222-d65178fb2268.png)
![image](https://user-images.githubusercontent.com/11549629/83269767-9dc28400-a1d8-11ea-9b86-bdb538020f56.png)
I think app is working as expected.

**Comment by sushilshinde** [comment] 2020-05-29 17:01
@narekcat @SathyaJayabal can you test and fix that against production data?

**Comment by narekcat** [comment] 2020-05-29 17:52
@sushilshinde - I have tested against production data and V5 api, but there are two challenges and I couldn't register non of them. I can test it if I can register one of this challenges:
http://local.topcoder-dev.com:3000/challenges/d9c74629-762f-4464-9753-ebd982c7990f
http://local.topcoder-dev.com:3000/challenges/55cff8bd-c622-412d-9683-ed85398044f7
Also I have tested it against V4 api and production data and it works correctly.

**Comment by SathyaJayabal** [comment] 2020-05-30 04:48
@sushilshinde I think we need to wait for
- the api to return all the correct challenges registered by the user.
- the user is able to register successfully to a challenge.

**Comment by sushilshinde** [comment] 2020-05-30 12:05
@narekcat wait for other issues to fix, keep this ticket with you. And you can still pick up other issues.

**Comment by sushilshinde** [comment] 2020-05-30 12:06
@SathyaJayabal please mention those other issues

**Comment by narekcat** [comment] 2020-05-30 12:19
@sushilshinde Ok.

**Comment by SathyaJayabal** [comment] 2020-06-01 03:04
> @sushilshinde I think we need to wait for
> 
> * the api to return all the correct challenges registered by the user.
> * the user is able to register successfully to a challenge.

https://github.com/topcoder-platform/community-app/issues/4384
https://github.com/topcoder-platform/community-app/issues/4380

**Comment by SathyaJayabal** [comment] 2020-06-01 07:04
@narekcat , recommended challenges should also not include the current challenge
V5: https://beta-community-app.topcoder.com/challenges/7b880e3f-160e-45b3-a619-c75ecfe3cc4e?tab=details
V4 URL:https://www.topcoder.com/challenges/30126519
This  challenge includes the current challenge in the recommended challenges section
cc @sushilshinde 
<img width="1440" alt="Screenshot 2020-06-01 at 12 32 04 PM" src="https://user-images.githubusercontent.com/58783823/83384111-31c46380-a404-11ea-8239-aa5de100439a.png">

**Comment by narekcat** [comment] 2020-06-01 13:20
@SathyaJayabal I have checked it and it works as expected:
V5: https://beta-community-app.topcoder.com/challenges/7b880e3f-160e-45b3-a619-c75ecfe3cc4e?tab=details
![image](https://user-images.githubusercontent.com/11549629/83412876-f3429f00-a42b-11ea-9ad9-c6e0bbe53d46.png)

**Comment by SathyaJayabal** [comment] 2020-06-02 05:50
@narekcat , its strange, it works as expected now. I will let you know in case I come across any more of these examples.

**Comment by narekcat** [comment] 2020-06-02 05:51
@SathyaJayabal Okay.

**Comment by SathyaJayabal** [comment] 2020-06-02 05:53
@narekcat , please check as logged out user. We can still see the current challenge in recommended challenges.
https://beta-community-app.topcoder.com/challenges/7b880e3f-160e-45b3-a619-c75ecfe3cc4e?tab=details
<img width="1440" alt="Screenshot 2020-06-02 at 11 22 33 AM" src="https://user-images.githubusercontent.com/58783823/83484803-60554380-a4c3-11ea-98e7-2919d19a8c71.png">

**Comment by SathyaJayabal** [comment] 2020-06-02 05:53
@narekcat please check above edit

**Comment by narekcat** [comment] 2020-06-02 05:55
@SathyaJayabal Okay.

**Comment by narekcat** [comment] 2020-06-02 07:08
@SathyaJayabal I can check if user is logged in before showing recommended challenges, but there is nothing about that in challenge specification and this form [thread](https://apps.topcoder.com/forums/?module=Thread&threadID=950302&start=0) the copilot said, that even if user isn't logged in, we must show recommended challenges.  Also if I hide recommended challenges then I need to hide recommended articles.

**Comment by SathyaJayabal** [comment] 2020-06-02 08:12
@narekcat , we have a misunderstanding. The requirement is that the current challenge itself must not be displayed in the recommended challenges section. In the example above we are looking at the  challenge spec for the challenge "Project UBahn | Integrate Elasticsearch in API" . This same challenge is also displayed in recommended challenges which is incorrect. 

please compare:
https://beta-community-app.topcoder.com/challenges/7b880e3f-160e-45b3-a619-c75ecfe3cc4e?tab=details
and
https://www.topcoder.com/challenges/30126519
in logged out state. 

Please let me know if you have any questions?

**Comment by narekcat** [comment] 2020-06-02 13:31
@SathyaJayabal Ok, sorry that was my mistake. I'll be more attentive.

**Comment by sushilshinde** [comment] 2020-06-03 12:46
@narekcat please PR asap

**Comment by narekcat** [comment] 2020-06-03 12:48
@sushilshinde I am waiting to this issues to be fixed.
https://github.com/topcoder-platform/community-app/issues/4384
https://github.com/topcoder-platform/community-app/issues/4380

**Comment by sushilshinde** [comment] 2020-06-03 12:49
ok :)

**Comment by narekcat** [comment] 2020-06-11 14:57
@SathyaJayabal @sushilshinde I have fixed this issue. It works in my local machine with dev beck end. Please see pull request https://github.com/topcoder-platform/community-app/pull/4522.

**Comment by sushilshinde** [comment] 2020-06-11 16:09
Thanks @narekcat

**Comment by SathyaJayabal** [comment] 2020-06-12 05:01
verified on beta
<img width="1440" alt="Screenshot 2020-06-12 at 10 23 51 AM" src="https://user-images.githubusercontent.com/58783823/84466794-e0d02d00-ac97-11ea-8c86-c7ddf291f917.png">

**Comment by SathyaJayabal** [comment] 2020-06-12 05:11
@narekcat 
The prize section is not formatted correctly and data  is displayed twice
<img width="1440" alt="Screenshot 2020-06-12 at 10 36 54 AM" src="https://user-images.githubusercontent.com/58783823/84467115-bd59b200-ac98-11ea-9a6b-c2338bebb9a9.png">

**Comment by narekcat** [comment] 2020-06-12 07:31
@SathyaJayabal Ok, I am working on it.

**Comment by narekcat** [comment] 2020-06-12 10:40
@SathyaJayabal I can't reproduce issue, because it shows error when I trying to open one of the challenges.
![image](https://user-images.githubusercontent.com/11549629/84494380-71b80000-acba-11ea-8486-f6f1cb5cc0fe.png)
I have tried to find out the problem, but couldn't. Do you know what is the reason of this error ?

**Comment by SathyaJayabal** [comment] 2020-06-12 11:04
@narekcat , I can see the challenge details fine. Please share the challenge id for which you are getting this error.
example:
https://test-community-app.topcoder-dev.com/challenges/6d98a924-fdc5-470e-84ab-7506fd45a4c6
Also can u look at the empty icon for the marathon matches shown in the below screenshot.
<img width="1440" alt="Screenshot 2020-06-12 at 4 32 12 PM" src="https://user-images.githubusercontent.com/58783823/84496306-5a810e80-acca-11ea-8945-574c93a4d291.png">

**Comment by narekcat** [comment] 2020-06-12 11:18
@SathyaJayabal I see this error for every challenge. I have merged `integration-v5-challenge-api` into my branch and after that it start to fail.

**Comment by SathyaJayabal** [comment] 2020-06-12 11:24
@sushilshinde , can you help out here.
@narekcat , what is your slack id?

**Comment by narekcat** [comment] 2020-06-12 11:25
@SathyaJayabal My slack id is Narek

**Comment by narekcat** [comment] 2020-06-12 13:57
@SathyaJayabal @sushilshinde I have tested in `integration-v5-challenge-api` branch and error still exist. I think the problem is with this commit github.com/topcoder-platform/topcoder-react-lib/commit/1ac7225d6f49c438ad1d820fa31edef7234907d8. I have checked out to commit before that one by running commant `git checkout 4be3737977d12dfbd1f9f06e917b78bad5423c48`, built topcoder-react-lib in my machine, changed topcoder-react-lib in package.json to my local one and the challenge details page opened correctly.

**Comment by SathyaJayabal** [comment] 2020-06-13 05:19
@narekcat , we see the issue on the latest build on test env. But it seems to be working fine on beta env. 
@sushilshinde , please help.

**Comment by narekcat** [comment] 2020-06-13 07:00
@SathyaJayabal I'll check it again.

**Comment by narekcat** [comment] 2020-06-13 08:37
@SathyaJayabal @sushilshinde  I have fixed UI issue with recommended challenges prize, see pull request https://github.com/topcoder-platform/community-app/pull/4528. 
![image](https://user-images.githubusercontent.com/11549629/84564428-9f608000-ad72-11ea-973a-876ca8750e39.png)
The V5 api doesn't return `subTrack` field in challenge object, that way the marathon matches icon is empty. If we don't need `subTrack` field any more, then I can fix it, but it is new issue.

**Comment by SathyaJayabal** [comment] 2020-06-13 09:41
@narekcat , we can see the subtrack in the listings page, so V% api should have that data. . I will  open another issue, if the fix includes additional effort. Let us know. cc @sushilshinde 

<img width="1440" alt="Screenshot 2020-06-13 at 3 09 13 PM" src="https://user-images.githubusercontent.com/58783823/84565632-06d4fa80-ad88-11ea-92b2-1a361b3bec22.png">

<img width="1440" alt="Screenshot 2020-06-13 at 3 08 55 PM" src="https://user-images.githubusercontent.com/58783823/84565617-f3299400-ad87-11ea-8bc6-9b082a2ae201.png">

**Comment by narekcat** [comment] 2020-06-13 09:51
@SathyaJayabal Ok, I can fix this issue. It requires additional efforts, please open new issue.

**Comment by sushilshinde** [comment] 2020-06-14 02:34
yes, please open it

**Comment by SathyaJayabal** [comment] 2020-06-15 03:34
Verified on test and beta
<img width="1440" alt="Screenshot 2020-06-15 at 8 50 14 AM" src="https://user-images.githubusercontent.com/58783823/84615643-30f0fe80-aee7-11ea-9afb-6cfe2467fe79.png">
<img width="1440" alt="Screenshot 2020-06-15 at 9 03 54 AM" src="https://user-images.githubusercontent.com/58783823/84615657-39493980-aee7-11ea-9859-8653fa4d5afc.png">

**Comment by crazyk07** [comment] 2020-06-15 11:30
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30127102<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed** 2020-06-15 11:29 UTC
Labels: Beta Env, Challenge Details Screen, P3, QA Pass, Test Env, dependent-on-another-issue-fix, tcx_Assigned, tcx_FixAccepted, v5-intgration-sub-code
