### ISSUE TITLE
[$10]Search icon is not focused nor read out as search icon

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3087] opened 2019-07-25 15:11 UTC
**Steps to Reproduce**
1. Go to https://www.topcoder.com/community/accessibility-testing
2. Hit tab key in page
3. Hit until reads out support

**Expected Result**
search icon should be read out and focused

**Actual Result**
Search icon is not focused nor read out as search icon

**Device**: Desktop/Labtop
**Browser**: All
**WCAG Category**: 2. Operable
**WCAG Level**: A
**WCAG Success Criterion**: 2.4.3 Focus Order
**Screen Reader Used**: Voiceover
**Accessibility Audit Tool used**: N/A

**Attachment**
https://topcodermsft-my.sharepoint.com/personal/msft-copilots_topcodermsft_onmicrosoft_com/Documents/Forms/All.aspx?cid=09f22811%2D138e%2D4d3b%2Da8d5%2Dd3693a709128&FolderCTID=0x0120005C598A51049FC14CBA882E1AEE168F51&id=%2Fpersonal%2Fmsft%2Dcopilots%5Ftopcodermsft%5Fonmicrosoft%5Fcom%2FDocuments%2F%5BFAST%5D%20Test%20for%20Accessibility%20Series%2FCreeya%2FBug%2D3

**Comment by cwdcwd** [comment] 2019-07-25 20:49
Contest https://www.topcoder.com/challenges/30097701 has been created for this ticket.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 20:49
Contest https://www.topcoder.com/challenges/30097701 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 20:50
Contest https://www.topcoder.com/challenges/30097701 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by kkartunov** [comment] 2019-07-26 07:21
@topcoder-platform/topcodercompetitors this is open for pickup. PR against `qa-accessibility` branch.

**Comment by crazyk07** [comment] 2019-07-26 12:26
Contest https://www.topcoder.com/challenges/30097701 has been updated - it has been assigned to rohitgupta_.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by r0hit-gupta** [comment] 2019-07-26 12:26
Duplicate of https://github.com/topcoder-platform/community-app/issues/3071

**Comment by PrakashDurlabhji** [comment] 2019-07-26 13:02
@r0hit-gupta  this is completed by one of my PR

**Comment by crazyk07** [comment] 2019-07-31 06:50
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed by crazyk07** 2019-07-31 06:50 UTC
Labels: Contentful, Duplicate
