### ISSUE TITLE
Chrome-Members – My Challenges are not getting listed in the member page.

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#1039] opened 2018-06-11 06:04 UTC
13. Summary:
Chrome-Members – My Challenges are not getting listed in the member page.
### Reproduction Steps ###
1.Log in as pshah_manager/topcoder123
2.Go to https://www.topcoder-dev.com/members/pshah_manager/( If you didn’t get expected UI, Please move the mouse towards pshah_manage on the right hand top corner ->Click Setting -> Again Click Profile) 
3.View the My Challenge Section.(You wont fine any challenge)
4.Now go to https://www.topcoder-dev.com/my-dashboard and View the “My Active challenges”
5.Observe the UI
### Actual  Result ###
Chrome-Members – My Challenges are not getting listed in the member page.
## Expected Result ###
Chrome-Members – My Challenges should be getting listed in the member page.
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated
Device: Window
OS: Windos 10 
Browser: Chrome

**Comment by youdare** [comment] 2018-06-11 06:05
![image](https://user-images.githubusercontent.com/31862600/41214934-7296d450-6d6b-11e8-9ab4-f5aca4432e9e.png)
![image](https://user-images.githubusercontent.com/31862600/41214943-7bd0ad3e-6d6b-11e8-8d19-ae43a063ea8f.png)

**Comment by youdare** [comment] 2018-06-11 19:28
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment] 2018-06-14 10:50
Duplicate of #987 the challenges tab is not implemented so it won't show up for any track/subTrack

**Closed by ThomasKranitsas** 2018-06-14 10:50 UTC
