### ISSUE TITLE
[$15] [FUNCTIONAL]  Country is a required field and it doesn't allow to save the profile without it, however, it was not required until you get in the update profile form

### ISSUE THREAD

**Issue by karinakohl** [topcoder-platform/community-app#1468] opened 2018-09-15 22:46 UTC
**Describe the bug**
Country is a required field and it doesn't allow to save the profile without it, however, it was not required until you get in the update profile form

**To Reproduce**
1. Go to Settings/profile/basic info just after create you account (through you email)
2. See that Country is empty
3. Scroll down to "Save Changes" button
4. See error "Country cannot be empty"

**Expected behavior**
If I create my account without the need to include country and I can navigate through topcoder without update it, it should not me mandatory when you go to your profile settigs page

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.5
 - Browser chrome
 - Version 69.0.3497.92

**Comment by karinakohl** [comment] 2018-09-16 00:58
@thomaskranitsas

**Comment by ThomasKranitsas** [comment] 2018-09-26 13:04
Contest https://www.topcoder.com/challenges/30071864 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-26 13:04
Contest https://www.topcoder.com/challenges/30071864 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-26 13:04
@topcoder-platform/topcodercompetitors this is open for pickup.

**Comment by ThomasKranitsas** [comment] 2018-09-26 13:10
Contest https://www.topcoder.com/challenges/30071864 has been updated - it has been assigned to sr_jr.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by simranb86** [comment] 2018-09-26 13:54
@ThomasKranitsas i see lot of issues reported with node 8.2.1, do i have to use any specific node version to build the project ? Kindly suggest.

**Comment by ThomasKranitsas** [comment] 2018-09-26 13:56
there is a `.nvmrc` file in the repo which defines the exact versions of node/npm you need to use.

If you have nvm installed you can run `nvm use` and it should pick the correct versions automatically.

**Comment by simranb86** [comment] 2018-09-26 18:17
@ThomasKranitsas Are we saying we need to make `Country` optional? If yes, then we will need to fix `JOIN US` flow too, as we have made it mandatory there now.  See 👇 

![countryfix](https://user-images.githubusercontent.com/40840038/46100137-535c5900-c1e6-11e8-8182-ef08ade2e943.jpg)

`I think we should force to update country, while we are moving to new application.`  Kindly suggest how we want to move ahead on this?

**Comment by simranb86** [comment] 2018-09-27 05:09
@ThomasKranitsas did you had a chance to look at this? Kindly confirm and will push in fix for making it optional, if we need it that way.

**Comment by ThomasKranitsas** [comment] 2018-09-27 13:00
No, the country is a required field.

What you need to investigate and fix is why the settings page doesn't pick the Country the user has selected in the registration flow.

**Comment by simranb86** [comment] 2018-09-27 13:28
@ThomasKranitsas Thanks, i just verified - it picks up fine and when i change it, it changes it fine too. So, next time i sign in and land onto Settings Screen i see the new country which i saved last time. 

So, this seems to be working fine now. Please validate once and confirm, if you still see issues.

**Comment by simranb86** [comment] 2018-09-27 13:33
`Expected behavior
If I create my account without the need to include country and I can navigate through topcoder without update it, it should not me mandatory when you go to your profile settigs page`

@ThomasKranitsas looks like we should close this - ☝️ expected behavior by reportee...

**Comment by ThomasKranitsas** [comment] 2018-09-27 13:40
I remember we've faced that issue again in the past. Specifically when choosing `USA`. I'll soon make some backend changes that may fix this.

I'll put this one on hold.

**Comment by simranb86** [comment] 2018-09-27 16:05
@ThomasKranitsas FYI - i did USA and then Virgin to test as options and it worked fine.

**Comment by ThomasKranitsas** [comment] 2018-10-11 14:14
Contest https://www.topcoder.com/challenges/30071864 has been updated - it has been assigned to sr_jr.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-10-11 14:14
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30071864<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed** 2018-10-11 14:14 UTC
Labels: Major, New Settings Page, On hold, tcx_Assigned, tcx_FixAccepted
