### ISSUE TITLE
[$40]Sub community filter not working

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4575] opened 2020-06-22 06:23 UTC
The sub community filter is not working
example:
https://beta-community-app.topcoder.com/challenges?communityId=wipro
communityId filter has to be updated to work with V5.

<img width="1440" alt="Screenshot 2020-06-22 at 11 52 26 AM" src="https://user-images.githubusercontent.com/58783823/85254906-e3443b00-b47e-11ea-85d0-c387f1230e2f.png">
<img width="1440" alt="Screenshot 2020-06-22 at 11 52 34 AM" src="https://user-images.githubusercontent.com/58783823/85254928-e9d2b280-b47e-11ea-9081-079af3b4f1ca.png">

**Comment by crazyk07** [comment] 2020-06-22 10:20
Contest https://www.topcoder.com/challenges/30130676 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-06-22 10:22
Contest https://www.topcoder.com/challenges/30130676 has been updated - it has been assigned to nursoltan-s.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by nursoltan-s** [comment] 2020-06-23 06:41
1. where community Id should come from?  "challenge.metadata" or "challenge.events" ?
2. How can i fetch all communityId's from API?

@rootelement @sushilshinde

**Comment by nursoltan-s** [comment] 2020-06-23 06:42
And can you please create some challenges as "Blockchain community" for testing purpose? Thanks

**Comment by SathyaJayabal** [comment] 2020-06-23 07:26
@nursoltan-s
Please check this link for blockchain challenges. You can also refer to how the sub community filter is used here. This is part fix for #4393 
https://test-community-app.topcoder-dev.com/__community__/blockchain/challenges?communityId=blockchain
jcori/appiro123
<img width="1440" alt="Screenshot 2020-06-23 at 12 52 34 PM" src="https://user-images.githubusercontent.com/58783823/85373230-97fa5d00-b550-11ea-905c-c2ceb1a84a35.png">

**Comment by nursoltan-s** [comment] 2020-06-25 07:13
@sushilshinde @SathyaJayabal @rootelement 

Hi. I've question for this one.
We're filtering by sub-communities using `groupIds` field. 
But some `groupIds` array is empty from returning `CommunityFilters`. For example: in TCO20 community, groupIds is empty. How can we handle if groupId is empty?

![Screenshot from 2020-06-25 15-09-38](https://user-images.githubusercontent.com/7783676/85673215-412e8800-b6f6-11ea-8b5a-4910f06a077c.png)

**Comment by crazyk07** [comment] 2020-07-04 02:10
Contest https://www.topcoder.com/challenges/30130676 has been updated - sr_jr has been unassigned.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-07-04 02:11
Contest https://www.topcoder.com/challenges/30130676 has been updated - sr_jr has been unassigned.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-07-04 02:12
Contest https://www.topcoder.com/challenges/30130676 has been updated - sr_jr has been unassigned.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by simranb86** [comment] 2020-07-04 02:13
@sushilshinde I think I know the issue, but not able to assign myself.

**Comment by crazyk07** [comment] 2020-07-04 02:13
Contest https://www.topcoder.com/challenges/30130676 has been updated - sr_jr has been unassigned.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-07-04 02:27
Contest https://www.topcoder.com/challenges/30130676 has been updated - it has been assigned to sr_jr.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by simranb86** [comment] 2020-07-05 02:03
@sushilshinde @rootelement this looks like API issue too - https://api.topcoder-dev.com/v5/challenges?group=20000010 returns nothing,  (20000010 is group id for blockchain)

**Comment by luizrrodrigues** [comment] 2020-07-20 17:20
@simranb86 you need call this with group **UUID** instead **legacyId**:

```
https://api.topcoder-dev.com/v5/challenges/?groups=b8fe66cc-935f-4986-a1cf-5e1dee943e8a&groups=713a5be0-48b1-44dd-94fe-f3d9a94209f1`
```

![image](https://user-images.githubusercontent.com/7029641/87966751-1dabf280-ca94-11ea-87ff-424c3ecb1fa4.png)

**Comment by crazyk07** [comment] 2020-07-21 04:30
Contest https://www.topcoder.com/challenges/30130676 has been updated - it has been assigned to luizrrodrigues.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by sushilshinde** [comment] 2020-08-24 09:39
@luizrrodrigues please update progress

**Comment by luizrrodrigues** [comment] 2020-08-24 10:23
@sushilshinde Already find the issue and testing the solution right now.

**Comment by luizrrodrigues** [comment] 2020-08-26 08:30
@sushilshinde PRs ready ☝️

**Comment by SathyaJayabal** [comment] 2020-08-27 12:59
@luizrrodrigues , filter working for sub-communities, but not for events
<img width="1440" alt="Screenshot 2020-08-27 at 6 27 19 PM" src="https://user-images.githubusercontent.com/58783823/91445033-2eba0180-e893-11ea-96ed-5a4c9229bf81.png">
<img width="1440" alt="Screenshot 2020-08-27 at 6 28 43 PM" src="https://user-images.githubusercontent.com/58783823/91445043-34174c00-e893-11ea-9015-8dbd601d7cbe.png">

**Comment by luizrrodrigues** [comment] 2020-08-27 13:48
@SathyaJayabal The issue is with missing var in Staging (@sushilshinde will add this)

@sushilshinde I also included a hotfix to tco19 (I forget to update this one before)

**Comment by luizrrodrigues** [comment] 2020-08-28 18:53
@SathyaJayabal This one waiting for env vars set.

@sushilshinde Let me know when done.

**Comment by sushilshinde** [comment] 2020-08-31 05:51
I'll set this today

**Comment by SathyaJayabal** [comment] 2020-08-31 10:45
verified on prod
<img width="1440" alt="Screenshot 2020-08-31 at 3 57 27 PM" src="https://user-images.githubusercontent.com/58783823/91712327-2ae4f280-eba5-11ea-93a6-680066e92da4.png">

**Comment by SathyaJayabal** [comment] 2020-09-01 12:12
verified on staging(develop branch)
<img width="1440" alt="Screenshot 2020-09-01 at 5 40 57 PM" src="https://user-images.githubusercontent.com/58783823/91849927-6a314300-ec7a-11ea-8d82-01a3548cbbe2.png">
<img width="1440" alt="Screenshot 2020-09-01 at 5 41 03 PM" src="https://user-images.githubusercontent.com/58783823/91849942-6f8e8d80-ec7a-11ea-8027-e169e4febbff.png">

**Comment by SathyaJayabal** [comment] 2020-09-01 13:05
verified on prod
<img width="1440" alt="Screenshot 2020-09-01 at 6 34 11 PM" src="https://user-images.githubusercontent.com/58783823/91854773-db282900-ec81-11ea-97d7-220a8fb562f6.png">
<img width="1440" alt="Screenshot 2020-09-01 at 6 34 18 PM" src="https://user-images.githubusercontent.com/58783823/91854784-e0857380-ec81-11ea-9bbb-63040b08c389.png">

**Comment by crazyk07** [comment] 2020-09-01 13:06
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-09-01 13:15
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30130676<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed** 2020-09-01 13:15 UTC
Labels: Challenge Listing, P1, Prod Env, QA Pass, tcx_Assigned, tcx_FixAccepted, v5-intgration-sub-code
