### ISSUE TITLE
**No proper validation in Name and Address**

### ISSUE THREAD

**Issue by ra304413** [topcoder-platform/community-app#915] opened 2018-06-08 20:12 UTC
**Reported URL**:https://www.topcoder-dev.com/settings/account/

**How to replicate**:Go to https://www.topcoder-dev.com/settings/account/ and enter numerical values in  name and address bar. Even if we give wrong values the data will get submitted.

**Actual Issue**:See screenshot

![validation_address_name](https://user-images.githubusercontent.com/40026802/41178898-6896bdb2-6b86-11e8-9140-1c596a15b3b7.PNG)

OS: Windows 10
Browser:Google chrome Version 67.0.3396.79 (Official Build) (64-bit)

**Comment by youdare** [comment] 2018-06-14 02:29
@ThomasKranitsas 

This defect is duplicate of #899

**Closed** 2018-06-14 12:10 UTC
Labels: Major, PD - Member - Migration
