### ISSUE TITLE
[$60] IDEA GENERATION challenges are not shown

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2192] opened 2019-03-17 05:14 UTC
![2](https://user-images.githubusercontent.com/42398485/54485595-94563180-4849-11e9-97c8-6db7d21b85a7.png)

1. Open the application and login as TonyJ
2. Go to https://www.topcoder.com/members/winterflame/details/?track=DEVELOP&subTrack=IDEA_GENERATION&tab=challenges

**Actual:** IDEA GENERATION challenges are not shown

**Expected:** Should show the 2 available challenges in the list

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10 | Browser: Google Chrome 73.0.3683.75

**Comment by ThomasKranitsas** [comment] 2019-03-22 22:27
Contest https://www.topcoder.com/challenges/30087010 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-03-22 22:27
Contest https://www.topcoder.com/challenges/30087010 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-03-22 23:13
Contest https://www.topcoder.com/challenges/30087010 has been updated - it has been assigned to gurmeetb.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by gurmeetb** [comment] 2019-03-24 06:02
@ThomasKranitsas taking some time as not able to replicate for mentioned but another user I tried, it worked fine. Giving me a few more hrs, else will open.

**Comment by ThomasKranitsas** [comment] 2019-03-24 11:35
@gurmeetb sure, no problem. I know it's a weird issue. Take as much time as you need

**Comment by ThomasKranitsas** [comment] 2019-03-24 11:35
Contest https://www.topcoder.com/challenges/30087010 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by gurmeetb** [comment] 2019-03-24 17:05
@ThomasKranitsas tried this via POSTMAN too, it doesn't bring in any IDEA_GENERATION challenges for winterflame

https://api.topcoder.com/v4/members/winterflame/challenges/?limit=50&offset=0

Opening up for others since spent a good time on this.

**Comment by ThomasKranitsas** [comment] 2019-03-24 17:17
Contest https://www.topcoder.com/challenges/30087010 has been updated - it has been assigned to rohitgupta_.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-03-25 19:33
Contest https://www.topcoder.com/challenges/30087010 has been updated - it has been assigned to rohitgupta_.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by r0hit-gupta** [comment] 2019-03-26 10:07
@ThomasKranitsas looks like there is an issue with the backend service. None of the challenges are received when using IDEA_GENERATION filter. I can take a look at the API code if you like.

**Comment by gurmeetb** [comment] 2019-03-26 20:24
> @ThomasKranitsas looks like there is an issue with the backend service. None of the challenges are received when using IDEA_GENERATION filter. I can take a look at the API code if you like.

@r0hit-gupta try for user talesforce, if not wrong it was returning 1 challenge for IDEA_GENERATION.

**Comment by r0hit-gupta** [comment] 2019-03-27 19:27
@gurmeetb I am not able to see any IDEA GENERATION challenges for user talesforce. Its showing 0 challenges.

**Comment by ThomasKranitsas** [comment] 2019-03-30 21:36
Contest https://www.topcoder.com/challenges/30087010 has been updated - it has been assigned to PkDurlabhji.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-04-05 19:15
Contest https://www.topcoder.com/challenges/30087010 has been updated - it has been assigned to PkDurlabhji.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by gurmeetb** [comment] 2019-04-21 06:52
@ThomasKranitsas can you open this so I can give second try?

**Comment by PrakashDurlabhji** [comment] 2019-04-21 07:04
@ThomasKranitsas sorry for delaying. you can open it as I failed rather I open myself now

**Comment by ThomasKranitsas** [comment] 2019-04-21 07:06
Contest https://www.topcoder.com/challenges/30087010 has been updated - it has been assigned to nahidshahin.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by nahidshahin** [comment] 2019-04-21 16:08
@ThomasKranitsas tried with `TonyJ` but no challenges of `IDEA_GENERATION` found. Can you please create test data?

**Comment by ThomasKranitsas** [comment] 2019-04-21 16:25
Let's close this for now as it seems not reproducible. We may open it later if we manage to reproduce it again.

**Comment by ThomasKranitsas** [comment] 2019-04-21 16:25
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed by ThomasKranitsas** 2019-04-21 16:25 UTC
Labels: Major, tcx_Assigned
