### ISSUE TITLE
Can't open "All projects" page

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2427] opened 2019-06-07 17:56 UTC
### Reproduction Steps: ###

1. Open https://test-community-app.topcoder-dev.com/challenges
2. Login with account: dan_developer/dantopcoder123
3. Try to click on arrow beside avatar 
4. Click on "All projects" item and observe result

### Expected Result: ###
Direct to "All projects" page without any Error.

### Actual Result: ###
Can't open "All projects" page.

### Screenshots or screencast: ###

See comment

### Browser Information: ###

Google Chrome 74.0 on Windows 10

**Comment by HongHT** [comment] 2019-06-07 19:05
https://gyazo.com/fd22f670d4d9bc32196b6d15a8930b1d

**Comment by nithyaasworld** [comment] 2019-06-09 19:15
Duplicate of https://github.com/topcoder-platform/community-app/issues/2395

**Closed by nithyaasworld** 2019-06-09 19:15 UTC
Labels: Bug Hunt, Navigation
