### ISSUE TITLE
[$40] Adding <br> tag in Contentful WYSIWYG creates too many breaks

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#1662] opened 2018-10-04 17:37 UTC
**Describe the bug**
When adding a break tag (<br>) to create space between text, tables, etc, the system adds more break tags than necessary

**To Reproduce**
1. Within a Content Block or Banner, write some text.
2. Press "return" or "enter" to go to a new line and write more text.
3. Preview the result.  Notice how one text of line follows another. That's fine, but sometimes we need more space in between.
4. Go back to Content Block and add a <br> in between the two lines.
5. Preview again and notice the massive amount of space between the text.
6. Check the Inspector and notice multiple break tags.

**Expected behavior**
One break line providing a normal amount of space between text, tables, etc.  2 breaks concurrently should create one more line of space and so on.

**Screenshots**
With no break:
<img width="731" alt="screen shot 2018-10-04 at 10 23 21 am" src="https://user-images.githubusercontent.com/1373998/46492027-4d0b4580-c7c1-11e8-80e7-b03966f2d6a4.png">
<img width="1025" alt="screen shot 2018-10-04 at 10 28 27 am" src="https://user-images.githubusercontent.com/1373998/46492039-5694ad80-c7c1-11e8-8623-9e3b00346c3c.png">

With one break tag in between tables:
<img width="727" alt="screen shot 2018-10-04 at 10 23 30 am" src="https://user-images.githubusercontent.com/1373998/46492070-67ddba00-c7c1-11e8-885b-226fe20ec0c1.png">
<img width="1334" alt="screen shot 2018-10-04 at 10 24 59 am" src="https://user-images.githubusercontent.com/1373998/46492072-68765080-c7c1-11e8-950a-effb5e275939.png">

**Comment by ThomasKranitsas** [comment] 2018-10-04 17:47
Contest https://www.topcoder.com/challenges/30072327 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-10-04 17:47
Contest https://www.topcoder.com/challenges/30072327 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-10-04 17:48
@topcoder-platform/topcodercompetitors this is open for pickup!

**Comment by ThomasKranitsas** [comment] 2018-10-04 17:48
Contest https://www.topcoder.com/challenges/30072327 has been updated - it has been assigned to daga_sumit.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sumitdaga** [comment] 2018-10-05 09:07
@ThomasKranitsas  
how to reproduce/test this issue?
is the WYSIWYG  part of the community app ?

**Comment by sumitdaga** [comment] 2018-10-05 10:29
@hokienick 
i don't think there is any issue on the community app side!
its possible that the two extra `<br>`  are because the `<br>` statement itself is on a new line  
so possibly,
1. you press enter , a `<br>` is introduced
2. on the next line you write `<br>` and then again press enter which introduces another `<br>`

so total 3 `<br>` statements
if you could try writing the `<br>` statement inline

also, i may be completely wrong :)

**Comment by hokienick** [comment] 2018-10-05 16:07
I'll keep that in mind!  Thanks @sumitdaga

**Comment by sumitdaga** [comment] 2018-10-05 18:36
@hokienick  
i am guessing you are adding content from the [contentful](https://www.contentful.com/) dashboard  
if so, i am afraid we can't really do anything about this

**Comment by hokienick** [comment] 2018-10-12 20:41
Ok, thank you for looking into this!  @ThomasKranitsas we can consider this closed.

**Comment by ThomasKranitsas** [comment] 2018-10-12 20:53
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed** 2018-10-13 12:31 UTC
Labels: tcx_Assigned, tcx_FixAccepted

**Comment by ThomasKranitsas** [comment] 2018-10-13 12:34
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30072327<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```
