### ISSUE TITLE
[$30][MSFT-231] [Challenge Feed][NVD] Prizes are incorrectly read-out by the Screen reader

### ISSUE THREAD

**Issue by veshu** [topcoder-platform/community-app#2889] opened 2019-07-17 07:09 UTC
**Steps to Reproduce**
1. Go to https://www.topcoder.com/challenges
2. Hover over the purse and then hover over the prizes

**Expected Result**
Should read-out the prizes correctly

**Actual Result**
Prizes are incorrectly read-out by the Screen reader

**Device**: Desktop/Labtop
**Operating System**: Windows
**Browser**: Chrome

**WCAG Category**: 1. Perceivable
**WCAG Level**: A
**WCAG Success Criterion**: 1.3.1 Info and Relationships
**Screen Reader Used**: Other
**Accessibility Audit Tool used**: N/A

**Attachment**
https://topcodermsft-my.sharepoint.com/personal/pd-topcoder_topcodermsft_onmicrosoft_com/Documents/Forms/All.aspx?cid=58da9b68%2Df2a3%2D45d2%2Dbbae%2D15abdfd0865b&FolderCTID=0x0120005C598A51049FC14CBA882E1AEE168F51&sortField=Modified&isAscending=true&id=%2Fpersonal%2Fpd%2Dtopcoder%5Ftopcodermsft%5Fonmicrosoft%5Fcom%2FDocuments%2FMSFT%2DTeams%2DQA%2FJune%202019%2F29%20Jun%2FTest%20Results%2FBug%20Videos%20%26%20Log%20Files%2Fcodejam%2DAccessibility%2F67

**Comment by ThomasKranitsas** [comment] 2019-07-18 09:57
Contest https://www.topcoder.com/challenges/30096023 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-19 08:14
Contest https://www.topcoder.com/challenges/30096023 has been updated - it has been assigned to daga_sumit.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by sumitdaga** [comment] 2019-07-19 08:14
@veshu  
i cannot reproduce this issue, can you give an example when it does not work!

**Comment by veshu** [comment] 2019-07-19 08:45
@sumitdaga Are you using this tool https://www.nvaccess.org/?

**Comment by sumitdaga** [comment] 2019-07-19 08:51
@veshu no i am using the [narrator](https://support.microsoft.com/en-in/help/22798/windows-10-complete-guide-to-narrator) app that comes with windows 10

**Comment by veshu** [comment] 2019-07-19 08:56
@sumitdaga This was raised using [NVD] tool. Some member has used title to define the tool they have used. Please check with NVD once, it must be replicable. Else we can ask QA reviewer to confirm.

Have you checked the video in attachment? It is reading improperly.

**Comment by sumitdaga** [comment] 2019-07-19 09:31
@veshu  i think i don't have access to the attachment video!  
but i used the NVD tool and it seems to read the correct amount

**Comment by veshu** [comment] 2019-07-19 09:48
@sumitdaga https://apps.topcoder.com/forums/?module=Thread&threadID=940852&start=0

There are credentials shared for one drive.  

The issue is it is not reading correctly. like it should be able read as "First prize is $1000, second prize 500" on hover but it said "one $1000, 2 500". Please check the video.

Regarding assignment yes you can pick another. I will get confirm with QA member till. Thanks!

**Comment by veshu** [comment] 2019-07-19 09:52
@drasticdpk @tosha5252 Can you please check if above issue is replicable or not.

**Comment by PrakashDurlabhji** [comment] 2019-07-19 17:40
@veshu I am able to replicate hence trying to solve it

**Comment by cwdcwd** [comment] 2019-07-19 17:41
Contest https://www.topcoder.com/challenges/30096023 has been updated - it has been assigned to PkDurlabhji.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-19 18:44
Contest https://www.topcoder.com/challenges/30096023 has been updated - it has been assigned to rashmi73.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by rashmi73** [comment] 2019-07-20 13:56
@veshu @codeMinter ready https://github.com/topcoder-platform/community-app/pull/2980

**Comment by cwdcwd** [comment] 2019-07-24 23:10
[500]: Challenge for the updated issue 2889 is creating, rescheduling this event<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-24 23:11
[400]: Failed to create challenge. Detail: Operation failed in the contest service facade.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-24 23:11
[400]: Failed to create challenge. Detail: Operation failed in the contest service facade.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-24 23:11
[500]: Challenge for the updated issue 2889 is creating, rescheduling this event<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-24 23:11
[500]: Challenge for the updated issue 2889 is creating, rescheduling this event<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-24 23:12
[400]: Failed to create challenge. Detail: Operation failed in the contest service facade.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-24 23:12
[400]: Failed to create challenge. Detail: Operation failed in the contest service facade.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 00:14
[500]: Challenge for the updated issue 2889 is creating, rescheduling this event<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 00:14
[500]: Challenge for the updated issue 2889 is creating, rescheduling this event<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 00:14
[504]: Failed to create challenge.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 00:14
[504]: Failed to create challenge.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 00:20
Contest https://www.topcoder.com/challenges/30097071 has been created for this ticket.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 00:28
Contest https://www.topcoder.com/challenges/30097071 has been updated - it has been assigned to rashmi73.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by rashmi73** [comment] 2019-07-28 07:46
@veshu yes updating, and i will paste verification video for same

**Comment by rashmi73** [comment] 2019-07-28 21:29
@veshu suddenly it has stopped working, i remember it was working well. watching it

**Comment by veshu** [comment] 2019-07-29 08:31
@rashmi73 Any update on this thanks!

**Comment by crazyk07** [comment] 2019-07-30 21:30
Contest https://www.topcoder.com/challenges/30097071 has been updated - it has been assigned to gets0ul.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by drasticdpk** [comment] 2019-07-31 09:43
Verified on 
Operating System: Windows
Browser: Chrome

**Comment by lakshmiathreya** [comment] 2019-07-31 16:02
Prizes are ready correctly on mouse hover. However, Prizes are skipped when tabbing from Skill list to # of participants. Hence setting to Fail.

**Comment by gets0ul** [comment] 2019-07-31 16:06
@lakshmiathreya 
That is out of scope of this issue requirement.
The expected result is to read out the prize in natural language on hovering.

**Comment by lakshmiathreya** [comment] 2019-07-31 16:46
@gets0ul - since 'Prizes being skipped' is addressed by #2828, closing this Issue.

**Comment by crazyk07** [comment] 2019-07-31 16:46
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30097071<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed by lakshmiathreya** 2019-07-31 16:46 UTC
Labels: Accessibility, Challenge Listing, P0, Prod QA Pass, tcx_FixAccepted
