### ISSUE TITLE
[$40]When traversing page using arrow key, the page is announced in loops.

### ISSUE THREAD

**Issue by veshu** [topcoder-platform/community-app#3250] opened 2019-08-21 14:06 UTC
**Describe the bug**

When traversing page using arrow key, the page is announced in loops.

**To Reproduce**
1. Go to the sample challenge page
2. Ensure that the screen reader is switched on. 
3.  Traverse to the last element in the page

**Expected behavior**
Should stop reading page at the end

**Actual behavior**
Once we reach the end of page and again down arrow is pressed, JAWS starts reading the page from starting. This should not happen.

**Additional context**

Type: Other

Page: https://www.topcoder.com/challenges/30098252

**Comment by crazyk07** [comment] 2019-08-21 17:06
Contest https://www.topcoder.com/challenges/30099931 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2019-08-21 17:07
Contest https://www.topcoder.com/challenges/30099931 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2019-08-21 20:40
Contest https://www.topcoder.com/challenges/30099931 has been updated - it has been assigned to nithyaasworld.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by veshu** [comment] 2019-08-26 15:20
@topcoder-platform/topcodercompetitors

This is open for pickup, Let us know if any concern. Thanks!

**Comment by veshu** [comment] 2019-08-27 04:02
@topcoder-platform/topcodercompetitors prize is doubled here.

**Comment by gets0ul** [comment] 2019-08-27 17:04
Can't reproduce it using down arrow key.  
Do you have video for this issue?

**Comment by veshu** [comment] 2019-08-28 03:33
@drasticdpk @lakshmiathreya 

Is this valid issue as I tested with github with tab key and once it reaches down to page, in next tab it will reach top and continues the same.

If it is valid could you please share the video with JAWS.

**Comment by drasticdpk** [comment] 2019-08-28 06:52
@veshu, below is my  finding.
For Tab key it is working as expected. Here tester is asking for arrow down key too. With down arrow key, JAWS is speaking last control(Which is also same in w3.org, github too.) and JAWS does not start reading the page from starting. So it is not issue.
Here is the reference :
https://monosnap.com/file/iR9UikgsBCAEAA2bMVGy7zJ1bTOsJ4

**Comment by veshu** [comment] 2019-08-28 06:54
@crazyk07 @Oanh-and-only-Oanh closing this based on confirmation from @drasticdpk 

cc @lakshmiathreya @tosha5252

**Closed** 2019-08-28 06:59 UTC
Labels: Accessibility, Can't Reproduce, Challenge Page, P3
