### ISSUE TITLE
[$80] SSF: When DataScience filter is removed, it is not showing right results

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2696] opened 2019-07-01 14:15 UTC
1. Go to https://beta-community-app.topcoder.com/challenges
2. Turn off Data Science filter and check

Actual:
It displays only 3 results and that too under the section "Open for registration"

However, When only Design filter is turned off (Dev and DS filter in On), it fetches right results.

Expected:
It should display all the sections like "My challenges", "Open for registration", etc with right number of results.

![image](https://user-images.githubusercontent.com/5114190/60443394-ce9ce080-9c38-11e9-9025-49e2f2b0a985.png)

**Comment by nithyaasworld** [comment] 2019-07-01 14:22
@sushilshinde This one seems to be new one too. Last time, I tested for about 2 hours and I did not see these issues.

**Comment by sushilshinde** [comment] 2019-07-01 14:22
ok

**Comment by ThomasKranitsas** [comment] 2019-07-02 10:21
@topcoder-platform/tcxcommunity @topcoder-platform/topcodercompetitors open for pickup

PR on ’ssf-merged-to-new-develop’ branch

**Comment by ThomasKranitsas** [comment] 2019-07-02 10:21
Contest https://www.topcoder.com/challenges/30094926 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-07-02 10:21
Contest https://www.topcoder.com/challenges/30094926 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-07-02 10:24
Contest https://www.topcoder.com/challenges/30094926 has been updated - it has been assigned to mhykol.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-07-03 08:12
@mhikeo what's the status here?

**Comment by mhikeo** [comment] 2019-07-03 08:21
hi @ThomasKranitsas. I'm unable to replicate this issue. Btw, I think fix for #2698 removed the logic for Design, Development & Data Science filtering.

**Comment by gurmeetb** [comment] 2019-07-03 08:23
Hi @ThomasKranitsas I can give this a try ?

**Comment by mhikeo** [comment] 2019-07-03 08:24
@gurmeetb you may take it

**Comment by ThomasKranitsas** [comment] 2019-07-03 08:26
Contest https://www.topcoder.com/challenges/30094926 has been updated - it has been assigned to gurmeetb.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by PrakashDurlabhji** [comment] 2019-07-03 08:26
@mhikeo i guess that logic was not properly working because it was unecessarily appending subtracks for which filter is not applied, hence subtracks were concated, and request parameter string was not correct.

I hope i have not missed anything major in that.

@ThomasKranitsas can you please review that

**Comment by ThomasKranitsas** [comment] 2019-07-03 08:28
@PrakashDurlabhji are you saying you fixed this in https://github.com/topcoder-platform/community-app/pull/2710 ?

**Comment by gurmeetb** [comment] 2019-07-03 08:28
@ThomasKranitsas should we keep this on hold until we verify #2698 ?

**Comment by ThomasKranitsas** [comment] 2019-07-03 08:28
I guess so. I'll verify if this has been fixed shortly.

**Comment by gurmeetb** [comment] 2019-07-03 08:30
Sure @ThomasKranitsas - kindly flag me here once verified, I will start work then.

**Comment by PrakashDurlabhji** [comment] 2019-07-03 08:38
@ThomasKranitsas not sure whether this issue is also covered in that PR, but i guess this issue should exist.

**Comment by ThomasKranitsas** [comment] 2019-07-03 08:56
@gurmeetb - https://github.com/topcoder-platform/community-app/pull/2710 does not fix this issue. You may work on this

**Comment by sushilshinde** [comment] 2019-07-04 04:37
@gurmeetb this is urgent

**Comment by gurmeetb** [comment] 2019-07-04 04:40
@sushilshinde sorry missed it, on it now, give me an hour max

**Comment by gurmeetb** [comment] 2019-07-04 05:41
@sushilshinde @ThomasKranitsas This looks like no more an issue - when I select Data Science only, I see only MM challenges, and when selected the other 2, it showed right no of challenges. 

This is `no longer a bug`, if you could help share the env where you are facing - I can try to see there too once but locally I don't see this issue now.

**Comment by gurmeetb** [comment] 2019-07-04 05:44
Also verified with Challenges counts, it all looks good.

**Comment by gurmeetb** [comment] 2019-07-04 05:55
@nithyaasworld I have tried with latest code on local and on beta, don't see this is an issue anymore. Can you help re-verify this once ?

**Comment by sushilshinde** [comment] 2019-07-05 06:18
@gurmeetb please proceed on this

**Comment by gurmeetb** [comment] 2019-07-05 09:05
@sushilshinde this looks to be working fine to me on beta with SSF. 

I have requested @nithyaasworld to re-validate once on beta. Let's wait for her update.

**Comment by nithyaasworld** [comment] 2019-07-05 09:35
The above scenario is working in Beta. But other combination which worked earlier is not working.

As part of this ticket, let's make sure that all combination of filters work.


![image](https://user-images.githubusercontent.com/5114190/60713153-26d42b00-9f36-11e9-9e0d-2ef4304837c2.png)

**Comment by nithyaasworld** [comment] 2019-07-05 09:49
@gurmeetb Just a FYI: You can see from this video (https://github.com/topcoder-platform/community-app/issues/2695#issuecomment-507270732) that this has worked earlier during my last testing and broken recently :(

So in order to make sure that nothing gets broken after this fix, I would like to verify all the filters available in Challenge listing page. 

Thanks.

**Comment by gurmeetb** [comment] 2019-07-05 10:01
@ThomasKranitsas ☝️ is breaking due to fix for https://github.com/topcoder-platform/community-app/issues/2698 - can you please re-open #2698 and ask the developer to provide non-breaking fix? 

@nithyaasworld we can close this as `Not a Bug` and we will track the above issue in #2698 - If I try to fix the above issue, means I need to revert the changes done in #2698 and we might go into loop.

**Comment by ThomasKranitsas** [comment] 2019-07-05 10:11
@PrakashDurlabhji ☝️

**Comment by ThomasKranitsas** [comment] 2019-07-05 10:13
@PrakashDurlabhji can you please check this and provide a fix?

**Comment by sushilshinde** [comment] 2019-07-05 16:15
@topcoder-platform/tcxcommunity @topcoder-platform/topcodercompetitors open for pickup

PR on ’ssf-merged-to-new-develop’ branch

**Comment by ThomasKranitsas** [comment] 2019-07-05 16:18
Contest https://www.topcoder.com/challenges/30094926 has been updated - it has been assigned to rashmi73.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2019-07-05 16:29
@rashmi73 this is P1, please submit asap

**Comment by rashmi73** [comment] 2019-07-05 16:59
@sushilshinde yes sure, but is this reproducible? looking at above comments?
only one case needs to be handled or all?

**Comment by nithyaasworld** [comment] 2019-07-05 18:50
@rashmi73 
The original issue described in this ticket is resolved but another issue with the filter is introduced. That is, It fetches MM matches when Dev filter is applied.

So once this has been fixed, I will be checking all the filters available in the challenge listing page to make sure no filters are broken.

![image](https://user-images.githubusercontent.com/5114190/60713153-26d42b00-9f36-11e9-9e0d-2ef4304837c2.png)

**Comment by rashmi73** [comment] 2019-07-05 20:02
@nithyaasworld @sushilshinde issue stated above in screenshot is not reproducible on my machine.

I visited https://beta-community-app.topcoder.com/challenges?filter[tracks][develop]=true

and i dont find any "MM" challenge on page.

so it is working perfectly fine.

what to do now then?

**Comment by gurmeetb** [comment] 2019-07-05 20:13
@rashmi73 click view more challenges for Open for Registration

**Comment by rashmi73** [comment] 2019-07-05 21:48
@sushilshinde @gurmeetb @ThomasKranitsas @nithyaasworld 
I analyzed complete scenario and found out that:

1.In issue #2698, prakash solved that ticket scenario perfectly  and also main title of this issue, but other scenarios started breaking.

2. so i reverted whatever prakash did, so on reverting, actual issue of 2698 comes back, so analyzed  and added additional conditions to satisfy all scenarios without breaking anything.

3. it is tested and working well on my local machine and PR is created.

https://github.com/topcoder-platform/community-app/pull/2718

Kindly check it and confirm if all is satisfied.

**Comment by sushilshinde** [comment] 2019-07-06 05:42
@ThomasKranitsas please review the PR?

**Comment by sushilshinde** [comment] 2019-07-08 17:32
@nithyaasworld PR merged for this issue

**Comment by sushilshinde** [comment] 2019-07-09 03:55
@nithyaasworld can you please verify fix

**Comment by nithyaasworld** [comment] 2019-07-09 11:30
@sushilshinde @rashmi73 

I tested the scenario given in this ticket description. I find that "My challenges" section is not displayed after removing the DataScience filter however I see the right panel a count of 8 for "My Challenges".

I did not proceed to check further on this ticket, as for every filter I apply, I have to wait for more than 45 seconds to see the result.

So I would like to test this after https://github.com/topcoder-platform/community-app/issues/2695 has been fixed. Thanks.

![image](https://user-images.githubusercontent.com/5114190/60884579-daa52580-a26a-11e9-8309-2b280ee3beb2.png)

**Comment by sushilshinde** [comment] 2019-07-09 13:11
ok thanks

**Comment by nithyaasworld** [comment] 2019-07-10 04:46
@rashmi73 I have changed the label to "tcx_feedback", so you can verify the issue stated in my last comment.

As noted earlier, complete testing on this ticket will be done once #2695 is fixed.

Thanks.

**Comment by nithyaasworld** [comment] 2019-07-12 03:07
@rashmi73 Please check my last 2 comments and proceed fixing. Thanks.

**Comment by rashmi73** [comment] 2019-07-18 23:00
@sushilshinde can we close this now?

**Comment by rashmi73** [comment] 2019-07-20 11:20
@nithyaasworld @sushilshinde any updates on this?

**Comment by nithyaasworld** [comment] 2019-07-20 14:03
Hey @rashmi73 

> I tested the scenario given in this ticket description. I find that "My challenges" section is not displayed after removing the DataScience filter however I see the right panel a count of 8 for "My Challenges".

is the above issue resolved?

**Comment by rashmi73** [comment] 2019-07-21 14:34
@nithyaasworld it is working fine on https://beta-community-app.topcoder.com/challenges. could you please confirm?

**Comment by rashmi73** [comment] 2019-07-24 11:29
@sushilshinde @nithyaasworld even here my efforts are wasted? will I atleast get paid for this? response is expected atleast here.

**Comment by nithyaasworld** [comment] 2019-07-24 11:57
@rashmi73 

Sorry I missed to notice your above comment.

> @nithyaasworld it is working fine on https://beta-community-app.topcoder.com/challenges. could you please confirm?

I don't think we still have the SSF fixes in the beta environment. We should be checking this on with Server Side Rendering Fixes.

**Comment by rashmi73** [comment] 2019-07-24 12:01
@nithyaasworld can you please help me a bit?

can you please ask @sushilshinde via slack to comment on https://github.com/topcoder-platform/community-app/issues/2359

**Comment by cwdcwd** [comment] 2019-07-25 03:08
[500]: Challenge for the updated issue 2696 is creating, rescheduling this event<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 03:08
[500]: Challenge for the updated issue 2696 is creating, rescheduling this event<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 03:08
[504]: Failed to create challenge.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 03:08
[504]: Failed to create challenge.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 03:39
Contest https://www.topcoder.com/challenges/30097459 has been created for this ticket.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 03:44
Contest https://www.topcoder.com/challenges/30097459 has been updated - it has been assigned to rashmi73.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by nithyaasworld** [comment] 2019-09-11 06:53
@rashmi73 @sushilshinde 

> I tested the scenario given in this ticket description. I find that "My challenges" section is not displayed after removing the DataScience filter however I see the right panel a count of 8 for "My Challenges".

This issue is still present. 

Also it took 40 seconds to load the results when DS filter is turned off.

**Comment by nithyaasworld** [comment] 2019-09-13 14:45
@rashmi73 It is NOT on production. It is about the SSR Fixes. I am not sure which branch it is. 

> I tested the scenario given in this ticket description. I find that "My challenges" section is not displayed after removing the DataScience filter however I see the right panel a count of 8 for "My Challenges".

Seems like the issue is not always reproducible. It was reproducible yesterday and NOT reproducible in the morning today and again reproducible now. Please find the screenshot below.

![image](https://user-images.githubusercontent.com/5114190/64871540-0e356f00-d663-11e9-9aac-7b076bdfb885.png)

**Comment by rashmi73** [comment] 2019-11-15 08:44
@sushilshinde can we close this now? PR for this issue was merged with I explaining a long discussion. 
@nithyaasworld

**Comment by rashmi73** [comment] 2019-11-19 09:37
@sushilshinde waiting for this.

@nithyaasworld request you to help me by notifying sushilshinde to comment on this issue. thanks

**Comment by nithyaasworld** [comment] 2019-11-19 09:41
@rashmi73 can you please share me the PR link?

As per my last testing results, we had some[ issue](https://github.com/topcoder-platform/community-app/issues/2696#issuecomment-531265886)

**Comment by rashmi73** [comment] 2019-11-19 10:17
@nithyaasworld here is PR link https://github.com/topcoder-platform/community-app/pull/2718

which was merged and working fine on that respective branch, after that I guess branch was merged to some other branch and finally to production

**Comment by rashmi73** [comment] 2019-11-19 18:40
@nithyaasworld any updates on above?

@sushilshinde

**Comment by rashmi73** [comment] 2019-11-20 08:34
@nithyaasworld request you once again to please notify @sushilshinde via slack to please comment here.

**Comment by rashmi73** [comment] 2019-11-21 19:01
@ThomasKranitsas even you used to take followup this ticket, hence requesting you too to take some action it or atleast notify @sushilshinde , to close it.
@jmgasper

**Closed** 2019-11-22 10:09 UTC
Labels: P1, Performance, tcx_Assigned, tcx_Feedback, tcx_FixAccepted

**Comment by rashmi73** [comment] 2019-11-22 10:13
@sushilshinde thanks, will check payment for this ticket too by EOD today

**Comment by rashmi73** [comment] 2019-11-23 19:07
@sushilshinde payment is not reflected in pacts yet. can you please confirm once again thanks

**Comment by sushilshinde** [comment] 2020-01-09 06:12
@rashmi73 this is done

FYI... @rootelement
