### ISSUE TITLE
[$40] Settings>Account>Linked Accounts: The "HEADS UP!" popup doesn't fit inside the page on mobile

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2119] opened 2019-03-16 08:39 UTC
**To Reproduce**
1. Open the application and login as TonyJ
2. Hover over the profile avatar > Click Settings
3. Click Account Tab > Linked Accounts
4. Cick button [delete link]: show "HEADS UP!" popup

**Actual:**
The width of "HEADS UP!" popup is bigger than the width of screen so it is cropped

**Expected**
The "HEADS UP!" popup should be fit inside the page

**Screenshots**

![viber image 2019-03-16 , 15 37](https://user-images.githubusercontent.com/26895101/54472824-88df1800-4801-11e9-9b8e-0410858c4e89.jpg)
![viber image 2019-03-16 , 15 37 03](https://user-images.githubusercontent.com/26895101/54472825-8977ae80-4801-11e9-8e95-846845e9ea0c.jpg)

** Environments:**
 - Device: Oppo F7, android 8.1
 - Browser [The latest Chrome]

**Comment by ThomasKranitsas** [comment] 2019-03-21 19:47
Contest https://www.topcoder.com/challenges/30086885 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-03-21 19:47
Contest https://www.topcoder.com/challenges/30086885 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-03-21 20:54
Contest https://www.topcoder.com/challenges/30086885 has been updated - it has been assigned to rohitgupta_.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by r0hit-gupta** [comment] 2019-03-21 21:06
Unable to reproduce this. The Modal fits exactly within the page for me.

**Comment by ThomasKranitsas** [comment] 2019-03-21 21:08
Please try on iPhone X.

**Comment by r0hit-gupta** [comment] 2019-03-21 21:38
Was able to reproduce and fix the issue. Please review.

**Comment by ThomasKranitsas** [comment] 2019-03-21 21:42
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30086885<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed** 2019-03-21 21:42 UTC
Labels: Minor, tcx_Assigned, tcx_FixAccepted
