### ISSUE TITLE
[$5] Error message shows up for second on the Account tab

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/community-app#5868] opened 2021-11-28 10:00 UTC
1. Open your profile.
2. click on the Account tab
3. Observe

Some error message shows up then disappears.

![Screenshot_2021-10-22_at_17.04.16](/uploads/ea7a18789de9d5c8f80cfa0ff7ea8329/Screenshot_2021-10-22_at_17.04.16.png)

Device: Laptop 
OS: MacOS Catalina 
Browser: Safari

**Comment by LieutenantRoger** [comment] 2021-11-30 13:36
Challenge https://www.topcoder.com/challenges/9ff06697-183e-4aae-9651-1ea1728c2e3b has been created for this ticket.<br/><br/>```This is an automated message for lieutenantroger via Topcoder X```

**Comment by LieutenantRoger** [comment] 2021-12-01 17:29
Challenge https://www.topcoder.com/challenges/9ff06697-183e-4aae-9651-1ea1728c2e3b has been assigned to LieutenantRoger.<br/><br/>```This is an automated message for lieutenantroger via Topcoder X```

**Comment by codejamtc** [comment] 2021-12-02 04:22
Can't reproduce it on Windows https://test-community-app.topcoder-dev.com/settings/account

https://user-images.githubusercontent.com/42398485/144357162-14b59034-a10c-41a2-9037-fbb8467c234c.mp4

**Comment by coderhacker** [comment] 2021-12-07 15:29
This is fixed on the stage.
![image](https://user-images.githubusercontent.com/62358241/145057961-39fe7cea-9cbc-49fa-8074-9109a4d2ca35.png)

**Comment by coderhacker** [comment] 2021-12-08 13:02
This is passed on to production

![image](https://user-images.githubusercontent.com/62358241/145211970-75337933-7401-41c8-a179-f90d5ac0fe4b.png)

**Comment by LieutenantRoger** [comment] 2021-12-08 13:03
Payment task has been updated: https://www.topcoder.com/challenges/9ff06697-183e-4aae-9651-1ea1728c2e3b
*Payments Complete*
Winner: LieutenantRoger
Challenge `9ff06697-183e-4aae-9651-1ea1728c2e3b` has been paid and closed.<br/><br/>```This is an automated message for lieutenantroger via Topcoder X```

**Closed by coderhacker** 2021-12-08 13:02 UTC
Labels: tcx_Assigned, tcx_FixAccepted, P3, QA Pass in PROD, Prod Env, Functional, QA Pass on Test, QA Pass in Staging, Staging Env, FE, CF, Valid
