### ISSUE TITLE
[FAST-70] Attachments is not getting focused while pressing tab key in the support popup.

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#3068] opened 2019-07-25 15:10 UTC
**Steps to Reproduce**
1. Login to https://www.topcoder.com/community/accessibility-testing.
2. Press tab using keyboard and move till support.
3. Press tab key in the support popup.
4. Observe whether Attachments option is getting highlighted.

**Expected Result**
Attachments option should get highlighted while pressing tab key.

**Actual Result**
Attachments option is not getting highlighted while pressing tab key.

**Device**: Desktop/Labtop
**Browser**: Chrome

**WCAG Category**: 3. Understandable
**WCAG Level**: A
**WCAG Success Criterion**: 2.1.1 Keyboard
**Screen Reader Used**: Other
**Accessibility Audit Tool used**: N/A

**Attachment**
https://topcodermsft-my.sharepoint.com/personal/msft-copilots_topcodermsft_onmicrosoft_com/Documents/Forms/All.aspx?cid=4ba34fa6%2D44e7%2D4e38%2D93a1%2D614b30b97b51&FolderCTID=0x0120005C598A51049FC14CBA882E1AEE168F51&id=%2Fpersonal%2Fmsft%2Dcopilots%5Ftopcodermsft%5Fonmicrosoft%5Fcom%2FDocuments%2F%5BFAST%5D%20Test%20for%20Accessibility%20Series%2Fjackgid16%2FBug3

**Comment by hokienick** [comment] 2019-07-25 19:18
Duplicate of #3110

**Closed by hokienick** 2019-07-25 19:18 UTC
Labels: Contentful, Duplicate
