### ISSUE TITLE
UX: Drop down symbol is not displayed for "Work" tab.

### ISSUE THREAD

**Issue by sraarum** [topcoder-platform/community-app#2506] opened 2019-06-07 19:57 UTC
**Describe the bug**
UX: Drop down symbol is not displayed for "Work" tab.

**To Reproduce**
1. In Mobile, Navigate to "https://test-community-app.topcoder-dev.com/challenges"
2. Login to Topcoder
3. Click on Menus on Top left corner
4. Works is displayed without any drop-down.
5. User will not understand if there are further options under Works unless clicked on it.

**Expected behavior**
Dropdown should be included like included for Community tab. Following screenshots will clarify.

**Screenshots**
Attached
![Screenshot_20190608-011435](https://user-images.githubusercontent.com/41059603/59130243-81588680-898c-11e9-979e-a3a73c6a9d09.png)
![1559937311389_0_IMG-20190608-WA0000](https://user-images.githubusercontent.com/41059603/59130251-8ae1ee80-898c-11e9-9297-a63f4fbe6dc3.jpg)

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
Device: Nokia 8.1
OS: Android 9
Browser : Chrome
Version : 75.0.3770.67

**Additional context**

**Comment by nithyaasworld** [comment] 2019-06-10 07:06
Thanks @sraarum But this is as per the design.

**Comment by sraarum** [comment] 2019-06-10 10:09
@nithyaasworld: Nithya I have added 2 screenshots for comparison. 1st screenshot is the right one but didn't highlight work tab. Thanks for your help.

**Comment by luizrrodrigues** [comment] 2020-01-10 11:23
@nahidshahin Any status on this one?

**Comment by yoution** [comment] 2020-01-11 02:29
@luizrrodrigues  please assign to me, and I do not know how to show the 'work' tab, I can only show the 'community' tab.Please tell me how to show the 'work' tab.
![image](https://user-images.githubusercontent.com/3863914/72197524-35f3e280-345d-11ea-8868-9e7adf1e5083.png)

**Comment by luizrrodrigues** [comment] 2020-01-11 02:48
@yoution WORK was renamed to COMMUNITY

**Comment by luizrrodrigues** [comment] 2020-01-13 20:05
@yoution Please what is the status in this one?

**Comment by yoution** [comment] 2020-01-13 22:46
@luizrrodrigues I can not reproduct the issue

**Comment by luizrrodrigues** [comment] 2020-01-14 01:08
@yoution Thanks for check.

**Comment by nithyaasworld** [comment] 2020-01-21 13:18
Cannot reproduce this in production too

**Comment by luizrrodrigues** [comment] 2020-01-21 21:11
@nithyaasworld Please add QA Pass here

**Comment by SathyaJayabal** [comment] 2020-02-04 09:35
Closing this as it cannot be reproduced

**Closed by SathyaJayabal** 2020-02-04 09:35 UTC
Labels: Can't Reproduce, Navigation, P3, UX
