### ISSUE TITLE
[$10][MSFT-133] [Challenge Page] Details, Registration and Submission tabs skipped by the screen reader

### ISSUE THREAD

**Issue by veshu** [topcoder-platform/community-app#2829] opened 2019-07-17 07:06 UTC
**Steps to Reproduce**
1. Go to https://www.topcoder.com/challenges/30095032
2. Switch on the screen reader
3. Tap on the page header and press tab button until it reaches to the challenge forum tab
2. Listen

**Expected Result**
It should be read-out by the screen reader

**Actual Result**
Details, Registration and Submission tabs skipped by the screen reader

**Device**: Desktop/Labtop
**Operating System**: Windows
**Browser**: Chrome

**WCAG Category**: 1. Perceivable
**WCAG Level**: A
**WCAG Success Criterion**: 1.3.2 Meaningful Sequence
**Screen Reader Used**: JAWS
**Accessibility Audit Tool used**: N/A

**Attachment**
https://topcodermsft-my.sharepoint.com/personal/pd-topcoder_topcodermsft_onmicrosoft_com/Documents/Forms/All.aspx?cid=6aa53cde%2D1eef%2D4bae%2Dbfe5%2Df5f5f79e9df4&FolderCTID=0x0120005C598A51049FC14CBA882E1AEE168F51&sortField=Modified&isAscending=true&id=%2Fpersonal%2Fpd%2Dtopcoder%5Ftopcodermsft%5Fonmicrosoft%5Fcom%2FDocuments%2FMSFT%2DTeams%2DQA%2FJune%202019%2F29%20Jun%2FTest%20Results%2FBug%20Videos%20%26%20Log%20Files%2Fcodejam%2DAccessibility%2F43

**Comment by ThomasKranitsas** [comment] 2019-07-18 09:38
Contest https://www.topcoder.com/challenges/30095994 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-07-18 09:38
Contest https://www.topcoder.com/challenges/30095994 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by r0hit-gupta** [comment] 2019-07-18 19:19
Please assign me

**Comment by cwdcwd** [comment] 2019-07-18 22:34
Contest https://www.topcoder.com/challenges/30095994 has been updated - it has been assigned to rohitgupta_.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by codeMinter** [comment] 2019-07-24 13:39
@r0hit-gupta please create separate PR per ticket.

**Comment by cwdcwd** [comment] 2019-07-25 00:50
[400]: Failed to create challenge. Detail: Operation failed in the contest service facade.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 00:50
[400]: Failed to create challenge. Detail: Operation failed in the contest service facade.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 00:51
[500]: Challenge for the updated issue 2829 is creating, rescheduling this event<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 00:52
[400]: Failed to create challenge. Detail: Operation failed in the contest service facade.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 00:52
[400]: Failed to create challenge. Detail: Operation failed in the contest service facade.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 02:48
[500]: Challenge for the updated issue 2829 is creating, rescheduling this event<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 02:48
[500]: Challenge for the updated issue 2829 is creating, rescheduling this event<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 02:48
[504]: Failed to create challenge.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 02:48
[504]: Failed to create challenge.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 03:28
[400]: Failed to create challenge. Detail: Operation failed in the contest service facade.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 03:28
[400]: Failed to create challenge. Detail: Operation failed in the contest service facade.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 03:33
[500]: Challenge for the updated issue 2829 is creating, rescheduling this event<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 03:33
[400]: Failed to create challenge. Detail: Operation failed in the contest service facade.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 03:33
[400]: Failed to create challenge. Detail: Operation failed in the contest service facade.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 03:33
[500]: Challenge for the updated issue 2829 is creating, rescheduling this event<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 03:34
[400]: Failed to create challenge. Detail: Operation failed in the contest service facade.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 03:34
[400]: Failed to create challenge. Detail: Operation failed in the contest service facade.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 04:01
[400]: Failed to create challenge. Detail: Operation failed in the contest service facade.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 04:01
[400]: Failed to create challenge. Detail: Operation failed in the contest service facade.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 04:06
[500]: Challenge for the updated issue 2829 is creating, rescheduling this event<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 04:06
[500]: Challenge for the updated issue 2829 is creating, rescheduling this event<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 04:06
[500]: Challenge for the updated issue 2829 is creating, rescheduling this event<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 04:06
[500]: Challenge for the updated issue 2829 is creating, rescheduling this event<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 04:11
[504]: Failed to create challenge.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 04:11
[504]: Failed to create challenge.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 04:33
Contest https://www.topcoder.com/challenges/30097552 has been created for this ticket.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 04:38
Contest https://www.topcoder.com/challenges/30097552 has been updated - it has been assigned to rohitgupta_.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by r0hit-gupta** [comment] 2019-07-25 16:40
@codeMinter the changes are only for a single issue. Coincidentally, it also fixes an another issue. Should I make two separate PRs with the same changes?

**Comment by veshu** [comment] 2019-07-25 17:01
@r0hit-gupta you looks agreed here https://github.com/topcoder-platform/community-app/issues/2822 to separate issue. If really duplicate then I will close this one and add prize to another issue.

**Comment by r0hit-gupta** [comment] 2019-07-25 17:13
@veshu I thought I had made a mistake, but upon closer inspection, change for one issues fixes another too. This issue is a subset https://github.com/topcoder-platform/community-app/issues/2822

**Comment by veshu** [comment] 2019-07-25 17:48
ok @codeMinter please consider this while review.

**Comment by r0hit-gupta** [comment] 2019-07-25 17:50
@veshu @codeMinter PR https://github.com/topcoder-platform/community-app/pull/2947 was closed. Can you please reopen and review. Thanks!

**Comment by codeMinter** [comment] 2019-07-26 18:54
@veshu we cannot track it to Prod deployment such cases, so we can close one and keep one, marking the other as Duplicate.

Let's get PR for #2822 as it is superset of this ticket.

**Comment by r0hit-gupta** [comment] 2019-07-26 18:58
Duplicate of #2822

**Comment by crazyk07** [comment] 2019-07-31 08:23
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30097552<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed** 2019-07-31 08:22 UTC
Labels: Accessibility, Dependency, Ready for Prod QA, tcx_FixAccepted
