### ISSUE TITLE
[$15] User Interface bug in Firefox 62.0 browser on Linux Mint 18

### ISSUE THREAD

**Issue by NehaSharma02** [topcoder-platform/community-app#1451] opened 2018-09-14 21:10 UTC
The height of the button named 'Add Hobby to your list" is not proper.

The link: https://www.topcoder.com/settings/profile

UI bug screenshot is attached. 
![selection_674](https://user-images.githubusercontent.com/37835397/45575346-d4375e80-b890-11e8-9b90-1b79d4eca2d8.png)

Please check and fix.

@birdofpreyru 
cc @ajefts

**Comment by ThomasKranitsas** [comment] 2018-09-29 13:04
Contest https://www.topcoder.com/challenges/30072047 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-29 13:04
Contest https://www.topcoder.com/challenges/30072047 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-29 13:05
@topcoder-platform/topcodercompetitors this is open for pickup

**Comment by sumitdaga** [comment] 2018-09-29 16:39
PR #1631 
@ThomasKranitsas 
i don't have linux mint 18 :) but i am guessing the issue is because of fixed width on the button and hence this should fix the issue ...

**Comment by ThomasKranitsas** [comment] 2018-09-30 13:28
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-30 13:29
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30072047<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-30 13:31
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-30 13:33
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-30 13:35
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-30 13:35
Payment failed: [400]: Failed to update challenge. Detail: javax.ejb.EJBTransactionRolledbackException<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-30 13:37
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-10-02 14:50
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed** 2018-10-05 17:50 UTC
Labels: tcx_FixAccepted, tcx_ReadyForReview
