### ISSUE TITLE
Change Forums setting in Profile settings need from legacy forums to Vanilla

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#5461] opened 2021-04-01 17:44 UTC
**Describe bug:**
When user clicks on Forums Settings in Profile settings here https://www.topcoder.com/settings/preferences, user is taken to legacy forums settings here https://apps.topcoder.com/forums/?module=Settings
![image](https://user-images.githubusercontent.com/47536078/113333453-4c42c400-92d7-11eb-9f2a-2df2198f1304.png)

**Expected behavior:**
**IDEALLY**, When user clicks on Forums Settings, the vanilla Forums settings page should be imbedded into Community App. It should NOT take the user to a separate page to manage their forums notification preferences. You can check with @jmgasper for help. See design below:
![image](https://user-images.githubusercontent.com/47536078/113335928-7f3a8700-92da-11eb-96af-fd1d2164a52b.png)

If embedding is not an option (too difficult), then when user clicks on Forums Settings, a new window opens to https://discussions.topcoder.com/profile/preferences

**Comment by hokienick** [comment] 2021-04-01 18:03
![forum preferences](https://user-images.githubusercontent.com/1373998/113335472-d55afa80-92d9-11eb-9817-5c3853fe4dcb.png)

**Comment by luizrrodrigues** [comment] 2021-04-01 18:53
Duplicate of #5433

**Closed** 2021-04-01 19:59 UTC
Labels: Forums, P1, Profile Settings
