### ISSUE TITLE
Devices - add lookup data

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#3547] opened 2020-01-07 17:37 UTC
When  users are adding devices to their profiles, allow them to select from structured data values instead of free form text entry.  For example, right now someone needs to type in "iPhone 6".  So, we have that data entered in different ways:  "iphone 6", "IPHONE 6", "iphone6", etc. 

<p></p>

The value add here is that this data helps us understand the capacity in the community to do work that requires specific devices, such as testing mobile apps.

**Comment by ajefts** [comment] 2020-01-07 17:37
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1763052

**Comment by SathyaJayabal** [comment] 2020-02-10 06:34
@drasticdpk, I cant find the feature on the product board. Can you add the link to the feature description or challenge spec ?

**Comment by drasticdpk** [comment] 2020-02-10 06:48
@SathyaJayabal  here the requested details :
https://www.topcoder.com/challenges/30113988?tab=details

**Comment by SathyaJayabal** [comment] 2020-02-10 08:44
1. Contact support should be a link to email support
<img width="959" alt="Screenshot 2020-02-10 at 1 44 44 PM" src="https://user-images.githubusercontent.com/58783823/74132013-a1230700-4c0b-11ea-915b-abdf857f9010.png">


@drasticdpk , Clarifications needed for the below
1. Can you share the rules on the order in which the device data is displayed once it is added. There seems to be some discrepancies from production. 
Example:
When  Only Type and Manufacturer is added, Production displays Manufacturer first and dev displays Type first. There are similar differences as to what is displayed on the first line and what is displayed below. 
<img width="856" alt="Screenshot 2020-02-10 at 1 31 53 PM" src="https://user-images.githubusercontent.com/58783823/74131216-e34b4900-4c09-11ea-86dd-ba67cd0e3eb5.png">
<img width="838" alt="Screenshot 2020-02-10 at 1 32 18 PM" src="https://user-images.githubusercontent.com/58783823/74131222-e5150c80-4c09-11ea-95d1-f3359fcebdd1.png">


2. Can you data where you have more than one model for a manufacturer and more than one OS for a model ? Can you also add data where you have more than 100 records in a drop down?

**Comment by SathyaJayabal** [comment] 2020-02-10 09:08
@drasticdpk 
1. Unable to add user trait error.
Steps to reproduce:
1. Add only one device 
2. click on edit the device
3. Delete the device
4. Now edit the device in the still open edit window
5. click on "Edit Device to your list"

See video 
[edit device.mov.zip](https://github.com/topcoder-platform/community-app/files/4179834/edit.device.mov.zip)

<img width="1409" alt="Screenshot 2020-02-10 at 2 25 46 PM" src="https://user-images.githubusercontent.com/58783823/74135052-9c615180-4c11-11ea-829d-f3889d54fbe1.png">

2. Another similar issue is (this issue also happens in production):

1. add two devices ( A and B)
2. click edit for on device A
3. now delete the device A
4. edit device A using the still open edit window and save the edit
5. Device B will be updated with the new changes.

See video
[edit delete device.mov.zip](https://github.com/topcoder-platform/community-app/files/4179849/edit.delete.device.mov.zip)

**Comment by Oanh-and-only-Oanh** [comment] 2020-02-10 17:14
@drasticdpk and @SathyaJayabal, regarding 1. "Contact support should be a link to email support", this doesn't need to be a link.

**Comment by drasticdpk** [comment] 2020-02-11 07:48
@SathyaJayabal , I have requested API team to update data accordingly to meet the test scenario. 
FYI Meantime you can test that scenario from postman too. 
https://github.com/topcoder-platform/lookups-api/tree/develop/docs

**Comment by drasticdpk** [comment] 2020-02-24 12:20
@SathyaJayabal 
> Can you share the rules on the order in which the device data is displayed once it is added. There seems to be some discrepancies from production.

 Updated as production.  
>Can you data where you have more than one model for a manufacturer and more than one OS for a model ? Can you also add data where you have more than 100 records in a drop down?

To meet this scenario, please use Device Type: "Smartphone", Manufacturer : "Samsung" 

Other issue has been fixed please test.
Note : Please don't select device type as "Mobile" it is no longer going to be in the dropdown. (already informed API team to remove it.

**Comment by SathyaJayabal** [comment] 2020-02-26 03:23
@drasticdpk , everything looks good except for this one issue.
From spec
"API can return max 100 rows at time. User should get that next data by scrolling it on UI Section. Mainly for Model Dropdown"

For the example (Device Type: "Smartphone", Manufacturer : "Samsung"), the first 100 records are loaded, but on scrolling further records are not loading.
[devices.mov.zip](https://github.com/topcoder-platform/community-app/files/4253291/devices.mov.zip)

**Comment by SathyaJayabal** [comment] 2020-02-27 14:14
@drasticdpk , verified on test

**Comment by sushilshinde** [comment] 2020-03-09 09:51
Production deployment on hold as production `v5/lookups API` isn't ready yet.

@Oanh-and-only-Oanh @drasticdpk

**Comment by Oanh-and-only-Oanh** [comment] 2020-03-26 18:49
Holding deployment. We need to do several things beforehand. 1) examine the current devices data of the members to see if the data is "worth" retaining and migrating. 2) IF the data is worth migrating, we need a plan to do so, 3) IF the data is NOT worth migrating, we can start from ground zero and let members know to please update their devices.

**Comment by sandhiyakavi** [comment] 2020-04-03 08:05
We are able to add the same device with same specification multiple times,

<img width="941" alt="device" src="https://user-images.githubusercontent.com/55895538/78338185-edf1e100-75af-11ea-9e4b-bd517f043099.PNG">


![image](https://user-images.githubusercontent.com/55895538/78338018-9e131a00-75af-11ea-971b-ed7888ac3dd3.png)

![image](https://user-images.githubusercontent.com/55895538/78338057-aec39000-75af-11ea-81b2-07fc135f93c0.png)

**Comment by SathyaJayabal** [comment] 2020-04-03 08:15
@Oanh-and-only-Oanh @LieutenantRoger , a couple of minor issues:

1. Able to add same devices multiple times. 
https://github.com/topcoder-platform/community-app/issues/3547#issuecomment-608292179

2. Icons are a bit different from production
<img width="120" alt="Screenshot 2020-04-03 at 1 37 49 PM" src="https://user-images.githubusercontent.com/58783823/78338509-8e480580-75b0-11ea-8c6d-7ab8b78a0b8e.png">
<img width="97" alt="Screenshot 2020-04-03 at 1 37 54 PM" src="https://user-images.githubusercontent.com/58783823/78338511-9011c900-75b0-11ea-9810-22dcef832dbd.png">

Another couple of issues that also exists in production
3. the delete confirmation message is not aligned correctly.
<img width="521" alt="Screenshot 2020-04-03 at 1 41 44 PM" src="https://user-images.githubusercontent.com/58783823/78338895-365dce80-75b1-11ea-8cfb-e79b2f42c07b.png">

**Comment by SathyaJayabal** [comment] 2020-04-03 08:28
@Oanh-and-only-Oanh @LieutenantRoger for laptops and desktops, since we have "any" for model and manufacturer, "Any" is displayed on device list. Is that fine?
<img width="351" alt="Screenshot 2020-04-03 at 1 56 12 PM" src="https://user-images.githubusercontent.com/58783823/78340094-20e9a400-75b3-11ea-9f9d-637e6947d93c.png">

**Comment by Oanh-and-only-Oanh** [comment] 2020-04-03 15:42
@SathyaJayabal and @LieutenantRoger, 
1) Able to add same devices multiple times.
#3547 (comment). Please resolved. There shouldn't be multiple for the same devices
2) Icons are a bit different from production. Not an issue. 
3) The delete confirmation message is not aligned correctly. Please center the delete message.

**Comment by LieutenantRoger** [comment] 2020-04-04 13:07
Hi @Oanh-and-only-Oanh 

2. Regarding the implementation flow,  will it be fine if for a user who added the same device twice, we simply ignore his second add operation without showing extra popup ?

**Comment by Oanh-and-only-Oanh** [comment] 2020-04-05 20:48
Hi @LieutenantRoger, that's find but we need to add a why for the user to know that it's a device they've already entered so they don't think it's a bug. Can we add a popup message that says, "Looks like you've already entered this device."

**Comment by LieutenantRoger** [comment] 2020-04-06 00:10
Sure

**Comment by LieutenantRoger** [comment] 2020-04-06 08:08
![image](https://user-images.githubusercontent.com/2875203/78536686-cfdee780-7820-11ea-980b-46fd5376d63b.png)


Popup message is added like this.

**Comment by SathyaJayabal** [comment] 2020-04-06 09:12
1. When you edit the device and click on save without updating any field, you get the "Looks lie you have already entered this device" error. The error must not be displayed in keeping with the existing behaviour.

2. A device is checked for uniqueness only when all the four DDs are filled. For example I am able to add the. below device twice because I have not filled in the OS value. Is this the expected behaviour?
<img width="1434" alt="Screenshot 2020-04-06 at 2 39 57 PM" src="https://user-images.githubusercontent.com/58783823/78542363-b3d54900-7814-11ea-88f9-da7a7c42da42.png">


@LieutenantRoger @sushilshinde  Do we have any style guides for the error and success messages?

**Comment by LieutenantRoger** [comment] 2020-04-06 09:43
ok, thanks.  I think success message has included in production. You can simply add a device successfully to see it. 

Will take a look at the edit issue.

**Comment by LieutenantRoger** [comment] 2020-04-06 11:32
> 1. When you edit the device and click on save without updating any field, you get the "Looks lie you have already entered this device" error. The error must not be displayed in keeping with the existing behaviour.
> 2. A device is checked for uniqueness only when all the four DDs are filled. For example I am able to add the. below device twice because I have not filled in the OS value. Is this the expected behaviour?
> 
> <img alt="Screenshot 2020-04-06 at 2 39 57 PM" width="1434" src="https://user-images.githubusercontent.com/58783823/78542363-b3d54900-7814-11ea-88f9-da7a7c42da42.png">
> 


1. The error message is removed under this sceario

2. Hmmm,  in my opinion this should be expected, so I didn't change anything for this point.

3. `Success message` popup is displayed when we add a device successfully, so the error popup message is following the same style, (success is using green color, error is using red color).

**Comment by sandhiyakavi** [comment] 2020-04-06 11:41
working as expected

![image](https://user-images.githubusercontent.com/55895538/78554870-8d6dd880-7829-11ea-828e-f31a0e6048ee.png)

**Comment by SathyaJayabal** [comment] 2020-04-06 11:56
@LieutenantRoger , I am not sure of the red colour used in the error message. I am marking this as QA pass as its a minor issue. @Oanh-and-only-Oanh Do we have a style guide for it? I could not find it in this guide
https://zeroheight.com/1g0pfacwv/p/4098cf-buttons--links/b/62b18f

**Comment by SathyaJayabal** [comment] 2020-04-06 12:11
verified delete conf message is centered
<img width="536" alt="Screenshot 2020-04-06 at 5 40 37 PM" src="https://user-images.githubusercontent.com/58783823/78557103-d1fb7300-782d-11ea-8e86-3a4fecbea3d9.png">

**Comment by Oanh-and-only-Oanh** [comment] 2020-04-06 14:56
@Dara-K, can you provide GUI KIT for this message?

**Comment by Dara-K** [comment] 2020-04-06 15:15
This is how a modal with buttons and title should look: https://marvelapp.com/5554efd/screen/66554187
If you need the exact design, I can do that. In this case the delete button should be the pink one from our GUI KIT and be on the right side, and the cancel should be on left side outlined.

**Comment by SathyaJayabal** [comment] 2020-04-07 08:55
@Dara-K , sorry for the misunderstanding, we wanted the kit for this error message. 
https://github.com/topcoder-platform/community-app/issues/3547#issuecomment-609641431

**Comment by Dara-K** [comment] 2020-04-07 21:14
Yes, I was saying we don't have that component in the GUI KIT now.  We keep updating it as we go on and we need things.

I designed it now here: https://marvelapp.com/5ij7312/screen/67963488

**Comment by LieutenantRoger** [comment] 2020-04-08 00:40
Hi @Dara-K 
I think we are discussing the tostar message in this snapshot.  ![image](https://user-images.githubusercontent.com/2875203/78536686-cfdee780-7820-11ea-980b-46fd5376d63b.png)

But I can see you have re-designed the popup https://marvelapp.com/5ij7312/screen/67963488 

By the way, we have merged the functionality code into `develop` branch for this ticket.  

@Oanh-and-only-Oanh  do we need to integrate the new style that @Dara-K has designed here: https://marvelapp.com/5ij7312/screen/67963488   ?

**Comment by SathyaJayabal** [comment] 2020-04-08 02:59
@LieutenantRoger @Dara-K @Oanh-and-only-Oanh  If we are updating the style, we need to do so for all the pages on the profile settings.  So, creating new issue to track the  design update to the pop-ups.

#4194

**Comment by Dara-K** [comment] 2020-04-08 07:49
Oh okay - I thought you're referring to the modal. Thanks for the clarification.

We don't have a style defined for the tostar message neither, but the modal window is also following the old style as well. I will re-design these 2 to follow the existing style on the site and send you later today.

**Comment by Dara-K** [comment] 2020-04-08 11:29
Here are the notification states: https://marvelapp.com/11607af4/screen/67982872

The one to use in the above case is the Warning one.

The modal window should be designed like this: https://marvelapp.com/11607af4/screen/67982871 (the above example with blue buttons is from the old Topcoder style 2013).

The guidelines for this GUI KIT are these ones: https://marvelapp.com/c7h2a6h/screen/59648056

Let me know if you need other elements.

**Comment by SathyaJayabal** [comment] 2020-04-08 11:40
@Dara-K , thank you.
We will track these updates in #4194

**Comment by Oanh-and-only-Oanh** [comment] 2020-04-08 15:37
@SathyaJayabal and @LieutenantRoger, let's update the popup message to the GUI KIT guidelines. Is this the last remaining issue for devices?

**Comment by SathyaJayabal** [comment] 2020-04-08 15:41
@Oanh-and-only-Oanh , wont it be better to update the popup messages for all the settings pages (education, work etc) together as a separate activity as all these pages use the same older style ?

#4194 can be used to track this.

**Comment by sandhiyakavi** [comment] 2020-04-10 05:28
Working as expected.

![image](https://user-images.githubusercontent.com/55895538/78965087-08d7ce80-7b37-11ea-9866-6d421ccdcb5a.png)

**Comment by Jobee1** [comment] 2020-04-13 15:24
Working as expected verified on Beta Environment: 
[3547_beta.zip](https://github.com/topcoder-platform/community-app/files/4470126/3547_beta.zip)

**Comment by Jobee1** [comment] 2020-04-13 15:25
Working on expected verified on Production environment:
[3547_production.zip](https://github.com/topcoder-platform/community-app/files/4470133/3547_production.zip)

**Closed** 2020-04-13 15:33 UTC
Labels: Beta Env, New feature, QA Pass
