### ISSUE TITLE
update filtering  UI on challenge listing

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#5068] opened 2020-10-08 04:45 UTC
Currently, the calendar interface on the challenge listings page is not user friendly. See below
![image](https://user-images.githubusercontent.com/47536078/95501599-67063280-095d-11eb-985e-837244009220.png)

Update:
We'd like to update the calendar UI so that it is easier for members to input dates without having to click though the calendar.

**Comment by Oanh-and-only-Oanh** [comment] 2020-10-08 20:26
Design f2f copiloted by eriantoongko

**Comment by eriantoongko** [comment] 2020-10-12 16:17
F2F Challenge: https://www.topcoder.com/challenges/cb13249a-48f2-4465-9e68-0a49ba5deac9
Desktop handoff: https://marvelapp.com/prototype/f70187e/screen/73550299/handoff
Tablet handoff: https://marvelapp.com/prototype/ba511cg/screen/73550331/handoff
Mobile handoff: https://marvelapp.com/prototype/9440hbh/screen/73550357/handoff
Source file: https://drive.google.com/drive/folders/1kcUbIpo5i0LExa_kfSSuyt1io8JBAeSc?usp=sharing

**Comment by maxceem** [comment] 2020-10-13 07:18
@Oanh-and-only-Oanh in general the task looks clear.

The only question is there UI for choosing month and year? 

![image](https://user-images.githubusercontent.com/146016/95828106-33e8e800-0d3d-11eb-9d4f-4a736fa7870c.png)

**Comment by eriantoongko** [comment] 2020-10-13 07:20
@maxceem @Oanh-and-only-Oanh I will ask the winner to provide the UI and keep you guys updated.

**Comment by eriantoongko** [comment] 2020-10-13 13:57
@maxceem @Oanh-and-only-Oanh month and year interaction added to the previous link.

**Comment by maxceem** [comment] 2020-10-13 14:33
Thanks, @eriantoongko.

Is it desired to implement a custom scrollbar for a month and year dropdowns, or we can use standard browser scrollbars? (I would recommend going with the standard ones).

   ![image](https://user-images.githubusercontent.com/146016/95873691-d6728c80-0d78-11eb-95e5-c3f2fb2b39f8.png)

**Comment by eriantoongko** [comment] 2020-10-13 14:49
@Oanh-and-only-Oanh actually what the designer using right now is a mac version scroll bar. I attach my chrome scroll bar.
<img width="1186" alt="Screen Shot 2020-10-13 at 9 48 31 PM" src="https://user-images.githubusercontent.com/28837725/95877067-efd9ff80-0d9d-11eb-9355-b77cf12ddecc.png">

**Comment by eriantoongko** [comment] 2020-10-13 14:50
@maxceem I think that is fine. We should use the native scrollbar provided by the OS.

**Comment by Oanh-and-only-Oanh** [comment] 2020-10-13 19:10
@eriantoongko, I don't think it's clear in the design that it's 2 separate calendars for choosing 2 dates (start and end). When user opens calendar for start date, only the exact date should be highlighted. Is it not a range like shown below.
![image](https://user-images.githubusercontent.com/47536078/95904874-f55b2980-0d4c-11eb-9a21-d6895b9e8871.png)

**Comment by maxceem** [comment] 2020-10-13 19:46
Ah, yes, I did think that this calendar is for choosing a range because it is highlighting a range and it also suggests choosing several predefined ranges on the left:

![image](https://user-images.githubusercontent.com/146016/95907571-6974ec00-0da4-11eb-904e-7f2959f2d367.png)

Another note from a non-USA citizen. I can see that the date format has been changed from `Nov 12 2000` to `11/12/2000` so it can be entered from the keyboard. Just would like note, that outside USA the date has another format: `DD/MM/YYYY` instead of `MM/DD/YYYY`. So non-USA citizens cannot be sure what date is shown as `11/12/2000` as it looks ambiguous.

**Comment by maxceem** [comment] 2020-10-14 10:14
@Oanh-and-only-Oanh just would like to confirm, that we also require that all the functionality should be accessible from the keyword:
- Calendar should be accessible using the keyword. We should be able to choose any date using keys `<Tab>`/`<Shift>`+`<Tab>`/`<Enter>` as it's implemented in the current calendar.
- We should also be able to enter dates from the keyword directly to the inputs using the input mask. 

   ![image](https://user-images.githubusercontent.com/146016/95975650-1ab86800-0e1f-11eb-8d04-bb1a82cd4110.png)

   It should automatically move the cursor during input, allow us to put the cursor in any place and allow using keyboard arrows to navigate between digits, something like in this [demo](https://robinherbots.github.io/Inputmask/).

**Comment by Oanh-and-only-Oanh** [comment] 2020-10-14 14:29
@maxceem that's correct. All functionality should be accessible from keyboard. @eriantoongko, can we update the style to fit the 2018 look and feel - more on the blue colors than green. Thank you.

**Comment by eriantoongko** [comment] 2020-10-14 18:57
Updated style back to blue:https://marvelapp.com/prototype/f70187e/screen/73620859

**Comment by maxceem** [comment] 2020-10-15 07:43
@Oanh-and-only-Oanh let me confirm the workflow:

1. When the user selects the  **first date**, there are 3 ways to go:
    1. Let the user select the **second date** immediately after selecting the first date (as it's done now).
    2. Keep the calendar open so the user can select another **first date**.
    3. Close calendar immediately after selecting the **first date**.
    
    ![image](https://user-images.githubusercontent.com/146016/96088639-65dd8400-0ece-11eb-8a7d-13bdeadf623b.png)

2. To make the calendar accessible from the keyboard we have to highlight a selected element when the user uses the keyboard, see demo:
    
    ![Oct-15-2020 10-20-03](https://user-images.githubusercontent.com/146016/96089903-2a43b980-0ed0-11eb-9a5d-1a5bdaf963c8.gif)

    We can use the same blue square as we do now, or would you like to highlight it another way in the new UI?

3. To confirm. Previously, we show a calendar widget when we click at any place in the input field:
     
    ![image](https://user-images.githubusercontent.com/146016/96092028-fae27c00-0ed2-11eb-9bed-2444eb0c8585.png)

    As now we can enter the date from the keyboard, to open the calendar we have to click on the calendar icon only:

     ![image](https://user-images.githubusercontent.com/146016/96092131-1ea5c200-0ed3-11eb-94a4-1f46251552ab.png)

**Comment by Oanh-and-only-Oanh** [comment] 2020-10-15 16:16
@maxceem,

1. When the user selects the first date, let the user select the second date immediately after selecting the first date (as it's done now).

2.The same blue square is fine. I just want to ensure it is keyword accessible.

3. Correct. user can enter the exact date or use the calendar feature by clicking on the calendar icon.

**Comment by Oanh-and-only-Oanh** [comment] 2020-10-19 15:42
Challenge link: https://www.topcoder.com/challenges/a4cf3c44-1944-4e90-aa37-e969e5ab6038

**Comment by maxceem** [comment] 2020-12-07 07:20
One more challenge is done to update the challenge filter UI in general https://www.topcoder.com/challenges/4d9f86b5-f492-4b31-bad0-521098798037?tab=details

There are 2 PRs:
Community App https://github.com/topcoder-platform/community-app/pull/5247
Topcoder React Lib https://github.com/topcoder-platform/topcoder-react-lib/pull/287
Submission is almost perfect, there are only a few minor issues:
- Avoid overflow in “specification review” https://gyazo.com/0577dd6ad940c3af5386f42249c3371b and https://monosnap.com/file/gmAv2m0T9Y91GE9x8Nv9caoZ3wi0EX 
- Click on "Clear filters" should clear the search box name as well.
- Search field disappears on the smaller screens https://monosnap.com/file/5SI9gi1zGGckSasf1WojLvfRCWwDSD

We would fix these issues after QA together with other issues found during QA.

**Comment by luizrrodrigues** [comment] 2020-12-07 10:39
@SathyaJayabal deployed to Stag env

**Comment by SathyaJayabal** [comment] 2020-12-08 05:47
@maxceem 
1. Once user accesses My Past  Challenges, and  then accesses any other bucket, or applies any other filter, the challenge list is not updated.
[My Past Challenges.mov.zip](https://github.com/topcoder-platform/community-app/files/5657009/My.Past.Challenges.mov.zip)

2. On clear filter, 

- the date range selection must also be cleared.

- the custom date range fields must not be displayed. 
[Clear filter date.mov.zip](https://github.com/topcoder-platform/community-app/files/5657012/Clear.filter.date.mov.zip)

3. @Oanh-and-only-Oanh, for the Open for review bucket, the sub communities filter do not apply (even in prod). Can  we hide  that filter ?

4. My Past Challenges: There is no "View More Challenges" link nor auto loading of more challenges on scrolling.

5. My Past challenges : The same 10 challenges are repeated. (see user: customeruser/appirio123)

<img width="1440" alt="Screenshot 2020-12-08 at 10 59 44 AM" src="https://user-images.githubusercontent.com/58783823/101444051-af81a280-3944-11eb-855f-5550bb7bfe7c.png">

5. Past Challenges:  If the number of results is less than 10, the View more challenges must not be displayed.
<img width="1440" alt="Screenshot 2020-12-08 at 11 05 33 AM" src="https://user-images.githubusercontent.com/58783823/101444366-59612f00-3945-11eb-9837-5350fa640ac3.png">

**Comment by Oanh-and-only-Oanh** [comment] 2020-12-08 06:35
@SathyaJayabal,
3) For the Open for review bucket, the sub communities filter do not apply (even in prod). Yes, we can hide that filter.

Please test thoroughly on the performance of this. We do not want listings performance to be negatively impacted.

**Comment by maxceem** [comment] 2020-12-08 07:42
Here are also 3 more issues:

6) Avoid overflow in “specification review” https://gyazo.com/0577dd6ad940c3af5386f42249c3371b and https://monosnap.com/file/gmAv2m0T9Y91GE9x8Nv9caoZ3wi0EX 

7) Click on "Clear filters" should clear the search box name as well.

8) Search field disappears on the smaller screens https://monosnap.com/file/5SI9gi1zGGckSasf1WojLvfRCWwDSD

**Comment by maxceem** [comment] 2020-12-08 07:51
@Oanh-and-only-Oanh @lakshmiathreya I've asked the winner of the challenge to make these final fixes.

**Comment by sandhiyakavi** [comment] 2020-12-09 05:16
@maxceem Keyword filter is missing and no challenge is displayed if a technology is clicked in Challenge listings/challenge details page.

![image](https://user-images.githubusercontent.com/55895538/101588103-f21cab00-3a28-11eb-8d2d-3d4e4386023c.png)

**Comment by SathyaJayabal** [comment] 2020-12-09 05:23
@Oanh-and-only-Oanh , the keywords  filter option is missing in the design. Is this intentional?
https://marvelapp.com/prototype/96cb17f/screen/74488185

**Comment by maxceem** [comment] 2020-12-09 07:45
> 1. Keyword filter is missing and no challenge is displayed if a technology is clicked in Challenge listings/challenge details page.

We didn't have it per design. @Oanh-and-only-Oanh Could you, please, clarify if we have to add it or no.

> 2. Can we increase the space between challenge type filter and challenge type checkboxes ?
> ![image](https://user-images.githubusercontent.com/146016/101599824-149bcd80-3a03-11eb-8e24-524c544a039c.png)

Sure, will do.

> 3 If a past challenge is clicked and from challenge details page if we click back button or technology/challenge type tag,The open for registration challenges are listed under Past challenges tab in challenge listings page.

The thing is, that "back" button and "technology/challenge type tag" on the Challenge Details page lead to the open for registration challenges, not to the previous filter. So it show open for registration challenges correctly. But we have to fix and show "Acitve" tab not, "Past Challenges" tab.

![image](https://user-images.githubusercontent.com/146016/101599657-c5ee3380-3a02-11eb-8875-0724fc5859bc.png)

**Comment by sandhiyakavi** [comment] 2020-12-09 07:54
@maxceem  Also If we minimize the screen, The track filter and close button is hiding behind the submenus of header, but displaying after scroll down.

![image](https://user-images.githubusercontent.com/55895538/101600570-d7553100-3a3e-11eb-8a78-d9fb2912fcbe.png)
![image](https://user-images.githubusercontent.com/55895538/101600650-f8b61d00-3a3e-11eb-9466-19f17a36da55.png)
[Track_filter_hided.zip](https://github.com/topcoder-platform/community-app/files/5664298/Track_filter_hided.zip)

**Comment by maxceem** [comment] 2020-12-09 07:59
> 

Yeah, I can reproduce it. This is existent issue 

![image](https://user-images.githubusercontent.com/146016/101601193-14043680-3a05-11eb-97f0-1466c5ad3429.png)

Would also ask to fix this it as a part of the final fixes.

**Comment by maxceem** [comment] 2020-12-09 09:48
@luizrrodrigues could you, please, help me to merge PR for the Topcoder React Lib https://github.com/topcoder-platform/topcoder-react-lib/pull/289 as a part of the final fixes.

**Comment by luizrrodrigues** [comment] 2020-12-09 10:42
@maxceem Sure, I'll merge and create test release now.

**Comment by maxceem** [comment] 2020-12-09 10:54
Thanks, @luizrrodrigues. Should I just redeploy stagging Community App, or should I update the version for `topcoder-react-lib` to another number first? https://github.com/topcoder-platform/community-app/blob/feature/filter-update/package.json#L146

**Comment by luizrrodrigues** [comment] 2020-12-09 10:55
@maxceem I'll create new version, merge `community-app` and update the version.

I'll let you know when deployed.

**Comment by luizrrodrigues** [comment] 2020-12-09 11:44
@maxceem Deployed to Stag.

**Comment by maxceem** [comment] 2020-12-09 13:04
Note, final fixes are now done for items 1-8.

New items 1-3 https://github.com/topcoder-platform/community-app/issues/5068#issuecomment-741596441 and https://github.com/topcoder-platform/community-app/issues/5068#issuecomment-741600474 are not yet fixed.

**Comment by Oanh-and-only-Oanh** [comment] 2020-12-09 15:42
> @Oanh-and-only-Oanh , the keywords filter option is missing in the design. Is this intentional?
> https://marvelapp.com/prototype/96cb17f/screen/74488185

@maxceem and @SathyaJayabal, this is intentional. we've condensed the functionality of the search bar so it can be used to search keyword, tags, and title. This was an enhancement of search feature made by @rootelement

**Comment by SathyaJayabal** [comment] 2020-12-09 16:43
> > @Oanh-and-only-Oanh , the keywords filter option is missing in the design. Is this intentional?
> > https://marvelapp.com/prototype/96cb17f/screen/74488185
> 
> @maxceem and @SathyaJayabal, this is intentional. we've condensed the functionality of the search bar so it can be used to search keyword, tags, and title. This was an enhancement of search feature made by @rootelement

@maxceem , in this case, when a user clicks on any of  the challenge tags, the url should be (example user clicks on tag `swagger`)
https://staging-community-app.topcoder.com/challenges?search=swagger&tracks[DS]=true&tracks[Des]=true&tracks[Dev]=true&tracks[QA]=true&types[]=CH&types[]=F2F&types[]=TSK
Instead of `tags[]=Swagger`.

**Comment by maxceem** [comment] 2020-12-09 16:56
>  in this case, when a user clicks on any of the challenge tags, the url should be (example user clicks on tag swagger)
https://staging-community-app.topcoder.com/challenges?search=swagger&tracks[DS]=true&tracks[Des]=true&tracks[Dev]=true&tracks[QA]=true&types[]=CH&types[]=F2F&types[]=TSK
> Instead of tags[]=Swagger.

Great catch @SathyaJayabal.

We should apply tag in URL as `search=<tag>` instead of `tags[]=<tag>`. When we are clicking any tag on the challenge details page:

![image](https://user-images.githubusercontent.com/146016/101660603-06c06980-3a50-11eb-9421-a62e26a69f26.png)

or in the challenge listing page:

![image](https://user-images.githubusercontent.com/146016/101660708-2061b100-3a50-11eb-8f58-54124fd09a8a.png)

**Comment by SathyaJayabal** [comment] 2020-12-09 17:02
> Note, final fixes are now done for items 1-8.
> 


@maxceem , I dont see #3  in the final fixes 
We still have sub communities filter for Open for review bucket
<img width="1440" alt="Screenshot 2020-12-09 at 10 31 54 PM" src="https://user-images.githubusercontent.com/58783823/101661529-64fc4500-3a6e-11eb-8c59-2c41eaa76aa1.png">

**Comment by maxceem** [comment] 2020-12-09 17:31
Thanks, @SathyaJayabal. Will ensure it's fixed with other issues that are left.

**Comment by luizrrodrigues** [comment] 2020-12-09 20:03
@maxceem I'll use Stag env to deploy a new feature, please let me know when ready to redeploy this one.

**Comment by SathyaJayabal** [comment] 2020-12-10 03:11
> @maxceem I'll use Stag env to deploy a new feature, please let me know when ready to redeploy this one.

@luizrrodrigues , not completed qa yet on  this deployment. But we will complete it along with the rest of the fixes.

**Comment by maxceem** [comment] 2020-12-13 10:08
@SathyaJayabal @luizrrodrigues

All fixes are done now and pushed to the `feature/filter-update` branch:
- 2 and 3 in https://github.com/topcoder-platform/community-app/issues/5068#issuecomment-741596441
- https://github.com/topcoder-platform/community-app/issues/5068#issuecomment-741600474
- https://github.com/topcoder-platform/community-app/issues/5068#issuecomment-741904592

**Comment by SathyaJayabal** [comment] 2020-12-14 08:30
@maxceem , everything is good except for the  "Specification Review" text overlap
<img width="424" alt="Screenshot 2020-12-14 at 1 37 17 PM" src="https://user-images.githubusercontent.com/58783823/102057925-b7de4f80-3e14-11eb-953c-cb2b2c195212.png">

**Comment by maxceem** [comment] 2020-12-14 08:52
@SathyaJayabal fixed and pushed to `feature/filter-update` branch:

![image](https://user-images.githubusercontent.com/146016/102060090-65903500-3dfa-11eb-9071-91fae2c09e4f.png)

**Comment by SathyaJayabal** [comment] 2020-12-14 09:36
Thanks @maxceem

**Comment by SathyaJayabal** [comment] 2020-12-15 09:22
verified on prod
<img width="1440" alt="Screenshot 2020-12-15 at 2 45 04 PM" src="https://user-images.githubusercontent.com/58783823/102195734-f8a59980-3ee4-11eb-91ec-6b77200333c8.png">

**Closed by SathyaJayabal** 2020-12-15 09:22 UTC
Labels: Challenge Listing, New feature, P2, Prod QA Pass
