### ISSUE TITLE
[$140] SSF: Results are loaded only after waiting for more than 40 seconds, when Development filter alone is chosen.

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#2695] opened 2019-07-01 13:38 UTC
**Prerequisite: User is logged in**

1. Go to https://beta-community-app.topcoder.com/challenges
2. Turn off the Design and DataScience filter
3. Observe

Actual:
It takes more than 45 seconds, to load the results. This also happen when switching between the options present in the right panel, with Dev Filter alone turned on.

Expected:
It should not take such long time to load the results.

Video:  will be attached shortly.

**Comment by nithyaasworld** [comment] 2019-07-01 13:44
Video: 
[load time when dev alone is selected.zip](https://github.com/topcoder-platform/community-app/files/3345841/load.time.when.dev.alone.is.selected.zip)

**Comment by sushilshinde** [comment] 2019-07-01 13:58
@nithyaasworld is this new?

**Comment by nithyaasworld** [comment] 2019-07-01 14:05
Yes @sushilshinde , It seems so!

**Comment by nithyaasworld** [comment] 2019-07-01 15:20
This issue happens for the following combination of filters too:

![image](https://user-images.githubusercontent.com/5114190/60447805-d9a83e80-9c41-11e9-8a69-df72f37a0f8b.png)

**Comment by ThomasKranitsas** [comment] 2019-07-02 08:42
@topcoder-platform/tcxcommunity @topcoder-platform/topcodercompetitors open for pickup 

PR on ’ssf-merged-to-new-develop’ branch

**Comment by ThomasKranitsas** [comment] 2019-07-02 08:47
[500]: Challenge for the updated issue 2695 is creating, rescheduling this event<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-07-02 08:50
Contest https://www.topcoder.com/challenges/30094893 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-07-02 08:50
Contest https://www.topcoder.com/challenges/30094893 has been updated - it has been assigned to gurmeetb.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-07-02 08:52
Contest https://www.topcoder.com/challenges/30094893 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-07-03 08:12
Contest https://www.topcoder.com/challenges/30094893 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-07-03 08:13
@topcoder-platform/tcxcommunity @topcoder-platform/topcodercompetitors prize increased on this one! Go for it!

**Comment by gurmeetb** [comment] 2019-07-03 08:18
FYI - the issue is when we do this, it hits backend to fetch approx 5000 challenges, we need to fix logic so it hits backend only upto allChallenges count which is just 600 approx.

@ThomasKranitsas sorry I couldn't put much time so opened it, but above analysis will help someone who picks next.

**Comment by ThomasKranitsas** [comment] 2019-07-03 08:20
Contest https://www.topcoder.com/challenges/30094893 has been updated - it has been assigned to PkDurlabhji.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2019-07-04 04:37
@PrakashDurlabhji this is urgent

**Comment by PrakashDurlabhji** [comment] 2019-07-04 04:43
@sushilshinde updating you shortly on this, but i feel i can complete #2696 more easily and fast.

**Comment by sushilshinde** [comment] 2019-07-05 06:19
@PrakashDurlabhji please update

**Comment by sushilshinde** [comment] 2019-07-05 12:58
@topcoder-platform/tcxcommunity @topcoder-platform/topcodercompetitors open for pickup

PR on ’ssf-merged-to-new-develop’ branch

**Comment by r0hit-gupta** [comment] 2019-07-05 13:22
Please assign me

**Comment by ThomasKranitsas** [comment] 2019-07-05 13:24
Contest https://www.topcoder.com/challenges/30094893 has been updated - it has been assigned to rohitgupta_.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by r0hit-gupta** [comment] 2019-07-05 19:03
Unable to reproduce. For me, the results take just 3-4 seconds to load after applying the said filters.

**Comment by sushilshinde** [comment] 2019-07-06 05:46
@nithyaasworld please help verify

**Comment by gurmeetb** [comment] 2019-07-06 06:51
@sushilshinde this is due to bug fix for #2698 created, let's wait for the revert of the same. I see we have PR - let's merge that and then test this

@nithyaasworld @r0hit-gupta ☝️

**Comment by sushilshinde** [comment] 2019-07-08 17:31
PR for https://github.com/topcoder-platform/community-app/issues/2696 is merged, please check test now @gurmeetb @nithyaasworld @r0hit-gupta

**Comment by r0hit-gupta** [comment] 2019-07-08 17:45
@sushilshinde still unable to reproduce. Can others please help and verify if its still an issue?

**Comment by nithyaasworld** [comment] 2019-07-08 22:18
@r0hit-gupta This is still reproducible. **Please log in** (this is important) and then try the steps given in the ticket description.

**Comment by sushilshinde** [comment] 2019-07-09 03:58
@r0hit-gupta can we get a fix today?

**Comment by r0hit-gupta** [comment] 2019-07-09 06:34
@nithyaasworld still unable to reproduce. Can you try this in incognito mode please?

**Comment by r0hit-gupta** [comment] 2019-07-09 06:39
If someone else is able to reproduce this. Please assign it to them. Thanks.

**Comment by nithyaasworld** [comment] 2019-07-09 07:42
@r0hit-gupta Yes, I tried with incognito mode only. 

Can you please confirm that **you have logged in** when trying to reproduce? Because this issue, **does NOT** occur if the user is **not logged in**.

**Comment by r0hit-gupta** [comment] 2019-07-09 07:43
@nithyaasworld yes, I had logged in.

**Comment by gurmeetb** [comment] 2019-07-09 08:11
@nithyaasworld let’s open it for pickup and see if someone else can replicate it.

**Comment by gets0ul** [comment] 2019-07-09 08:55
Please assign me.

**Comment by sushilshinde** [comment] 2019-07-09 09:12
@topcoder-platform/tcxcommunity @topcoder-platform/topcodercompetitors open for pickup

Please submit in 24 hours

PR on ’ssf-merged-to-new-develop’ branch

**Comment by sushilshinde** [comment] 2019-07-09 09:13
> Please assign me.

Are you not able to assign yourself?

**Comment by ThomasKranitsas** [comment] 2019-07-09 09:40
Contest https://www.topcoder.com/challenges/30094893 has been updated - it has been assigned to gets0ul.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by gets0ul** [comment] 2019-07-09 17:40
@sushilshinde  @nithyaasworld @ThomasKranitsas 
This issue was introduced by the following PR:
https://github.com/topcoder-platform/topcoder-react-lib/pull/72  

This commit to the master branch uses getAll which recursively trying to load more and more user challenges at once, which are lots of them, hence the long time.
https://github.com/topcoder-platform/topcoder-react-lib/blob/03b677d74effa8dabc4c5e5c8f34eede75915df8/src/actions/challenge-listing.js#L198-L200

The develop branch does not have this issue, as it retrieves the user challenges per page. The page loads in acceptable time.
https://github.com/topcoder-platform/topcoder-react-lib/blob/3a520fff5b8aa633c0a2f1d23f21adc83bb7c0f2/src/actions/challenge-listing.js#L198-L201  

So what should we do here?

**Comment by sushilshinde** [comment] 2019-07-10 05:58
@ThomasKranitsas need your comment

**Comment by ThomasKranitsas** [comment] 2019-07-10 06:34
The implementation is wrong. It's following the **eager loading** pattern which is definitely not a good idea.

The idea was to be able to load the first set of challenges, display them in the UI and then keep loading the next sets of challenges page by page and show them in the UI. This is some sort of **lazy loading**.

**Comment by ThomasKranitsas** [comment] 2019-07-10 09:18
@gets0ul can you please implement the above ASAP? This is urgent.

**Comment by gets0ul** [comment] 2019-07-10 11:40
@ThomasKranitsas So the way the develop branch of topcoder-react-lib does is not what desired here?

**Comment by ThomasKranitsas** [comment] 2019-07-10 13:14
Correct. You need to change the implementation based on my previous comment

**Comment by gets0ul** [comment] 2019-07-10 18:16
@ThomasKranitsas which branch should I use for topcoder-react-lib?

**Comment by ThomasKranitsas** [comment] 2019-07-10 20:49
@sushilshinde ☝️

**Comment by gets0ul** [comment] 2019-07-11 00:21
The PR is for develop branch on topcoder-react-lib.

**Comment by nithyaasworld** [comment] 2019-07-11 03:55
@sushilshinde @ThomasKranitsas Can we please merge this PR if ready and deploy to beta for testing? As every request to fetch_matching_results takes more than 45 seconds, its getting hard for me to verify the "Ready for QA" tickets.

Thanks.

**Comment by sushilshinde** [comment] 2019-07-11 06:11
Checking

**Comment by sushilshinde** [comment] 2019-07-11 06:14
@ThomasKranitsas please review the submission

**Comment by ThomasKranitsas** [comment] 2019-07-11 06:56
The implementation is not correct. What you're doing is:
- Load the first set of challenges
- Load every other set recursively and show everything at once

Sorry if my explanation wasn't clear enough. What I mean in my previous post is, we need to load and display all pages one by one.

I'm assuming the best way to do that is to move the recursion to the frontend.

The flow should be:
- Load and show the first set of challenges
- Load and show the next set of challenges until there are no more challenges.

You need to show the results from each page right after you get the API response. We don't want to wait until **everything** is loaded.

**Comment by gets0ul** [comment] 2019-07-11 07:18
> we need to load and display all pages one by one.  

> You need to show the results from each page right after you get the API response.

This is exactly what the current develop tree of topcoder-react-lib is doing right now, it loads and displays page one by one.  

No need for a fix. Just revert the changes in `src/actions/challenge-listing.js` from this commit https://github.com/topcoder-platform/topcoder-react-lib/commit/f02ed92ec182ae651dcdb5f2812076ac26994c8a#diff-8cf4059b48130a5066e66e4a473bb4a6

> The flow should be:
> 
> Load and show the first set of challenges
> Load and show the next set of challenges until there are no more challenges.

That's what I did with my submission while still keeping the changes from said commit above.
Have you test it? The long loading time is gone.

**Comment by gets0ul** [comment] 2019-07-11 07:45
As the issue is urgent, you can unassign me for now so maybe others can jump in with a more fitted solution.  
Thank you.

**Comment by ThomasKranitsas** [comment] 2019-07-11 07:48
I just tested. Seems to be working

**Comment by ThomasKranitsas** [comment] 2019-07-11 07:49
@sushilshinde can you also test on your end just to be sure?

**Comment by sushilshinde** [comment] 2019-07-11 07:57
ok I'll

**Comment by nithyaasworld** [comment] 2019-07-12 02:36
@sushilshinde @ThomasKranitsas @gets0ul 

Issues stated [here ](https://github.com/topcoder-platform/community-app/issues/2695#issue-462720143)and [here](https://github.com/topcoder-platform/community-app/issues/2695#issuecomment-507309511) still exists. Can you please check?

**Comment by sushilshinde** [comment] 2019-07-12 05:14
@gets0ul please refer to the code https://github.com/topcoder-platform/community-app/tree/server_side_filtering

Let us know if you can submit the fix today

**Comment by gets0ul** [comment] 2019-07-12 06:30
@sushilshinde I am not sure if Ifollow. Did you mean I should make changes to `server_side_filtering` branch or `ssf-merged-to-new-develop`?  

@nithyaasworld 
Did you you do your check on https://beta-community-app.topcoder.com/challenges?
I see that it still has the problem.  
Are you sure that it runs with updated build with my fix?

**Comment by sushilshinde** [comment] 2019-07-12 06:34
@gets0ul  no, the same thing was working on server_side_filtering branch when @nithyaasworld tester, but after merge with the release branch this issues started popping up.

**Comment by gets0ul** [comment] 2019-07-12 06:39
@sushilshinde I submit the PR to develop branch of topcoder-react-lib, so I didn't include the dist build in it.  You need to build by yourrself.  
Have you run the build before publish the topcoder-react-lib `npm run build`?  
Thanks.

**Comment by ThomasKranitsas** [comment] 2019-07-12 07:04
Closing this one. I'll take care of the remaining fixes.

**Comment by ThomasKranitsas** [comment] 2019-07-12 07:05
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30094893<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed by ThomasKranitsas** 2019-07-12 07:04 UTC
Labels: P1, Performance, tcx_Assigned, tcx_Feedback, tcx_FixAccepted

**Comment by lakshmiathreya** [comment] 2019-08-21 05:20
@ThomasKranitsas @Oanh-and-only-Oanh @kkartunov - Listing latency issue seems resolved. Pls confirm if this fix is moving to Prod today? If so - we need to review the need for regression testing based on the following:-
1. Are there other changes going to Prod alongwith this change?
2. What were the changes made to improve performance - any possible functional impact?
