### ISSUE TITLE
[$30] - 'Forum' link is not displayed in Design Challenges

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#191] opened 2017-08-24 14:00 UTC
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL http://community-app.topcoder.com/challenges

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058662/?type=design

- Register for the Challenge

- Check the tabs

Actual Result(s)
-----------------------------------------------------------------
- 'Forum' link is not displayed in Design Challenges

Expected Result(s)
-----------------------------------------------------------------
- Must display the forum link as a tab as per the design document

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment] 2017-08-24 14:01
![9](https://user-images.githubusercontent.com/4592712/29669946-bd13149c-8902-11e7-9050-2c403f752744.jpg)

**Comment by birdofpreyru** [comment] 2017-08-24 22:47
Accepted, 3 points.
### Note
The challenge referenced by *sdgun* is already finished, and it is fine that you don't see forum link if you are not registered, however, I have checked with an open desing challenge, registered to it, and I see not link nor immediately, nor when I reload the page. This should be fixed.

**Comment by shubhendusaurabh** [comment] 2017-08-25 03:41
assigning myself

**Comment by shubhendusaurabh** [comment] 2017-08-25 03:55
@birdofpreyru There is one open design challenge and can't reproduce with that.

**Comment by birdofpreyru** [comment] 2017-08-25 11:42
@shubhendusaurabh Hmm... I'll double-check later. I saw this problem yesterday, but probably it was due to some temporary problems in the backend.

**Comment by shubhendusaurabh** [comment] 2017-08-31 06:42
@birdofpreyru this issue happens if you register for a new challenge. userroles is empty for while, may be due to api caching.

**Closed** 2017-09-01 14:48 UTC
Labels: Bug Bash - READY FOR REVIEW, Bug Hunt - ACCEPTED
