### ISSUE TITLE
[$30] The profile image I upload from iPhone 6s shows up upside down on desktop.

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1334] opened 2018-09-13 21:48 UTC
**Describe the bug**
The profile image I upload from iPhone 6s shows up upside down on desktop and in the top right corner of the phone as well.

**To Reproduce**
1. Go to 'https://www.topcoder-dev.com/settings/profile' on the iPhone.
2. Add a profile image
3. Go to 'https://www.topcoder-dev.com/settings/profile' on desktop.

**Expected behavior**
The image should be saved in the right direction.

**Screenshots**
![img_3879](https://user-images.githubusercontent.com/35376779/45517737-75e67f00-b7af-11e8-8ffc-9c0bdeacdfcb.PNG)
<img width="1280" alt="screenshot 2018-09-13 23 44 36" src="https://user-images.githubusercontent.com/35376779/45517748-7d0d8d00-b7af-11e8-8dd2-e56d513fd000.png">

**Desktop: MacBook Pro**
 - OS: Mac OS High Sierra
 - Browser: Safari
 - Version: 11.1.2

**Smartphone:**
 - Device: iPhone 6s
 - OS: iOS 11
 - Browser: safari

**Comment by PereViki** [comment] 2018-09-14 05:15
@ThomasKranitsas

**Comment by ThomasKranitsas** [comment] 2018-09-26 12:49
@topcoder-platform/topcodercompetitors this is open for pickup

**Comment by ThomasKranitsas** [comment] 2018-09-26 12:55
[500]: Challenge for the updated issue 1334 is creating, rescheduling this event<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-26 12:55
[500]: Challenge for the updated issue 1334 is creating, rescheduling this event<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-26 12:55
[500]: Challenge for the updated issue 1334 is creating, rescheduling this event<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-26 13:38
[500]: Challenge for the updated issue 1334 is creating, rescheduling this event<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-26 13:49
[500]: Challenge for the updated issue 1334 is creating, rescheduling this event<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-26 15:39
Contest https://www.topcoder.com/challenges/30071870 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-26 15:40
Contest https://www.topcoder.com/challenges/30071870 has been updated - it has been assigned to daga_sumit.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-26 15:40
Contest https://www.topcoder.com/challenges/30071870 has been updated - it has been assigned to daga_sumit.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-26 23:50
Contest https://www.topcoder.com/challenges/30071870 has been updated - it has been assigned to asmn.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by zjuasmn** [comment] 2018-09-26 23:59
cannot reproduce the issue

**Comment by ThomasKranitsas** [comment] 2018-09-27 01:49
Contest https://www.topcoder.com/challenges/30071870 has been updated - it has been assigned to diazz.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by suppermancool** [comment] 2018-09-27 02:48
@ThomasKranitsas 
i added new module for fixing orientation
`blueimp-load-image`
please run
`npm i`
before running

**Comment by ThomasKranitsas** [comment] 2018-09-27 13:08
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30071870<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed** 2018-09-27 13:07 UTC
Labels: Major, New Settings Page, tcx_Assigned, tcx_FixAccepted, tcx_ReadyForReview
