### ISSUE TITLE
ERROR: Failed to load the challenge

### ISSUE THREAD

**Issue by swetaipec** [topcoder-platform/community-app#593] opened 2017-11-15 16:49 UTC
Challenge #30060458 does not exist!

**Comment by atelomycterus** [comment] 2017-11-15 17:03
I have the same issue all day. I tried to load different challenges.

**Comment by birdofpreyru** [comment] 2017-11-23 14:46
I believe, it was a temporary problem, caused by instability of the backend API, and should not be an issue anymore; thus closing this ticket for now.

**Closed by birdofpreyru** 2017-11-23 14:46 UTC
