### ISSUE TITLE
Sub menus are not expanded when user switches the orientation

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2603] opened 2019-06-09 13:33 UTC
![image](https://user-images.githubusercontent.com/42398485/59159566-34aaa380-8a91-11e9-945c-878aeb361285.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Portrait)
3. Tap Menu > Work > Tracks/Compete or Community > Expand the submenu
5. Go to Landscape view

**Actual:** Submenus are not expanded when user switches the orientation

**Expected:** Should enable the submenu because the 'Track' is already selected

**Reproducibility Rate:** 3/3

**Environment:** Samsung Galaxy Tab A (2017), 7 inch

**Browser:** Chrome 75.0.3770.80

**Comment by LieutenantRoger** [comment] 2020-01-16 04:51
Hi @luizrrodrigues 

Are you able to reproduce ? I seemed not able to

**Comment by LieutenantRoger** [comment] 2020-01-17 02:27
Up

**Comment by luizrrodrigues** [comment] 2020-01-17 02:38
Checking

**Comment by luizrrodrigues** [comment] 2020-01-17 22:19
@LieutenantRoger Thanks for checking this one, again looks like already fixed with other ticket.

**Comment by nithyaasworld** [comment] 2020-01-21 13:40
Cannot reproduce in production env too

**Comment by luizrrodrigues** [comment] 2020-01-21 21:19
@nithyaasworld Please add QA Pass here

**Comment by luizrrodrigues** [comment] 2020-02-28 23:11
@nithyaasworld I think we good to close this one.

**Closed** 2020-10-15 04:39 UTC
Labels: Can't Reproduce, Navigation, P4, Tablet
