### ISSUE TITLE
[$60]Challenge List Filter Issue

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/community-app#1816] opened 2018-12-12 11:52 UTC
**Describe the bug**
When the user filter challenges by tracks and after reload the page, the filters by track got lost, even though user can see them in the URL and this has been working before (at least a month ago) as reported by the user

**To Reproduce**
1. Open  https://www.topcoder.com/challenges
2. Turn off tracks Design and Data Science so only Development track left. You could see that list of challenges now has only development challenges as expected and URL become like this: https://www.topcoder.com/challenges?filter[tracks][develop]=true. So this URL suppose to show only development challenges.
3. Now either press Reload in the browser or navigate directly by link https://www.topcoder.com/challenges?filter[tracks][develop]=true
All the challenges will be shown and switches for all three tracks will be enabled.

See demo video https://monosnap.com/file/SxUxy58XczqQvyEHZGlOue83jgwEee

**Expected behavior**
only Development track switch is enabled and only development challenges are listed.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [70.0.3538.110]

**Smartphone (please complete the following information):**
NA

**Additional context**
Note, that if user filter only challenges "open for registration" the URL will become like this https://www.topcoder.com/challenges?filter[tracks][develop]=true&bucket=openForRegistration and after page reload filter "open for registration" will persist as expected. So the only filter by tracks got lost as far as the user sees.

**Comment by sushilshinde** [comment] 2018-12-14 08:01
PR on
https://github.com/topcoder-platform/community-app/tree/hot-fixes

Prod mode setup locally
If you want run app in prod mode locally refer README

**Comment by ThomasKranitsas** [comment] 2018-12-14 08:02
Contest https://www.topcoder.com/challenges/30077021 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-12-14 08:02
Contest https://www.topcoder.com/challenges/30077021 has been updated - it has been assigned to gurmeetb.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-12-14 08:03
Contest https://www.topcoder.com/challenges/30077021 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2018-12-14 09:56
try this, I deployed your code here 

https://beta-community-app.topcoder.com/challenges?filter[tracks][develop]=true

**Comment by gurmeetb** [comment] 2018-12-14 09:58
checking

**Comment by sushilshinde** [comment] 2018-12-14 11:15
@gurmeetb 

Clear this cache and reload

![screen shot 2018-12-14 at 4 45 00 pm](https://user-images.githubusercontent.com/683231/50000456-a660d380-ffbf-11e8-9a8a-9fe0ff29364e.png)

**Comment by gurmeetb** [comment] 2018-12-14 12:57
please see - https://youtu.be/5WJrFz2h6Z0

**Comment by sushilshinde** [comment] 2018-12-17 04:19
I did check the video, but we need to get that solved for the deployment environment.

**Comment by gurmeetb** [comment] 2018-12-17 04:50
ok, let me try one more time and will open for others to pickup, if I cannot still replicate post fix. Not sure much can be done related to deployment environment, we might need to push client side logs to test that. Is that fine ?

**Comment by sushilshinde** [comment] 2018-12-17 10:33
clientside logs?

**Comment by gurmeetb** [comment] 2018-12-17 10:46
adding js logs and then we can see what is coming in deployment env.

**Comment by gurmeetb** [comment] 2018-12-17 14:05
@sushilshinde since locally it is working fine, can we move this to test env so we know the root cause of why fix fails there ? We can revert this once tested.

**Comment by sushilshinde** [comment] 2018-12-17 14:08
Sure I can but check lint errors

**Comment by gurmeetb** [comment] 2018-12-17 14:11
Ah my bad, fixed it. Please flag once on test server.

**Comment by gurmeetb** [comment] 2018-12-18 07:31
@sushilshinde did we had chance to push this to test env ?

**Comment by gurmeetb** [comment] 2018-12-18 13:59
@sushilshinde not sure what is causing this but from logs I see filterState is empty on test env while not on local setup. Is this something to do with env settings ? 

Kindly feel free to open for pickup, as I am not able to replicate it locally after the fix provided. Before I was able to see the issue.

**Comment by sushilshinde** [comment] 2018-12-18 15:52
@gurmeetb it's is related to env setup. 

Is a service worker causing issues here?

**Comment by gurmeetb** [comment] 2018-12-18 17:05
```
@gurmeetb it's is related to env setup.
Is a service worker causing issues here?
```

Do you mean env setup on myside ? Could you guide with some more insights ?

**Comment by sushilshinde** [comment] 2018-12-19 11:41
Submit in 24 hours 

@topcoder-platform/topcodercompetitors this one is open for pickup

**Comment by ThomasKranitsas** [comment] 2018-12-19 12:02
Contest https://www.topcoder.com/challenges/30077021 has been updated - it has been assigned to gauravseta.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by gurmeetb** [comment] 2018-12-21 05:13
@sushilshinde can we release this so someone who can fix this within 24 hrs can pick up? I am looking forward to this fix too.

**Comment by Gauravseta** [comment] 2018-12-21 21:12
@sushilshinde PR within few hours

**Comment by sushilshinde** [comment] 2018-12-24 15:09
@Gauravseta are you working on this?

**Comment by sushilshinde** [comment] 2019-01-07 09:59
@topcoder-platform/topcodercompetitors this one is open for pickup

**Comment by ThomasKranitsas** [comment] 2019-01-07 10:07
Contest https://www.topcoder.com/challenges/30077021 has been updated - it has been assigned to daga_sumit.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sumitdaga** [comment] 2019-01-07 10:09
@sushilshinde   
which branch should i use?

**Comment by sumitdaga** [comment] 2019-01-07 11:01
and by the way i think not just tracks but none of the query parameters are working as of now!

**Comment by sumitdaga** [comment] 2019-01-08 10:54
@sushilshinde   
i cannot reproduce this locally although i know as a fact that it does not work on the production site!

**Comment by gurmeetb** [comment] 2019-01-08 10:57
@sumitdaga you can reproduce it locally if you revert my change from MR - after which even I wasn't able to reproduce locally but I agree issue exists on prod env. 

@sushilshinde  I think it has to do with env for sure like conveyed before.

**Comment by sushilshinde** [comment] 2019-01-13 10:45
@topcoder-platform/topcodercompetitors this one is open for pickup

PR on https://github.com/topcoder-platform/community-app/tree/hot-fixes

**Comment by ThomasKranitsas** [comment] 2019-01-14 02:16
Contest https://www.topcoder.com/challenges/30077021 has been updated - it has been assigned to diazz.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by suppermancool** [comment] 2019-01-14 04:50
@sushilshinde done in https://github.com/topcoder-platform/community-app/pull/1870

**Comment by sushilshinde** [comment] 2019-01-14 15:06
Thanks @suppermancool wil check

**Closed** 2019-01-15 13:24 UTC
Labels: tcx_Assigned, tcx_FixAccepted, tcx_ReadyForReview
