### ISSUE TITLE
[$30] - [Bug Hunt - NEW BUG]Unexpected URL is not handled properly

### ISSUE THREAD

**Issue by twicoder** [topcoder-platform/community-app#190] opened 2017-08-24 13:59 UTC
1) try to open url: http://community-app.topcoder.com/challenges/*
2) Page body is not shown
<img width="1639" alt="2017-08-24 9 59 01" src="https://user-images.githubusercontent.com/3046795/29669897-87dbeb54-8917-11e7-8332-38b8e5c81433.png">

**Comment by birdofpreyru** [comment] 2017-08-24 22:44
Accepted, 3 points.

### Expected Fix
The routing should be corrected, to ensure that when a non-digital challenge ID is supplied in such route, it renders 404 Error page.

**Comment by birdofpreyru** [comment] 2017-08-24 22:50
Please also take into account #192 which is also caused by incorrect challenge ID used in URL. That should also render 404 error page.

**Comment by elfman** [comment] 2017-08-25 03:31
assign myself

**Comment by elfman** [comment] 2017-08-25 05:56
PR arised.
#192 is not fixed in this PR, server should return something when chanlengeId is not exist, currently it keeps the link waiting and nothing response.

**Comment by birdofpreyru** [comment] 2017-08-25 11:41
@ajefts @skyhit See the last comment. It looks like when we pass a non-existing challenge ID into the backend, it just stucks, rather than returning and error (404?) right away.

**Closed** 2017-09-07 12:59 UTC
Labels: Bug Hunt - PAID
