### ISSUE TITLE
Sub community filters are not working

### ISSUE THREAD

**Issue by nithyaasworld** [topcoder-platform/community-app#3278] opened 2019-09-03 13:08 UTC
**Describe The Bug**
Sub community filters are not working on challenge page. It always fetches blank results.

![image](https://user-images.githubusercontent.com/5114190/64175887-ec293900-ce79-11e9-8733-6b2c9f15a031.png)

![image](https://user-images.githubusercontent.com/5114190/66109106-944d3180-e5e1-11e9-9b9f-67ebb9804e21.png)

**Step to reproduce**
1. Visit www.topcoder.com/challenges
2. Click the Filters button
3. Switch the `Sub community`
4. The challenge listing should be filtered accordingly, currently it display blank screen for `TCO19` and `TCO20` Sub community 

**Expected result**
The challenge list on the page should display the correctly filtered challenges.

**Additional Context**

The work should be done against branch: `hot-fix-sub-community-filter`
Please use `npm run build && npm start` to verify your solution locally.

**Comment by nithyaasworld** [comment] 2019-11-21 11:47
Confirming that this is still an issue.

cc: @sushilshinde

**Comment by SathyaJayabal** [comment] 2020-01-30 08:21
Additionally when the sub community filter is added, the number of filters applied count is not updated on the filter button
<img width="1408" alt="Screenshot 2020-01-30 at 1 50 02 PM" src="https://user-images.githubusercontent.com/58783823/73431914-84631580-4367-11ea-966d-6c0bd3dcbf42.png">

cc: @sushilshinde

**Comment by lakshmiathreya** [comment] 2020-03-09 16:36
@sushilshinde @Oanh-and-only-Oanh this is continuing to fail - verified on Beta with 0.23.02. Pls advise reg timeline for fix.

**Comment by Oanh-and-only-Oanh** [comment] 2020-03-10 04:25
@lakshmiathreya @sushilshinde, adding this issue to list of hot-fixes to be worked on soon.

**Comment by LieutenantRoger** [comment] 2020-03-11 04:41
This ticket seems containing two issues:

1. one is about the sub-community filter
2. one is about the the number of filters applied count is not updated on the filter button

@SathyaJayabal  Could you please re-create a ticket for the number 2 above ?

**Comment by crazyk07** [comment] 2020-03-11 11:10
Contest https://www.topcoder.com/challenges/30119039 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by LieutenantRoger** [comment] 2020-03-11 11:17
Hi @topcoder-platform/topcodercompetitors
This ticket is open, please come to pick it up, thanks.

**Comment by Oanh-and-only-Oanh** [comment] 2020-08-20 16:52
closing ticket. duplicate of https://github.com/topcoder-platform/community-app/issues/4575

**Closed by Oanh-and-only-Oanh** 2020-08-20 16:52 UTC
Labels: Challenge Listing, P2, hot-fix
