### ISSUE TITLE
[$40] A skill gets immediately removed in the first tap on iPhone

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1478] opened 2018-09-16 00:50 UTC
**Describe the bug**
If I click on a skill it immediately gets removed without letting the user know what will happen, as there is no hover effect on mobile.

**To Reproduce**
1. Go to 'https://www.topcoder.com/settings/profile'
2. Click on 'Skill'
3. Tap on a skill you already added.

**Expected behavior**
First the user should see the remove message on the icon, and the removal should happen on the next tap.

**Screenshots** Cannot really show this with a screenshot
![img_3900](https://user-images.githubusercontent.com/35376779/45591751-39578680-b95b-11e8-9727-066d0282ab2a.PNG)

**Smartphone:**
 - Device: iPhone 6s
 - OS: iOS 11
 - Browser: safari

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment] 2018-09-26 10:43
Contest https://www.topcoder.com/challenges/30071831 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-26 10:43
Contest https://www.topcoder.com/challenges/30071831 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-26 11:55
Contest https://www.topcoder.com/challenges/30071831 has been updated - it has been assigned to PkDurlabhji.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by PrakashDurlabhji** [comment] 2018-09-27 13:29
@ThomasKranitsas working on it PR soon

**Comment by nahidshahin** [comment] 2018-09-28 15:05
@ThomasKranitsas I want to work on it

**Comment by ThomasKranitsas** [comment] 2018-09-28 15:06
@nahidshahin I see there's a pending invitation... Please check your email and accept the invitation. Then I'll assign you to the ticket.

**Comment by nahidshahin** [comment] 2018-09-28 15:12
@ThomasKranitsas is it possible to send it again. I'm not able to find

**Comment by nahidshahin** [comment] 2018-09-28 19:29
@ThomasKranitsas Skill add is not working. Getting 400 while calling https://api.topcoder-dev.com/v3/members/nahidshahin1/skills, error message is `Tag id 121 is not valid`. Any idea why?

**Comment by ThomasKranitsas** [comment] 2018-09-28 20:01
Skills only work in prod... you need to run the app against the prod API

**Comment by nahidshahin** [comment] 2018-09-29 12:38
The issue is a bit tricky, someone please try it. I'm leaving it.

**Comment by ThomasKranitsas** [comment] 2018-09-29 12:54
@topcoder-platform/topcodercompetitors this is open for pickup

**Comment by ThomasKranitsas** [comment] 2018-09-29 15:11
Contest https://www.topcoder.com/challenges/30071831 has been updated - it has been assigned to diazz.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by suppermancool** [comment] 2018-09-29 15:44
done in https://github.com/topcoder-platform/community-app/pull/1628

**Comment by ThomasKranitsas** [comment] 2018-09-30 13:47
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30071831<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed** 2018-09-30 13:46 UTC
Labels: Major, New Settings Page, tcx_Assigned, tcx_FixAccepted, tcx_ReadyForReview
