### ISSUE TITLE
Update link to Forums preferences

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#5382] opened 2021-02-23 10:45 UTC
Link from preferences page is pointing to old forums. This has to be updated

<img width="1440" alt="Screenshot 2021-02-23 at 4 14 54 PM" src="https://user-images.githubusercontent.com/58783823/108833068-509e0200-75f2-11eb-8343-06a076da4052.png">

existing link:https://apps.topcoder.com/forums/?module=Settings
@jmgasper , do you have user preferences on vanilla? 

cc @sushilshinde @Oanh-and-only-Oanh

**Comment by jmgasper** [comment] 2021-02-23 10:48
@SathyaJayabal - I think it should be https://discussions.topcoder.com/profile/preferences

**Comment by luizrrodrigues** [comment] 2021-03-16 17:04
Duplicate of #5433

**Closed by luizrrodrigues** 2021-03-16 17:04 UTC
Labels: P3, Prod Env
