### ISSUE TITLE
New nav - add support for custom logo url

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/community-app#2708] opened 2019-07-02 13:33 UTC
As per title. Please, add support so logo could be linkable to some URL. If not specified default to base URL.

**Comment by luizrrodrigues** [comment] 2020-01-22 01:33
Duplicate of https://github.com/topcoder-platform/navigation-component/issues/104

**Comment by nithyaasworld** [comment] 2020-01-22 12:00
Closing this as this is handled in https://github.com/topcoder-platform/navigation-component/issues/104

**Closed by nithyaasworld** 2020-01-22 12:00 UTC
Labels: Navigation, P3
