### ISSUE TITLE
[$100]Fix listing issues : Stalled issues and bucket issues (It's urgent)

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1738] opened 2018-11-05 07:07 UTC
For the branch `mm-develop-merge`
1. Fix Stalled issues, which are not there on the production

<img width="1650" alt="mm-deveop-merge" src="https://user-images.githubusercontent.com/683231/47982785-029a2300-e0f7-11e8-8f49-0e96d95a0986.png">

2. These stalled items are missing from `Open for registration` bucket they should be under this bucket.

3. My Challenges bucket isn't displayed - all the challenges which I'm registered for should be under this bucket

Compare results with topcoder.com/challenges(v3 API) for reference.

Run in production mode(v4 API), there is data model difference in v3 and v4 API.

Instruction to run an app in production mode

```
rm -rf node_modules
npm i
npm run build
npm start
```

Check **Deployment and Execution** section in the doc for details 
https://github.com/topcoder-platform/community-app/blob/develop/README.md

Create PR for changes, I'll reopen for pickup if the PR not submitted within 8 hours

**Repos :** 

https://github.com/topcoder-platform/community-app/tree/mm-develop-merge
https://github.com/topcoder-platform/topcoder-react-lib#new-develop-mm

**Comment by ThomasKranitsas** [comment] 2018-11-05 07:08
Contest https://www.topcoder.com/challenges/30073811 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-11-05 07:08
Contest https://www.topcoder.com/challenges/30073811 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-11-05 07:09
Contest https://www.topcoder.com/challenges/30073811 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by nahidshahin** [comment] 2018-11-05 07:12
Can I work on this, please?

**Comment by ThomasKranitsas** [comment] 2018-11-05 07:13
Contest https://www.topcoder.com/challenges/30073811 has been updated - it has been assigned to rashmi73.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2018-11-05 07:14
@topcoder-platform/topcodercompetitors this one is open for pickup

**Comment by rashmi73** [comment] 2018-11-05 07:15
@nahidshahin i took this once @sushilshinde added open for pickup tag.

**Comment by ThomasKranitsas** [comment] 2018-11-05 07:17
Contest https://www.topcoder.com/challenges/30073811 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2018-11-06 10:15
@rashmi73 are you working on this?

**Comment by sushilshinde** [comment] 2018-11-06 10:29
@prasadadarkar30 this is urgent

**Comment by rashmi73** [comment] 2018-11-06 10:30
@sushilshinde but m working on it. i am going to raise PR soon.

**Comment by sushilshinde** [comment] 2018-11-06 10:31
@rashmi73 it's over 24 hours

**Comment by prasadadarkar30** [comment] 2018-11-06 10:34
@sushilshinde i will urgently. but please explain pt 1 and 2 a bit. m confused with them. pt 3 is clear.

**Comment by ThomasKranitsas** [comment] 2018-11-06 10:34
Contest https://www.topcoder.com/challenges/30073811 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2018-11-06 10:41
@prasadadarkar30 

1. some challenges are stalled on `mm-develop-merge` branch and not on the topcoder.com/challenges, run production mode.

2. All these items which are displayed as 'Stalled' should be part of `Open for registration` bucket, which is not.

Compare `https://topcoder.com/challenges` vs `http://beta-community-app.topcoder.com/challenges`

**Comment by prasadadarkar30** [comment] 2018-11-06 21:44
@sushilshinde isnt relaoding of app not available on npm start? because after saving any changes , app doesnt reload.

**Comment by ThomasKranitsas** [comment] 2018-11-06 22:50
Contest https://www.topcoder.com/challenges/30073811 has been updated - it has been assigned to gauravseta.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2018-11-07 01:15
Instruction to run an app

```
rm -rf node_modules
npm i
npm run build
npm start


```
Check **Deployment and Execution** section in the doc for details 
https://github.com/topcoder-platform/community-app/blob/develop/README.md

**Comment by ThomasKranitsas** [comment] 2018-11-07 01:17
Contest https://www.topcoder.com/challenges/30073811 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2018-11-08 04:06
@Gauravseta when are you submitting it?

**Comment by ThomasKranitsas** [comment] 2018-11-08 05:14
Contest https://www.topcoder.com/challenges/30073811 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-11-08 05:16
Contest https://www.topcoder.com/challenges/30073811 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2018-11-08 05:17
@topcoder-platform/topcodercompetitors this one is open for pickup

**Comment by ThomasKranitsas** [comment] 2018-11-08 05:35
Contest https://www.topcoder.com/challenges/30073811 has been updated - it has been assigned to gurmeetb.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2018-11-08 05:35
@gurmeetb please do

**Comment by Gauravseta** [comment] 2018-11-08 05:36
@sushilshinde PR #1741

**Comment by sushilshinde** [comment] 2018-11-08 05:37
That's old code @gurmeetb

**Comment by sushilshinde** [comment] 2018-11-08 05:38
If the fix is is in topcoder-lib it needs to be fixed there, package.json should' be updated

**Comment by ThomasKranitsas** [comment] 2018-11-08 05:40
Contest https://www.topcoder.com/challenges/30073811 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by gurmeetb** [comment] 2018-11-08 05:43
@sushilshinde who is working on this? I see @Gauravseta is raising MR after I picked up item, while he was sitting with item for a day plus?

**Comment by gurmeetb** [comment] 2018-11-08 05:44
@sushilshinde kindly confirm :point_up:

**Comment by sushilshinde** [comment] 2018-11-08 05:44
@gurmeetb your please go ahead and work on it.

**Comment by gurmeetb** [comment] 2018-11-08 05:44
Thanks @sushilshinde

**Comment by gurmeetb** [comment] 2018-11-08 05:46
Yes looking at it now..

**Comment by ThomasKranitsas** [comment] 2018-11-08 05:47
Contest https://www.topcoder.com/challenges/30073811 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by gurmeetb** [comment] 2018-11-08 07:50
@sushilshinde what is best way to test the v3/v4 APIs at `topcoder-react-lib` ?

**Comment by sushilshinde** [comment] 2018-11-08 10:07
https://github.com/topcoder-platform/topcoder-react-lib/tree/new-develop-mm branch is already configured to use v4 API

Here you can check data model differences

https://api.topcoder.com/v4/challenges
https://api.topcoder.com/v3/challenges

**Comment by sushilshinde** [comment] 2018-11-08 10:34
@gurmeetb just paginate via results like this you will marathon matches also. We need to support MARATHON_MATCH and DEVELOP_MARATHON_MATCH as well.

`https://api.topcoder.com/v4/challenges/?filter=status%3DCOMPLETED&limit=50&offset=0`

**Comment by Gauravseta** [comment] 2018-11-08 10:38
@sushilshinde why these links where not given to me?
https://api.topcoder.com/v4/challenges
https://api.topcoder.com/v3/challenges

anyways i can complete this if given chance, as these links were only thing i missed.

**Comment by sushilshinde** [comment] 2018-11-08 10:40
@Gauravseta if this goes for open pickup again, please take it up

**Comment by gurmeetb** [comment] 2018-11-08 10:50
@sushilshinde The API is at fault, if API doesn't returns `currentPhases` in the response, it goes to `STALLED` stage. The best place for this fix is on server side of the APIs. We can add code to check for dates but that would be kind of adding redundant code in `topcoder-react-lib`. 

Take a case for below DEVELOP_MARATHON_MATCH where we get back `currentPhases`, it is shown fine on UI :
"name": "This is test MM - do not register  - only for MM-V4 testers",

Let me know if you want to take this approach or fix the API server-side rather which is at fault ?

**Comment by gurmeetb** [comment] 2018-11-08 10:55
@sushilshinde ☝️

**Comment by sushilshinde** [comment] 2018-11-08 11:00
Ok, let fix it in the lib first if the current phase is missing then compute otherwise use whatever is providexd @gurmeetb

**Comment by gurmeetb** [comment] 2018-11-08 11:00
@sushilshinde thanks

**Comment by gurmeetb** [comment] 2018-11-08 11:38
@sushilshinde how do we include local Topcoder-react-lib in community-app? I followed the README of Topcoder-react-lib and added following but `npm i` cannot find it

```
"dependencies": {
....
"topcoder-react-lib": "/Users/gb/Desktop/topCoder/topcoder-react-lib",
...
}
```

**Comment by sushilshinde** [comment] 2018-11-08 11:42
There are many solutions 

but this is simple fork `topcoder-react-lib`, build, commit dist folder and use
     
`topcoder-react-lib": "git+https://github.com/{your-repo-here}/topcoder-react-lib#new-develop-mm
`

**Comment by gurmeetb** [comment] 2018-11-08 11:55
Thanks README suggested me above so was taking it but this helps. Testing fix.

**Comment by gurmeetb** [comment] 2018-11-08 12:32
@sushilshinde looks like I was looking at wrong file, I will open it as I am done with 8 hrs, I will pick up again in 8 hrs, if we don't have solution.

**Comment by sushilshinde** [comment] 2018-11-08 12:37
@gurmeetb do you have an solution.

**Comment by rashmi73** [comment] 2018-11-08 12:40
@sushilshinde i agree with gurmeetb. testing even a single chnage takes 15+ mins to build because of production build. hot reloading only on  dev. is it possible to have it on prod?

**Comment by sushilshinde** [comment] 2018-11-08 12:48
@gurmeetb @rashmi73 i understand but as long as you are working on the solution it's ok to keep the ticket even beyond 8 hours, just inform me.

**Comment by ThomasKranitsas** [comment] 2018-11-08 12:57
Contest https://www.topcoder.com/challenges/30073811 has been updated - it has been assigned to gurmeetb.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by gurmeetb** [comment] 2018-11-08 12:59
@sushilshinde yes, I know the RCA and know the cause of the issue, finding the right file which is changing the status is trick, where I got blocked hence unlocked tickets for others. 

I will continue my work on it.

**Comment by gurmeetb** [comment] 2018-11-08 16:22
@sushilshinde the fix is working with dev env, testing with prod, will raise MR in few mins.

**Comment by gurmeetb** [comment] 2018-11-08 17:34
@sushilshinde fix is ready, having merge issues with fork, resolving them and will open MR.

**Comment by gurmeetb** [comment] 2018-11-08 17:58
@sushilshinde it is read, kindly verify ☝️

**Comment by ThomasKranitsas** [comment] 2018-11-14 08:14
Contest https://www.topcoder.com/challenges/30073811 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2018-11-14 08:15
@topcoder-platform/topcodercompetitors this one is open for pickup

**Comment by ThomasKranitsas** [comment] 2018-11-14 08:18
Contest https://www.topcoder.com/challenges/30073811 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by gurmeetb** [comment] 2018-11-14 08:35
@nahidshahin 1st is fixed, look at MR. Thought to flag you so you don't invest time there.

**Comment by sushilshinde** [comment] 2018-11-14 13:33
@nahidshahin Shall I assign this https://github.com/topcoder-platform/community-app/issues/1754 as well to you if you have a bandwidth. It's related to current issues.

**Comment by gurmeetb** [comment] 2018-11-14 13:57
@sushilshinde #1754 is already fixed as part of https://github.com/topcoder-platform/community-app/pull/1746, if I am not wrong. Please check once.

**Comment by gurmeetb** [comment] 2018-11-14 14:11
@sushilshinde I just verified - and yes my MR has fixed that already. If you want I can raise new MR for #1754 - see attached. 

![1](https://user-images.githubusercontent.com/14284629/48487799-456da080-e845-11e8-9e15-f5dcbcfb51cc.jpg)

**Comment by sushilshinde** [comment] 2018-11-14 14:16
@gurmeet, that's a different issue. This is related to Direct-MM.

**Comment by ThomasKranitsas** [comment] 2018-11-15 03:45
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed by ThomasKranitsas** 2018-11-15 03:45 UTC
Labels: Challenge Listing, tcx_OpenForPickup
