### ISSUE TITLE
[$20] - [Bug Hunt - NEW BUG]Cannot read property 'on' of undefined and resource missing

### ISSUE THREAD

**Issue by twicoder** [topcoder-platform/community-app#174] opened 2017-08-24 13:14 UTC
<img width="1658" alt="2017-08-24 9 11 27" src="https://user-images.githubusercontent.com/3046795/29667977-1a24eada-8911-11e7-8542-13a6901ca765.png">

**Comment by birdofpreyru** [comment] 2017-08-24 21:51
In principle, this does not look like a bug in Community App for me.
First one is caused by a 3-rd party analytics script added to `renderer.jsx` by Tony, and the resources, I believe, are requested from the backend according to the data returned from APIs. However, I'll rely on the final judgement by Tony, on whether it is a bug, and what we should do with it.

**Comment by birdofpreyru** [comment] 2017-08-24 21:52
@ajefts

**Comment by birdofpreyru** [comment] 2017-08-29 16:21
Ok, I'll just accept this for 1 point.
Missing resources are, most probably, a backend-issue. However, if somebody have an idea why that analytics script causes the error visible in console, and how we fix it, feel free to pick-up this ticket and offer a fix. I guess, probably, just that analytics code should be updated.

**Comment by birdofpreyru** [comment] 2017-09-05 00:24
UPDATE: Generation of links to avatar images have been corrected during the work on another problem, thus the part related to missing resources has been fixed. The error in analytics script is still to be solved.

**Comment by birdofpreyru** [comment] 2017-10-09 15:04
The remaining error message does not show up in the console anymore. Not sure, when and how was it fix, but for now we can close the issue.

**Closed by birdofpreyru** 2017-10-09 15:04 UTC
Labels: Bug Hunt - PAID
