### ISSUE TITLE
[$20] Layout issue in the Weblink placeholders if the content is long

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1426] opened 2018-09-14 18:10 UTC
## Steps to Reproduce

1. Open the Application and Login as a valid user [Portrait]
2. Go to Settings > Account > Linked Account
3. Enter some long domain names (HTTP://WWW.SELFASSEMBLYSITES.COM, HTTP://WWW.ENTREPRENEUR.COM)
4. Check the list in Portrait view

## Actual Result(s)

- Layout issue in the Weblink placeholders if the content is long

## Expected Result(s)

- Must have a fixed width for the gray color section

## Frequency

- 5/5

## Environment Details

- **Device(s):** Samsung Galaxy S5
- **Operating System:** Android 6.0.1
- **Size:** 5.1 inches (~69.6% screen-to-body ratio)
- **Resolution:** 1080 x 1920 pixels (~432 ppi pixel density)
- **Browser(s):** FF 62

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment] 2018-09-14 18:12
The icons with gray background section is different from item to item

![issue_20180914_131129](https://user-images.githubusercontent.com/4592712/45567572-cb5a7480-b81f-11e8-8341-b674686952cc.png)

**Comment by ThomasKranitsas** [comment] 2018-09-29 12:57
Contest https://www.topcoder.com/challenges/30072037 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-29 12:57
Contest https://www.topcoder.com/challenges/30072037 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-29 13:00
@topcoder-platform/topcodercompetitors this is open for pickup

**Comment by nahidshahin** [comment] 2018-09-29 13:01
@ThomasKranitsas want to pick it

**Comment by ThomasKranitsas** [comment] 2018-10-05 17:55
@nahidshahin I see there's a pending invitation for you to join our org.

Please check your emails, accept the invitation, go to the challenge forum and use the x.topcoder.com link to register with Topcoder-X otherwise I can't pay you for your work.

Thank you!

**Comment by nahidshahin** [comment] 2018-10-06 18:46
@ThomasKranitsas I checked my email but I can't find anything. What can I do?

**Comment by ThomasKranitsas** [comment] 2018-10-07 09:08
Contest https://www.topcoder.com/challenges/30072037 has been updated - it has been assigned to nahidshahin.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by nahidshahin** [comment] 2018-10-11 19:02
@ThomasKranitsas the issue is merged. Can you please complete the payment? Thanks

**Comment by ThomasKranitsas** [comment] 2018-10-11 19:08
Of course :)

**Comment by ThomasKranitsas** [comment] 2018-10-11 19:09
Please do let me know if there are more tickets where the payment wasn't processed

**Closed by ThomasKranitsas** 2018-10-11 19:08 UTC
Labels: Minor, New Settings Page, tcx_Assigned, tcx_FixAccepted

**Comment by ThomasKranitsas** [comment] 2018-10-11 19:12
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30072037<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```
