### ISSUE TITLE
[$50]Undefined id in challenge details page

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/community-app#1785] opened 2018-12-05 07:33 UTC
**Describe the bug**
Challenge details page does not shows links for download materials for registered users.

**To Reproduce**
1. Go to any challenge for which you have not yet registered.  
2. Register for the challenge.
3. Looks for download section where you ll see empty spaces. On inspecting the element, one could see that the hyperlink is having docid field set to undefined.

**Expected behavior**
The users should be able to view downloadable items (if available ) under download section once the user registers for the challenge

**Screenshots**
Challenge Page 
![image](https://user-images.githubusercontent.com/45197181/49497173-ba088d80-f88d-11e8-9e97-22b0d6618b45.png)

Challenge Page post registration
![image](https://user-images.githubusercontent.com/45197181/49497202-d5739880-f88d-11e8-8476-22042f124875.png)

Inspecting the Element shows the docid being set to undefined.
![image](https://user-images.githubusercontent.com/45197181/49497268-fdfb9280-f88d-11e8-817a-0e78972afff8.png)

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Browser [chrome]
 - Version [70.0.3538.102

**Additional context**

**Comment by RiteshTC** [comment] 2018-12-05 07:35
@cwdcwd @sushilshinde

**Comment by ThomasKranitsas** [comment] 2018-12-06 16:35
Contest https://www.topcoder.com/challenges/30076266 has been updated - it has been assigned to gurmeetb.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by gurmeetb** [comment] 2018-12-06 16:40
@sushilshinde which branch should be used ?

**Comment by sushilshinde** [comment] 2018-12-06 16:48
https://github.com/topcoder-platform/community-app/tree/hot-fixes

**Comment by cwdcwd** [comment] 2018-12-06 18:49
![](https://github.trello.services/images/mini-trello-icon.png) [File attachments not showing on challenge page.](https://trello.com/c/F62jkdYA/17-file-attachments-not-showing-on-challenge-page)

**Comment by gurmeetb** [comment] 2018-12-06 20:12
@sushilshinde I tried via UI but invasion as it shows I am registered but doesn't shows the full Documents sections - see below

![onprod](https://user-images.githubusercontent.com/14284629/49609364-48316080-f9c1-11e8-9ad9-bec09ddebce4.jpg)

So I tried using API `https://api.topcoder.com/v4/challenges/30075934` and in response I don't see `documents` elements - can you confirm if the API being used by me is correct ?

**Comment by gurmeetb** [comment] 2018-12-06 20:13
And it doesn't lets me unregister, can we push some sample challenges as all challenges don't have documents.

**Comment by sushilshinde** [comment] 2018-12-07 02:12
Ok I'll create challenges on dev

**Comment by gurmeetb** [comment] 2018-12-07 06:00
@sushilshinde any updates here ☝️

**Comment by sushilshinde** [comment] 2018-12-07 08:55
@gurmeetb I did launch a challenge it takes around 4 hours to launch.

**Comment by gurmeetb** [comment] 2018-12-07 09:58
@sushilshinde  Could you help me with name for challenge so I can try in few hrs once it is live ?

**Comment by gurmeetb** [comment] 2018-12-07 11:51
@sushilshinde can you suggest ☝️ ? I think it should be up now

**Comment by sushilshinde** [comment] 2018-12-07 11:56
There is a problem in creating challenges in dev environment. Once that is up will create a new one.

**Comment by gurmeetb** [comment] 2018-12-07 11:58
ah, ok

**Comment by gurmeetb** [comment] 2018-12-07 12:09
@sushilshinde can I pick up other while we are on hold for this ?

**Comment by sushilshinde** [comment] 2018-12-07 13:37
@gurmeetb  keep watch on this within an hour and half

https://www.topcoder-dev.com/challenges/30054405

**Comment by gurmeetb** [comment] 2018-12-07 17:58
still waiting for challenge to be active, so putting back on hold.

**Comment by sushilshinde** [comment] 2018-12-12 13:33
@m-yadav can you ask a person to create similar challenge in dev env (topcoder-dev.com) because I [created one](https://www.topcoder-dev.com/challenges/30054460) and that doesn't show Downloads options

**Comment by RiteshTC** [comment] 2018-12-13 12:06
@sushilshinde request you to kindly attach a file in files section.
<img width="1282" alt="filessection" src="https://user-images.githubusercontent.com/5771673/49937680-89fc6280-fefd-11e8-886c-fb0eb553004d.png">

**Comment by sushilshinde** [comment] 2018-12-13 12:12
I did try to attach but doesn't reflect

**Comment by RiteshTC** [comment] 2018-12-13 12:48
@sushilshinde 
Probably its a configuration issue with dev environment. Please reach out to the product manager to confirm.

**Comment by sushilshinde** [comment] 2018-12-13 13:06
@ajefts please help here.

**Comment by gurmeetb** [comment] 2018-12-17 14:13
@ajefts any update here ?

**Comment by ajefts** [comment] 2018-12-24 16:06
@sushilshinde what help is needed here?  Can you reproduce the issue in prod, check logs, check configs, etc?

fyi @cwdcwd

**Comment by gurmeetb** [comment] 2018-12-26 12:05
@ajefts @cwdcwd we are looking to push a challenge on dev which has documents attached on Challenge Page for download by users.

**Comment by sushilshinde** [comment] 2019-01-07 10:01
Let me try upload doc today

**Comment by sushilshinde** [comment] 2019-01-09 15:49
This is an API issue

**Comment by gurmeetb** [comment] 2019-01-18 15:49
@sushilshinde As discussed we need change in back-end, V4 gave me response like below
```
“documents”: [
               {
                   “documentName”: “Not related to  the challenge spec”,
                   “url”: “78396/30073144/download.png”
               }
           ],
```

While V3 gave, 
```
"documents": [
                {
                    "documentname": "Not related to  the challenge spec",
                    "documentid": 27525872,
                    "url": "https://sampe-documentProviderUrl/27525872"
                }
            ],
```

When tested hard-coding V3 response, the doc shows fine as below, so no code changes needed here. `Once we fix API, it will work fine` 

![hardcoded_json-doc_shows](https://user-images.githubusercontent.com/14284629/51397217-be031d00-1b66-11e9-9414-630023589253.jpg)

**Comment by gurmeetb** [comment] 2019-01-21 14:30
@sushilshinde shall we close this and open one for backend API fix?

**Comment by ThomasKranitsas** [comment] 2019-01-22 06:12
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30076266<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2019-01-23 15:54
@gurmeetb issue still exists even though API returns documentId

**Comment by sushilshinde** [comment] 2019-01-24 10:53
Deployed on prod

**Closed** 2019-01-24 10:53 UTC
Labels: tcx_FixAccepted, tcx_Paid
