### ISSUE TITLE
Private member profiles should be open up in a new browser tab

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4082] opened 2020-03-09 18:42 UTC
~1) **Behavior**: When a Topgear member clicks a member's handle, it navigates user to the public domain i.e. https://www.topcoder.com/members/Rinal~

~**Expected behavior**: When a Topgear member clicks a member's handle, user is navigated to the member's profile page WITHIN Topgear's domain.  i.e. https://topgear.topcoder.com/members/Rinal~

~2) If the member's handle is NOT part of Topgear's groupID, when a Topgear user clicks on a public member handle, this image and message should appear.
![image](https://user-images.githubusercontent.com/47536078/76247168-59889e80-61fc-11ea-9f0a-c225a6029a98.png)~

As we have discussed, we will implement this logic:

1) When we are under topgear domain, e.g. topgear.topcoder-dev.com, we then should open up a member's profile page in a new tab, (with the subdomain info retained in the url of the new browser tab)

2) When we are under public domain, e.g. www.topcoder-dev.com, we should retain the logic as is.

The updated requirement work will be done against `feature-private-navigation`

**Comment by LieutenantRoger** [comment] 2020-03-10 03:17
@Oanh-and-only-Oanh   For #1,  we seems not having a challenge that can allow us to reproduce this in the `topgear` domain right now.  https://topgear.topcoder-dev.com/challenges , all the challenges in this page can't display detail. So where we can find a member to click under `topgear` domain in development envrionment?

**Comment by LieutenantRoger** [comment] 2020-03-10 03:35
#2, why a topgear user is able to click a member's handle in public domain ?  I seems could only think up that this scenario will happen only when a topgear user try to fill the link in the browser directly like this:  https://topgear.topcoder.com/members/Rinal

**Comment by LieutenantRoger** [comment] 2020-03-10 03:44
FYI, I have draft a challenge spec for this ticket, please take a look:  
https://docs.google.com/document/d/1FzTgw7HcOicgOzlWyMd1AmPHId5F9FljRWyVn2MI9_A/edit?usp=sharing

**Comment by Oanh-and-only-Oanh** [comment] 2020-03-10 17:31
@atif, please help with question 1 above.

**Comment by Oanh-and-only-Oanh** [comment] 2020-03-10 17:32
question 2. @LieutenantRoger, a scenario would be...

**Comment by LieutenantRoger** [comment] 2020-03-11 01:48
Question 1:  I found two challenges that allowing us to see a member handle.

https://topgear.topcoder-dev.com/challenges/30055960?tab=registrants
https://topgear.topcoder-dev.com/challenges/30055753?tab=registrants

For this, it looks we need to find all areas on the topgear site where it shows a member's handle, this looks like a side task.

@Oanh-and-only-Oanh  

1) I think we need a separate task to find all the url links where the displayed content has member handle rendered.
2) Do we need to take care of other private group or only `topgear` 

Question 2:  The comment seems not complete.

**Comment by LieutenantRoger** [comment] 2020-03-11 02:08
https://docs.google.com/document/d/1QEvbKQ9xPKqMZqWv_Fu9SQOMBQaWAAM39bpMj_yTDuc/edit?usp=sharing

Here's a challenge spec to find all the URLs which contain member handle link under the `topgear` domain.

**Comment by Oanh-and-only-Oanh** [comment] 2020-03-11 02:43
Question 2: takes this challenge for example, https://topgear.topcoder.com/challenges/30118814, it's a public challenge but it's also made available on topgear. So if a topgear user goes into the registrant or submission tabs of that challenge and clicks on a public member's handle, it will take the user to the public domain. We want to change it so if it is a public handle, the topgear member should see below instead.

**Comment by LieutenantRoger** [comment] 2020-03-11 03:08
I don't have access to above challenge.  I think we need to setup a test challenge under topgear.topcoder-dev.com while we can use `TonyJ` user to visit, and this challenge will contain both topgear user and public user in registration and submission tab.

We will perhaps setup up more public handles in topgear domain in other areas (identified here: https://docs.google.com/document/d/1QEvbKQ9xPKqMZqWv_Fu9SQOMBQaWAAM39bpMj_yTDuc/edit?usp=sharing) to verify the navigation as well.

**Comment by Oanh-and-only-Oanh** [comment] 2020-03-11 03:18
@lakshmiathreya, can you help with the above? We need to set up a test challenge under  topgear.topcoder-dev.com

**Comment by LieutenantRoger** [comment] 2020-03-13 11:21
We need similar challenges in below private group as well in order to test the result:

https://cs.topcoder-dev.com/challenges
https://veterans.topcoder-dev.com/challenges
https://blockchain.topcoder-dev.com/challenges?communityId=blockchain
https://cognitive.topcoder-dev.com/challenges?communityId=cognitive

**Comment by LieutenantRoger** [comment] 2020-03-19 08:00
@Oanh-and-only-Oanh 

Is it possible a public member only can register a private group challenge ?  

It seems impossible given the current business logic as the private group challenge won't be visiable to public member.

**Comment by LieutenantRoger** [comment] 2020-03-21 10:33
@Oanh-and-only-Oanh 

Please try to click the member-handles under this screen: 

https://topgear.topcoder-dev.com/challenges/30055646?tab=registrants


https://topgear.topcoder-dev.com/members/tester1234  (Here is an example when a user is not having stats data).

https://topgear.topcoder-dev.com/members/dan_developer (Here is another example when a user is having stats data).

**Comment by Oanh-and-only-Oanh** [comment] 2020-03-22 03:52
@LieutenantRoger, a public member cannot register for a private group challenge because it will not be visible on the public domain.

**Comment by LieutenantRoger** [comment] 2020-03-22 04:08
Right , so topgear user under topgear domain won't able to click a public member to visit its profile, this will lead to point 2 above will never happen.

So for a topgear user who does't have history data, could you check wheather this meet expectation above ?

**Comment by Oanh-and-only-Oanh** [comment] 2020-03-22 17:06
> Right , so topgear user under topgear domain won't able to click a public member to visit its profile, this will lead to point 2 above will never happen.


> So for a topgear user who does't have history data, could you check wheather this meet expectation above ?  https://topgear.topcoder-dev.com/members/tester1234

 Correct

**Comment by LieutenantRoger** [comment] 2020-03-23 02:05
`>>  topgear user can click on public member but it will show below`

Could you please tell how a topgear user click on public member's handle ?   In another word, will public members show up on topgear.topcoder.com site ?

**Comment by Oanh-and-only-Oanh** [comment] 2020-03-23 03:09
all public challenges are visible on the topgear site so if a public member registers for a public challenge, a topgear user would be able to see the public user's handle in the topgear site.

**Comment by LieutenantRoger** [comment] 2020-03-23 03:21
Ah, got it, that clarifies this.

**Comment by LieutenantRoger** [comment] 2020-03-23 08:41
Hi @Oanh-and-only-Oanh 

Does this look fine when a topgear user visit public member's profile screen ?

https://take.ms/34K4P

**Comment by Oanh-and-only-Oanh** [comment] 2020-03-24 02:28
That's correct.

**Comment by sandhiyakavi** [comment] 2020-03-27 06:34
Tested the Fix.The Topgear user is still able to see the public member's handle details.

I have also attached video for better clarity.

![image](https://user-images.githubusercontent.com/55895538/77728560-c84e6000-7022-11ea-8ed8-5698c0fa2b11.png)

[issue#4082_video.zip](https://github.com/topcoder-platform/community-app/files/4391880/issue.4082_video.zip)

**Comment by LieutenantRoger** [comment] 2020-03-27 14:47
Hi @SathyaJayabal  

It seems you are using wrong url when testing. 

Please always use url format like `topgear.topcoder-dev.com` with sub-domain at the head of the url.   

Current deployment URL like `community-app.topcoder-dev.com/__community__/wipro` won't work.

**Comment by SathyaJayabal** [comment] 2020-03-27 15:16
cc @sandhiyakavi .

**Comment by SathyaJayabal** [comment] 2020-03-31 06:29
@LieutenantRoger 
When accessing the profile of a topgear user. the profile is displayed correctly within the topgear site.
But when accessing the profile of the member who does not belong to topgear group, we do not get the new page with "This member does not have a profile on this sub community " message. Please also refer to video.
[private profile.mov.zip](https://github.com/topcoder-platform/community-app/files/4407138/private.profile.mov.zip)

<img width="1440" alt="Screenshot 2020-03-31 at 11 54 09 AM" src="https://user-images.githubusercontent.com/58783823/77994030-ef6ca080-7346-11ea-924b-583979e7f04d.png">

**Comment by SathyaJayabal** [comment] 2020-03-31 07:14
The 'tester1234' user is a public user who does not belong to the topgear group.  When clicking on the user's handle(from public contest registrant list) the below screen is displayed.
<img width="1440" alt="Screenshot 2020-03-31 at 11 54 09 AM" src="https://user-images.githubusercontent.com/58783823/77997380-f3032600-734c-11ea-97ff-3902f27bb1d9.png">

But this is wrong and the expected screen should be 
Expected screen
![76247168-59889e80-61fc-11ea-9f0a-c225a6029a98](https://user-images.githubusercontent.com/58783823/77997447-0dd59a80-734d-11ea-89aa-e992db09c0f0.png)

@Oanh-and-only-Oanh , please confirm if this is the correct understanding ?

**Comment by LieutenantRoger** [comment] 2020-03-31 07:18
Hi @Oanh-and-only-Oanh 

Could you please confirm above snapshot is correct or not ?  

We can get tester1234's profile data like this, https://monosnap.com/file/2VuWojABcot1YwlL2tz5zeti2GloNA

Though the actual data in the response is empty like this: https://monosnap.com/file/ANfAQfhZP6j3zMtJa939LAUMngOivX

From this comment above, https://github.com/topcoder-platform/community-app/issues/4082#issuecomment-602240405

I think you mentioned the snapshot posted by @SathyaJayabal  should be the expected 

Current logic is when we visit a non-existing user profile in topgear site, 
e.g. topgear.topcoder-dev.com/dan_developer1 (non existing user profile should also be considered not belong to topgear group I think).

So when we visit topgear.topcoder-dev.com/dan_developer1 , we will show the UI like this https://take.ms/34K4P as the API won't return us  data even the empty data structure like when we visit `test1234`.


btw: current backend has no way to distinguish whether a profile is from public or from private group, for example, these are the data returned when we request user `test1234` profile. https://monosnap.com/file/rfnO89LLsiH4hrNMp1P24uinZqWonF

We don't have a field identify whether this user is public member only, or topgear member only info.

**Comment by LieutenantRoger** [comment] 2020-03-31 07:39
Maybe we need to make the /:handle api to support groupIds query parameter as well, so when we visit topgear.topcoder-dev.com/test1234,  the API should not return any data back as `test1234` doesn't belong to `topgear` group.

**Comment by SathyaJayabal** [comment] 2020-04-01 05:41
@LieutenantRoger , we tested only the member handles on the registrants list of a challenge. Can you provide the results of the challenge mentioned here so that we can test all the pages identified ?
https://github.com/topcoder-platform/community-app/issues/4082#issuecomment-597407107

**Comment by LieutenantRoger** [comment] 2020-04-01 11:36
Hi @SathyaJayabal  please see this file

https://docs.google.com/document/d/1h89l4a060GlHJoZtHFurACXT9UuX8Ft9OfpJeuYwNfc/edit?usp=sharing

**Comment by Oanh-and-only-Oanh** [comment] 2020-04-01 15:44
@LieutenantRoger and @SathyaJayabal,  

> Hi @Oanh-and-only-Oanh
> 
> Could you please confirm above snapshot is correct or not ?
> 
> We can get tester1234's profile data like this, https://monosnap.com/file/2VuWojABcot1YwlL2tz5zeti2GloNA
> 
> Though the actual data in the response is empty like this: https://monosnap.com/file/ANfAQfhZP6j3zMtJa939LAUMngOivX
> 
> From this comment above, [#4082 (comment)](https://github.com/topcoder-platform/community-app/issues/4082#issuecomment-602240405)
> 
> I think you mentioned the snapshot posted by @SathyaJayabal should be the expected
> 
> Current logic is when we visit a non-existing user profile in topgear site,
> e.g. topgear.topcoder-dev.com/dan_developer1 (non existing user profile should also be considered not belong to topgear group I think).
> 
> So when we visit topgear.topcoder-dev.com/dan_developer1 , we will show the UI like this https://take.ms/34K4P as the API won't return us data even the empty data structure like when we visit `topgear.topcoder-dev.com/test1234`.
> 
> btw: current backend has no way to distinguish whether a profile is from public or from private group, for example, these are the data returned when we request user `test1234` profile. https://monosnap.com/file/rfnO89LLsiH4hrNMp1P24uinZqWonF
> 
> We don't have a field identify whether this user is public member only, or topgear member only info.

**Comment by LieutenantRoger** [comment] 2020-04-01 16:35
ok thanks @Oanh-and-only-Oanh @SathyaJayabal 

1. https://github.com/topcoder-platform/community-app/issues/4082#issuecomment-606456009  

as mentioned here, we will have to make '/:handle' accept groupid as well. @urwithat :point_up:

**Comment by urwithat** [comment] 2020-04-04 10:15
@Oanh-and-only-Oanh - @LieutenantRoger and I have discussed this, we need to sync up to agree on the direction forward.

**Comment by SathyaJayabal** [comment] 2020-04-13 05:29
@Oanh-and-only-Oanh @LieutenantRoger , I have a couple of questions regarding the new requirements. According to the new requirement, when. a user clicks on the member handle in topgear domain, the public member profile must be displayed on a new tab
1.   How about users who are members only in the topgear community.  Will these members have a public profile page ?
2.  These are pages identified on topgear where the member handle is displayed as a link.
https://github.com/topcoder-platform/community-app/issues/4082#issuecomment-607196986
a. Challenge pages( challenge details -> registrants tab, submissions tab, winners tab, past challenge listings page). The challenge details page work fine and the public member profile is opened on the new tab. But for the past challenges listings page, the public profile opens in the same tab.
b. Leaderboard page: Here the public profile opens in the new tab, but we are getting a 404 error. This may be because the leaderboard seems to display data from the production and not dev backend.
c. Member profile history pages:  
Eg: https://topgear.topcoder-dev.com/members/TonyJ/details/?track=DEVELOP&subTrack=CODE&tab=statistics
Here the topgear profile page is opened in a new tab. Is this the correct behaviour ?

**Comment by LieutenantRoger** [comment] 2020-04-13 14:25
Hi @SathyaJayabal 

1) No, they don't. We only distinguish the  member stats and member stats history based on the community we are in on the Profile screen. (member profile data on the Profile screen will be identical across different communities. 

2) I will need to do some more changes for these.  

I think we can follow this logic.

When we login as a topgear user.  (topgear.topcoder-dev.com)
Clicked any member profile (e.g. dan_developer or test1234), we should open up the member's profile in this url in a new browser tab: topgear.topcoder-dev.com/members/dan_developer  or topgear.topcoder-dev.com/members/test1234 

When we login as a public user. (www.topcoder-dev.com)
Clicked any member profile (e.g. dan_developer or test1234), we should open up the member's profile in this url in current browser tab: www.topcoder-dev.com/members/dan_developer or www.topcoder-dev.com/members/test1234 

We don't bring in UI changes for these process. 
I will need to make more changes based on above logic description.  

And please also let me know if these clarify your questions above.

**Comment by Oanh-and-only-Oanh** [comment] 2020-04-13 15:22
@SathyaJayabal, this new flow is intended to help keep a Topgear user from leaving Topgear domain when they click on public member link in the Topgear page. Before, clicking on public  member link will direct them to public profile on Topcoder and there's no way to navigate back to Topgear. This new approach will open public profile in a new window so Topgear member can still have their Topgear tab open to navigate back.

**Comment by SathyaJayabal** [comment] 2020-04-13 15:42
@Oanh-and-only-Oanh @LieutenantRoger , so on the topgear domain:

-  clicking on public member's handle will open the public profile in a new tab (eg: www.topcoder-dev.com/members/dan_developer).

- clicking on topgear member's handle will open the topgear profile in a new tab (eg: topgear.topcoder-dev.com/members/TonyJ)

**Comment by LieutenantRoger** [comment] 2020-04-13 15:51
I think in your case, both will be opened with topgear.topcoder-dev.com/members/xxxx, as the login member is from topgear domain.  We don't have a public profile and topgear profile distinguish.  

We only distinguish their stats and stats history.  For example, if a member A belongs to both public community and topgear community.  

When a topgear user on topgear domain visits A profile, we show A's topgear stats and stats history accordingly.

When a public user on public domain visits A profile, we show A's public stats and stats history accordingly.

The personal profile related data for A are identical across public domain and topgear domain.  

This is how our current system designed.   Does this make sense to you ?

**Comment by SathyaJayabal** [comment] 2020-04-13 15:55
@LieutenantRoger , but according to @Oanh-and-only-Oanh's comments above, it says new approach will open public profile in new window.
"Before, clicking on public member link will direct them to public profile on Topcoder and there's no way to navigate back to Topgear. This new approach will open public profile in a new window so Topgear member can still have their Topgear tab open to navigate back."

**Comment by LieutenantRoger** [comment] 2020-04-13 16:09
Hmmm, this is good discussion. 

@Oanh-and-only-Oanh  We don't distignish between 'public profile' or 'topgear profile'. We only distinguish 'public stats' or 'topgear stats'.

So we will have to follow below url redirection.

Login as Topgear user: (current browser url is: topgear.topcoder.com/xxxxxxx)
Click any member handle will open up the member's profile in a new tab with this url: topgear.topcoder-dev.com/members/the_member_handle

Login as Public user: (current browser url is: www.topcoder-dev.com/xxxxxxxx)
Click any member handle will open up the member's profile in current browser tab, with this Url:
www.topcoder-dev.com/members/the_member_handle.  

-----------------------------------------------------------------------------------------------------------

Note, we need to maintain the sub-domain on visiting the profile page because the member stats related data will require this part as input parameter to query the desired data.   

So maybe we don't need to open up a new tab under topgear scenario as well.

**Comment by Oanh-and-only-Oanh** [comment] 2020-04-14 03:37
Hmmm, this is not quite right either...

**Comment by SathyaJayabal** [comment] 2020-04-14 04:34
@LieutenantRoger for the below section, there is no change right as this is the current bahaviour ?  The testing scope will be only on topgear domain. Am I correct?
Login as Public user: (current browser url is: www.topcoder-dev.com/xxxxxxxx)
Click any member handle will open up the member's profile in current browser tab, with this Url:
www.topcoder-dev.com/members/the_member_handle.

**Comment by LieutenantRoger** [comment] 2020-04-14 13:45
The code that will change would correlated, so login as public user scenario needs to be tested for the same.

**Comment by SathyaJayabal** [comment] 2020-04-15 04:32
@LieutenantRoger 
1. Challenge pages
Submissions tab - Member handle link is incorrect
2. Past challenges listings page, the public profile opens in the same tab.

3. Leaderboard page: Link is correct, but we are getting a 404 error. This may be because the leaderboard seems to display data from the production and not dev backend. Should work in Beta/Production.

Works fine in other cases.
Video
https://drive.google.com/open?id=1Lv_fszJRhWjWlEv_f_7vro0xlGjAXMSG

**Comment by SathyaJayabal** [comment] 2020-04-15 04:34
> The code that will change would correlated, so login as public user scenario needs to be tested for the same.

Would that mean testing everyplace  the member handle appears on the topcoder community site?

**Comment by LieutenantRoger** [comment] 2020-04-15 12:53
@SathyaJayabal  Correct

**Comment by LieutenantRoger** [comment] 2020-04-15 13:15
> @LieutenantRoger
> 
> 1. Challenge pages
>    Submissions tab - Member handle link is incorrect
> 2. Past challenges listings page, the public profile opens in the same tab.
> 3. Leaderboard page: Link is correct, but we are getting a 404 error. This may be because the leaderboard seems to display data from the production and not dev backend. Should work in Beta/Production.
> 
> Works fine in other cases.
> Video
> https://drive.google.com/open?id=1Lv_fszJRhWjWlEv_f_7vro0xlGjAXMSG

Video is not accessible, requested has been sent.  Better to change the setting into viewable via this link.

**Comment by LieutenantRoger** [comment] 2020-04-15 14:41
@SathyaJayabal  
1. Fixed
2. Fixed

The dev is occupied, I have deployed the fix under `test env` for verifying.  Thanks.

**Comment by SathyaJayabal** [comment] 2020-04-17 05:18
@LieutenantRoger ,
The challenge details page winners tab is displaying a JS error "window not defined" when accessed directly(both in topgear and in topcoder site). This issue is not present in production.


<img width="1438" alt="Screenshot 2020-04-17 at 10 47 43 AM" src="https://user-images.githubusercontent.com/58783823/79534694-e4c93f80-8098-11ea-89ef-38c66b4f17e1.png">

**Comment by SathyaJayabal** [comment] 2020-04-17 05:26
@LieutenantRoger @sushilshinde another issue we see is the way the links behave based on the url format. Clicking on the member handle opens a new tab for the second url. So like @LieutenantRoger said the fix does not work with the second url format. 
https://www.topcoder-dev.com/challenges/30056507?tab=registrants
https://community-app.topcoder-dev.com/challenges/30056507?tab=registrants

Is this fine? We will not be able to test this fix on beta. Also we will always have this different behaviour in beta/test envs compared to production.

**Comment by SathyaJayabal** [comment] 2020-04-17 06:53
Topgear pages
-> Challenge Details: Registrants, Submission and Winners- Opens in new tab - Pass
-> Profile->Stats history: all the link opens in new tab - Pass
-> Leaderboard: Opens in same tab but displays 404 https error - Will this work on production @LieutenantRoger ?

Topcoder pages
All pages opens in the same tab except for
-> Profile->Stats history: Opens in new tab (same as existing behaviour, like in production) Is this fine @LieutenantRoger ?

List of pages tested on topcoder site
https://docs.google.com/spreadsheets/d/1eGFFGgCSd2LEi7DNpDV6fhZmzNWGTtDz658bG9QHokE/edit?usp=sharing

**Comment by LieutenantRoger** [comment] 2020-04-17 11:35
> Topgear pages
> -> Challenge Details: Registrants, Submission and Winners- Opens in new tab - Pass
> -> Profile->Stats history: all the link opens in new tab - Pass
> -> Leaderboard: Opens in same tab but displays 404 https error - Will this work on production @LieutenantRoger ?
> 
> Topcoder pages
> All pages opens in the same tab except for
> -> Profile->Stats history: Opens in new tab (same as existing behaviour, like in production) Is this fine @LieutenantRoger ?
> 
> List of pages tested on topcoder site
> https://docs.google.com/spreadsheets/d/1eGFFGgCSd2LEi7DNpDV6fhZmzNWGTtDz658bG9QHokE/edit?usp=sharing

1. The leaderboard member-handle under topgear domain will open up in a new tab. Please see the code when I check this page: https://monosnap.com/file/TeD7luiCkCXnWMhYOIyBEJXenKCMZb.  

I don't have access to production data, presumably the 404 error will disappear on production as 404 indicates the member even doesn't have a profile in backend. 


2. Hmm, according the new navigation rule, it should open in the same tab.  I'll check this. 

3.Besides, the window is not define issue is valid, will take a look there.

**Comment by SathyaJayabal** [comment] 2020-04-17 13:10
https://github.com/topcoder-platform/community-app/issues/4082#issuecomment-615047842
-fixed
[winners tab.mov.zip](https://github.com/topcoder-platform/community-app/files/4493075/winners.tab.mov.zip)

**Comment by LieutenantRoger** [comment] 2020-04-18 13:40
Thanks @SathyaJayabal   

I have merged the `develop` branch code into this feature-branch for this ticket and deployed the code onto `dev env`, please test it on Monday. 

Thanks

**Comment by sandhiyakavi** [comment] 2020-04-20 04:29
@LieutenantRoger  If we click the member handle from the member search results, it is directing to the member profile from the legacy page.

Attached video for the same.

![image](https://user-images.githubusercontent.com/55895538/79713983-6378e380-830a-11ea-9799-883c08f724ef.png)

[member_search_legacypage.zip](https://github.com/topcoder-platform/community-app/files/4501236/member_search_legacypage.zip)

**Comment by sandhiyakavi** [comment] 2020-04-20 06:41
Other than the above issue, everything is good

Topgear page:
1. Challenge Details: Registrants, Submission and Winners- Opens in new tab - Pass
2. Profile->Stats history: all the link opens in new tab - Pass
3. Leaderboard: Opens in new tab but displays 404 HTTP error (need to test in Prod)

Topcoder page:
1. Challenge Details: Registrants, Submission and Winners- Opens in same tab - Pass
2. Profile->Stats history: all the link opens in same tab - Pass
3. Member search->opens in same tab but legacy page displayed.(above mentioned issue).

**Comment by LieutenantRoger** [comment] 2020-04-20 15:19
@SathyaJayabal   It's environment issue, because the search page on dev environment is routing to legacy app, but the search in production page is still inside community-app.

We are not using legacy search page in production, so we don't need to fix the legacy page.  I guess @sushilshinde  will have to update the search route on the dev environment to be served inside community-app as well.

Here's a snapshot for comparison.
 
https://take.ms/G4qlQ

**Comment by SathyaJayabal** [comment] 2020-04-21 03:57
@LieutenantRoger marking this as pass as per previous comment

**Comment by sushilshinde** [comment] 2020-04-21 05:18
@LieutenantRoger please raise PR to develop

**Comment by SathyaJayabal** [comment] 2020-04-22 09:05
Verified on dev env(develop branch)
Topgear pages:
Challenge Details: Registrants, Submission and Winners- Opens in new tab - Pass
Profile->Stats history: all the link opens in new tab - Pass
Leaderboard: Opens in new tab-verified this one on beta.
[topgear leaderboard.mov.zip](https://github.com/topcoder-platform/community-app/files/4514986/topgear.leaderboard.mov.zip)

Topcoder pages:
Challenge Details: Registrants, Submission and Winners- Opens in same tab - Pass
Profile->Stats history: all the link opens in same tab - Pass
Member search->opens in same tab. verified this one on beta.
[search results.mov.zip](https://github.com/topcoder-platform/community-app/files/4514996/search.results.mov.zip)

**Comment by sandhiyakavi** [comment] 2020-04-24 11:24
@LieutenantRoger @Oanh-and-only-Oanh  Need clarification for the below.

In the tco20 pages, 
Leaderboard page: https://tco20.topcoder.com/competition-overview/qa/leaderboard
Regional Leaderboard page: https://tco20.topcoder.com/regional-events/southern-asia/leaderboard
Opens in new tab with the url like https://tco20.topcoder.com/members/cyberjag/ . is that the expected behaviour?

[Leaderboard_page.zip](https://github.com/topcoder-platform/community-app/files/4528549/Leaderboard_page.zip)
[RegionalEvent_leaderboard_page.zip](https://github.com/topcoder-platform/community-app/files/4528550/RegionalEvent_leaderboard_page.zip)

**Comment by LieutenantRoger** [comment] 2020-04-24 12:30
Hi @sandhiyakavi 

I think this is expected behavior.  tco20.topcoder.com can be treated as a sub-community as well, as it is for tco20 only. 

@Oanh-and-only-Oanh  please comment more if you have otherwise opinion. :)

**Comment by sandhiyakavi** [comment] 2020-04-24 12:40
Except the above clarification.Everything else is working fine.

Topgear pages:
Challenge Details: Registrants, Submission and Winners- Opens in new tab - Pass
Leaderboard: Opens in new tab - Pass

Topcoder pages:
Challenge Details: Registrants, Submission and Winners- Opens in same tab - Pass
Profile->Stats history: all the link opens in same tab - Pass
Member search->opens in same tab - Pass

**Closed** 2020-04-24 14:46 UTC
Labels: Merged for smoke, Need clarification, P1, Prod Env

**Comment by lakshmiathreya** [comment] 2020-04-27 13:35
@SathyaJayabal - why isnt this set to Pass?
