### ISSUE TITLE
Ratings not updated on profile

### ISSUE THREAD

**Issue by m-yadav** [topcoder-platform/community-app#3227] opened 2019-08-19 08:49 UTC
**Describe the bug**
A user reported that rating in his profile (https://www.topcoder.com/members/square1001) shows 2313 rating, which is only updated to TCO19 Round 3B match. His real rating is 2435, so it seems like the rating history graph is not updated (or rollbacked).

Note: In match stats (https://community.topcoder.com/stat?c=round_stats_sorted&rd=17663&dn=1&sq=Round_Statistics_Data&sc=16&sd=asc) it is updated. It is just non-updated in the dashboards/profile.

**Comment by m-yadav** [comment] 2019-08-19 09:30
cc : @urwithat

**Comment by sharathkumaranbu** [comment] 2019-08-19 10:19
I have the same issue in code track as well

The profile page and dashboard page still shows old rating and color

https://www.topcoder.com/members/Sharathkumar92

If I register for any challenge, I see yellow rating with updated value.

Challenge listing page

![image](https://user-images.githubusercontent.com/7723558/63258024-c0faf300-c298-11e9-8725-0a2c6b723117.png)

Rating value updated in OR but the color is coming from MM track, I have raised issue for that with support but value is updated.

![image](https://user-images.githubusercontent.com/7723558/63258060-d243ff80-c298-11e9-9c3f-b74dd7546914.png)

**Comment by RishiRajSahu** [comment] 2019-10-11 05:08
@codeMinter this is the older issue, I think its fixed..Have you seen the rating on profile of square1001. It seems right to me. Or what should be the new correct rating otherwise ?

**Comment by codeMinter** [comment] 2019-10-11 05:35
@RishiRajSahu The rating shown https://community.topcoder.com/stat?c=round_stats_sorted&rd=17663&dn=1&sq=Round_Statistics_Data&sc=16&sd=asc and https://www.topcoder.com/members/square1001 are still not in sync. 

Can you once validate if the loader for using ratings to DynamoDb is working fine?

**Comment by RishiRajSahu** [comment] 2019-10-11 05:41
It was 2435 on Aug 10, after that it dropped for next SRMs, please check carefully on the graph.

Also the loader is working fine, and I am aware that yesterday there was an SRM so if the member has participated in that the new rating will be updated today, as the loader hasn't yet ran.

**Comment by codeMinter** [comment] 2019-10-11 05:51
oh yes, was looking at old SRM numbers. It matches as per last one https://community.topcoder.com/stat?c=round_stats&rd=17678

**Comment by codeMinter** [comment] 2019-10-11 05:54
> I have the same issue in code track as well
> 
> The profile page and dashboard page still shows old rating and color
> 
> https://www.topcoder.com/members/Sharathkumar92
> 
> If I register for any challenge, I see yellow rating with updated value.
> 
> Challenge listing page
> 
> ![image](https://user-images.githubusercontent.com/7723558/63258024-c0faf300-c298-11e9-8725-0a2c6b723117.png)
> 
> Rating value updated in OR but the color is coming from MM track, I have raised issue for that with support but value is updated.
> 
> ![image](https://user-images.githubusercontent.com/7723558/63258060-d243ff80-c298-11e9-9c3f-b74dd7546914.png)

@sharathkumaranbu for your case, I see color and ratings match. Recently we have updated the ratings colors in July/Aug time frame. Your rating and color match as per https://www.topcoder.com/members/Sharathkumar92/details/?track=DEVELOP&subTrack=CODE

Can you elaborate on the issue, if different ?

**Comment by codeMinter** [comment] 2019-10-11 05:55
> The profile page and dashboard page still shows old rating and color

@sharathkumaranbu for your case, I see color and ratings match. Recently we have updated the ratings colors in July/Aug time frame. Your rating and color match as per https://www.topcoder.com/members/Sharathkumar92/details/?track=DEVELOP&subTrack=CODE

Can you elaborate on the issue, if different ?

**Comment by Oanh-and-only-Oanh** [comment] 2019-10-14 18:20
Closing issue- Not a bug

**Closed by Oanh-and-only-Oanh** 2019-10-14 18:20 UTC
Labels: P1
