### ISSUE TITLE
Create content model for Tutorial/Editorial Pages

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1062] opened 2018-06-13 16:07 UTC
We'd like to create a generic content model that we can use for tutorials and editorial-like content.  The components of it will be:

title
author
text (can include images and formatting)
date published
tags

It would be very similar to a blog post format, and we'd like to be able to reuse it for many purposes.  For example, we should use it to support SRM editorials, Data Science tutorials, etc.

Some form of commenting/discussion around each article will be an important v2 feature.

**Comment by vic-topcoder** [comment] 2018-06-13 22:28
@ajefts Several questions:

- What formatting is supported in the Content (text)? 
- Do you have an excerpt for public view as part of it, and should it be show in different page (like a category page)?
- If you have except, do you have a header image/preview image for category listing?
- Do we have a related challenge link for the editorial (if it is an analysis of solutions on a marathon match or particular problem)?

**Comment by birdofpreyru** [comment] 2018-06-13 23:12
@ajefts we don't need new models for these, this are covered by _Route_ and _Viewport_ components (probably with some pending enhancements to them). Give me a few days to better assess their current performance, clean-up small sins, and document the current state of things.

@vic-topcoder I did not get, what do you mean by _except_? For text blocks we have high level setup to support anything you want. Large text blocks should be written in Markdown (MD) format, and we have solution to recognize any HTML / JSX code blend in into MD markup. It is on my todo list to start documentation pages for content creators :)

**Comment by vic-topcoder** [comment] 2018-06-13 23:32
If we follow the Wordpress post structure, they have some more fields to a post - like a short piece of text that is displayed only on specific pages, which is different from the main body. There are also other fields - like the header image that I've mentioned.

Good to know we need full support for MD as style. In this case I would defer to using the challenge page styling as default for a post.

**Comment by birdofpreyru** [comment] 2018-06-13 23:43
Wordpress data model comes with blog posts in mind. For Tutorials/Editorials in Contentful, I believe, we should forget about Wordpress model. It will will be more like this: you need a new tutorial - you create such tutorial page, with the content to show at that page; do you need a content page that shows the list of relevant tutorials, with brief abstracts - you create it as independent page, adding all necessary abstracts there. I.e. the abstracts will be not a part of tutorial object, but a part of the content page.

**Comment by vic-topcoder** [comment] 2018-06-13 23:45
I would expect to be able to edit the related Abstract and Tutorial content at the same interface. Abstract === Excerpt

**Comment by birdofpreyru** [comment] 2018-06-13 23:51
Well, such Wordpress-like entries will be covered by blog post objects in https://github.com/topcoder-platform/community-app/issues/1063, we can use those for tutorials.

**Comment by kkartunov** [comment] 2018-06-14 04:09
It also looks to me that the `Blog Post` object from #1063 meets all criteria required here. We can re-use it. Probably rename `Blog Post` to just `Post` and tell content writers they should use it for posts, tutorials, editorials and etc.?
Regarding abstract it is included by design as Description === Abstract === Excerpt but we can rename it as we want.

**Comment by nithyaasworld** [comment] 2019-06-19 11:42
Closing this as the issue seems to have resolved. Please re-open if not.

**Closed by nithyaasworld** 2019-06-19 11:42 UTC
