### ISSUE TITLE
Unable To Open Challenge Liberty Unstructured/ Exploratory Bug Hunt Challenge

### ISSUE THREAD

**Issue by VanitaW** [topcoder-platform/community-app#594] opened 2017-11-15 16:49 UTC
![screen shot 2017-11-15 at 10 48 11 am](https://user-images.githubusercontent.com/12702517/32848686-b2bc2e3a-c9f2-11e7-8db3-947ec97b70fe.png)

**Comment by birdofpreyru** [comment] 2017-11-23 14:46
I believe, it was a temporary problem, caused by instability of the backend API, and should not be an issue anymore; thus closing this ticket for now.

**Closed by birdofpreyru** 2017-11-23 14:46 UTC
