### ISSUE TITLE
[$100]The "My Challenges" does not list the correct challenges the member is registered with

### ISSUE THREAD

**Issue by tmalbonph** [topcoder-platform/community-app#4782] opened 2020-08-19 10:18 UTC
**Describe the bug**
The "My Challenges" does not list the correct challenges the member is registered with
 
**To Reproduce**
1. Go to https://www.topcoder.com/challenges
2. Select a challenge and register with that challenge.
3. Do step 2 twice or more.
4. Visit the page https://www.topcoder.com/challenges/?bucket=my

**Expected behavior**
The page should list all the challenges the member have registered with

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: Version 84.0.4147.125 (Official Build) (64-bit)

**I have register with 5 challenges here:**
![software-challenges-listing](https://user-images.githubusercontent.com/3745678/90622702-11a88180-e248-11ea-84a2-1ef189b766e6.png)

**But the My Challenges page only listed 1 challenge**
![my-bucket-listing](https://user-images.githubusercontent.com/3745678/90622696-0fdebe00-e248-11ea-8378-76fea16814e2.png)

**Comment by SathyaJayabal** [comment] 2020-08-19 12:00
@sushilshinde , api response returns all 5 challenges for the user
https://api.topcoder.com/v5/challenges?status=Active&memberId=22874592

Not able to reproduce the above scenario with the test users

**Comment by tmalbonph** [comment] 2020-08-19 12:01
@SathyaJayabal you should use different user if you can't reproduce what was posted

**Comment by crazyk07** [comment] 2020-08-19 16:51
Contest https://www.topcoder.com/challenges/30137842 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by sushilshinde** [comment] 2020-08-19 16:52
@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup

Submit in 8 hours and PR to

https://github.com/topcoder-platform/community-app/tree/integration-v5-challenge-api
https://github.com/topcoder-platform/topcoder-react-lib/tree/integration-v5-challenge-api

run `npm run test` before PR

**Comment by crazyk07** [comment] 2020-08-19 16:55
Contest https://www.topcoder.com/challenges/30137842 has been updated - it has been assigned to cagdas001.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by cagdas001** [comment] 2020-08-19 17:17
I can't reproduce either.

@tmalbonph if you can constantly reproduce the issue, could you help us by taking a screencast & collecting some logs? (console & network tab of devtools)

You can export the logs of network tab by following this guide: https://developers.google.com/web/tools/chrome-devtools/network/reference#export

Reproduce the issue while devtools is logging, and then share us them

**Comment by tmalbonph** [comment] 2020-08-19 20:49
@cagdas001 
1.The error still exist.
2.The challenge that is not showing are those challenges that I was registered from Aug 11, 2020 12:27 EDT to Aug 17, 2020 16:31 EDT
3. (I am guessing for this item) If the database is migrated into a new one to fit the new API; It is possible the error could came from missing value for added new field.

**Comment by sushilshinde** [comment] 2020-08-20 16:21
@tmalbonph  can you find me on Topcoder Community Slack

My handle : Sushil

**Comment by tmalbonph** [comment] 2020-08-21 08:02
@sushilshinde okay - will DM you now

**Comment by sumitdaga** [comment] 2020-08-21 08:27
@sushilshinde @SathyaJayabal @cagdas001  
i can see a similar issue, at the moment i am registered in 8 challenges but i can only see 2 in My Challenges section  
i came here to log an issue and saw there is already one logged  
and yes https://api.topcoder.com/v5/challenges?status=Active&memberId={myUserId} does return all the 8 challenges  

thanks

**Comment by cagdas001** [comment] 2020-08-21 08:40
@sumitdaga 

You fired this request (https://api.topcoder.com/v5/challenges?status=Active&memberId={myUserId})  manually or this is the request you're seeing in the network tab of DevTools?

What I understand is, you see this request in network tab and response contains all the 8 challenges, but in the My Challenges bucket, you only see 2 of them. Is my understanding correct? 

If so, could you share the response of this request containing all 8 challenges so we can check if there is an issue with those specific challenges? In addition do see any error in console?

Thanks

**Comment by cagdas001** [comment] 2020-08-23 21:07
PRs:
#4801 and topcoder-platform/topcoder-react-lib#228

I drop out the resource-api call here, and use `GET /challenges?memberId=<memberId>&status=Active` instead. Resource API is returning thousands of challenge Ids, and the same operation is already being done by the challenge-api when we use `memberId` criteria. 

https://github.com/topcoder-platform/challenge-api/blob/d66fbfa9ec2d4197bcd4f6c8419cf5af73f38230/src/services/ChallengeService.js#L406-L411
```js
  if (criteria.memberId) {
    // logger.error(`memberId ${criteria.memberId}`)
    const ids = await helper.listChallengesByMember(criteria.memberId)
    // logger.error(`response ${JSON.stringify(ids)}`)
    accessQuery.push({ terms: { _id: ids } })
  }
```

https://github.com/topcoder-platform/challenge-api/blob/d66fbfa9ec2d4197bcd4f6c8419cf5af73f38230/src/common/helper.js#L623-L628
```js
async function listChallengesByMember (memberId) {
  const token = await getM2MToken()
  const url = `${config.RESOURCES_API_URL}/${memberId}/challenges?perPage=10000`
  const res = await axios.get(url, { headers: { Authorization: `Bearer ${token}` } })
  return res.data || []
}
```

Also there were some unnecessary calls, it should now be more efficient & fast (for e.g. it was calling the old endpoint twice, and the new endpoint is already called when the page first initialized. so no need to call again)

----

Btw, one thing to note about resource-api, `perPage` parameter is not consistent with the count of returned resources. For e.g. it returns 960 resources when we use default size (1000), or 1060 when we use `perPage=1100`

I guess it's because of this line, which creates a duplicate-free list: https://github.com/topcoder-platform/resources-api/blob/c7be0c0c4f1531b9bcb26de60fa0645c6bee6a43/src/services/ResourceService.js#L450

```js
  const arr = _.uniq(_.map(result, 'challengeId'))
```

So, looks like ES returns exactly `perPage` records (1000, or 1100 for e.g.), but because of this line, we see less in the final response.

**Comment by rootelement** [comment] 2020-08-24 12:27
We have an open issue to add an isActive flag to resources to mirror the challenge state. That will allow us to filter resources, or challenges a resource is associated with, to the state of the challenge you're looking for. Usually you'll be looking for Active challenges, which should cut it down significantly. 

https://github.com/topcoder-platform/challenge-api/issues/241

**Comment by SathyaJayabal** [comment] 2020-08-25 07:14
@cagdas001 , which user did you use to reproduce this issue?

**Comment by cagdas001** [comment] 2020-08-25 09:48
@SathyaJayabal you can ask @tmalbonph and @sumitdaga (they're present on Slack) to validate the fix on staging env. https://staging-community-app.topcoder.com

 If you have an old account that has lots of challenges, you can probably reproduce with it too.

**Comment by tmalbonph** [comment] 2020-08-25 10:24
@sushilshinde The "My Challenges" display correct challenges registered

as listed on **my bucket list**
![Screenshot from 2020-08-25 18-16-27](https://user-images.githubusercontent.com/3745678/91163444-28475080-e700-11ea-8c6c-5e8c93111d4b.png)

**Comment by sumitdaga** [comment] 2020-08-25 11:15
@sushilshinde @SathyaJayabal  @cagdas001  
its ok now, all my challenges are being displayed in "My Challenges" bucket  
thanks

**Comment by lakshmiathreya** [comment] 2020-08-25 13:04
Admin users unable to see My Challenges ...
<img width="1656" alt="Screenshot 2020-08-25 at 6 32 14 PM" src="https://user-images.githubusercontent.com/51733042/91177574-8b85b280-e701-11ea-992c-c8cfcdff0712.png">

**Comment by SathyaJayabal** [comment] 2020-08-25 14:50
@cagdas001 , yes the admin users are able to see my challenges in Production, but not on staging after the fix.

**Comment by sushilshinde** [comment] 2020-08-26 04:09
@rootelement

**Comment by sushilshinde** [comment] 2020-08-27 10:12
@rootelement here is an example 

## On dev with TonyJ, API returns results 

```
curl 'https://api.topcoder-dev.com/v5/challenges?perPage=99&page=1&status=Active&memberId=40152905' \
  -H 'authority: api.topcoder-dev.com' \
  -H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJUb3Bjb2RlciBVc2VyIl0sImlzcyI6Imh0dHBzOi8vYXBpLnRvcGNvZGVyLWRldi5jb20iLCJoYW5kbGUiOiJkYW5fZGV2ZWxvcGVyIiwiZXhwIjoxNTk4NTIzMzIwLCJ1c2VySWQiOiI0MDE1MjkwNSIsImlhdCI6MTU5ODUyMjcyMCwiZW1haWwiOiJ0amVmdHMrZGFuX2RldmVsb3BlckB0b3Bjb2Rlci5jb20iLCJqdGkiOiI4MWFjNGYyYy1jZGQ2LTQ3MTAtOWUwNy1mMmExNGRlNjRjMzYifQ.s982Mtf4kVHK2-UUNo9VeQv3dH3gVdv8zNy6fMxWY_8' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'accept: */*' \
  -H 'origin: https://www.topcoder-dev.com' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://www.topcoder-dev.com/challenges' \
  -H 'accept-language: en-US,en;q=0.9,la;q=0.8' \
  --compressed
```
<img width="2004" alt="Postman 2020-08-27 15-40-13" src="https://user-images.githubusercontent.com/683231/91427574-bc89f280-e87b-11ea-982f-a28ad83ba067.png">


##On prod with _sushilshinde it doesn't return results

```
curl 'https://api.topcoder.com/v5/challenges?perPage=99&page=1&status=Active&memberId=40623428' \
  -H 'authority: api.topcoder.com' \
  -H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJUb3Bjb2RlciBVc2VyIiwiQ2xpZW50IE1hbmFnZXIiLCJjb3BpbG90IiwiRGVsZWdhdGUgUG9saWN5IExvYWRlciIsInJvenlrYyIsImFkbWluaXN0cmF0b3IiXSwiaXNzIjoiaHR0cHM6Ly9hcGkudG9wY29kZXIuY29tIiwiaGFuZGxlIjoiX3N1c2hpbHNoaW5kZSIsImV4cCI6MTU5ODUyMzI2MywidXNlcklkIjoiNDA2MjM0MjgiLCJpYXQiOjE1OTg1MjI2NjMsImVtYWlsIjoic3VzaGlsLnNoaW5kZUB0b3Bjb2Rlci5jb20iLCJqdGkiOiJlNGJiM2ExNi0xOThlLTQ2MTgtOGU2Mi02NTg1NjQ0OTNiODgifQ.C5BxtFBC39KqDO4aGEooaF46rnFHxFFEHcaMf4sLkyM' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'accept: */*' \
  -H 'origin: https://staging-community-app.topcoder.com' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://staging-community-app.topcoder.com/challenges' \
  -H 'accept-language: en-US,en;q=0.9,la;q=0.8' \
  -H 'if-none-match: W/"2-l9Fw4VUO7kr8CvBlt4zaMCqXZ0w"' \
  --compressed
```

<img width="2032" alt="Postman 2020-08-27 15-40-57" src="https://user-images.githubusercontent.com/683231/91427595-c14ea680-e87b-11ea-827e-52b9e806cc02.png">

**Comment by lakshmiathreya** [comment] 2020-08-27 11:50
Admin user in Prod: 
<img width="1484" alt="Screenshot 2020-08-27 at 5 15 55 PM" src="https://user-images.githubusercontent.com/51733042/91438523-21981500-e889-11ea-8724-f98b2b71de39.png">
Same user in Beta (v4):
<img width="1460" alt="Screenshot 2020-08-27 at 5 19 54 PM" src="https://user-images.githubusercontent.com/51733042/91438786-8f444100-e889-11ea-97b8-dc653e492988.png">

**Comment by cagdas001** [comment] 2020-08-27 12:00
That's because Beta still uses `GET /resources/<memberId>/challenges` endpoint to get user challenges. We have changed it to use `GET /challenges?memberId=<userId>&status=Active` instead

If this issue is urgent, we can switch back to the  `GET /resources/<memberId>/challenges` endpoint, with a larger `perPage` parameter (details https://github.com/topcoder-platform/community-app/issues/4782#issuecomment-678825053)

**Comment by sushilshinde** [comment] 2020-08-27 12:08
Plus it should not return "My Challenges" without token 

http://api.topcoder.com/v5/challenges?status=Active&memberId=40623428

**Comment by sushilshinde** [comment] 2020-08-27 13:21
here is the difference 

https://api.topcoder.com/v4/challenges?status=Active&memberId=40594007

https://api.topcoder.com/v5/challenges?status=Active&memberId=40594007

**Comment by cagdas001** [comment] 2020-08-27 13:53
> Plus it should not return "My Challenges" without token
>
> http://api.topcoder.com/v5/challenges?status=Active&memberId=40623428

It should return only Submitter roles (that's how `resource-api` works). But, since the M2M token is being passed to the `GET /resources/<memberId>/challenges` endpoint, it currently returns all challenges.

See here: https://github.com/topcoder-platform/challenge-api/blob/081c4fea75365f45a80531bb4afaea530d8cab10/src/common/helper.js#L624

Ideally, it should pass the user's (calling the endpoint) token and not the M2M token, so `resource-api` can return correct challengeIds based on the token's auth level

Currently anyone (without any valid token), can see all the challenges of a member (no matter what the member's role in challenge is)


One more thing, it's using `perPage=10000` parameter for this call. Considering the huge amount of resources admins have access to, 10000 even might not be enough. I'm not sure as I don't have any admin account experiencing this issue, but this might be the root cause


As a workaround, I'll now prepare a PR that reverts the previous changes (https://github.com/topcoder-platform/community-app/issues/4782#issuecomment-678825053) and switch back to the `GET /resources/<userId>/challenges` endpoint, with a large `perPage` parameter

**Comment by cagdas001** [comment] 2020-08-27 16:16
#4825 and topcoder-platform/topcoder-react-lib#232 revert the previous changes and increase the `perPage` value. This should work for now

**Comment by sushilshinde** [comment] 2020-08-28 09:58
@cagdas001 thanks, will merge this on monday.

**Comment by sushilshinde** [comment] 2020-08-31 08:44
@rootelement we are switching back to the original solution, waited for your reply though.

**Comment by SathyaJayabal** [comment] 2020-08-31 10:59
@cagdas001 , All challenges are displayed under My Challenges
<img width="1440" alt="Screenshot 2020-08-31 at 2 57 02 PM" src="https://user-images.githubusercontent.com/58783823/91713269-0ee25080-eba7-11ea-90a7-203396376a62.png">

**Comment by tmalbonph** [comment] 2020-08-31 11:28
Visiting "My Challenges" link here https://staging-community-app.topcoder.com/challenges/?bucket=my **gives the wrong Challenges listing**

![Screenshot from 2020-08-31 19-26-15](https://user-images.githubusercontent.com/3745678/91715288-ef0b5680-ebbf-11ea-9aee-29399d01fef5.png)

**Comment by cagdas001** [comment] 2020-08-31 12:08
@SathyaJayabal Looks like one of my commits was not involved in the PR. It will be fixed after merging this https://github.com/topcoder-platform/topcoder-react-lib/pull/236 and deployed

**Comment by SathyaJayabal** [comment] 2020-09-02 03:14
@sumitdaga @tmalbonph , can one of you verify if the "My Challenges" bucket is working fine for you ?

**Comment by cagdas001** [comment] 2020-09-02 03:18
@SathyaJayabal the fix is deployed to the prod? If it's not, they'll need to test it out with staging env

**Comment by SathyaJayabal** [comment] 2020-09-02 03:20
> @sumitdaga @tmalbonph , can one of you verify if the "My Challenges" bucket is working fine for you ?

@sumitdaga @tmalbonph , the url to test this is `https://staging-community-app.topcoder.com/challenges?`

**Comment by tmalbonph** [comment] 2020-09-02 03:21
@SathyaJayabal Visiting "My Challenges" link here https://staging-community-app.topcoder.com/challenges/?bucket=my **gives the correct Challenges listing**

![Screenshot from 2020-09-02 11-18-46](https://user-images.githubusercontent.com/3745678/91928278-3a337f80-ed0e-11ea-99ec-60680358b311.png)

The **Online Review Listing** here: https://software.topcoder.com/review/actions/ListProjects

![Screenshot from 2020-09-02 11-20-09](https://user-images.githubusercontent.com/3745678/91928342-5e8f5c00-ed0e-11ea-89ef-aba2cc790f88.png)

**Comment by SathyaJayabal** [comment] 2020-09-02 03:22
@tmalbonph, Thank you

**Comment by SathyaJayabal** [comment] 2020-09-02 03:28
@sushilshinde @lakshmiathreya , can one of you please verify my challenges works fine on staging for admin user?

**Comment by SathyaJayabal** [comment] 2020-09-02 04:07
Verified if the `my challenges` bucket for the following roles on staging
```
submitter
observer
reviewer
copilot
```

**Comment by sumitdaga** [comment] 2020-09-02 05:59
@SathyaJayabal  yes, it is fixed here https://staging-community-app.topcoder.com/challenges/?bucket=my  
I can see all my challenges in `My Challenges` bucket.  

Thanks

**Comment by SathyaJayabal** [comment] 2020-09-02 06:13
thanks @sumitdaga ,

verified with admin role
<img width="1481" alt="Screenshot 2020-09-02 at 11 25 46 AM" src="https://user-images.githubusercontent.com/58783823/91938377-8c29d480-ed11-11ea-9451-74fa1caec4be.png">

**Comment by SathyaJayabal** [comment] 2020-09-02 10:24
Verified my challenges bucket on staging (develop branch)

**Comment by SathyaJayabal** [comment] 2020-09-03 03:59
@tmalbonph @sumitdaga , this fix has been released. Can one of you please verify on production.
https://www.topcoder.com/challenges?
Thank you both for your help with testing this issue.

**Comment by tmalbonph** [comment] 2020-09-03 04:07
@SathyaJayabal Viewing now the link here: https://www.topcoder.com/challenges/?bucket=my **Display correct challenges I am register with**
![Screenshot from 2020-09-03 12-05-45](https://user-images.githubusercontent.com/3745678/92070161-ed1ede80-eddd-11ea-9ce9-b85a9fd1b85c.png)

**Verification via Online Review**
![Screenshot from 2020-09-03 12-06-05](https://user-images.githubusercontent.com/3745678/92070181-f445ec80-eddd-11ea-98a3-1c3a5b076249.png)

**Comment by crazyk07** [comment] 2020-09-03 04:07
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by SathyaJayabal** [comment] 2020-09-03 04:09
@tmalbonph Thanks.

**Comment by crazyk07** [comment] 2020-09-03 04:11
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30137842<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed** 2020-09-03 04:10 UTC
Labels: Challenge Listing, P2, Prod Env, QA Pass, tcx_Assigned, tcx_FixAccepted, v5-intgration-sub-code
