### ISSUE TITLE
[$30] Add Handle to member ratings page

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#3465] opened 2019-11-21 17:55 UTC
Let's click [link of my SRM rating graph](https://www.topcoder.com/members/square1001/details/?track=DATA_SCIENCE&subTrack=SRM) - you'll see, that the handle name "square1001" is nowhere in this page.  
  
It's confusing whose rating graph it is, and the current only way to see is to see the link of the page. We need to add the member handle to this page.

<p></p>

**Comment by ajefts** [comment] 2019-11-21 17:55
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/3141275

**Comment by codeMinter** [comment] 2019-11-27 02:32
@ajefts @Oanh-and-only-Oanh can you share snapshot of how we want to show handle, as I don't have access to https://tcprod.productboard.com/feature-board/planning/features/3141275

**Comment by codeMinter** [comment] 2019-11-27 02:37
![SRM](https://user-images.githubusercontent.com/14284629/69688714-da5bd880-10ec-11ea-8f44-a71aedffbaab.png)

Does something like this looks good? We will have same colouring affect as rating for handle and for label "handle" like "rating" - didn't wanted to invest time into implementation first so thought to get design approval first. 

@Oanh-and-only-Oanh @ajefts ☝️

**Comment by Oanh-and-only-Oanh** [comment] 2019-11-27 03:25
@codeMinter, let's show profile picture and username and use the same coloring as their "rating". No need to have "handle" label.

**Comment by codeMinter** [comment] 2019-11-30 00:37
<img width="1225" alt="srm_handle" src="https://user-images.githubusercontent.com/14284629/69893451-a3c5ce00-1337-11ea-867c-d343935c5a13.png">

@Oanh-and-only-Oanh FYI ☝️

**Comment by codeMinter** [comment] 2019-12-02 14:56
@Oanh-and-only-Oanh @nithyaasworld  this is on DEV - http://www.topcoder-dev.com/members/tourist/details/?track=DATA_SCIENCE&subTrack=SRM

**Comment by Oanh-and-only-Oanh** [comment] 2019-12-02 17:18
@codeMinter, can you 1) make username name a hyperlink that directs them to the profile page 2) if no profile picture is available, make default profile picture this? https://icon-library.net/icon/default-profile-icon-24.html

**Comment by nithyaasworld** [comment] 2019-12-03 04:52
@codeMinter @Oanh-and-only-Oanh Can we reduce the font of the handle name as it looks big if the handle name is little big?

![image](https://user-images.githubusercontent.com/5114190/70021480-db8e7900-15b6-11ea-9c90-71a1c2a5fc29.png)

![image](https://user-images.githubusercontent.com/5114190/70021436-c0bc0480-15b6-11ea-993c-953f51b84e7d.png)

**Comment by codeMinter** [comment] 2019-12-03 04:53
@nithyaasworld Sure will do so.

**Comment by codeMinter** [comment] 2019-12-03 04:57
> @codeMinter, can you 1) make username name a hyperlink that directs them to the profile page 2) if no profile picture is available, make default profile picture the current default icon
> ![image](https://user-images.githubusercontent.com/47536078/69981439-29d44700-14e7-11ea-9189-96fa35184612.png)

@Oanh-and-only-Oanh Since the users are landing from profile page to this screen. would adding something like `< ` before SRM make sense here which takes them back to profile page. Thoughts ?

for 2) I checked the code, we are already using the default one. Do we have something else as default ? any pointers where I can check default pic?

**Comment by Oanh-and-only-Oanh** [comment] 2019-12-03 17:10
@codeMinter, for 1)  something like < before SRM works, 2) since we're already using the default one if user has no profile picture, no changes then.

**Comment by codeMinter** [comment] 2019-12-05 04:28
@Oanh-and-only-Oanh @nithyaasworld this is on test, can you help test this ?

**Comment by codeMinter** [comment] 2019-12-05 18:32
@Oanh-and-only-Oanh As discussed, we now show image and handle on all stats pages. It is ready on TEST server now.

**Comment by nithyaasworld** [comment] 2019-12-06 19:01
@codeMinter This seems to be not available on Test environment now. Kindly help to deploy it again for testing.

**Comment by nithyaasworld** [comment] 2019-12-06 19:02
Please ignore, just saw that Oanh has already tested this.

**Comment by nithyaasworld** [comment] 2019-12-11 09:43
Verification screenshot:

![image](https://user-images.githubusercontent.com/5114190/70610012-cfdf2a00-1c28-11ea-8c64-08385a51f27f.png)

**Comment by SathyaJayabal** [comment] 2019-12-14 07:55
Verified in production
<img width="1400" alt="3465 verification" src="https://user-images.githubusercontent.com/58783823/70845479-2c368980-1e75-11ea-8526-a93812c28282.png">

**Comment by Oanh-and-only-Oanh** [comment] 2020-01-15 18:31
@SathyaJayabal, looks like this is still an issue....

**Comment by crazyk07** [comment] 2020-01-15 20:04
Contest https://www.topcoder.com/challenges/30112840 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by kkartunov** [comment] 2020-01-15 20:05
@topcoder-platform/topcodercompetitors this one is reopened and ready for pickup.

The issue is blank screen is displayed when clicking on the handle link that has been fixed here. The result is nothing changes and browser is never redirected to the user profile.

Expected behavior: The link should work correctly and browser should navigate to the user profile on click.

**Comment by crazyk07** [comment] 2020-01-16 02:55
Contest https://www.topcoder.com/challenges/30112840 has been updated - it has been assigned to rashmi73.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by kkartunov** [comment] 2020-01-16 09:00
@rashmi73  thanks for pickup. Please, PR to https://github.com/topcoder-platform/community-app/tree/feature-member-profiles branch. Thanks

**Comment by rashmi73** [comment] 2020-01-16 20:20
@kkartunov PR https://github.com/topcoder-platform/community-app/pull/3577

**Comment by kkartunov** [comment] 2020-01-21 07:35
@SathyaJayabal @nithyaasworld this is ready for testing on dev.

**Comment by SathyaJayabal** [comment] 2020-01-22 07:20
@kkartunov 

1. Access the ratings page directly (using the url) and not from the profile page.
https://www.topcoder.com/members/FireIce/details/?track=DEVELOP&subTrack=ASSEMBLY_COMPETITION
https://www.topcoder.com/members/birdofpreyru/details/?track=DEVELOP&subTrack=CODE
2. Click on < .
3. A blank page is displayed.

< button works fine when you access the page from the profile page.

Note: I think this is the same issue as with the member handle link displaying a blank page.

**Comment by kkartunov** [comment] 2020-01-22 07:37
@SathyaJayabal this is the same in prod. This means the ^^^ issue is not related to this one here. You should open another for this.

**Comment by SathyaJayabal** [comment] 2020-01-22 07:42
@kkartunov , yes you are right. I will create a new issue.

**Comment by SathyaJayabal** [comment] 2020-01-22 12:52
@kkartunov @Oanh-and-only-Oanh , the user handle opens the profile page in a new tab. I hope this is expected behaviour.

**Comment by SathyaJayabal** [comment] 2020-01-23 09:07
Verified in production
[handle.mov.zip](https://github.com/topcoder-platform/community-app/files/4102156/handle.mov.zip)

**Comment by crazyk07** [comment] 2020-01-23 09:08
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30112840<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed by SathyaJayabal** 2020-01-23 09:07 UTC
Labels: Member Profiles, P4, Prod Env, QA Pass, tcx_Assigned, tcx_FixAccepted
