### ISSUE TITLE
[$50] Profile - Issue when accessing the accounts settings page via URL

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/community-app#1204] opened 2018-08-16 10:46 UTC
If you visit the URL https://community-app.topcoder-dev.com/settings/account you will get the following error:

```
Minified React error #267; visit https://reactjs.org/docs/error-decoder.html?invariant=267&args[]=undefined for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

That is probably because somewhere we're calling `React.cloneElement()` with `null` as parameter.
You need to find the root of this issue and fix it.

Screenshot:
<img width="1415" alt="screen shot 2018-08-16 at 13 45 31" src="https://user-images.githubusercontent.com/4612921/44204284-af00e480-a15a-11e8-9146-92c06e2f3d52.png">

**Comment by ThomasKranitsas** [comment] 2018-08-16 10:46
@topcoder-platform/topcodercompetitors new ticket

**Comment by ThomasKranitsas** [comment] 2018-08-16 10:51
Contest https://www.topcoder.com/challenges/30069600 has been created for this ticket.

**Comment by rashmi73** [comment] 2018-08-16 10:52
@ThomasKranitsas can u please assign it to me thanks

**Comment by ThomasKranitsas** [comment] 2018-08-16 10:52
Contest https://www.topcoder.com/challenges/30069600 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment] 2018-08-16 10:53
Contest https://www.topcoder.com/challenges/30069600 has been updated - it has been assigned to rashmi73.

**Comment by rashmi73** [comment] 2018-08-16 20:09
@ThomasKranitsas i spent time on it, but m confused 

1.why are u hitting url with "community-app" prepend in url?
2. If we remove it then its normal url and it is working perfectly. why are u checking different environment?
3. is there any else repo which is to be seen?

some indication wud be helpful.

**Comment by ThomasKranitsas** [comment] 2018-08-16 20:27
www.topcoder.com points to the legacy code https://github.com/appirio-tech/topcoder-app

the code from this repo is deployed under community-app.topcoder.com

We use nginx to configure which routes render the code from which repo but using `community-app` instead of `www` ensures that what you see is coming from this repo.

For example:
Compare https://community-app.topcoder.com/members/thomaskranitsas with https://www.topcoder.com/members/thomaskranitsas

you'll see that the first link has the same result as the `new-master` branch of this repo while the second link has the same result as the `master` branch of the topcoder-app repo.

**Comment by rashmi73** [comment] 2018-08-16 20:32
@ThomasKranitsas so i need to look at "new-master" branch of this repo? and raise PR against "new-master"?

**Comment by ThomasKranitsas** [comment] 2018-08-16 20:33
No, you still need to work based on the new-develop branch

**Comment by rashmi73** [comment] 2018-08-16 20:39
@ThomasKranitsas ok then on deploying locally, and visiting locally "http://localhost:3000",

i get page with all links where i can reach out to each page, and then reaching to "http://localhost:3000/settings/account" works well.

then how wud i reproduce that error locally?
where to go after deploying locally? which link?

**Comment by ThomasKranitsas** [comment] 2018-08-17 13:02
Assuming that you've configured everything properly based on the README.md, it should be http://local.topcoder-dev.com:3000/settings/account

**Comment by ThomasKranitsas** [comment] 2018-08-17 13:02
@rashmi73 can you give me an ETA?
It's urgent to complete this ticket ASAP.

**Comment by sumitdaga** [comment] 2018-08-17 13:10
please assign it to me, when you decide to move on!

**Comment by ThomasKranitsas** [comment] 2018-08-17 13:10
@rashmi73 I'm assigning this to someone else as this is super urgent and it's already been 24h since you started working on this.

The issue you were facing was not a blocker that prevented you from working. Everything is documented in the readme.md

**Comment by ThomasKranitsas** [comment] 2018-08-17 13:11
Contest https://www.topcoder.com/challenges/30069600 has been updated - it has been assigned to daga_sumit.

**Comment by sumitdaga** [comment] 2018-08-17 14:19
@ThomasKranitsas 
please see if this fixes the issue!

**Comment by ThomasKranitsas** [comment] 2018-08-17 14:37
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30069600

**Closed** 2018-08-17 14:37 UTC
Labels: Assigned, Fix accepted

**Comment by rashmi73** [comment] 2018-08-17 14:44
@ThomasKranitsas yes everything was configured properly, but i feel it shud be in more detail which link goes where  because even after investing time in it i was confused though completely aware about other components.
