### ISSUE TITLE
User avatar is broken on the IE11

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2426] opened 2019-06-07 17:54 UTC
![image](https://user-images.githubusercontent.com/42398485/59123666-64d43400-8923-11e9-8a2d-71ac1e364fdc.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer

**Actual:** User avatar is broken on the IE11

**Expected:** Should display the user avatar

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10

**Browser:** IE11

**Comment by luizrrodrigues** [comment] 2020-01-07 17:12
Duplicate of #2466

**Closed** 2020-01-07 17:13 UTC
Labels: Navigation, P3, UI
