### ISSUE TITLE
 challenges data not loaded even if there are successful challenges data

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#892] opened 2018-06-08 19:20 UTC
### Reported URL ###
https://www.topcoder-dev.com/members/TonyJ/details/?track=DEVELOP&subTrack=FIRST_2_FINISH&tab=challenges

### Reproduction Steps ###
1. open https://www.topcoder-dev.com/members/TonyJ/details/?track=DEVELOP&subTrack=FIRST_2_FINISH&tab=challenges

2. click CHALLENGES tab, observe

### Expected Result ###
It should display details about 5 challenges

### Actual Result ###

See screenshot, it shows 'Sorry, no successful challenges found.'

### Screenshots ###

See comments section.

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment] 2018-06-08 19:21
<img width="1255" alt="t" src="https://user-images.githubusercontent.com/4590317/41176743-2af15be4-6b94-11e8-8895-b692024e6779.png">

**Comment by winterflame** [comment] 2018-06-11 05:09
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Blocker

**Comment by ThomasKranitsas** [comment] 2018-06-14 10:11
Duplicate of #987 the challenges tab is not implemented so it won't show up for any track/subTrack

**Closed by ThomasKranitsas** 2018-06-14 10:11 UTC
