### ISSUE TITLE
OCR pdf to key value json pair challenge page is not working.

### ISSUE THREAD

**Issue by mahantesh-wipro** [topcoder-platform/community-app#590] opened 2017-11-15 14:18 UTC
The link to register for the aforementioned title doesn't work.

**Comment by birdofpreyru** [comment] 2017-11-23 14:46
I believe, it was a temporary problem, caused by instability of the backend API, and should not be an issue anymore; thus closing this ticket for now.

**Closed by birdofpreyru** 2017-11-23 14:46 UTC
