### ISSUE TITLE
There is no sign of validation in the Birth Date field

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1388] opened 2018-09-14 02:02 UTC
**Describe the bug**
I can type whatever I wish into the date field of the Basic Info form.

**To Reproduce**
1. Go to 'https://community-app.topcoder-dev.com/settings/profile'
2. Click on 'Basic Info'
3. Scroll down to 'Birth Date' field
4. Start to type, then exit the field.
5. See error... there is no error message at all.

**Expected behavior**
There should be some kind of validation on the date field.

**Screenshots**
<img width="1280" alt="screenshot 2018-09-14 03 59 00" src="https://user-images.githubusercontent.com/35376779/45525361-eb177b80-b7d2-11e8-85c8-d5fe6ed535d2.png">

**Desktop: MacBook Pro**
 - OS: Mac OS High Sierra
 - Browser: Safari
 - Version: 11.1.2

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment] 2018-09-19 17:39
The DOB field seems to be broken. Duplicate of #1305

**Closed by ThomasKranitsas** 2018-09-19 17:39 UTC
