### ISSUE TITLE
Can't open Settings page

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2422] opened 2019-06-07 17:51 UTC
### Reproduction Steps: ###

1. Open https://test-community-app.topcoder-dev.com/challenges
2. Login with account: dan_developer/dantopcoder123
3. Try to click on arrow beside avatar 
4. Click on Settings item and observe result

### Expected Result: ###
Direct to settings page without any Error.

### Actual Result: ###
Can not open Settings page.

### Screenshots or screencast: ###

See comment

### Browser Information: ###

Google Chrome 74.0 on Windows 10

**Comment by HongHT** [comment] 2019-06-07 18:41
![1](https://user-images.githubusercontent.com/26895101/59126071-566f3200-898e-11e9-8db5-3bb40fec43df.png)

**Comment by nithyaasworld** [comment] 2019-06-09 18:25
Duplicate of https://github.com/topcoder-platform/community-app/issues/2402

**Closed by nithyaasworld** 2019-06-09 18:25 UTC
Labels: Bug Hunt, Navigation
