### ISSUE TITLE
[$50] All the remove notifications are not displayed

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1484] opened 2018-09-16 01:19 UTC
## Steps to Reproduce

1. Open the Application and Login as a valid user
2. Go to Settings > Profile > Skills
3. Add 20-30 skills (Machine Learning, Google App Engine etc..)
4. Remove one item > Success! Skill "C" was removed.
5. Remove another item > No Success! message

## Actual Result(s)

- All the remove notifications are not displayed

## Expected Result(s)

- Must display all the skill remove notifications

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** IE11

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment] 2018-09-16 02:04
https://www.screencast.com/t/pFsJwZ8uR

**Comment by sumitdaga** [comment] 2018-09-21 17:34
@ThomasKranitsas @sdgun 
the skills section does not work against development db but works against production
but i cannot reproduce this issue against production ....

**Comment by ThomasKranitsas** [comment] 2018-09-21 17:35
I just tried and it worked the 1st time but I was able to reproduce the issue on the 2nd time

**Comment by sumitdaga** [comment] 2018-09-21 17:38
@ThomasKranitsas 
ok so there is an issue when you try to remove skills fast one after the other!
what should be the behaviour in this case, as the confirm popup is pretty slow ?

**Comment by ThomasKranitsas** [comment] 2018-09-21 17:41
I can think of 2 solutions:

1. Modify the notification text to include all removed items. Something like a summary of the actions.
Example:
```
The following skills have been removed:
- abc
- xyz
```

2. Be able to show multiple notifications. This may flood the screen but it would be better than not showing some of the notifications.

You can implement any of the 2 solutions or suggest a better one.

**Comment by cwdcwd** [comment] 2018-09-21 20:45
@suppermancool pls ignore as I tinker with the labels and assignment

**Comment by ThomasKranitsas** [comment] 2018-09-21 20:46
Contest https://www.topcoder.com/challenges/30071540 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-21 20:47
Contest https://www.topcoder.com/challenges/30071540 has been updated - it has been assigned to diazz.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-09-26 08:53
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30071540<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed** 2018-09-26 08:53 UTC
Labels: Major, New Settings Page, tcx_Assigned, tcx_FixAccepted, tcx_ReadyForReview
