### ISSUE TITLE
Hover over the menu is not highlighting as expected in Marvelapp

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2527] opened 2019-06-07 21:37 UTC
**Describe the bug**
Hover over the menu is not highlighting as expected in Marvelapp

**To Reproduce**
1. Open the test URL and log in
2. Click on Work
3. Click on Tracks
4. Hover over the menu options

**Expected behavior**
Hover over the menu should highlight as per Marvelapp

**Screenshots**
![image](https://user-images.githubusercontent.com/51492004/59134805-d9878c80-897c-11e9-9cbb-cae380832c72.png)

**Smartphone:**
 - Device: Samsung Galaxy Tab A
 - OS: Android 8.1.0
 - Browser : Chrome 
 - Version : 74.0.3729.157

**Comment by nithyaasworld** [comment] 2019-06-10 10:34
![image](https://user-images.githubusercontent.com/5114190/59190107-7a529380-8b99-11e9-8c7f-5adfb3efedd3.png)

**Comment by LieutenantRoger** [comment] 2020-01-15 02:18
@luizrrodrigues  is this for android tablet ? Hover state normally doesn't needed under mobile devices.

Also, the selection indicator is having the same style as showing in the snapshot.

**Comment by luizrrodrigues** [comment] 2020-01-15 02:28
@LieutenantRoger Yeah, thanks for check.

Looks like this one was fixed.

**Comment by nithyaasworld** [comment] 2020-01-21 12:59
Not able to reproduce

**Comment by luizrrodrigues** [comment] 2020-01-21 21:18
@nithyaasworld Please add QA Pass here

**Comment by luizrrodrigues** [comment] 2020-02-28 23:11
@nithyaasworld I think we good to close this one.

**Closed** 2020-10-15 04:39 UTC
Labels: Can't Reproduce, Navigation, P4, UI
