### ISSUE TITLE
$75 | New Nav - Need "default" navigation back to dashboard

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#2396] opened 2019-06-03 07:51 UTC
**Describe the bug**

There is no way to go back to Dashboard

**To Reproduce**
1. Go to `https://test-community-app.topcoder-dev.com/challenges` or 
https://test-community-app.topcoder-dev.com/members/TonyJ or any other page
2. There is no link to go back to Dashboard

**Expected behavior**
Member should be able to click and go back to dashboard from any page of the app.

**Screenshots**

![back to dashboard](https://user-images.githubusercontent.com/683231/58785020-5542ab80-8602-11e9-923f-680cdeffad80.png)

If 1 or 2 are the options, then they are not working right now

**Desktop:**
 - OS: Mac
 - Chrome

**Comment by vic-topcoder** [comment] 2019-06-03 17:08
The Dashboard is displayed when the user clicks on Work and is logged in. If they're not logged in, the home page of the community website should be displayed instead.

<img width="1282" alt="Screen Shot 2019-06-03 at 10 08 10 AM" src="https://user-images.githubusercontent.com/8484061/58820479-9083b100-85e7-11e9-80a4-b0fef12b5367.png">

**Comment by Oanh-and-only-Oanh** [comment] 2019-06-03 18:38
@ThomasKranitsas, the navigation menu should always be expanded once member is logged in.

**Comment by vic-topcoder** [comment] 2019-06-03 22:08
To accomodate the missing navigation options from the sidebar, let's introduce a second-level navigation that lists all current navigation items once the user is logged in. In the attachment above Dashboard/Challenges/History/Payments, etc., are in the sidebar. Instead, to accommodate the intermediate state let's use the secondary menu.

We should have a new secondary navigation with the following structure:

- Dashboard
- My Profile
- Payments

We moved the Settings and Log Out as part of the standard user drop-down (people expect to find those options in the user drop-down.)
<img width="1496" alt="Screen Shot 2019-06-03 at 3 06 00 PM" src="https://user-images.githubusercontent.com/8484061/58837680-241da780-8611-11e9-9962-d808220c2ff5.png">

**Comment by applehit16** [comment] 2019-06-08 19:19
I can work on this one

**Comment by luizrrodrigues** [comment] 2019-06-08 19:59
Assigned to @applehit16

**Comment by applehit16** [comment] 2019-06-09 02:52
I tried to understand the requirements

1. > the navigation menu should always be expanded once member is logged in.
rather than
![image](https://user-images.githubusercontent.com/48845164/59154363-d72d3d00-8a25-11e9-9e9c-4beb20acc1ee.png)
The "Work" should be expanded to left
![image](https://user-images.githubusercontent.com/48845164/59154368-e57b5900-8a25-11e9-9484-c261d2eb3ebf.png)
@Oanh-and-only-Oanh 

2. 
> We should have a new secondary navigation with the following structure:
Dashboard
My Profile
Payments

@vic-tian Where are we having this secondary navigation? under "Work"?  if we have dashboard as option of secondary navigation, then what's the behavior of clicking the logo and "Work"?

3. 
> To accomodate the missing navigation options from the sidebar, let's introduce a second-level navigation that lists all current navigation items once the user is logged in. In the attachment above Dashboard/Challenges/History/Payments, etc., are in the sidebar. Instead, to accommodate the intermediate state let's use the secondary menu.

@vic-tian I don't see any sidebar in https://test-community-app.topcoder-dev.com/my-dashboard

4.
> We moved the Settings and Log Out as part of the standard user drop-down (people expect to find those options in the user drop-down.)

what's this to do with the old nav? in the new nav, payment is part of user dropdown
![image](https://user-images.githubusercontent.com/48845164/59154429-e365ca00-8a26-11e9-994e-b7e53f016f23.png)

@vic-tian Sorry, I still don't quite understand what you are trying to express. Can you attach a mock up or something?

**Comment by luizrrodrigues** [comment] 2019-06-09 08:02
@applehit16 

1. Yes

2. Yes, secondary navigation under *Work*. 
When clicking in *Work*, *Dashboard* will be selected by default. (Like when clicking in *Complete*, *All challenges* selected by default)
When clicking in the logo if the user is logged when to go Dashboard.

3. 4.
@Oanh-and-only-Oanh @vic-tian Please confirm if we need *Payments* in the dropdown menu and *Work* secondary menu.

**Comment by luizrrodrigues** [comment] 2019-06-12 17:26
@applehit16 Any status on this?

**Comment by applehit16** [comment] 2019-06-12 17:42
Sorry, a bit busy these two days. And was waiting for confirmation from
Vic-tan, but I’ll try to submit in following 12hrs. If I broke the rule,
feel free to make the issue open

**Comment by luizrrodrigues** [comment] 2019-06-12 17:46
@applehit16 Oh sorry. I'll request confirmation again.

**Comment by luizrrodrigues** [comment] 2019-06-12 17:47
@vic-tian @Oanh-and-only-Oanh Please can confirm item 3 and 4: https://github.com/topcoder-platform/community-app/issues/2396#issuecomment-500180560

**Comment by applehit16** [comment] 2019-06-13 06:39
Things keep coming, feel free to reassign from me, sorry for the delay...

**Comment by luizrrodrigues** [comment] 2019-06-13 06:47
@applehit16 Okay, no problem.

**Comment by ya3ya6** [comment] 2019-06-13 09:57
Hi, Can i work on it?

**Comment by ya3ya6** [comment] 2019-06-13 10:05
And it's my first time on bug bash, Do i have only 12 hours to complete this?

**Comment by sushilshinde** [comment] 2019-06-13 10:51
@luizrrodrigues can we speed up, this one

**Comment by luizrrodrigues** [comment] 2019-06-13 11:20
@ya3ya6 Yep, need have 12h to submit.

**Comment by luizrrodrigues** [comment] 2019-06-13 11:21
Assigned to @ya3ya6

**Comment by ya3ya6** [comment] 2019-06-13 11:26
@luizrrodrigues thanks. i get "unauthorized" error because of "contentful cms". should i use create "contentful cms" by my own or you'll share its api keys?

**Comment by luizrrodrigues** [comment] 2019-06-13 11:47
@ya3ya6 Please check your email.

**Comment by ya3ya6** [comment] 2019-06-13 12:44
@sushilshinde , @luizrrodrigues
- Currently In the last version of "community-app", when user hover on his profile image, A secondary navigation will expand and there is "Dashboard" Link on there. as you see here (its screenshot of current version on my local host):

![nav](https://user-images.githubusercontent.com/17860215/59432138-d9afde00-8dfb-11e9-94d0-faad14aec8b8.png)
- However, It's linked to https://www.topcoder.com/my-dashboard instead of http://local.topcoder-dev.com:3000/my-dashboard , wich may be intential.
- The main topcoder logo is linked to https://www.topcoder.com (home page), Not dashboard.

It just looks as @vic-tian commented before: https://github.com/topcoder-platform/community-app/issues/2396#issuecomment-498444734

So it seems that it's fixed from before, and user have an option to go back to dashboard.

So should i do anything? Should i change the target to local host, or should i set the target of Main logo to Dashboard, instead of home?

**Comment by luizrrodrigues** [comment] 2019-06-13 13:39
@ya3ya6 

- You need to use branch `feature-new-nav`
- Nav links was fixed in another issue

What we looking for here is:
- Navigation need be always expanded when used is logged.
- When click in Work need to show a secondary menu:
    - Dashboard
    - My Profile
    - Payments
- When in Logo need go to TC Home page (Currently just collapse the menu)

**Comment by luizrrodrigues** [comment] 2019-06-15 04:12
@ya3ya6 any status on this?
Please sent a PR/Update in next 12h or this one will be open for pickup.

**Comment by ya3ya6** [comment] 2019-06-15 07:37
@luizrrodrigues Sorry for delay. Still working on it.
I will post a PR or Complete update in next 12 hours. Thanks.

**Comment by luizrrodrigues** [comment] 2019-06-15 21:46
@ya3ya6 Checking staus.

**Comment by ya3ya6** [comment] 2019-06-16 03:57
Hi, Pull requests are in:
https://github.com/topcoder-platform/community-app/pull/2629
https://github.com/topcoder-platform/navigation-component/pull/20

**Comment by ya3ya6** [comment] 2019-06-16 03:58
@luizrrodrigues Hi, Sorry for delay. Pull requests are in:
https://github.com/topcoder-platform/community-app/pull/2629
https://github.com/topcoder-platform/navigation-component/pull/20

**Comment by Oanh-and-only-Oanh** [comment] 2019-06-17 15:11
@luizrrodrigues, sorry for delay in responding.

 item 3: Please confirm if we need Payments in the dropdown menu and Work secondary menu. 
**We do want a Work secondary menu. Dashboard (default tab), My Profile, and Payments will be in secondary menu under Work. Dropdown menu will have Settings and Logout**

**Comment by luizrrodrigues** [comment] 2019-06-19 00:59
@ya3ya6 Looks good, some requests:

- Please remove **Payments** from dropdown menu
- Remove **All projects** from dropdown menu

**Comment by ya3ya6** [comment] 2019-06-19 05:01
@luizrrodrigues Thanks for review. i'll add requirements and fix the tests. And a question: Should i change the name of this level 2 menu from "Profile" to "Dashboard"?

**Comment by luizrrodrigues** [comment] 2019-06-19 11:06
Level 2 need be:
- Dashboard
- My Profile
- Payments

**Comment by ya3ya6** [comment] 2019-06-19 11:27
@LieutenantRoger Thanks. but i meant the name of level2 itself. i changed it to "Dashboard", you can see it on updated pull request : https://github.com/topcoder-platform/community-app/pull/2629

**Comment by luizrrodrigues** [comment] 2019-06-19 11:29
I give feedback in #2629

**Comment by luizrrodrigues** [comment] 2019-06-19 12:18
@Oanh-and-only-Oanh Please let me know if new secondary menu placement looks right:

![](https://user-images.githubusercontent.com/17860215/59761401-f8095400-92a9-11e9-9f2d-b4243f6bfdec.png)

**Comment by ya3ya6** [comment] 2019-06-19 13:15
@Oanh-and-only-Oanh 
To complete the comment of @luizrrodrigues , let me explain the bahaviour :
When user clicks on "work" , Dashboard (first sub menu) will be selected. and the selected item will be "Dashboard". So work is not selectable, work button usage is expanding the work menu when user is not logged in, and also selecting the dashboard. here is a video of behaviour (in this video the name of it submenu is Profile, instead of Dashboard (it's prev version)):
[Video_19-06-19_17-29-58.zip](https://github.com/topcoder-platform/community-app/files/3306200/Video_19-06-19_17-29-58.zip)

**Comment by Oanh-and-only-Oanh** [comment] 2019-06-19 14:11
@luizrrodrigues, DASHBOARD should not be in top level nav. It's is only in secondary nav level under WORK. It should be the default page when logged-in members click WORK.

**Comment by luizrrodrigues** [comment] 2019-06-19 14:15
@Oanh-and-only-Oanh Thanks.

@ya3ya6 Need follow structure shared here:
https://github.com/topcoder-platform/community-app/pull/2629#issuecomment-503520012

**Comment by vic-tian** [comment] 2019-06-19 14:22
This is not according to the design. Let's fix the intended behavior of the navigation:
- When a member is logged into the system, the WORK (Should be named COMMUNITY - @Oanh-and-only-Oanh please confirm) item is selected and the new secondary menu is displayed.
<img width="1283" alt="Screen Shot 2019-06-19 at 7 13 48 AM" src="https://user-images.githubusercontent.com/8484061/59773302-3d099800-9262-11e9-8860-e08ce579b459.png">

- When a member is not logged into the system (anonymous, public viewer), the WORK (COMMUNITY) navigation item should load the public page. This behavior is very similar to what GitHub experience is.
<img width="1280" alt="Screen Shot 2019-06-19 at 7 19 44 AM" src="https://user-images.githubusercontent.com/8484061/59773572-ab4e5a80-9262-11e9-9d39-675cb62bd458.png">

**Comment by luizrrodrigues** [comment] 2019-06-19 14:40
@vic-tian Change to Community will be fixed here: https://github.com/topcoder-platform/community-app/issues/2640

**Comment by ya3ya6** [comment] 2019-06-19 14:40
@luizrrodrigues Thanks.

Sorry for missunderstanding and causing delay.

1. (+ @vic-tian) what about mobile? can you share a picture about how mobile should behave? cause there is no space under work for mobile.

2. is any force to reuse level 3 menu , or it can be separate? i mean, this secondary menu should be similar to other third level menus, but its parent is not a level 2 menu, and it's probably not reusable.

3. When user clicks the Work button, It should expand the menu If user is not logged in, and if it's expanded already, it should select this secondary menu?

And finally, It's completely another approach and i should start from zero, plus it's not easy. it takes about 2/3 days, is it ok? if not, please reassign me from this, because i don't want to cause daley to this anymore. (and sorry again for this)

**Comment by luizrrodrigues** [comment] 2019-06-19 15:00
3. If not logged user, when click in Work will expand and load Community Home page.

**Comment by vic-tian** [comment] 2019-06-19 16:05
Mobile interaction is focused on presenting the option of the main page/section of Community or Business as "Home Page", the secondary menu is displayed on the top of the page as drop-down. Check https://marvelapp.com/1dgiejg6/screen/54473672 or https://marvelapp.com/89423f8/screen/54595272
<img width="519" alt="image" src="https://user-images.githubusercontent.com/8484061/59781706-35052480-9271-11e9-97bd-9c0f3e351eff.png">
<img width="523" alt="Screen Shot 2019-06-19 at 9 04 21 AM" src="https://user-images.githubusercontent.com/8484061/59781730-42baaa00-9271-11e9-8178-05112ac5912f.png">

**Comment by luizrrodrigues** [comment] 2019-06-19 21:09
@ya3ya6 you think will able to complete this until tomorrow? I see you progress effort and progress here, we need done ASAP to smoke test on Friday.

Please let me know.

Thanks.

**Comment by ya3ya6** [comment] 2019-06-19 21:37
@luizrrodrigues Thanks. I think i can do it in about 18 hours from now, is it ok?

**Comment by luizrrodrigues** [comment] 2019-06-19 21:55
@ya3ya6 Yes, keep me updated and feel free to send PR to pre check.

**Comment by ya3ya6** [comment] 2019-06-19 22:02
@luizrrodrigues ok, i will. thanks.

**Comment by ya3ya6** [comment] 2019-06-20 17:21
@luizrrodrigues Hi. The code is ready But there is some conflicts on Commits, so please let me fix pull request conflicts and i'll let you know where pull request is ready.

**Comment by ya3ya6** [comment] 2019-06-20 19:26
@luizrrodrigues 
Sorry for delay.
These are new pull requests , please review them :
https://github.com/topcoder-platform/navigation-component/pull/28
https://github.com/topcoder-platform/community-app/pull/2649
(Previous pull requests are invalid, i deleted the privious repository and created a new one. please remove them)

**Comment by luizrrodrigues** [comment] 2019-06-21 01:02
@ya3ya6 I found an issue in Mobile, looks like Desktop secondary menu showing.

![image](https://user-images.githubusercontent.com/7029641/59890330-c4602400-93a6-11e9-8c59-6b5107d5d408.png)

**Comment by ya3ya6** [comment] 2019-06-21 03:08
@sushilshinde sorry , i didn't noticed that. fixed and pr updated: https://github.com/topcoder-platform/navigation-component/pull/28

**Closed** 2019-06-21 13:11 UTC
Labels: Navigation, P2, nav_Assigned, nav_FixAccepted, nav_Paid
