### ISSUE TITLE
[$10][MSFT-198] [Challenge feed][Firefox] The link Topcoder icon contain has no text

### ISSUE THREAD

**Issue by veshu** [topcoder-platform/community-app#2863] opened 2019-07-17 07:08 UTC
**Steps to Reproduce**
1) Go to the web accessibility evaluation tool page http://wave.webaim.org
2)  Type 'https://www.topcoder.com/challenges' in textbox to check.
3)  Observe the Header Topcoder icon link has no text.

**Expected Result**
Topcoder icon link must be provide text within the link that describe the functionality or target of the link

**Actual Result**
Header TopCoder icon link contain no text.

**Device**: Desktop/Labtop
**Operating System**: Windows
**Browser**: Firefox

**WCAG Category**: 1. Perceivable
**WCAG Level**: A
**WCAG Success Criterion**: 1.1.1 Non-Text Content
**Screen Reader Used**: Other
**Accessibility Audit Tool used**: Web Accessibility Toolbar (WAT)

**Attachment**
https://topcodermsft-my.sharepoint.com/personal/pd-topcoder_topcodermsft_onmicrosoft_com/Documents/Forms/All.aspx?cid=8ab28edc%2Dd11f%2D4bb3%2Db9cf%2Da743b86a634f&FolderCTID=0x0120005C598A51049FC14CBA882E1AEE168F51&id=%2Fpersonal%2Fpd%2Dtopcoder%5Ftopcodermsft%5Fonmicrosoft%5Fcom%2FDocuments%2FMSFT%2DTeams%2DQA%2FJune%202019%2F29%20Jun%2FTest%20Results%2FBug%20Videos%20%26%20Log%20Files%2Fkmurti%2FAccessibility%2F6

**Comment by ThomasKranitsas** [comment] 2019-07-18 10:01
Contest https://www.topcoder.com/challenges/30096030 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-07-18 10:01
Contest https://www.topcoder.com/challenges/30096030 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by romitgit** [comment] 2019-07-18 16:02
Please assign this to me.

**Comment by codeMinter** [comment] 2019-07-23 08:05
@veshu this is also duplicate of #2740, closing related PR

**Comment by cwdcwd** [comment] 2019-07-25 00:41
Contest https://www.topcoder.com/challenges/30097117 has been created for this ticket.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by cwdcwd** [comment] 2019-07-25 00:41
Contest https://www.topcoder.com/challenges/30097117 has been updated - it has been assigned to Timor.<br/><br/>```This is an automated message for lazybaer via Topcoder X```

**Comment by crazyk07** [comment] 2019-07-31 06:25
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30097117<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed** 2019-07-31 06:25 UTC
Labels: Accessibility, Challenge Listing, Dependency, Prod QA Pass, tcx_FixAccepted
