### ISSUE TITLE
[$35]My Challenges bucket not showing up | For the branch mm-develop-merge

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1756] opened 2018-11-15 03:53 UTC
My Challenges bucket isn't displayed - all the challenges which I'm registered for should be under this bucket

<img width="3600" alt="topcoder challenges 2018-11-15 09-24-08" src="https://user-images.githubusercontent.com/683231/48529305-733ffd00-e8b8-11e8-951d-8e72e888bd9c.png">

Compare results with topcoder.com/challenges(v3 API) for reference.

Run in production mode(v4 API), there is data model difference in v3 and v4 API.

Instruction to run an app in production mode

```
rm -rf node_modules
npm i
npm run build
npm start
```

Check **Deployment and Execution** section in the doc for details 
https://github.com/topcoder-platform/community-app/blob/develop/README.md

Create PR for changes, I'll reopen for pickup if the PR not submitted within 8 hours

**Repos :** 

https://github.com/topcoder-platform/community-app/tree/mm-develop-merge
https://github.com/topcoder-platform/topcoder-react-lib#new-develop-mm

**Comment by ThomasKranitsas** [comment] 2018-11-15 03:53
Contest https://www.topcoder.com/challenges/30074453 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by gurmeetb** [comment] 2018-11-15 03:56
@sushilshinde let me give one try again today, as got 2-3 hrs...

**Comment by ThomasKranitsas** [comment] 2018-11-15 03:56
Contest https://www.topcoder.com/challenges/30074453 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by gurmeetb** [comment] 2018-11-15 03:56
@sushilshinde but I don't see OPEN-FOR-PICKUP, can I still assign myself ?

**Comment by sushilshinde** [comment] 2018-11-15 03:57
@gurmeetb try now

**Comment by ThomasKranitsas** [comment] 2018-11-15 03:57
Contest https://www.topcoder.com/challenges/30074453 has been updated - it has been assigned to gurmeetb.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2018-11-15 03:57
@gurmeetb accidentally deleted your comment sorry about that

**Comment by gurmeetb** [comment] 2018-11-15 06:07
@sushilshinde no worries. I need to head out right now. If you feel this is urgent, please feel free to open it else I will address it in few hrs...

**Comment by sushilshinde** [comment] 2018-11-15 10:02
@topcoder-platform/topcodercompetitors this one is open for pickup

**Comment by ThomasKranitsas** [comment] 2018-11-15 12:58
Contest https://www.topcoder.com/challenges/30074453 has been updated - it has been assigned to diazz.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by suppermancool** [comment] 2018-11-15 14:32
@sushilshinde the api v4 always return list of my challenges empty
https://api.topcoder.com/v4/members/diazz/challenges/?filter=status%3DACTIVE&limit=50&offset=0
but api v3 return correct list of my challenges
https://api.topcoder.com/v3/members/diazz/challenges/?filter=status%3DACTIVE&limit=50&offset=0

this is server issue, can you check with server guy?

**Comment by sushilshinde** [comment] 2018-11-15 17:01
@skyhit can help please

**Comment by skyhit** [comment] 2018-11-16 00:50
@sushilshinde @suppermancool the problem is fixed

**Comment by sushilshinde** [comment] 2018-11-16 02:53
Thanks @skyhit

**Comment by suppermancool** [comment] 2018-11-16 03:38
thanks @skyhit . @sushilshinde the my challenges work now, pls check again

**Comment by sushilshinde** [comment] 2018-11-16 03:41
Will check @suppermancool 

Can you also have a look at https://github.com/topcoder-platform/community-app/issues/1757

**Comment by suppermancool** [comment] 2018-11-16 03:44
@sushilshinde checking , thanks

**Comment by sushilshinde** [comment] 2018-11-16 03:46
@suppermancool where is PR for this?

**Comment by sushilshinde** [comment] 2018-11-16 05:36
@suppermancool what you did here :)

Yeah working :)

**Comment by suppermancool** [comment] 2018-11-16 05:38
@sushilshinde i just investigated the bug, it is take time for debuging, expecially in production mode

**Comment by ThomasKranitsas** [comment] 2018-11-16 05:40
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30074453<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed** 2018-11-16 05:39 UTC
Labels: Challenge Listing, tcx_Assigned, tcx_FixAccepted
