### ISSUE TITLE
Collapse icon is not displayed when User-Menu is in Open state

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2436] opened 2019-06-07 18:04 UTC
**Pre-Requisite**

**Steps to Reproduce**

1. Navigate to "https://test-community-app.topcoder-dev.com/challenges"
2. Login to Topcoder
3. Click on User Name handle

**Actual behavior**
Collapse icon is not displayed when User-Menu is in Open state

**Expected behavior**
Collapse icon should be displayed when User-Menu is in Open state

**Screen shots/video**
![image](https://user-images.githubusercontent.com/6736067/59124276-e86e3f00-897c-11e9-877d-58d01185b226.png)

**Environment :**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 75.0.3770.80 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by nithyaasworld** [comment] 2019-06-09 20:08
![image](https://user-images.githubusercontent.com/5114190/59163580-7d5d6d80-8b20-11e9-8424-dee0815543a2.png)

**Comment by luizrrodrigues** [comment] 2020-01-15 16:59
@rashmi73 Any status in this one?

**Comment by LieutenantRoger** [comment] 2020-01-16 04:56
Not able to reproduce, please double check

**Comment by luizrrodrigues** [comment] 2020-01-17 22:06
@LieutenantRoger Thanks for check. Looks like already fixed in another issue.

**Closed** 2020-04-21 03:56 UTC
Labels: Navigation, P4, QA Pass, Test Env, UI
