### ISSUE TITLE
Challenges tab broken for all tracks

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#4949] opened 2020-09-17 17:54 UTC
**Current Behavior:**

Challenges tab is broken for all tracks.
1. Go to https://www.topcoder.com/members/ShindouHikaru/details/?track=DEVELOP&subTrack=FIRST_2_FINISH&tab=challenges
2. See message that there are no successful challenges found. 
![image](https://user-images.githubusercontent.com/47536078/93509212-46096f00-f8d4-11ea-84fe-25cae06462be.png)

**Expected Behavior:**
Clicking on the Challenge Tab should show list of past challenges the member participated in

**Comment by Oanh-and-only-Oanh** [comment] 2020-09-17 17:58
NOTE: MM past challenges is out of scope as that is a separate issue tracked here https://github.com/topcoder-platform/community-app/issues/4926 and https://github.com/topcoder-platform/community-app/issues/4112

**Comment by crazyk07** [comment] 2020-09-17 17:58
Contest https://www.topcoder.com/challenges/30142354 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-09-17 18:00
Contest https://www.topcoder.com/challenges/30142354 has been updated - it has been assigned to rashmi73.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by Oanh-and-only-Oanh** [comment] 2020-09-17 22:12
Submit in 8 hours and PR to:

https://github.com/topcoder-platform/community-app/tree/milestone-20200924
https://github.com/topcoder-platform/topcoder-react-lib/tree/milestone-20200924

run npm run test before PR

**Comment by luizrrodrigues** [comment] 2020-09-18 15:52
@Oanh-and-only-Oanh This one is duplication of #4527

**Closed** 2020-09-18 15:55 UTC
Labels: Member Profiles, P2, tcx_Assigned

**Comment by luizrrodrigues** [comment] 2020-09-18 15:57
Duplicate of #4527
