### ISSUE TITLE
TopCoder Logo isn't in the middle of the screen as shown in the designs

### ISSUE THREAD

**Issue by DonPablito** [topcoder-platform/community-app#2462] opened 2019-06-07 18:42 UTC
**Description**
On top of the Page the Topcoder Logo should be in the middle of the screen but it's left shifted

**To Reproduce**
1. Go to https://test-community-app.topcoder-dev.com/challenges and Login
2. Now on top navigation bar the topcoder logo is left shifted. 

**Expected behavior**
The Topcoder logo should be in the middle of the screen

**Screenshots**

![Screenshot_20190608-000344__01](https://user-images.githubusercontent.com/29794211/59126122-ea86cc80-8981-11e9-9db5-d4aba248d205.jpg)

**Smartphone (please complete the following information):**
 - Device: One Plus 6T
 - OS: Android 9.0.0
 - Browser Chrome
 - Version 74.0.3729.157

**Comment by nithyaasworld** [comment] 2019-06-09 19:27
Duplicate of https://github.com/topcoder-platform/community-app/issues/2398

**Closed by nithyaasworld** 2019-06-09 19:27 UTC
Labels: Bug Hunt, P3, UI
