### ISSUE TITLE
[$20] - Stalled challenges displayed in 'Open for registration' section

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#284] opened 2017-08-25 07:39 UTC
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- In the 'Open for registration' section > Sort by: Time to Register

- Check the Stalled challenges

Actual Result(s)
-----------------------------------------------------------------
- Stalled challenges displayed in 'Open for registration' section

Expected Result(s)
-----------------------------------------------------------------
- Must omit the Stalled challenges from the Open for registration

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment] 2017-08-25 07:40
![53](https://user-images.githubusercontent.com/4592712/29704270-b713ef28-8996-11e7-91bb-a3c4e0b97095.jpg)

**Comment by birdofpreyru** [comment] 2017-08-25 13:39
Accepted, 3 points.

**Comment by elfman** [comment] 2017-08-26 04:01
The bug is caused by the data from backend, it contains some mistake, the registration time has passed, but the status of registration phase is still open.
The filter used phase state to judge if the registration is open, now I change it to use registration time. But I still think the backend should fix this.

**Comment by birdofpreyru** [comment] 2017-09-01 13:00
@elfman This fixes the issue for MMs, but not for F2F. I have feeling that I've already saw a fix for F2F case somewhere during this Bug Bash, but I am really a bit lost now, so I don't remember, was it already merged-in and broken again, or is it still pending the merge. Anyway, I don't accept this at least until I find the fix for F2F.

**Closed** 2017-09-04 17:18 UTC
Labels: Bug Bash - ACCEPTED, Bug Hunt - PAID
