### ISSUE TITLE
Show 'No Past Challenges found' when the request time exceeds the configured time.

### ISSUE THREAD

**Issue by LieutenantRoger** [topcoder-platform/community-app#3609] opened 2020-01-24 04:33 UTC
**Describe the bug**

"when the user searches for a keyword that is not present in the past challenges, the search results (Message "No Past Challenges found") must be displayed at a reasonable amount of time(let's make a configured reasonable time for now so we can tweak and change later). At present the search keeps going on for more than a few minutes.

Please see video
https://drive.google.com/open?id=1jwq43QZpOgPzeR1lv-1b0oi_ErqeBOax

**Comment by Oanh-and-only-Oanh** [comment] 2020-01-24 04:46
duplicate of 3610

**Closed** 2020-01-24 04:46 UTC
Labels: Challenge Listing, P4
