### ISSUE TITLE
Duplicate Work menus displayed

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2533] opened 2019-06-07 23:16 UTC
![image](https://user-images.githubusercontent.com/42398485/59138041-5fd9a980-8950-11e9-9e91-6b4b5c853240.png)

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Landscape)
3. Tap Menu > Work (All the sub-menus are listed horizontally)
4. Go to Portrait view
5. Tap Menu > Work
6. Go to Landscape view

**Actual:** Duplicate Work menus displayed

**Expected:** Should display only the horizontal menu in landscape view

**Reproducibility Rate:** 3/3

**Environment:** iPad Air 2, iOS 12.2

**Browser:** Safari 12

**Comment by nithyaasworld** [comment] 2019-06-10 10:44
Duplicate of https://github.com/topcoder-platform/community-app/issues/2498

**Closed by nithyaasworld** 2019-06-10 10:44 UTC
Labels: Bug Hunt, Functional, Navigation, P2
