### ISSUE TITLE
Profile Settings Only Display if The Page Is Refreshed

### ISSUE THREAD

**Issue by VanitaW** [topcoder-platform/community-app#2529] opened 2019-06-07 22:33 UTC
**Describe the bug**
Profile settings will not display until the browser will refresh

**To Reproduce**
1.  Steps to reproduce the behavior:
2.  Open safari browser on iOS mobile device.
3.  Go to https://test-community-app.topcoder-dev.com/challenges .
4.  Click on 'Login'
5.  Sign in using username: dan_developer password: dantopcoder123 . If you are redirected to to the Topcoder live site, go to https://test-community-app.topcoder-dev.com/challenges
6.  Click on the profile picture in the upper right hand corner.
7.  Click on 'Settings'.
8.  Observe that the settings do not display.
9.  Refresh the browser
10. Observe that the profile settings display.

**Expected behavior**
The profile file information  to display when 'Settings' is clicked.

**Actual behavior**
Nothing happened when 'Settings' is clicked.  

**Screenshots**

![BeforeBrowserRefresh](https://user-images.githubusercontent.com/12702517/59136788-4df50800-894a-11e9-947b-24f9d2177467.png)

![AfterBrowserRefresh](https://user-images.githubusercontent.com/12702517/59136791-52212580-894a-11e9-8874-77c09cbeee8a.png)

**Smartphone:**
 - Device: iPhone SE
 - OS: 12.2
 - Browser: Safari
 - Version: 12

**Additional context**

**Comment by nithyaasworld** [comment] 2019-06-09 18:30
Duplicate of https://github.com/topcoder-platform/community-app/issues/2402

Please always check for duplicates before logging a new defect!

**Closed by nithyaasworld** 2019-06-09 18:30 UTC
Labels: Bug Hunt, Functional, Major, Navigation
