### ISSUE TITLE
Zip file upload shown for Topgear submission instead of URL field

### ISSUE THREAD

**Issue by aah-74** [topcoder-platform/community-app#1840] opened 2018-12-20 10:57 UTC
**Describe the bug**
For Topgear challenges, the registrant has to submit the URL of the code. Zip file submissions are not allowed.  However for the particular challenge in specific group; challenges are asking submitter to upload code. 

**To Reproduce**
login into Topgear.topcoder.com
submit for a challenge. 
the screen asks for drop the zip file in stead of edit box to upload URL

**Expected behavior**
URL field should Appear

**Screenshots**
![err](https://user-images.githubusercontent.com/40483249/50280971-106ff180-0474-11e9-8c38-f58b3104341b.png)

**Desktop (please complete the following information):**
chrome

**Smartphone (please complete the following information):**
 -

**Comment by ThomasKranitsas** [comment] 2018-12-21 17:18
Where are the group Ids for topgear configured?

Is that `src/server/tc-communities/wipro/metadata.json`?

If yes, then you may need to update the configs.
For example, this https://topgear.topcoder.com/challenges/30076324?tab=details has groupId: 20000041 which does not exist in the above file.

**Comment by ajefts** [comment] 2018-12-21 17:37
This issue is resolved by cleaning up the groups.  The issue is that some of the groups where not set as a sub group of the wipro all group.  No code/app changes are needed.

**Closed** 2019-01-07 09:53 UTC
