### ISSUE TITLE
Common Issue > Currently selected items on the menu reload the page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2421] opened 2019-06-07 17:49 UTC
![image](https://user-images.githubusercontent.com/42398485/59123327-9698cb00-8922-11e9-964d-e16b98f393ab.png)
![image](https://user-images.githubusercontent.com/42398485/59123340-9c8eac00-8922-11e9-8712-b6f2c3539e00.png)

1. Open the application and login using valid credentials
2. Click Menu > Work > Tracks
3. Default Competitive programming is selected
4. Click Competitive programming

**Actual:** Currently selected items on the menu reload the page

**Expected:** Currently selected item should not reload the page (inactive link)

**Reproducibility Rate:** 3/3

**Environment:** HP Pavilion x360 14 inch; Windows 10

**Browser:** Chrome 75.0.3770.80 (Official Build) (64-bit)

**Comment by luizrrodrigues** [comment] 2019-06-09 19:21
Duplicate of #2403

**Comment by nithyaasworld** [comment] 2019-06-09 19:22
Thanks @luizrrodrigues

**Closed** 2019-06-09 19:22 UTC
Labels: Bug Hunt, Functional, Navigation, P2, nav_BugAccepted
