### ISSUE TITLE
Delete Button on Linked Accounts isn’t clickable- PD - Member - Migration- BLOCKER

### ISSUE THREAD

**Issue by psharneja** [topcoder-platform/community-app#1018] opened 2018-06-10 18:40 UTC
@ThomasKranitsas   
Delete / Recycle Button on Linked Accounts isn’t clickable
![screenshot from 2018-06-10 20-13-10](https://user-images.githubusercontent.com/18382400/41205161-c085992c-6d0b-11e8-8ef5-310b798c1fd1.png)

**Comment by ThomasKranitsas** [comment] 2018-06-14 10:12
duplicate of https://github.com/topcoder-platform/community-app/issues/941

**Closed by ThomasKranitsas** 2018-06-14 10:12 UTC
Labels: Blocker, PD - Member - Migration
