### ISSUE TITLE
[$75] - Submissions Management Page

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/community-app#577] opened 2017-11-09 11:29 UTC
1. When more submissions are uploaded on the latest submission should be on top always

2.  For design, the preview image is other than the one selected by us and is also distorted.

**Comment by birdofpreyru** [comment] 2017-11-10 09:25
@Dara-K for (2), can you help to reproduce the problem in dev environment? I.e.:
- Login as `dan_developer` / `dantopcoder123` at accounts.topcoder-dev.com/member
- Submit to https://www.topcoder-dev.com/challenges/30050696/?type=design something that the preview at submission management page will be different from the intended one
- Ping me with the details.

**Comment by Dara-K** [comment] 2017-11-10 13:16
@birdofpreyru I tried that with 2 submissions, but none of them appear after the upload..

**Comment by birdofpreyru** [comment] 2017-11-10 17:46
@Dara-K that's strange, will you send me the files you tried to upload, and the address of the challenge, so I can check what's up?

**Comment by Dara-K** [comment] 2017-11-10 19:43
@birdofpreyru The address of the challenge is this https://www.topcoder-dev.com/challenges/30050696/?type=design as you said so

Here are the files: https://www.dropbox.com/s/12vyg12stmjsnbp/LUX28%20Files.zip?dl=0 

I tried again now, still doesn't work.

**Comment by zjuasmn** [comment] 2017-11-28 20:44
After submission, the post request to `https://api.topcoder-dev.com/v3/submissions/` returns 

```
{"id":"-26aabce0:15cf5da6e7d:-7e05","result":{"success":true,"status":400,"metadata":null,"content":"User not registered for submission"},"version":"v3"}
```

It seems to be a backend API  issue.

**Comment by ThomasKranitsas** [comment] 2019-03-21 08:04
Contest https://www.topcoder.com/challenges/30086841 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-06-03 10:55
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed by ThomasKranitsas** 2019-06-03 10:55 UTC
