### ISSUE TITLE
Zurich filter not getting applied periodically

### ISSUE THREAD

**Issue by mtwomey** [topcoder-platform/community-app#3331] opened 2019-09-25 15:24 UTC
See video here:

https://youtu.be/f75qP2ihAzE

**Comment by sushilshinde** [comment] 2019-09-26 04:52
@skyhit metadata for the private community is wrong, a filter needs to consider the context/subcommunity filter.

**Comment by sushilshinde** [comment] 2019-09-26 08:25
**Steps to reproduce:** 
0. Login with `dan_developer / dantopcoder123` on https://community-app.topcoder-dev.com/
1. Go https://community-app.topcoder-dev.com/__community__/zurich
2. `Challenges` link in the top menu
3. Wait for challenges to load
4. Metadata on the right-hand side is wrong, sometimes it gets
![Zurich Community Challenges 2019-09-26 13-49-23](https://user-images.githubusercontent.com/683231/65671404-cc45f900-e064-11e9-9ccd-a9715861fdee.png)
 refreshed but it is inconsistent


**Fix required**
Add group Id to the every listing call in the private community context

Endpoint - https://api.topcoder-dev.com/v4/challenges

Filter -  https://github.com/appirio-tech/ap-challenge-microservice/blob/42934543c34be05a7f8746462efe44e051e6ad73/swagger.yaml#L100

**Comment by sushilshinde** [comment] 2019-09-26 08:33
@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup

**Comment by crazyk07** [comment] 2019-09-26 08:37
[500]: Challenge for the updated issue 3331 is creating, rescheduling this event<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2019-09-26 08:37
[500]: Challenge for the updated issue 3331 is creating, rescheduling this event<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2019-09-26 08:37
[500]: Challenge for the updated issue 3331 is creating, rescheduling this event<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2019-09-26 08:39
Contest https://www.topcoder.com/challenges/30103372 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2019-09-26 08:41
Contest https://www.topcoder.com/challenges/30103372 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2019-09-26 08:48
Contest https://www.topcoder.com/challenges/30103372 has been updated - it has been assigned to anonymousjaggu.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by anonymousjaggu** [comment] 2019-09-27 11:34
The issue is There  are few requests for getting the data without the group id but those request should not be made

**Comment by sushilshinde** [comment] 2019-09-27 11:36
**Requirement** 
https://github.com/topcoder-platform/community-app/issues/3331#issuecomment-535397435

@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup

**Comment by crazyk07** [comment] 2019-09-27 11:55
Contest https://www.topcoder.com/challenges/30103372 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2019-09-27 11:58
Contest https://www.topcoder.com/challenges/30103372 has been updated - it has been assigned to rashmi73.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by sushilshinde** [comment] 2019-09-27 12:00
@rashmi73 As this is P0, please submit in 12 hours

**Comment by rashmi73** [comment] 2019-09-27 21:35
@sushilshinde I got idea what needs to be done exactly, need to pass groupids in call when page loaded is from zurich url

but unable to access https://github.com/appirio-tech/ap-challenge-microservice/blob/42934543c34be05a7f8746462efe44e051e6ad73/swagger.yaml#L100

can you please provide me access to it? so I raise PR by making changes in api call based on what is passed in props.

**Comment by sushilshinde** [comment] 2019-09-28 09:04
@rashmi73 please check attachment 

[swagger.txt](https://github.com/topcoder-platform/community-app/files/3665254/swagger.txt)

**Comment by sushilshinde** [comment] 2019-09-29 05:18
@rashmi73 are you working on this or I will re-open it for pickup. 

Please communicate when pick-up the P0 ticket.

**Comment by sushilshinde** [comment] 2019-09-29 07:19
@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup

**Comment by crazyk07** [comment] 2019-09-29 08:03
Contest https://www.topcoder.com/challenges/30103372 has been updated - it has been assigned to rashmi73.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by rashmi73** [comment] 2019-09-29 08:04
@sushilshinde sorry for delay. I will finish it. PR in sometime

**Comment by sushilshinde** [comment] 2019-09-30 05:32
**Requirement**

https://github.com/topcoder-platform/community-app/issues/3331#issuecomment-535397435

@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup

**Comment by crazyk07** [comment] 2019-09-30 05:46
Contest https://www.topcoder.com/challenges/30103372 has been updated - it has been assigned to PkDurlabhji.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by sushilshinde** [comment] 2019-09-30 08:42
@PrakashDurlabhji it's P0 please submit in 4 hours

**Comment by crazyk07** [comment] 2019-09-30 13:22
Contest https://www.topcoder.com/challenges/30103372 has been updated - it has been assigned to rohitgupta_.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by PrakashDurlabhji** [comment] 2019-09-30 13:28
@sushilshinde apology for delay

**Comment by PrakashDurlabhji** [comment] 2019-09-30 13:38
@sushilshinde shall I raise PR now?

**Comment by PrakashDurlabhji** [comment] 2019-09-30 13:47
@rohitgupta if you havent started working yet?

**Comment by mtwomey** [comment] 2019-09-30 17:09
@PrakashDurlabhji If you have solved it, please submit the PR and we'll award you the prize.

**Comment by mtwomey** [comment] 2019-09-30 17:09
@r0hit-gupta Please advise if you've also started working it (if so, we'll work something out).

**Comment by codeMinter** [comment] 2019-10-01 05:23
Challenge launched here for the same 
https://www.topcoder.com/challenges/30103753

**Comment by codeMinter** [comment] 2019-10-02 01:19
@nithyaasworld this is on DEV, can you please validate and confirm? Thanks

**Comment by nithyaasworld** [comment] 2019-10-03 04:57
@codeMinter I am looking at this. So far its good. I will check further and confirm shortly.

**Comment by nithyaasworld** [comment] 2019-10-03 05:27
@codejamtc The fix looks good to me

**Comment by nithyaasworld** [comment] 2019-10-03 05:27
@codeMinter

**Comment by lakshmiathreya** [comment] 2019-10-03 05:38
@nithyaasworld pls elaborate on your verification ... include screenshots ...

**Comment by nithyaasworld** [comment] 2019-10-03 06:16
1. Navigated to https://community-app.topcoder-dev.com/__community__/zurich being logged in as dan_developer
2. Clicked on Challenges link. It navigated to the URL https://community-app.topcoder-dev.com/__community__/zurich/challenges?communityId=zurich
3. removed the ?communityId=zurich from the end of the above url and pressed enter. It again navigated back to the URL https://community-app.topcoder-dev.com/__community__/zurich/challenges?communityId=zurich

When the URL is with ?communityId=zurich, it displays only the Zurich challenges

![image](https://user-images.githubusercontent.com/5114190/66103297-efc3f300-e5d2-11e9-82f3-cbca7d1effc5.png)


It always navigates to ?communityId=zurich, when I access https://community-app.topcoder-dev.com/__community__/zurich/challenges

Also tested on Beta Environment

However, it still lists Topcoder challenges in the 'Open for Review' filter. A new issue will be raised to address this.

![image](https://user-images.githubusercontent.com/5114190/66103426-5ea14c00-e5d3-11e9-8071-5c77244fa7e1.png)

**Comment by lakshmiathreya** [comment] 2019-10-03 13:32
@Nithya for the Zurich filter issue - could you reference the new Issue here - for the 'Open for Review' showing other Challenges?

**Comment by lakshmiathreya** [comment] 2019-10-03 13:42
New Issue opened for the 'Open for Review' showing other Challenges issue - 3362.

**Comment by lakshmiathreya** [comment] 2019-10-04 04:44
Verified that the Zurich filter is applied correctly.

**Closed by lakshmiathreya** 2019-10-04 04:44 UTC
Labels: Challenge Listing, F2F, P0, Prod QA Pass, Zurich, hot-fix
