### ISSUE TITLE
Clicking on "All projects", Not navigating to All projects page

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2424] opened 2019-06-07 17:52 UTC
**Pre-Requisite**

**Steps to Reproduce**

1. Navigate to "https://test-community-app.topcoder-dev.com/"
2. Login to Topcoder
3. Click on User Name handle -->then Click on "All projects"

**Actual behavior**
Not navigating to All projects page

**Expected behavior**
User should be navigate to All projects page

**Screen shots/video**
https://i.imgur.com/VsLC6sn.png
![image](https://user-images.githubusercontent.com/6736067/59123842-da6bee80-897b-11e9-88f1-66da9f4e42fa.png)

**Environment :**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 75.0.3770.80 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

**Comment by nithyaasworld** [comment] 2019-06-09 19:09
Duplicate of https://github.com/topcoder-platform/community-app/issues/2395

**Closed by nithyaasworld** 2019-06-09 19:09 UTC
Labels: Bug Hunt, Functional, Navigation, P2
