### ISSUE TITLE
Profile menu is not matching with Marvelapp option

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2528] opened 2019-06-07 22:20 UTC
**Describe the bug**
Profile menu is not matching with Marvelapp option

**To Reproduce**
1. Open the test URL and log in
2. Click on user profile

**Expected behavior**
Menu options are not matching with MarvelApp.

**Screenshots**
![image](https://user-images.githubusercontent.com/51492004/59135094-fd979d80-897d-11e9-82fe-4a97f8421195.png)

**Smartphone:**
 - Device: Samsung Galaxy Tab A
 - OS: Android 8.1.0
 - Browser : Chrome 
 - Version : 74.0.3729.157

**Comment by nithyaasworld** [comment] 2019-06-10 10:37
duplicate of https://github.com/topcoder-platform/community-app/issues/2523

**Closed by nithyaasworld** 2019-06-10 10:37 UTC
Labels: Bug Hunt, Navigation, P2, UI
