### ISSUE TITLE
[$50] Clicking on Type tag in challenge details page must filter challenges by type in challenge listings page

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4734] opened 2020-08-11 04:36 UTC
1. Go to Challenge details page
example:
https://www.topcoder.com/challenges/21ba3d19-3f7a-4abc-8d28-7c932887f0f6
2. Click on type tag
<img width="1440" alt="Screenshot 2020-08-11 at 10 01 41 AM" src="https://user-images.githubusercontent.com/58783823/89857571-18852380-dbba-11ea-8385-6a32c510db11.png">
Actual: :Challenge listings page is displayed with all challenges
<img width="1440" alt="Screenshot 2020-08-11 at 10 03 13 AM" src="https://user-images.githubusercontent.com/58783823/89857630-3c486980-dbba-11ea-99ef-64ea6d766958.png">
Expected: Only challenges of type "first2finish" must be displayed.

**Comment by crazyk07** [comment] 2020-09-10 05:13
Contest https://www.topcoder.com/challenges/30141160 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by luizrrodrigues** [comment] 2020-09-10 05:13
@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup

Submit in 8 hours and PR to:

https://github.com/topcoder-platform/community-app/tree/milestone-20200924
https://github.com/topcoder-platform/topcoder-react-lib/tree/milestone-20200924

run `npm run test` before PR

**Comment by crazyk07** [comment] 2020-09-10 05:59
Contest https://www.topcoder.com/challenges/30141160 has been updated - it has been assigned to khushimehta03.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by khushimehta03** [comment] 2020-09-10 20:52
@luizrrodrigues unable to reproduce, already working

**Comment by luizrrodrigues** [comment] 2020-09-10 21:06
@khushimehta03 If you test with previous link (beta) please ignore this one, beta currently using v4 API.

Please test in Prod: https://www.topcoder.com/challenges/21ba3d19-3f7a-4abc-8d28-7c932887f0f6

**Comment by luizrrodrigues** [comment] 2020-09-11 22:26
@khushimehta03 Any progress in this one?

**Comment by crazyk07** [comment] 2020-09-12 00:55
Contest https://www.topcoder.com/challenges/30141160 has been updated - it has been assigned to rashmi73.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by rashmi73** [comment] 2020-09-12 10:34
@luizrrodrigues PR https://github.com/topcoder-platform/community-app/pull/4902

**Comment by sandhiyakavi** [comment] 2020-09-17 05:16
Verified .Working as expected.

[Filter_challenge_type.zip](https://github.com/topcoder-platform/community-app/files/5236491/Filter_challenge_type.zip)
[Filter_F2F_type.zip](https://github.com/topcoder-platform/community-app/files/5236492/Filter_F2F_type.zip)
[Filter_task_type.zip](https://github.com/topcoder-platform/community-app/files/5236493/Filter_task_type.zip)

**Comment by sandhiyakavi** [comment] 2020-09-17 08:51
Verified on staging.

[Filter_Challenge type.zip](https://github.com/topcoder-platform/community-app/files/5237673/Filter_Challenge.type.zip)
[Filter_F2F type.zip](https://github.com/topcoder-platform/community-app/files/5237674/Filter_F2F.type.zip)
[Filter_task type.zip](https://github.com/topcoder-platform/community-app/files/5237677/Filter_task.type.zip)

**Comment by SathyaJayabal** [comment] 2020-09-17 12:45
verified on prod
[type filter.mov.zip](https://github.com/topcoder-platform/community-app/files/5239127/type.filter.mov.zip)

**Comment by crazyk07** [comment] 2020-09-17 12:50
Payment failed: [500]: Failed to get billing detail for the project.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by SathyaJayabal** [comment] 2020-09-17 13:00
reopening for payment processing

**Comment by crazyk07** [comment] 2020-09-17 13:00
Payment failed: [500]: Failed to get billing detail for the project.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-09-17 15:54
Payment failed: [500]: Failed to get billing detail for the project.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-09-18 02:31
Payment failed: [500]: Failed to get billing detail for the project.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-09-18 04:20
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30141160<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed** 2020-09-18 04:19 UTC
Labels: tcx_FixAccepted, tcx_ReadyForReview
