### ISSUE TITLE
Challenges tab in user profile isn't working

### ISSUE THREAD

**Issue by abhinav-koppula** [topcoder-platform/community-app#5020] opened 2020-09-30 07:20 UTC
**Describe the bug**
Challenges tab of user profile is not working.
Sample link:
https://www.topcoder.com/members/mancoolgunda/details/?track=DEVELOP&subTrack=CODE&tab=challenges

**To Reproduce**
1. Go to any user profile
2. Click on 'Code' in Development Activity
3. Click on 'Challenges' tab
4. It shows 'Sorry, no successful challenges found.'

**Expected behavior**
It should show all the successful challenges with the prize (if applicable)

**Screenshots**
![image](https://user-images.githubusercontent.com/3524245/94654850-4e719900-031b-11eb-8c8f-0405daee2abf.png)

**Comment by Oanh-and-only-Oanh** [comment] 2020-09-30 15:31
duplicate of this ticket. https://github.com/topcoder-platform/community-app/issues/4527 please following progress of the bug fix there.

**Closed by Oanh-and-only-Oanh** 2020-09-30 15:31 UTC
