### ISSUE TITLE
[$60]Incorrect URL to My Dashboard in Forums Navigation

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/community-app#4166] opened 2020-04-02 22:53 UTC
To Replicate:
1. Go to the Topcoder Forums: https://apps.topcoder.com/forums/

2. Mouseover your handle in the top right and mouseover "Dashboard".  Notice the url has an extra slash after topcoder.com/

3.  This causes the link to reroute to an old version of the dashboard from two years ago.
<img width="1717" alt="Screen Shot 2020-04-02 at 3 50 03 PM" src="https://user-images.githubusercontent.com/1373998/78307148-1cad8000-74fa-11ea-9cee-11042ccec2e1.png">

**Comment by Oanh-and-only-Oanh** [comment] 2020-04-03 16:15
similar to this issue #3984, we need to update footer on Forums legacy app to the new URL https://www.topcoder.com/privacy-policy/

**Comment by crazyk07** [comment] 2020-04-15 23:43
Contest https://www.topcoder.com/challenges/30122352 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-04-16 17:03
Contest https://www.topcoder.com/challenges/30122352 has been updated - it has been assigned to Narekvar90.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by narekcat** [comment] 2020-04-16 18:02
Hi. Please give me Forums legacy app repository.

**Comment by narekcat** [comment] 2020-04-16 18:53
I searched in Topcoder Platform and found out this repository: https://github.com/topcoder-platform/tc-website-master, where the issue is located. Also there are many privacy policy old urls, I changed only in footer. Need I to change it in all fiels ? This is PR https://github.com/topcoder-platform/tc-website-master/pull/1.

**Comment by skyhit** [comment] 2020-04-17 05:39
@sushilshinde @Oanh-and-only-Oanh the code change looks fine, we should try to deploy and verify, how can I do?

**Comment by Oanh-and-only-Oanh** [comment] 2020-04-20 14:37
@skyhit, we need to put this one on hold and take off TCX since the issues is on a a legacy app we're looking to deprecate in the near future anyways.

**Comment by crazyk07** [comment] 2020-04-20 14:37
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30122352<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed** 2020-04-20 15:23 UTC
Labels: Code Review Passed, tcx_Assigned, tcx_FixAccepted, tcx_Paid

**Comment by skyhit** [comment] 2020-04-20 23:55
@Oanh-and-only-Oanh the PR for tc-website is not merged and deployed.
