### ISSUE TITLE
issues if user is not rated in SRM

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#913] opened 2018-06-08 20:10 UTC
### Reported URL ###
https://www.topcoder-dev.com/members/pshah_manager/details/?track=DATA_SCIENCE&subTrack=SRM&tab=statistics

### Reproduction Steps ###

1. open https://www.topcoder-dev.com/members/pshah_manager/details/?track=DATA_SCIENCE&subTrack=SRM&tab=statistics

2. observe

### Expected Result ###
1. no need to show blank graph if not rated in SRM
2. RATING and RANK should be N/A, not 0

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment] 2018-06-08 20:10
<img width="1376" alt="11" src="https://user-images.githubusercontent.com/4590317/41178836-15305f2e-6b9b-11e8-98c2-56accc312640.png">

**Comment by winterflame** [comment] 2018-06-11 05:13
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Minor

**Comment by ThomasKranitsas** [comment] 2018-08-14 20:58
Duplicate of https://github.com/topcoder-platform/community-app/issues/983 ?

**Closed by ThomasKranitsas** 2018-08-14 20:58 UTC
Labels: Minor, PD - Member - Migration
