### ISSUE TITLE
Skills aligned to the left, so there is a lot of white space on the right

### ISSUE THREAD

**Issue by PereViki** [topcoder-platform/community-app#1471] opened 2018-09-16 00:26 UTC
**Describe the bug**
When I open my Skill section, I find a list of skill boxes. These boxes are arranged in two columns and aligned to the left. There is an unreasonably large space on the right.

**To Reproduce**
1. Go to 'https://www.topcoder.com/settings/profile'
2. Click on 'Skill'
3. See error

**Expected behavior**
The available screen should be filled nicely. The boxes could also be aligned in the middle, and 3 columns could also fit.

**Screenshots**
![img_3896](https://user-images.githubusercontent.com/35376779/45591602-d6b0bb80-b957-11e8-8594-66a4c76a0326.PNG)

**Smartphone:**
 - Device: iPhone 6s
 - OS: iOS 11
 - Browser: safari

@ThomasKranitsas

**Comment by ThomasKranitsas** [comment] 2018-09-20 16:47
duplicate of #1470 

The issue is essentially the same

**Closed by ThomasKranitsas** 2018-09-20 16:47 UTC
