### ISSUE TITLE
 CHALLENGE DETAILS FAILS TO SHOW - PD - Member - Migration - MAJOR

### ISSUE THREAD

**Issue by psharneja** [topcoder-platform/community-app#1024] opened 2018-06-10 18:56 UTC
@ThomasKranitsas 
Many a times CHALLENGE DETAILs of a member profiles doesn't show any result
![screenshot from 2018-06-11 00-24-20](https://user-images.githubusercontent.com/18382400/41205264-f697196c-6d0d-11e8-8755-3baae3a24168.png)

**Comment by sjbr** [comment] 2018-06-11 13:40
https://github.com/topcoder-platform/community-app/issues/980

**Comment by psharneja** [comment] 2018-06-11 15:42
Those aren't same

**Comment by ThomasKranitsas** [comment] 2018-06-13 21:52
Duplicate of #973

**Closed by ThomasKranitsas** 2018-06-13 21:52 UTC
