### ISSUE TITLE
In Linked account , If we give invalid domain site name we are getting message as “LOADING DATA. THIS WILL TAKE A FEW MINUTES.”  AND  WE ARE NOT ABLE TO DELETE THE LINK

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/community-app#929] opened 2018-06-08 20:42 UTC
Summary:
In Linked account , If we give invalid domain site name we are getting message as “LOADING DATA. THIS WILL TAKE A FEW MINUTES.”  AND  WE ARE NOT ABLE TO DELETE THE LINK

### Reported URL ###
https://www.topcoder-dev.com/settings/profile/
### Log In Used ###
pshah_manager 
### Reproduction Steps ###
1.	Go to https://www.topcoder-dev.com/settings/profile/
2.	In ADD A WEB LINK TYPE “WWW.GO.COM
3.	CLICK ADD BUTTON
4.	NOW URL WILL BE ADDED
5.	SCROLL DOWN AND VIEW THE LINKED ACCOUNTS SECTION
6.	TRY TO DETE THE INVALID SITE NAME
### Expected Result ###
In Linked account , If we give invalid domain site name we should not get message as “LOADING DATA. THIS WILL TAKE A FEW MINUTES.”  AND SHOULD ALLOW DELETE THE LINK

### Actual  Result ###
In Linked account , If we give invalid domain site name we are getting message as “LOADING DATA. THIS WILL TAKE A FEW MINUTES.”  AND  WE ARE NOT ABLE TO DELETE THE LINK

### Screenshots ###

See in comment section

### Issue Information ###

Frequency: Repeated

Device: Windows

OS: Windows 10

Browser: Chrome

**Comment by youdare** [comment] 2018-06-08 20:42
![image](https://user-images.githubusercontent.com/31862600/41180076-94787138-6b8a-11e8-8330-d7dcaa51e8bc.png)

**Comment by youdare** [comment] 2018-06-11 19:35
@ThomasKranitsas Labels for this issue:
PD - Member - Migration
Major

**Comment by ThomasKranitsas** [comment] 2018-06-14 12:16
duplicate of https://github.com/topcoder-platform/community-app/issues/894

**Closed by ThomasKranitsas** 2018-06-14 12:16 UTC
Labels: Major, PD - Member - Migration
