### ISSUE TITLE
[$50]Subcommunity  filter does not include  private groups

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4650] opened 2020-07-16 05:25 UTC
Subcommunity  filter does not include  private groups
https://www.topcoder.com/challenges?
https://beta-community-app.topcoder.com/challenges?

cc @lakshmiathreya @Oanh-and-only-Oanh @sushilshinde 

<img width="1440" alt="Screenshot 2020-07-16 at 10 19 56 AM" src="https://user-images.githubusercontent.com/58783823/87628277-304dc100-c74e-11ea-9e52-a80b7e05fdfd.png">
<img width="1440" alt="Screenshot 2020-07-16 at 10 20 39 AM" src="https://user-images.githubusercontent.com/58783823/87630511-e3201e00-c752-11ea-9b25-51bbb1476580.png">

**Comment by crazyk07** [comment] 2020-07-18 09:44
[500]: Challenge for the updated issue 4650 is creating, rescheduling this event<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-07-18 09:44
Contest https://www.topcoder.com/challenges/30133391 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by sushilshinde** [comment] 2020-07-20 08:24
@narekcat any updates?

**Comment by narekcat** [comment] 2020-07-20 08:27
@sushilshinde I am working on it. I will finish in nexy six hours.

**Comment by narekcat** [comment] 2020-07-20 12:47
@sushilshinde I think the problem is with back-end. This [url](https://community-app.topcoder-dev.com/community-app-assets/api/tc-communities?groups%5B0%5D=72a0b8a0-aa45-44f7-86c2-bf9de6321e5b&groups%5B1%5D=b8fe66cc-935f-4986-a1cf-5e1dee943e8a&groups%5B2%5D=025da0c3-09b1-4d56-9f24-ec7bf8a1eeea) doesn't return the "TopGear Community" private community.

**Comment by sushilshinde** [comment] 2020-07-20 14:11
@narekcat it's a proxy call to groups API. 

@luizrrodrigues we did use direct call to groups API with user token?

**Comment by luizrrodrigues** [comment] 2020-07-20 14:48
@sushilshinde 
- To get user groups this is done with the user token.
- To get all groups (used in filter and community sub-pages) this is done via m2m

**Comment by SathyaJayabal** [comment] 2020-07-20 14:52
@luizrrodrigues , filter also only shows the users groups. for example only a topgear member can see the topgear option in the filter dropdown.
This is the behaviour in prod.

cc @sushilshinde

**Comment by luizrrodrigues** [comment] 2020-07-20 15:00
@SathyaJayabal I'm testing with **TonyJ** user, this user is member from **TopGear Community** but this not showing in filters.

Looks like filter are loaded from here: https://github.com/topcoder-platform/community-app/blob/develop/src/server/tc-communities/index.js
This load metadata from JSON files, but look like **TopGear** not included on this.

@sushilshinde We have a good reason to follow this way instead call data directly from API?

**Comment by SathyaJayabal** [comment] 2020-07-20 16:36
@luizrrodrigues , this was working previously. see screenshot in the below issue- We only had trouble with the filters not returning the group's challenges.
https://github.com/topcoder-platform/community-app/issues/4575

**Comment by luizrrodrigues** [comment] 2020-07-20 17:09
@SathyaJayabal Need to call `challenges` with Group UUID, not with legacyId. I'll comment in #4575

**Comment by luizrrodrigues** [comment] 2020-07-23 13:13
@sushilshinde PR's are ready:
https://github.com/topcoder-platform/topcoder-react-lib/pull/211
https://github.com/topcoder-platform/community-app/pull/4680

**Comment by sushilshinde** [comment] 2020-07-23 13:14
Thank @luizrrodrigues

**Comment by crazyk07** [comment] 2020-07-24 02:03
Contest https://www.topcoder.com/challenges/30133391 has been updated - it has been assigned to luizrrodrigues.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by SathyaJayabal** [comment] 2020-07-27 05:09
verified on beta
<img width="1440" alt="Screenshot 2020-07-27 at 10 38 16 AM" src="https://user-images.githubusercontent.com/58783823/88505520-52b8c780-cff5-11ea-8126-cf2e5ba2f3f5.png">

**Comment by crazyk07** [comment] 2020-07-27 14:28
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30133391<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed** 2020-07-27 14:28 UTC
Labels: Beta Env, Challenge Listing, P2, QA Pass, tcx_Assigned, tcx_FixAccepted, v5-intgration-sub-code
