### ISSUE TITLE
[$20]Registration: Challenge terms displayed even if the user has already agreed to the terms

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4548] opened 2020-06-17 06:37 UTC
Registration: Challenge terms displayed even if the user has already agreed to the terms. Onclicking on agree nothing happens and the user cannot proceed to register. We see the following error in the api response
https://api.topcoder.com/v2/terms/21303/agree
https://beta-community-app.topcoder.com/challenges/adb02d6f-dcc6-4fcc-b7a4-a16c7d173839
user:picachui
<img width="1440" alt="Screenshot 2020-06-17 at 12 04 48 PM" src="https://user-images.githubusercontent.com/58783823/84863717-06dc3f80-b093-11ea-8ea3-f3082ae79271.png">

Another example:https://beta-community-app.topcoder.com/challenges/d3886070-f6f7-4f23-81b5-9fb7e3272c06

**Comment by sushilshinde** [comment] 2020-06-17 12:08
@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup

Submit in 8 hours and PR to

https://github.com/topcoder-platform/community-app/tree/integration-v5-challenge-api
https://github.com/topcoder-platform/topcoder-react-lib/tree/integration-v5-challenge-api

run `npm run test` before PR

**Comment by crazyk07** [comment] 2020-06-17 12:11
Contest https://www.topcoder.com/challenges/30130201 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-06-17 12:22
Contest https://www.topcoder.com/challenges/30130201 has been updated - it has been assigned to cagdas001.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by cagdas001** [comment] 2020-06-17 15:08
What is the password of `picachui` user?

**Comment by cagdas001** [comment] 2020-06-17 15:45
@sushilshinde @SathyaJayabal

> What is the password of picachui user?

**Comment by rootelement** [comment] 2020-06-17 16:19
Did you try `appirio123`?

**Comment by SathyaJayabal** [comment] 2020-06-17 16:44
@cagdas001 , thats my production user id. Please use your handle.

**Comment by cagdas001** [comment] 2020-06-17 16:45
> Did you try `appirio123`?

@rootelement Yes I tried it, didn't work. The issue is that, the login link redirects me to the https://accounts.topcoder.com domain while the beta domain is actually https://beta-community-app.topcoder.com

I couldn't find a login link on beta instance so can't login with `appirio123`

**Comment by cagdas001** [comment] 2020-06-17 16:47
> @cagdas001 , thats my production user id. Please use your handle.

Okay, thank you. I thought it won't prompt me the dialog with my own username since I already agreed them before, but it did. Now I can reproduce

**Comment by SathyaJayabal** [comment] 2020-06-17 16:50
@cagdas001 , beta uses production backend and you can use your topcoder handle to test.Let me get a test user  ready for you

**Comment by SathyaJayabal** [comment] 2020-06-17 16:52
> > @cagdas001 , thats my production user id. Please use your handle.
> 
> Okay, thank you. I thought it won't prompt me the dialog with my own username since I already agreed them before, but it did. Now I can reproduce

Yes, thats the error. The Front end prompts even when the user is already agreed to the terms. We need to check if the user is already agreed, before displaying the prompt.

**Comment by cagdas001** [comment] 2020-06-17 23:30
Releasing as I'm currently having some issues with `node-gyp` on my Windows machine

**Comment by crazyk07** [comment] 2020-06-17 23:33
Contest https://www.topcoder.com/challenges/30130201 has been updated - it has been assigned to PkDurlabhji.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by sushilshinde** [comment] 2020-06-18 10:18
@PrakashDurlabhji wait for confirmation on v5 terms API shift

**Comment by PrakashDurlabhji** [comment] 2020-06-22 09:38
@sushilshinde shall I proceed with this?

**Comment by sushilshinde** [comment] 2020-06-22 10:02
Yes use terms v5 api

**Comment by PrakashDurlabhji** [comment] 2020-06-22 22:57
@sushilshinde working

**Comment by PrakashDurlabhji** [comment] 2020-06-23 07:01
@SathyaJayabal was it ever working perfectly?

1. I remember when agreement used to be seen by me and I register than nothing happens.
2. then i refresh the challenge page and i am found to be registered. so is this expected flow?
3. also can you please give some test challenges where i may not have agreed yet.

**Comment by PrakashDurlabhji** [comment] 2020-06-23 08:09
@sushilshinde I guess terms api not yet on V5 because this is not working

https://api.topcoder.com/v5/terms/detail/21303

Need clarification label was removed by me mistakenly.

**Comment by PrakashDurlabhji** [comment] 2020-06-23 10:53
@SathyaJayabal @sushilshinde can anyone please raise a ticket v5 terms api migration on respective repo? Apology for removing need clarification label earlier

**Comment by SathyaJayabal** [comment] 2020-06-23 11:23
@PrakashDurlabhji , please see below documentation for v5 terms.  https://github.com/topcoder-platform/terms-service/blob/dev/docs/swagger.yaml

**Comment by sushilshinde** [comment] 2020-06-23 12:22
@luizrrodrigues can you also guide @PrakashDurlabhji in implementation as your issues also related.

**Comment by luizrrodrigues** [comment] 2020-06-23 12:33
@PrakashDurlabhji Instead `https://api.topcoder.com/v5/terms/detail/21303` you need to use `https://api.topcoder-dev.com/v5/terms/b11da5cd-713f-478d-90f4-f679ef53ee95` to get details.

@sushilshinde I think this one is a duplication of #4562

Both issues need to update the terms to use V5 API.

**Comment by PrakashDurlabhji** [comment] 2020-06-23 12:43
@sushilshinde thanks.

Also I am actively trying to make a call from postman.
and yes @luizrrodrigues I just debugged and found mapping that 'terms/detail/21303' is now /terms/uuid'.

@SathyaJayabal @luizrrodrigues I do not find in swagger https://github.com/topcoder-platform/terms-service/blob/dev/docs/swagger.yaml
the api to get all terms of challenge by challengeId.

1. In prod rite now there is a call to get challenge terms 
this.private.api.get(`/terms/${challengeId}?role=Submitter`)

2. and then after selecting a termuseOfid from above response we call 'terms/detail/21303' in prod.

3. so mapping of '/detail' is there in v5, but what about this '`/terms/${challengeId}?role=Submitter`'?

I am stuck here

**Comment by PrakashDurlabhji** [comment] 2020-06-23 13:02
@SathyaJayabal @sushilshinde @luizrrodrigues 

Though I feel its not correct usage of api, I am bit confused.

1. I just tried in POSTMAN https://api.topcoder.com/v5/terms?legacyId=30130750
and passed tokenV3 in authorization .
2. It says "You are not allowed to perform this action".

 I feel everything is smooth for terms details but not for getting all terms of a challenge.

**Comment by PrakashDurlabhji** [comment] 2020-06-23 13:53
@SathyaJayabal waiting for endpoint

just for note down: http://localhost:3000/challenges/847bc43a-53c1-4cdd-a2ac-d3a7eb5ee25c

**Comment by rootelement** [comment] 2020-06-23 14:43
You need to use the array of terms on the challenge response, then call the terms api for details. Right now there's no multi-id filter, so you'll have to hit it for each. The order of operations here should be:
1. Filter the challenge's terms on roleId for submitter
2. Loop through those terms IDs calling the terms api

This is similar to how it's done in the resources api:

https://github.com/topcoder-platform/resources-api/blob/b5c242e00bdfab55a49ba2d4e25d7a23dacd2aa7/src/services/ResourceService.js#L158

https://github.com/topcoder-platform/resources-api/blob/cfa7b62938fbf6daee4a44ad3a745566fcc08ba7/src/common/helper.js#L430

**Comment by luizrrodrigues** [comment] 2020-06-23 15:26
@PrakashDurlabhji Please check about duplication with @sushilshinde 
I'm already implementing this in issue #4562

**Comment by crazyk07** [comment] 2020-06-24 11:46
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30130201<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed** 2020-06-24 11:46 UTC
Labels: Beta Env, Challenge Details Screen, Need clarification, P1, tcx_Assigned, tcx_FixAccepted, v5-intgration-sub-code
