### ISSUE TITLE
[Web-Firefox] Sentence How to Start a Career as a UI / UX Designer Having Grammatical Error

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/community-app#3936] opened 2020-02-07 20:56 UTC
URL: https://www.topcoder.com/thrive/tracks?track=Design&tax=How-To

**Describe the bug**
Sentence How to Start a Career as a UI / UX Designer Having Grammatical Error

**To Reproduce**
1. Go to https://www.topcoder.com/thrive/tracks?track=Design&tax=How-To

2. Scroll Down Mouse To How to Start a Career as a UI / UX Designer  & Observe

3. See Screenshot

**Expected behavior**
Sentence How to Start a Career as a UI / UX Designer Should Be Written As How to Start a Career as an UI / UX Designer 

**Actual Behaviour**
Sentence Is Written As How to Start a Career as a UI / UX Designer 

**Screenshots**
![Gramatical](https://user-images.githubusercontent.com/42583358/74065184-4e362d80-4a1a-11ea-8725-7d31cf765419.png)

**Desktop (please complete the following information):**
 - OS: 
![Mac Version](https://user-images.githubusercontent.com/42583358/74065217-5db57680-4a1a-11ea-9f3d-59f355573be3.png)

 - Browser 
![Firefox Version](https://user-images.githubusercontent.com/42583358/74065240-6c039280-4a1a-11ea-8cae-d3e7054250dc.png)

**Additional context**
UX Issue

**Comment by winterflame** [comment] 2020-02-13 11:51
Not a bug, it's correct. Also, content issues are out of scope.

**Closed by winterflame** 2020-02-13 11:51 UTC
