### ISSUE TITLE
Different font loaded for the sub menu titles

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2495] opened 2019-06-07 19:25 UTC
1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Portrait)
3. Tap Menu > Work > Compete

**Actual:** Different font loaded for the sub menu titles

**Expected:** Should display the same font for the sub menus as well

**Reproducibility Rate:** 3/3

**Environment:** iPad Air 2, iOS 12.2

**Browser:** Safari 12

**Comment by nithyaasworld** [comment] 2019-06-09 21:43
@codejamtc Please attach screenshot

**Comment by nithyaasworld** [comment] 2019-06-09 21:47
Also did you compare it with the Design in **HandOff mode**? are the font, size and other attribute of the sub menu same as in the Design spec.

**Comment by codejamtc** [comment] 2019-06-09 21:49
![image](https://user-images.githubusercontent.com/42398485/59164697-3054a980-8ad6-11e9-961d-79bcdbb21ee7.png)

https://marvelapp.com/89423f8/screen/54595272

**Comment by nithyaasworld** [comment] 2019-06-10 06:46
@codejamtc Can you please tell me in detail about what is the Expected Font and what is the Actual Font?

Please use this link to see the design in handoff mode: https://marvelapp.com/89423f8/screen/54595272/handoff

Click on the Solutions menu in the design screen. It opens the Solutions' CSS at the right panel. Compare it with the actual and post your results here. Thanks.

![image](https://user-images.githubusercontent.com/5114190/59177376-89294e00-8b79-11e9-8827-2a5a0bb8afee.png)

**Comment by codejamtc** [comment] 2019-06-10 18:32
I can see Roboto as the font in the design document

![image](https://user-images.githubusercontent.com/42398485/59217564-d4485e80-8b83-11e9-81b6-e3d23a2891f9.png)

But I couldn't track down the font visible on the iPad Safari since I don't own a MacBook I don't think they have in-built developer tool for mobile safari in iPad or iPhone.

**Comment by nithyaasworld** [comment] 2019-06-10 18:52
So how do you say " Different font loaded for the sub menu titles" ?

**Comment by codejamtc** [comment] 2019-06-10 18:59
@nithyaasworld It's visually different. Design vs iPad (Safari)

**Comment by nithyaasworld** [comment] 2019-06-10 19:16
Hey @codejamtc It seems like you are referencing "WORK" which has Roboto font. But the reported  bug is for the "Compete" menu which has the "BarlowCondensed".

"Compete" is same in both mobile view as well as in Desktop view.

Am I missing something ?

**Comment by codejamtc** [comment] 2019-06-10 19:47
@nithyaasworld I am sorry about that, I am referring to the sub-menus "Compete", "Tracks" and "Community"

![image](https://user-images.githubusercontent.com/42398485/59221862-d9121000-8b8d-11e9-82bd-49c31dbc3bd6.png)

**Original iPad Mobile Safari Screenshot:**

![image](https://user-images.githubusercontent.com/42398485/59164697-3054a980-8ad6-11e9-961d-79bcdbb21ee7.png)

**Android Mobile screenshot:**

![4](https://user-images.githubusercontent.com/42398485/59222277-b92f1c00-8b8e-11e9-9343-a0c13674a7a3.jpg)

**iPhone Mobile Safari screenshot:**

![image](https://user-images.githubusercontent.com/42398485/59222120-648ba100-8b8e-11e9-9364-0271cd6e0ec2.png)

I think this is something to do with the mobile Safari; Android, Chrome font matches with the desktop

**Comment by nithyaasworld** [comment] 2019-06-10 19:57
@luizrrodrigues I am not sure if it is just the visual difference or there is actual font mismatch in mobile Safari. Please take care. Thanks.

**Comment by luizrrodrigues** [comment] 2019-06-10 20:35
@nithyaasworld @codejamtc Here looks fine in iPhone Simulator:

![image](https://user-images.githubusercontent.com/7029641/59225054-28fcd100-8ba6-11e9-90bd-9c9d5f86409c.png)

**Comment by luizrrodrigues** [comment] 2019-06-11 00:04
@nithyaasworld This is font mismatch, check bellow TCO have right font, (See the **C**):

![Screen Shot 2019-06-10 at 21 02 13](https://user-images.githubusercontent.com/7029641/59234485-52782580-8bc3-11e9-8672-3e1177017d56.png)

**Comment by nithyaasworld** [comment] 2019-06-11 04:59
Thanks @luizrrodrigues. Got that!

 By design, First level menus are of font BarlowCondensed and Second Level Menus are of font Roboto.

But checking the letter "C" of the **FIRST LEVEL MENU** (which Compete, Tracks, Community) in Android Chrome and iOS Safari looks different. This needs to be fixed.

**Comment by sjbr** [comment] 2020-01-09 15:34
@luizrrodrigues 
Please assign this one to me
Thanks

**Comment by yoution** [comment] 2020-01-10 13:44
can not reproduct it

**Comment by luizrrodrigues** [comment] 2020-01-10 14:25
Have you test this in Safari iPad?

**Comment by yoution** [comment] 2020-01-10 14:27
you mean only reproduct in ipad?I test in ipad simulator

**Comment by luizrrodrigues** [comment] 2020-01-10 14:33
@yoution Yeah, I think this one already fixed.

**Comment by nithyaasworld** [comment] 2020-01-21 13:47
Verified that its fixed in production already.

**Comment by SathyaJayabal** [comment] 2020-02-04 09:42
Closing this as this has been verified in production

**Closed by SathyaJayabal** 2020-02-04 09:42 UTC
Labels: Navigation, P3, Prod QA Pass, UI
