### ISSUE TITLE
Sub-Item underline highlighter is not changing position when window is resized

### ISSUE THREAD

**Issue by kiranmaroju** [topcoder-platform/community-app#2479] opened 2019-06-07 19:00 UTC
**Pre-Requisite**

**Steps to Reproduce**

1. Navigate to "https://test-community-app.topcoder-dev.com/challenges"
2. Login to Topcoder
3. Click Work-->Tracks, 
4, Try Resizing the window size, and check the Sub-Item underline highlighter 

**Actual behavior**
Sub-Item underline highlighter is not changing position when window is resized

**Expected behavior**
Sub-Item underline highlighter should change accordingly when window is resized

**Screen shots/video**
https://drive.google.com/uc?id=1pGnxMVW8YEaSQ2ndoybtJcEuKDiTXKGM

**Environment :**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 75.0.3770.80 (Official Build) (64-bit)

 
**Reproducible rate**
3/3

**Comment by nithyaasworld** [comment] 2019-06-09 21:29
Duplicate of https://github.com/topcoder-platform/community-app/issues/2407

**Closed by nithyaasworld** 2019-06-09 21:29 UTC
Labels: Bug Hunt, Navigation, P3, UI
