### ISSUE TITLE
[$40]Challenge Details: Checkpoints tab not displayed

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4516] opened 2020-06-11 08:37 UTC
Challenge Details: Checkpoints tab not displayed for design challenges with checkpoint phase
Examples:
Dev backend:
V5 URL: https://test-community-app.topcoder-dev.com/challenges/4bccb4bb-b0a1-4046-8da0-69e4027fbc1a
V4 URL: https://qa-community-app.topcoder-dev.com/challenges/30021775
Prod backend
V5 URL:https://beta-community-app.topcoder.com/challenges/6b29e50f-fe49-47a8-a949-f96a00c22448
V4 URL: https://www.topcoder.com/challenges/30126386

<img width="1440" alt="Screenshot 2020-06-11 at 2 05 43 PM" src="https://user-images.githubusercontent.com/58783823/84363683-b7a69280-abec-11ea-99c7-a76ee07c06d0.png">
<img width="1440" alt="Screenshot 2020-06-11 at 2 05 46 PM" src="https://user-images.githubusercontent.com/58783823/84363706-bf663700-abec-11ea-86ae-8cd425ca1f59.png">
<img width="1440" alt="Screenshot 2020-06-11 at 2 05 55 PM" src="https://user-images.githubusercontent.com/58783823/84363718-c3925480-abec-11ea-8afc-f5409e02751c.png">
<img width="1440" alt="Screenshot 2020-06-11 at 2 05 59 PM" src="https://user-images.githubusercontent.com/58783823/84363737-c8570880-abec-11ea-91d1-26ecfc8bf9c0.png">

**Comment by crazyk07** [comment] 2020-06-11 10:09
Contest https://www.topcoder.com/challenges/30129402 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-06-11 10:09
Contest https://www.topcoder.com/challenges/30129402 has been updated - it has been assigned to PkDurlabhji.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by PrakashDurlabhji** [comment] 2020-06-11 23:58
@sushilshinde I anaylzed well.

there is no checkpoints array present in v5 urls

https://api.topcoder.com/v5/challenges/6b29e50f-fe49-47a8-a949-f96a00c22448?
http://api.topcoder-dev.com/v5/challenges?legacyId=30021775

whereas available in v4
http://api.topcoder-dev.com/v4/challenges/30021775

hence it fails because a check is applied at checkpoints tab

**Comment by sushilshinde** [comment] 2020-06-12 08:27
ok so this is an API issue?

**Comment by rootelement** [comment] 2020-06-12 13:54
This is not an api issue. You will need to call to the submissions api with the submissionPhaseId:
https://api.topcoder-dev.com/v5/submissions?submissionPhaseId=775498

```json
[
   {
      "updatedBy":"ghoster",
      "created":"2020-06-09T06:30:34.809Z",
      "legacySubmissionId":209335,
      "isFileSubmission":false,
      "type":"Contest Submission",
      "url":"https://s3.amazonaws.com/topcoder-dev-submissions/9146ff17-7a4d-41f3-812b-7471bd692fb0.zip",
      "challengeId":30056709,
      "createdBy":"ghoster",
      "review":[
         {
            "score":100,
            "updatedBy":"MeaSS8yPG4VIer4XalVqOAYhnCNecGfN@clients",
            "reviewerId":"36f37d48-77a8-413f-8bed-e39f154f1301",
            "submissionId":"9146ff17-7a4d-41f3-812b-7471bd692fb0",
            "createdBy":"MeaSS8yPG4VIer4XalVqOAYhnCNecGfN@clients",
            "created":"2020-06-09T06:30:49.191Z",
            "scoreCardId":101761150,
            "typeId":"d96d5f17-5884-47b8-bfea-bddf066e451f",
            "id":"8a2ed5aa-37e2-4059-a449-7d5eab4f1d70",
            "updated":"2020-06-09T06:30:49.191Z",
            "status":"completed"
         },
         {
            "score":100,
            "updatedBy":"maE2maBSv9fRVHjSlC31LFZSq6VhhZqC@clients",
            "reviewerId":"aec9a3d6-50cd-46aa-a462-fcb1ccb55de9",
            "submissionId":"9146ff17-7a4d-41f3-812b-7471bd692fb0",
            "createdBy":"maE2maBSv9fRVHjSlC31LFZSq6VhhZqC@clients",
            "created":"2020-06-09T06:30:40.134Z",
            "scoreCardId":30001850,
            "typeId":"68c5a381-c8ab-48af-92a7-7a869a4ee6c3",
            "id":"d1c2b66c-9feb-4ff4-be6b-850225f100c7",
            "updated":"2020-06-09T06:30:40.134Z",
            "status":"completed"
         }
      ],
      "id":"9146ff17-7a4d-41f3-812b-7471bd692fb0",
      "submissionPhaseId":775498,
      "updated":"2020-06-09T06:30:34.809Z",
      "fileType":"zip",
      "memberId":10098915
   }
]
```

**Comment by PrakashDurlabhji** [comment] 2020-06-13 12:37
@rootelement @sushilshinde  I guess there is some misunderstanding from your side or I am not able interpret it. Let me explain my best till now.

1. Kindly go to https://www.topcoder.com/challenges/30126386?tab=checkpoints and see the checkpoints page.
2. Now go to http://api.topcoder.com/v4/challenges/30126386 you would checkpoints array.
3. Now the content of checkpoints array is 

```
			"checkpoints": [{
				"submitter": "ndondo_",
				"submissionId": 375068,
				"submissionTime": "2020-05-27T01:20:44.000Z"
			}]
```
4. "Feedback 375068 " can be seen on checkpoints tab.
5. so checkpoints array is needed.
6. Now as @rootelement mentions in above comment to hit submission api, but from where to get submissionphaseId?
7. do I need to take it out from phase array having submission object, from there I need to pick the phaseId field and hit the api as you said?
8. Even If I do that then the response pasted by @rootelement , how to match it? I can see submissionId can be matched,but what about "submitter"?
9. Also I feel submitter field has least importance when i visit https://www.topcoder.com/challenges/30126386?tab=checkpoints because only submissionId can be seen on page.
10. then by the response of @rootelement , we will display "Feedback 9146ff17-7a4d-41f3-812b-7471bd692fb0" are we going to display something like this?

I am totally confused, may be I am missing something, Any extra doc which is shared internally at your side for this submission phase id topic would help me? I can read that then.

Waiting for some more clarification

**Comment by rootelement** [comment] 2020-06-15 13:14
Yes, if this is the case, those checkpoints are being referred to by their ID. The new IDs are UUIDs. We can treat it like Github where a hash is referred to by the first chunk of the hash. So in that case, show "Feedback 9146ff17", splitting it on the first `-`

I'm not sure that's the best solution, but that's the similar solution to what we have now. We _could_ also look up the handles for the checkpoints, and show that, but I'm not sure that's something we'd want to show on that page.

**Comment by PrakashDurlabhji** [comment] 2020-06-17 12:34
@sushilshinde PR https://github.com/topcoder-platform/community-app/pull/4551

**Comment by SathyaJayabal** [comment] 2020-06-18 04:01
Checkpoint tab not yet displayed
<img width="1440" alt="Screenshot 2020-06-18 at 9 29 36 AM" src="https://user-images.githubusercontent.com/58783823/84976806-6f382900-b146-11ea-9823-94b22d7190af.png">

**Comment by sushilshinde** [comment] 2020-06-18 09:25
@sushilshinde I anaylzed well.

there is no checkpoints array present in v5 urls

https://api.topcoder.com/v5/challenges/6b29e50f-fe49-47a8-a949-f96a00c22448?
http://api.topcoder-dev.com/v5/challenges?legacyId=30021775

whereas available in v4
http://api.topcoder-dev.com/v4/challenges/30021775

hence it fails because a check is applied at checkpoints tab

**Comment by crazyk07** [comment] 2020-06-18 09:42
Contest https://www.topcoder.com/challenges/30129402 has been updated - it has been assigned to nursoltan-s.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-06-18 10:28
Contest https://www.topcoder.com/challenges/30129402 has been updated - PkDurlabhji has been unassigned.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-06-18 10:29
Contest https://www.topcoder.com/challenges/30129402 has been updated - it has been assigned to PkDurlabhji.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by PrakashDurlabhji** [comment] 2020-06-18 11:59
@sushilshinde both PR are required. at frontend as well as topcoder-react-lib.

#4551
https://github.com/topcoder-platform/topcoder-react-lib/pull/199

out of which 1 is already merged of frontend hence only topcoder-react-lib need to be merged

**Comment by PrakashDurlabhji** [comment] 2020-06-18 12:03
<img width="756" alt="Capture" src="https://user-images.githubusercontent.com/28830240/85017849-cb706c80-b189-11ea-8c11-c04d08a35d3f.PNG">

Verification  screenshot

**Comment by sushilshinde** [comment] 2020-06-18 12:07
ok thanks @PrakashDurlabhji

**Comment by SathyaJayabal** [comment] 2020-06-19 05:08
@sushilshinde @PrakashDurlabhji , according to this comment
https://github.com/topcoder-platform/community-app/issues/4516#issuecomment-643282797
we should sue the submissions api to get the checkpoint details.

But the api call used here is the older V2 call.
https://api.topcoder.com/v2/design/challenges/checkpoint/30127234

@sushilshinde , please confirm if this is the right approach.
<img width="1440" alt="Screenshot 2020-06-19 at 10 36 33 AM" src="https://user-images.githubusercontent.com/58783823/85098610-d6261280-b218-11ea-81e4-a39bbdd4f2b1.png">

**Comment by PrakashDurlabhji** [comment] 2020-06-19 08:07
@SathyaJayabal Yes to my best it is right approach, as earlier I messed up in analyzing the flow and I even confused @rootelement I believe.Hence after digging up I came to know flow is simple.

@sushilshinde is aware of flow.

Waiting for confirmation.

**Comment by sushilshinde** [comment] 2020-06-19 09:07
@skyhit any idea?

**Comment by sushilshinde** [comment] 2020-06-19 09:09
@PrakashDurlabhji follow this https://github.com/topcoder-platform/community-app/issues/4516#issuecomment-643282797

**Comment by PrakashDurlabhji** [comment] 2020-06-19 09:41
@sushilshinde are you sure? because it does not match the relevant data and also till now we were using same v2 call though I am aware we are upgrading.

1. I feel even if we have migrated then we should be using a endpoint similar to /design/checkpoint and pass "ChallengeId"?
2. @rootelement should take a look again at data being received because it nowhere matches the data.

rest I would implement as you say

**Comment by SathyaJayabal** [comment] 2020-06-19 09:54
@PrakashDurlabhji , we do not use this call in production. This was used before V4.

**Comment by PrakashDurlabhji** [comment] 2020-06-19 10:34
@rootelement @SathyaJayabal 
sorry for dragging it long

1. can you please go to https://www.topcoder.com/challenges/30127234?tab=checkpoints
2. data present in checkpoints tab is coming from here https://api.topcoder.com/v2/design/challenges/checkpoint/30127234

can you please correct me if i am wrong? even i am running prod locally and verifying it in few minutes where this call was used in production or not

@rootelement sushil and I are waiting for your confirmation

**Comment by SathyaJayabal** [comment] 2020-06-19 10:37
@PrakashDurlabhji , yes you are right, this call is used in prod.

**Comment by PrakashDurlabhji** [comment] 2020-06-19 10:48
@SathyaJayabal then I hope my solution is accepted because prod using same api, and also if we wish to move to v5, then I feel same endpoint should be moved to v5, and I still feel @rootelement may have mistaken the endpoint interpretation in hurry.

Hence lets see what are inputs from @rootelement  because I myself mistaken the checkpoints array then pasted a huge explanation which was irrelevant and expected root element and messd up everything once again.

**Comment by PrakashDurlabhji** [comment] 2020-06-19 10:50
@SathyaJayabal Yes it is used I just confirmed running locally

Request URL: https://api.topcoder.com/v2/design/challenges/checkpoint/30126386
Request Method: GET
Status Code: 200

**Comment by PrakashDurlabhji** [comment] 2020-06-20 08:24
@sushilshinde can we close this? @SathyaJayabal

**Comment by PrakashDurlabhji** [comment] 2020-06-22 04:46
@SathyaJayabal any updates on this?

**Comment by SathyaJayabal** [comment] 2020-06-22 04:50
@PrakashDurlabhji , we are  waiting for confirmation from @rootelement before we close it.

**Comment by rootelement** [comment] 2020-06-23 14:28
@SathyaJayabal @PrakashDurlabhji @sushilshinde I've reviewed this with @ThomasKranitsas and I think we need to leave this as is for now. We don't have anything in Submissions API to do it, and it's not something that should be added to the challenge response. Please log this on the community app repo as a TechDebt item, and we'll get it in the pipeline for the submissions api or somewhere where it fits better.

**Comment by PrakashDurlabhji** [comment] 2020-06-23 14:37
@sushilshinde @rootelement I hope something would be paid for my extensive efforts and explanation.

**Comment by SathyaJayabal** [comment] 2020-06-24 05:45
@sushilshinde @PrakashDurlabhji , marking this as pass as per this comment
https://github.com/topcoder-platform/community-app/issues/4516#issuecomment-648194267

**Comment by SathyaJayabal** [comment] 2020-06-24 05:50
https://github.com/topcoder-platform/community-app/issues/4591

**Comment by crazyk07** [comment] 2020-06-25 14:20
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30129402<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed** 2020-06-25 14:19 UTC
Labels: Beta Env, Challenge Details Screen, P1, QA Pass, Test Env, tcx_Assigned, tcx_FixAccepted, v5-intgration-sub-code
