### ISSUE TITLE
[$260]Track and Subtrack enhancements : Details page

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#4709] opened 2020-08-05 10:51 UTC
**Part 1 - Resolve subtrack removal impact on details page.**

Going forwards on details page subtrack info won't be available as a higher-level property but the subtrack value will be part of tags list. So any logic which is based of subtrack should check tags list for particular subtrack, and use it in the existing render logic.

For example : 

If it’s Track: Data Science
If it’s Type: Challenge
Look in the tags property for a “Marathon Match” tag

 **Part 2 - Impact of new QA track**

QA track details page experience is exactly same as Develop track

**Comment by rootelement** [comment] 2020-08-05 13:03
Here is an example Marathon Match (with the spec removed for brevity):
```json
{
        "id": "d20b22b7-6d29-45cf-b7cf-18dc856b0e6b",
        "legacyId": "30135273",
        "status": "Active",
        "track": "Data Science",
        "type": "Challenge",
        "trackId": "c0f5d461-8219-4c14-878a-c3a3f356466d",
        "typeId": "927abff4-7af9-4145-8ba1-577c16e64e2e",
        "legacy": {
            "track": "DEVELOP",
            "subTrack": "DEVELOP_MARATHON_MATCH",
            "forumId": 79795,
            "directProjectId": 22249,
            "reviewType": "COMMUNITY",
            "reviewScorecardId": 30000224
        },
        "task": {
            "isTask": false,
            "isAssigned": false,
            "memberId": null
        },
        "name": "Rodeo II Sprint: Sub-Seasonal Climate Forecasting - prec56 Task, period #23",
        "descriptionFormat": "HTML",
        "projectId": 10461,
        "created": "2020-07-30T10:26:34Z",
        "createdBy": "nofto",
        "updated": "2020-07-30T10:29:39Z",
        "updatedBy": "nofto",
        "timelineTemplateId": "87ab69d5-09ec-45ef-b3d1-f6f6f1fdf2f3",
        "phases": [
            {
                "duration": 1209600,
                "scheduledEndDate": "2020-08-18T00:09:00Z",
                "actualEndDate": "2020-08-05T12:49:17Z",
                "isOpen": true,
                "name": "Registration",
                "phaseId": "a93544bc-c165-4af4-b55e-18f3593b457a",
                "actualStartDate": "2020-08-04T00:09:41Z",
                "id": "e96d5ea4-f774-4819-9cba-84c708cbad2c",
                "scheduledStartDate": "2020-08-04T00:09:41Z"
            },
            {
                "duration": 1209300,
                "scheduledEndDate": "2020-08-18T00:12:00Z",
                "actualEndDate": "2020-08-05T12:49:17Z",
                "isOpen": true,
                "name": "Submission",
                "phaseId": "6950164f-3c5e-4bdc-abc8-22aaf5a1bd49",
                "actualStartDate": "2020-08-04T00:17:08Z",
                "id": "e17929ff-e578-418b-93e5-844d34f08887",
                "scheduledStartDate": "2020-08-04T00:17:08Z"
            },
            {
                "duration": 3974400,
                "scheduledEndDate": "2020-10-03T00:12:00Z",
                "actualEndDate": "2020-08-05T12:49:17Z",
                "isOpen": false,
                "name": "Review",
                "phaseId": "aa5a3f78-79e0-4bf7-93ff-b11e8f5b398b",
                "actualStartDate": "2020-08-05T12:49:17Z",
                "id": "db83971e-9cd7-4877-82d4-44cf9bc69359",
                "scheduledStartDate": "2020-08-18T00:12:00Z"
            }
        ],
        "terms": [
            {
                "roleId": "732339e7-8e30-49d7-9198-cccf9451e221",
                "id": "9ef9dec4-dddb-48c9-9cce-659db68bc5ac"
            },
            {
                "roleId": "3eedd4a4-3c68-4f68-8de4-a1ca5c2055e5",
                "id": "e3370508-a541-4b9c-b83f-3bad33dcca4c"
            },
            {
                "roleId": "318b9c07-079a-42d9-a81f-b96be1dc1099",
                "id": "e3370508-a541-4b9c-b83f-3bad33dcca4c"
            },
            {
                "roleId": "ff556573-5da6-4392-b38c-08c1d7599c4a",
                "id": "e3370508-a541-4b9c-b83f-3bad33dcca4c"
            },
            {
                "roleId": "e0544b94-6420-4afc-8f63-238eddc751b9",
                "id": "e3370508-a541-4b9c-b83f-3bad33dcca4c"
            },
            {
                "roleId": "0e9c6879-39e4-4eb6-b8df-92407890faf1",
                "id": "aaa50b65-fb27-44e1-8398-03d70ce4ac5a"
            },
            {
                "roleId": "cfe12b3f-2a24-4639-9d8b-ec86726f76bd",
                "id": "11ad4ba8-c3ec-4cf9-98e6-c7f43a5bd89f"
            },
            {
                "roleId": "d663fc84-5c37-43d1-a537-793feffb7667",
                "id": "e3370508-a541-4b9c-b83f-3bad33dcca4c"
            }
        ],
        "startDate": "2020-08-04T00:09:41Z",
        "numOfSubmissions": 3,
        "numOfRegistrants": 17,
        "endDate": "2020-10-03T00:12:00Z",
        "currentPhaseNames": [
            "Registration",
            "Submission"
        ],
        "registrationStartDate": "2020-08-04T00:09:41Z",
        "registrationEndDate": "2020-08-05T12:49:17Z",
        "submissionStartDate": "2020-08-04T00:17:08Z",
        "submissionEndDate": "2020-08-05T12:49:17Z",
        "prizeSets": [
            {
                "prizes": [
                    {
                        "type": "USD",
                        "value": 500
                    },
                    {
                        "type": "USD",
                        "value": 350
                    },
                    {
                        "type": "USD",
                        "value": 250
                    },
                    {
                        "type": "USD",
                        "value": 175
                    },
                    {
                        "type": "USD",
                        "value": 100
                    }
                ],
                "description": "Challenge Prizes",
                "type": "placement"
            }
        ],
        "tags": [
            "Machine Learning",
            "Data Science",
            "Other",
            "Marathon Match"
        ],
        "groups": [],
        "winners": [],
        "metadata": [
            {
                "name": "allowStockArt",
                "value": "false"
            }
        ],
        "events": [],
        "numOfCheckpointSubmissions": 0
    }
```

**Comment by luizrrodrigues** [comment] 2020-08-06 04:23
@rootelement 

**Data Science** challenges type are always a Marathon Match?

**Comment by crazyk07** [comment] 2020-08-06 07:39
Contest https://www.topcoder.com/challenges/30136115 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-08-06 07:39
Contest https://www.topcoder.com/challenges/30136115 has been updated - it has been assigned to luizrrodrigues.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by rootelement** [comment] 2020-08-06 16:59
@luizrrodrigues no. There should be a tag on marathon matches. otherwise, it's just a data science challenge and should be displayed like develop challenges.

Same with QA. They should look just like develop challenges.

**Comment by luizrrodrigues** [comment] 2020-08-06 17:15
@rootelement 

- If track = data science : show orange color
- If tag have marathon match : show challenge in marathon format
- If track = qa : show purple color
- If track = development : show green color and dev format
- If track = design : show blue color and design format

To QA in tag, I think no need to check because QA always show like dev format

cc @SathyaJayabal

**Comment by rootelement** [comment] 2020-08-06 22:34
@luizrrodrigues yes that's correct

**Comment by sushilshinde** [comment] 2020-08-10 05:58
@luizrrodrigues please PR asap

**Comment by SathyaJayabal** [comment] 2020-08-10 06:05
Note: Fix includes
https://github.com/topcoder-platform/community-app/issues/4720#issuecomment-670350492

**Comment by luizrrodrigues** [comment] 2020-08-10 06:46
@sushilshinde PRs are ready ☝️

**Comment by SathyaJayabal** [comment] 2020-08-10 08:00
@luizrrodrigues, Marathon Match details page display must be different. 
1. Marathon matches submissions tab display has ranking, provisional scores and submission history  
2. Additional My submissions tab(if user has registered)

Please compare with V4 for expected behaviour
https://www.topcoder.com/challenges/30129332
https://beta-community-app.topcoder.com/challenges/118cb7f0-25e9-40e5-83ee-bd6fb3514e1d 
cc @sushilshinde

**Comment by luizrrodrigues** [comment] 2020-08-10 08:02
@SathyaJayabal @sushilshinde hotfix: https://github.com/topcoder-platform/community-app/pull/4729

**Comment by SathyaJayabal** [comment] 2020-08-10 13:24
Verified

**Comment by crazyk07** [comment] 2020-08-10 14:54
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30136115<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed** 2020-08-10 14:53 UTC
Labels: Challenge Details Screen, Must-fix-before-v5-release, QA Pass, tcx_Assigned, tcx_FixAccepted, v5-intgration-sub-code
