### ISSUE TITLE
[$100] SSF - My Challenges bucket differs from production and actual data

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#2387] opened 2019-05-31 12:59 UTC
Serverside filtering issues observed on **My Challenges** bucket

1. https://beta-community-app.topcoder.com/challenges

<img width="3604" alt="Topcoder Challenges 2019-05-31 18-24-30" src="https://user-images.githubusercontent.com/683231/58707129-a3bd3380-83d1-11e9-8044-cc2af86b7199.png">

**Expected behavior**
It should show all my challenges

**Desktop (please complete the following information):**
 - OS: Mac
 - Chrome Incognito

**Comment by ThomasKranitsas** [comment] 2019-06-03 14:22
@topcoder-platform/topcodercompetitors this is open for pickup.

PR on `server_side_filtering` branch.

**Comment by ThomasKranitsas** [comment] 2019-06-03 14:26
Contest https://www.topcoder.com/challenges/30092404 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-06-03 14:28
Contest https://www.topcoder.com/challenges/30092404 has been updated - it has been assigned to gurmeetb.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-06-04 11:23
Contest https://www.topcoder.com/challenges/30092404 has been updated - it has been assigned to nauhil.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by nauhil** [comment] 2019-06-04 23:08
I've digged into and found the root of issue is pagination fetch data

For example from my account

1)
Due to just fetch first 50 records of challenges when Bucket is All Challenges, so The challenge `
Project zu Hause | VSCode IDE - Part 1` is not included in the first 50 records.

So there're only 4 challenges as picture displayed
![Alt text](https://monosnap.com/image/l3PpSkaaAw9SuQS2udNR5NR4C5h3rY)

2) 
The challenge `Project zu Hause | VSCode IDE - Part 1` is still not included when Bucket is My Challenges as picture displayed ![Alt text](https://monosnap.com/image/xtysHCtnv3uk84paDg5ipflmv5NO8q)

The reason is that
first step: `fetch first 50 records`
https://api.topcoder.com/v4/challenges/?filter=status=ACTIVE&limit=50&offset=0, the challenge api fetched results `don't include` The challenge `Project zu Hause | VSCode IDE - Part 1`
https://api.topcoder.com/v4/members/nauhil/challenges/?filter=status=ACTIVE&limit=50&offset=0, the user challenge api  fetched results `include` The challenge `Project zu Hause | VSCode IDE - Part 1`

After filtered https://github.com/topcoder-platform/topcoder-react-lib/blob/3a520fff5b8aa633c0a2f1d23f21adc83bb7c0f2/src/actions/challenge-listing.js#L212, The challenge `Project zu Hause | VSCode IDE - Part 1` is removed

---------------------------------------------------------------

second step: `fetch second 50 records`
https://api.topcoder.com/v4/challenges/?filter=status=ACTIVE&limit=50&offset=0, the challenge api fetched results `include` The challenge `Project zu Hause | VSCode IDE - Part 1`
https://api.topcoder.com/v4/members/nauhil/challenges/?filter=status=ACTIVE&limit=50&offset=0, the user challenge api results `don't include` The challenge `Project zu Hause | VSCode IDE - Part 1`

After filtered https://github.com/topcoder-platform/topcoder-react-lib/blob/3a520fff5b8aa633c0a2f1d23f21adc83bb7c0f2/src/actions/challenge-listing.js#L212, The challenge `Project zu Hause | VSCode IDE - Part 1` is still removed

---------------------------------------------------------------

There's a demo video https://www.dropbox.com/s/rgqv0cf22ljm1kj/My%20Challenges%20bucket%20differs%20from%20production%20and%20actual%20data.mp4?dl=0

**Comment by nauhil** [comment] 2019-06-05 06:35
Option A
Fetch all user challenges when fetch challenges  every time.

Option B
Fetch challenges and user challenges both use same sort 

However, both options cannot make sure fetch all my challenges when Bucket is All challenges

Any thoughts?

**Comment by ThomasKranitsas** [comment] 2019-06-10 09:34
@nauhil let's go with option A, please

**Comment by nauhil** [comment] 2019-06-11 05:24
OK.

I'll implement it ASAP

**Comment by nauhil** [comment] 2019-06-11 08:10
Just update topcoder-react-lib

PR https://github.com/topcoder-platform/topcoder-react-lib/pull/71

@sushilshinde @ThomasKranitsas Please check it

**Comment by nauhil** [comment] 2019-06-13 10:28
@ThomasKranitsas Due to I have urgent private task need to finish it for now. I'm afraid I don't have enough time to handle this issue.

I open the issue for other members

**Comment by ThomasKranitsas** [comment] 2019-06-13 10:40
Contest https://www.topcoder.com/challenges/30092404 has been updated - it has been assigned to gauravseta.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2019-06-13 11:22
Some decisions on pending this, so kept it on hold.

**Comment by nithyaasworld** [comment] 2019-09-11 08:58
This is not reproducible now.

**Closed by nithyaasworld** 2019-09-11 08:58 UTC
Labels: On hold, P2, Performance

**Comment by crazyk07** [comment] 2019-09-11 09:11
Contest https://www.topcoder.com/challenges/30102008 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2019-09-11 09:12
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for crazyk via Topcoder X```
