### ISSUE TITLE
[$100] SSF - Requirements missing from my specs

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#2661] opened 2019-06-25 12:30 UTC
@ThomasKranitsas

URL - https://beta-community-app.topcoder.com/challenges

1. Point # 2 is not implemented from https://github.com/topcoder-platform/topcoder-react-lib/pull/71#issuecomment-501635184

2. console error continues to show, switch between the buckets

![image](https://user-images.githubusercontent.com/683231/60098288-c9402180-9772-11e9-842e-444241ef6387.png)

3. `View more challenges` button doesn't show up, please check this video https://www.youtube.com/watch?v=7Y8VTcvkhx8

**Comment by sushilshinde** [comment] 2019-06-25 12:37
@nithyaasworld FYI

**Comment by sushilshinde** [comment] 2019-06-30 10:54
@ThomasKranitsas updates?

**Comment by ThomasKranitsas** [comment] 2019-06-30 12:34
@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup. I was not able to reproduce **1** and **3** so you may only have to fix the 2nd requirement.

This is urgent! Do not pick this up if you can't fix it soon.

PR on `server_side_filtering` branch.

**Comment by ThomasKranitsas** [comment] 2019-06-30 12:39
[500]: Challenge for the updated issue 2661 is creating, rescheduling this event<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-06-30 12:41
[500]: Challenge for the updated issue 2661 is creating, rescheduling this event<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-06-30 12:42
Contest https://www.topcoder.com/challenges/30094655 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-06-30 12:43
Contest https://www.topcoder.com/challenges/30094655 has been updated - it has been assigned to gurmeetb.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-06-30 12:44
Contest https://www.topcoder.com/challenges/30094655 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by gurmeetb** [comment] 2019-06-30 13:59
@ThomasKranitsas I tried playing around with `View More Challenges` and not able to replicate either. I have raised PR for fix for **2**

**Comment by gurmeetb** [comment] 2019-07-01 13:02
@ThomasKranitsas @sushilshinde does this looks good now or we need some changes? Kindly flag.

**Comment by ThomasKranitsas** [comment] 2019-07-01 13:04
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30094655<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed** 2019-07-01 13:03 UTC
Labels: Challenge Listing, P1, Performance, tcx_Assigned, tcx_FixAccepted, tcx_ReadyForReview
