### ISSUE TITLE
[$100] Profile shows in tablet view by default

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#1150] opened 2018-08-09 16:26 UTC
When I load the page in a standard browser size, the left menu icons are collapsing to tablet view.  It should be expanded with the labels...

![image](https://user-images.githubusercontent.com/3812270/43912112-5672b400-9bcf-11e8-90b3-408ab7fa15e6.png)

**Comment by ajefts** [comment] 2018-08-09 16:26
![](https://github.trello.services/images/mini-trello-icon.png) [Topcoder-X for Bug Tickets](https://trello.com/c/nyRjqZic/51-topcoder-x-for-bug-tickets)

**Comment by ThomasKranitsas** [comment] 2018-08-10 17:43
The issue is that we're using the wrong breakpoints.

**Comment by ThomasKranitsas** [comment] 2018-08-11 17:03
Contest https://www.topcoder.com/challenges/30069265 has been created for this ticket.

**Comment by ThomasKranitsas** [comment] 2018-08-11 17:03
Contest https://www.topcoder.com/challenges/30069265 has been updated - the new changes has been updated for this ticket.

**Comment by ThomasKranitsas** [comment] 2018-08-11 17:04
Update the breakpoints based on the following requirements:
### Desktop
Anything from `1025px` and above

### Tablet
From `769px` to `1024px`

### Mobile
Anything bellow `768px`

**Comment by asadath1395** [comment] 2018-08-11 17:37
I would like to work on this one

**Comment by ThomasKranitsas** [comment] 2018-08-11 17:39
Contest https://www.topcoder.com/challenges/30069265 has been updated - it has been assigned to thomaskranitsas.

**Comment by ThomasKranitsas** [comment] 2018-08-11 17:39
@asadath1395 are you registered on this https://www.topcoder.com/challenges/30069264?tab=details challenge?
If not please register and follow the link from the challenge forum otherwise I can't add you to any ticket

**Comment by ThomasKranitsas** [comment] 2018-08-11 17:43
Contest https://www.topcoder.com/challenges/30069265 has been updated - it has been assigned to sadathanwar17.

**Comment by ThomasKranitsas** [comment] 2018-08-11 17:43
Ok, I've assigned this ticket to you.

**Comment by ThomasKranitsas** [comment] 2018-08-11 17:56
@asadath1395 please keep working on this ticket. Ignore the changes on the assignees. I'm doing some tests

**Comment by ThomasKranitsas** [comment] 2018-08-11 17:57
Contest https://www.topcoder.com/challenges/30069265 has been updated - it has been assigned to thomaskranitsas.

**Comment by ThomasKranitsas** [comment] 2018-08-11 17:57
Contest https://www.topcoder.com/challenges/30069265 has been updated - it has been assigned to sadathanwar17.

**Comment by ThomasKranitsas** [comment] 2018-08-11 18:01
Contest https://www.topcoder.com/challenges/30069265 has been updated - it has been assigned to thomaskranitsas.

**Comment by ThomasKranitsas** [comment] 2018-08-11 18:02
Contest https://www.topcoder.com/challenges/30069265 has been updated - it has been assigned to sadathanwar17.

**Comment by ThomasKranitsas** [comment] 2018-08-12 16:06
@asadath1395 just checking on this. It's been 22 hours since you started working on it. Note that you can only keep a ticket for 24h then you have to open it for pickup again.

**Comment by sadathanwar17** [comment] 2018-08-12 16:10
@ThomasKranitsas Little bit busy right now, so won't be able to complete this. Please open it for others to pick it up.

**Comment by ThomasKranitsas** [comment] 2018-08-12 16:11
@topcoder-platform/topcodercompetitors this is now open for pickup

**Comment by sandipanghos** [comment] 2018-08-12 16:11
@ThomasKranitsas  please assign me the ticket.

**Comment by ThomasKranitsas** [comment] 2018-08-12 16:12
Contest https://www.topcoder.com/challenges/30069265 has been updated - it has been assigned to sandipanghosh64.

**Comment by ThomasKranitsas** [comment] 2018-08-12 16:12
@sandipanghos sure

**Comment by sandipanghos** [comment] 2018-08-12 16:13
Thanks

**Comment by ThomasKranitsas** [comment] 2018-08-12 16:29
There are many ways to do it but what I recommend is:
- Fork the repo
- Clone your forked repo locally (eg `git clone https://github.com/ThomasKranitsas/community-app`
- Add our repo as `upstream` (eg `git remote add upstream https://github.com/topcoder-platform/community-app`)
- `git fetch upstream` (always do that before you create a new branch to get the latest code)
- Create a new branch `git checkout -b issue-<ticket number> upstream/new-develop`
- Make your changes.
- Push your changes.
- Create a pull request.

**Comment by ThomasKranitsas** [comment] 2018-08-12 20:25
@sandipanghos why do you need the backend code? We don't have a single code base for the backend. There are many microservices that have a separate code base.

The scope of this ticket is to fix the styles of all sub-pages of the settings page to update the breakpoints based on the requirements above. You also need to make sure the layout is not broken after your changes.

**Comment by sandipanghos** [comment] 2018-08-12 20:43
@ThomasKranitsas ok.

**Comment by ThomasKranitsas** [comment] 2018-08-13 15:05
@sandipanghos any update?

**Comment by sandipanghos** [comment] 2018-08-13 16:54
@ThomasKranitsas working on it .The labels are showing with image .
fixing the alignment of UI

**Comment by ThomasKranitsas** [comment] 2018-08-13 16:55
Ok, thanks for the update.

**Comment by ThomasKranitsas** [comment] 2018-08-14 08:02
@sandipanghos I'm afraid I'll have to remove you from this ticket as it's been way too long since you started.

**Comment by nauhil** [comment] 2018-08-14 08:04
Can I pick up this issue ?

**Comment by ThomasKranitsas** [comment] 2018-08-14 08:06
@nauhil sure! Can you please register on Topcoder X using this link https://x.topcoder.com/api/v1/github/teams/registration/887210ad-9ed5-4641-b0ff-12b1d8191d63-1533938364810

Otherwise I won't be able to assign you to the ticket and pay you

**Comment by ThomasKranitsas** [comment] 2018-08-14 08:07
Contest https://www.topcoder.com/challenges/30069265 has been updated - it has been assigned to nauhil.

**Comment by ThomasKranitsas** [comment] 2018-08-14 11:14
Payment failed: [500]: Failed to activate challenge. Detail: javax.ejb.EJBTransactionRolledbackException

**Closed** 2018-08-14 16:32 UTC
Labels: Fix accepted, Paid
