### ISSUE TITLE
[$50]Challenge terms not displayed for not logged in user

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4752] opened 2020-08-13 09:55 UTC
Challenge terms not displayed for not logged in user
example:
https://beta-community-app.topcoder.com/challenges/90dfc2ef-f79b-46be-9976-0520bc383fc6?tab=details
https://www.topcoder.com/challenges/30136673?tab=details
<img width="1440" alt="Screenshot 2020-08-13 at 3 23 31 PM" src="https://user-images.githubusercontent.com/58783823/90121055-20d78d00-dd79-11ea-85ae-a4ff66d18f61.png">

**Comment by crazyk07** [comment] 2020-08-24 09:41
Contest https://www.topcoder.com/challenges/30138276 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-08-24 09:42
Contest https://www.topcoder.com/challenges/30138276 has been updated - it has been assigned to Narekvar90.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-08-24 09:42
Contest https://www.topcoder.com/challenges/30138276 has been updated - cagdas001 has been unassigned.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by narekcat** [comment] 2020-08-24 09:43
@cagdas001 Thank you.

**Comment by narekcat** [comment] 2020-08-24 17:09
@SathyaJayabal @sushilshinde The problem is with getting Submitter `roleId`. To get Submitter `roleId` we need to make request to this url https://api.topcoder-dev.com/v5/resource-roles?name=Submitter&isActive=true, but it returns error 401, because when user is not logged in there is no token. How can I get Submitter `roleId` ?

**Comment by sushilshinde** [comment] 2020-08-27 11:38
@narekcat can you check on prod

**Comment by narekcat** [comment] 2020-08-27 11:40
@sushilshinde ok, I'll check.

**Comment by sushilshinde** [comment] 2020-08-27 11:50
@rootelement @Oanh-and-only-Oanh please help here

**Comment by luizrrodrigues** [comment] 2020-08-30 21:32
@narekcat API was updated, please do needed changes.

**Comment by narekcat** [comment] 2020-08-31 05:57
@luizrrodrigues Ok, thank you.

**Comment by narekcat** [comment] 2020-08-31 12:21
@SathyaJayabal @sushilshinde I have fixed this issue, please see pull request https://github.com/topcoder-platform/topcoder-react-lib/pull/237.

**Comment by SathyaJayabal** [comment] 2020-09-03 15:51
verified on staging
<img width="1440" alt="Screenshot 2020-09-03 at 9 19 32 PM" src="https://user-images.githubusercontent.com/58783823/92137831-482af280-ee2b-11ea-888a-0e115f28f607.png">
<img width="1440" alt="Screenshot 2020-09-03 at 9 19 35 PM" src="https://user-images.githubusercontent.com/58783823/92137863-537e1e00-ee2b-11ea-9bee-a17bc5116f76.png">

**Comment by SathyaJayabal** [comment] 2020-09-08 12:28
verified on staging(develop)
<img width="1440" alt="Screenshot 2020-09-08 at 5 34 10 PM" src="https://user-images.githubusercontent.com/58783823/92474486-8c3a4080-f1f9-11ea-9948-9911e0f02088.png">

**Comment by SathyaJayabal** [comment] 2020-09-08 14:08
verified on prod
<img width="1440" alt="Screenshot 2020-09-08 at 7 38 13 PM" src="https://user-images.githubusercontent.com/58783823/92487430-dc6dce80-f20a-11ea-8d92-1f645eb6576c.png">

**Comment by crazyk07** [comment] 2020-09-08 14:12
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30138276<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed** 2020-09-08 14:12 UTC
Labels: Beta Env, Challenge Details Screen, P3, Prod QA Pass, tcx_Assigned, tcx_FixAccepted, v5-integration-codefreeze, v5-intgration-sub-code
