### ISSUE TITLE
The title on submenu can't show immediately on mobile in the first time

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2440] opened 2019-06-07 18:07 UTC
### Reproduction Steps: ###

1. Open https://test-community-app.topcoder-dev.com/challenges
2. Login with account: dan_developer/dantopcoder123
2. Try to click on menu icon on the top left
3. Click on items on submenu and observe 

### Expected Result: ###
The title on submenu should show immediately on mobile.

### Actual Result: ###
The title on submenu can't show immediately on mobile in the first time.

### Screenshots or screencast: ###

See comment

### Browser Information: ###
Oppo F7, android 8.1
Google Chrome version latest on mobile

**Comment by HongHT** [comment] 2019-06-07 18:53
![7](https://user-images.githubusercontent.com/26895101/59126801-23c63900-8990-11e9-8050-d373599479ee.png)

**Comment by LieutenantRoger** [comment] 2020-01-11 08:07
@luizrrodrigues  

Could you reproduce this ? 
I tried on an `Honor 6x Phone` with Android `8.0.0`,  with Chrome version: `76.0.3809.111` but can't reproduce this.

**Comment by luizrrodrigues** [comment] 2020-01-11 11:26
@LieutenantRoger I'll re check and let you know

**Comment by LieutenantRoger** [comment] 2020-01-13 05:28
up

**Comment by luizrrodrigues** [comment] 2020-01-13 20:03
@LieutenantRoger Thanks for check.
Looks like this was fixed.

**Comment by nithyaasworld** [comment] 2020-01-21 13:42
Cannot reproduce in production too.

**Comment by luizrrodrigues** [comment] 2020-01-21 21:10
@nithyaasworld Please add QA Pass here

**Comment by SathyaJayabal** [comment] 2020-02-04 09:31
Closing this as it seems not reproducible

**Closed by SathyaJayabal** 2020-02-04 09:31 UTC
Labels: Can't Reproduce, Navigation, P3, UI
