### ISSUE TITLE
[$100] - NDA differences between design and development

### ISSUE THREAD

**Issue by Dara-K** [topcoder-platform/community-app#647] opened 2017-12-08 02:04 UTC
As we talked earlier - check attached image to see the differences marked

![nda_differences](https://user-images.githubusercontent.com/25185079/33747658-dd50073e-dbcc-11e7-899d-de021a59dcae.png)

**Comment by Dara-K** [comment] 2017-12-11 17:49
Please let me know when you fixed this :)

**Comment by Dara-K** [comment] 2017-12-16 13:47
Also the buttons should stay at the bottom of the window like in the design - user can scroll. @birdofpreyru

**Comment by imadx** [comment] 2018-01-07 08:51
What can I do to reproduce this page?

**Comment by birdofpreyru** [comment] 2018-01-07 15:21
@imadx 
Option #1: Try to register to an NDA protected challenge in dev environment: https://www.topcoder-dev.com/challenges/30050950/
Option #2: Follow these instructions to mock-up terms service to always see the terms when you are trying to register for a challenge via the locally launched app: https://github.com/topcoder-platform/community-app/blob/develop/docs/mocking-terms.md

**Comment by chongluo** [comment] 2018-01-07 16:02
Can you please specify the behavior of the button? Now it is gone if agree clicked and next button does not show. Do you want the next button show after agree clicked?

**Comment by birdofpreyru** [comment] 2018-01-07 16:34
@chongluo I might be wrong now, but I believe the `Next` button shows up only when you look at a term that you have agreed with some time before, in this case it just moves to the next term of the challenge or community. If you look at a term not agreed before you see `Agree` button instead, and after agreement is done it automatically moves you to the next term, if any, or to the operation protected by the terms.

**Comment by chongluo** [comment] 2018-01-07 16:40
Another question about the blue and green tab. Can you please explain the logic when and which color show be shown? I might be wrong but I am assuming when a term agreed and tab and the line after it become blue, the terms the user reading but not click agree is green and the line after it is gray, and the rest of the tabs and lines are gray. Can you please confirm that?

**Comment by birdofpreyru** [comment] 2018-01-07 16:46
I guess, the current logic should be correct, most probably no need to modify that. I think, green circle is always the currently displayed term, no matter agreed or not, blue circles and lines are the agreed terms, and gray ones are the not yet agreed ones.

**Comment by chongluo** [comment] 2018-01-07 16:59
Should I change the title Terms & Conditions of Use or just keep it?

**Comment by birdofpreyru** [comment] 2018-01-07 17:41
@chongluo Let's expose it via props, and use the title from design for the challenge page, while keeping the current title as the default value (we use terms component to also show terms for sub-communities).

**Comment by Dara-K** [comment] 2018-01-07 19:30
> I think, green circle is always the currently displayed term, no matter agreed or not, blue circles and lines are the agreed terms, and gray ones are the not yet agreed ones.

This is correct.

**Comment by birdofpreyru** [comment] 2018-01-09 23:03
@imadx I accept your PR for this, but some final fixes are necessary:
- Styling of *Acceptance of Terms and Conditions* is still different from what is told at the screenshot;
- Font size of the main terms text is 16px instead of 15px;

@Dara-K will also have a look at this and may ask for further corrections.

**Comment by Dara-K** [comment] 2018-01-10 11:58
@imadx 
Thanks for fixing this. Looks much better than the original. There are still some small issues I noticed. Check attached files.

@birdofpreyru : When I go back and forth between Appirio NDA and Standard Terms for Topcoder Competitions v2.1 and sometimes both or only one terms of the pages was disappearing.

![02_apprio_nda](https://user-images.githubusercontent.com/25185079/34771703-32ec104c-f60e-11e7-9ff2-af18ffb22b2d.png)
![03_content_dissapears](https://user-images.githubusercontent.com/25185079/34771705-3318fdc8-f60e-11e7-8f3c-2ef57b505773.png)
![01_tc_terms_and_conditions](https://user-images.githubusercontent.com/25185079/34771706-33391504-f60e-11e7-8dbf-709a94d47ae6.png)

**Comment by imadx** [comment] 2018-01-11 00:46
@Dara-K, @birdofpreyru added PR for these changes: https://github.com/topcoder-platform/community-app/pull/728

**Comment by birdofpreyru** [comment] 2018-01-11 12:49
@Dara-K update is ready for the review at www.topcoder-dev.com

**Comment by Dara-K** [comment] 2018-01-11 15:44
@imadx  @birdofpreyru Looking better, but we still have a couple of things to fix - note that I changed some padding values and the bottom part still looks cut+ there is no scrollbar, so right now I cannot see the bottom buttons.

Thanks!

**Comment by imadx** [comment] 2018-01-12 02:44
@Dara-K, The titles of the terms (_TopCoder_ -> _Topcoder_) come from the original data response... it should be changed
    
![image](https://user-images.githubusercontent.com/8768454/34857286-f0187522-f76f-11e7-8aad-748ae2e78f1b.png)

The buttons are not visible as this set of terms are set with some `view only` property.
From which browser is this screenshot taken from?

**Comment by Dara-K** [comment] 2018-01-12 12:22
I am using Firefox 57.0.4

Regarding the title, it's official we use Topcoder now. We had some variations in time like TopCoder or topcoder, but we now we settled with this. I remember Nick writing on Slack to use Topcoder everywhere we have to, to send a consistent message.

**Comment by birdofpreyru** [comment] 2018-01-13 13:43
@imadx I've merged in the last PR from you, and it still looks like there are a few differences from the last screenshot posted by Dara:
- The vertical spacing around the progress bar is 20px instead of 25px
- Topcoder is still written as TopCoder in some places. I got that it comes from API. Let's leverage it at the frontend side, though, just explicitely replacing TopCoder by Topcoder in those strings just before rendering them.
- I noted that when I open terms modal via the link in the challenge specs sidebar, the color scheme in of the progress bar, which acts as the term selector, is different: all circles are gray, and the current one is highlighted blue. The line is sometimes highlighted blue, sometimes not. Let's better use the same color scheme as when we agree to them: with the circle of the current term being green, and all agreed terms being blue, others - gray.

With this changes I'll be find to close this ticket, if @Dara-K does not have anything else to add.

**Comment by birdofpreyru** [comment] 2018-01-24 19:25
Hey @imadx, have decided not to bother with the final corrections requested above, or have I just occasionally lost related PR? :)

**Comment by ishan-madhusanka** [comment] 2018-01-26 06:59
I was not well for the past week... :) added a PR https://github.com/topcoder-platform/community-app/pull/754

**Comment by birdofpreyru** [comment] 2018-01-28 15:32
@imadx I got a msg from @Dara-K that she still sees issues on this page. As this Bug Bash had to be closed already a while ago, I suggest that I just accept it for 70% of the original prize, and we'll clean-up the remaining stuff some time later.

**Comment by imadx** [comment] 2018-01-29 05:24
@birdofpreyru Sure... that should be good... :+1:

**Closed** 2019-07-11 16:39 UTC

**Comment by ThomasKranitsas** [comment] 2019-07-11 16:42
Contest https://www.topcoder.com/challenges/30095598 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-07-11 16:42
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```
