### ISSUE TITLE
Dashboard shows HTML

### ISSUE THREAD

**Issue by codeMinter** [topcoder-platform/community-app#3222] opened 2019-08-16 06:21 UTC
**Describe the bug**
on Dashboard page when I close the banner of RODEO II, HTML is shown. 

**To Reproduce**
1. Go to 'https://www.topcoder.com/my-dashboard'
2. Click on 'Close of the RODEO II banner'
3. See error

**Expected behavior**
No HTML should be shown

**Screenshots**
<img width="1513" alt="DashboardShowsHTML" src="https://user-images.githubusercontent.com/14284629/63147555-62412b00-bfb3-11e9-865f-89e799bdd636.png">

**Comment by nithyaasworld** [comment] 2019-09-24 22:36
Closing this as this is no more an issue

**Comment by nithyaasworld** [comment] 2019-10-10 06:48
This issue is happening again.

CC: @codeMinter @sushilshinde @Oanh-and-only-Oanh @lakshmiathreya 


![image](https://user-images.githubusercontent.com/5114190/66545265-ed741280-eb57-11e9-80a0-78c11a92248d.png)

**Comment by nithyaasworld** [comment] 2019-11-06 12:10
Confirming that this is still an issue

**Comment by sandhiyakavi** [comment] 2020-04-06 05:00
The issue is not happening now.

![image](https://user-images.githubusercontent.com/55895538/78524442-99d63f00-77f1-11ea-9277-c32892552992.png)

cc: @SathyaJayabal

**Closed** 2020-04-06 07:06 UTC
Labels: P3, UX
