### ISSUE TITLE
If 'Machine Learning' skill is on the first column; it goes out of the section and part of the item is not visible

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1485] opened 2018-09-16 01:23 UTC
## Steps to Reproduce

1. Open the Application and Login as a valid user
2. Go to Settings > Profile > Skills
3. Add 20-30 skills (Machine Learning, Google App Engine etc..)
4. Get 'Machine Learning' displayed on the first column

## Actual Result(s)

- If 'Machine Learning' skill is on the first column; it goes out of the section and part of the item is not visible

## Expected Result(s)

- Must display the item fully

## Frequency

- 5/5

## Environment Details

- **Device(s):** Laptop
- **Resolution:** 1366 x 768
- **Operating System:** Windows 7 64bit
- **Browser(s):** IE11

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section

**Comment by sdgun** [comment] 2018-09-16 01:37
![2018-09-15_20-36-57](https://user-images.githubusercontent.com/4592712/45591991-21fea600-b927-11e8-826e-3b7292d701ab.png)

**Comment by ThomasKranitsas** [comment] 2018-09-20 17:42
duplicate of #1483

**Closed by ThomasKranitsas** 2018-09-20 17:42 UTC
