### ISSUE TITLE
[$1]Past challenges for Data Science track aren't showing up | URGENT

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#1992] opened 2019-03-01 15:16 UTC
![topcoder challenges 2019-03-01 20-45-54](https://user-images.githubusercontent.com/683231/53647205-0a13a800-3c63-11e9-8528-95813f399d3e.png)

**Comment by sushilshinde** [comment] 2019-03-01 15:17
![](https://github.trello.services/images/mini-trello-icon.png) [Past challenges for Data Science Track isn't showing up](https://trello.com/c/GXzwP8Oy/35-past-challenges-for-data-science-track-isnt-showing-up)

**Comment by sushilshinde** [comment] 2019-03-01 15:18
@topcoder-platform/topcodercompetitors this one is open for pickup

PR on https://github.com/topcoder-platform/community-app/tree/hot-fixes

**Comment by ThomasKranitsas** [comment] 2019-03-01 15:20
Contest https://www.topcoder.com/challenges/30085142 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-03-01 15:20
Contest https://www.topcoder.com/challenges/30085142 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-03-01 15:20
Contest https://www.topcoder.com/challenges/30085142 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-03-01 15:21
Contest https://www.topcoder.com/challenges/30085142 has been updated - it has been assigned to rashmi73.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sushilshinde** [comment] 2019-03-01 15:22
@rashmi73 it's urgent, please PR asap

**Comment by ThomasKranitsas** [comment] 2019-03-01 15:22
Contest https://www.topcoder.com/challenges/30085142 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by rashmi73** [comment] 2019-03-01 15:24
@sushilshinde yes

**Comment by rashmi73** [comment] 2019-03-01 22:47
@sushilshinde since a long time on this and came to conclusion after debugging it that it is working pefectly fine on hot-fixes bbranch.
also attaching screenshot
![datasciencepast1](https://user-images.githubusercontent.com/41687423/53670832-1a974300-3ca2-11e9-884e-869c824ea6fb.png)

**Comment by rashmi73** [comment] 2019-03-01 23:06
@sushilshinde also working perfectly on master branch too

**Comment by rashmi73** [comment] 2019-03-02 14:28
@sushilshinde any updates?

**Comment by sushilshinde** [comment] 2019-03-04 14:42
@rashmi73 it is working locally, you are right. I'm still testing.

**Comment by rashmi73** [comment] 2019-03-05 20:19
@sushilshinde all working well?

**Comment by ThomasKranitsas** [comment] 2019-03-07 15:28
Contest https://www.topcoder.com/challenges/30085142 has been updated - it has been assigned to thomaskranitsas.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by Oanh-and-only-Oanh** [comment] 2019-03-22 17:05
@ThomasKranitsas how's this going?

**Comment by ThomasKranitsas** [comment] 2019-03-22 17:09
It seems to be working on my end. I can't reproduce the issue

**Comment by Oanh-and-only-Oanh** [comment] 2019-03-22 17:13
looks like it got resolved. let's close this ticket then.

**Comment by ThomasKranitsas** [comment] 2019-03-22 17:14
Contest https://www.topcoder.com/challenges/30085142 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2019-03-22 17:15
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30085142<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed** 2019-03-22 17:14 UTC
Labels: Challenge Listing, Major, P1, tcx_Assigned, tcx_FixAccepted
