### ISSUE TITLE
 skills list cannot be loaded

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#932] opened 2018-06-08 20:50 UTC
### Reported URL ###
https://apps.topcoder-dev.com/forums/?module=Settings

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/settings/profile/

3. enter c++ for add a new skill

4. observe

### Expected Result ###
should load related skills list

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment] 2018-06-08 20:51
<img width="1181" alt="c" src="https://user-images.githubusercontent.com/4590317/41180389-b1a862c0-6ba0-11e8-84eb-01ab47fea953.png">

**Comment by winterflame** [comment] 2018-06-11 05:56
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Blocker

**Comment by ThomasKranitsas** [comment] 2018-06-14 12:04
duplicate of https://github.com/topcoder-platform/community-app/issues/893

**Closed by ThomasKranitsas** 2018-06-14 12:04 UTC
Labels: Blocker, PD - Member - Migration
