### ISSUE TITLE
[$75] Search by date filter

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/community-app#4984] opened 2020-09-22 05:41 UTC
The current implementation, returns all challenges that are active within the specified date ranges.
But the new implementation does not return these challenges. Not sure how the new search works, it does not even return challenges which have the start date with the specified date range.

Please compare results with prod.
<img width="1440" alt="Screenshot 2020-09-22 at 11 05 44 AM" src="https://user-images.githubusercontent.com/58783823/93847335-4df65400-fcc4-11ea-8556-39bfd21fa2f5.png">
<img width="1440" alt="Screenshot 2020-09-22 at 11 05 48 AM" src="https://user-images.githubusercontent.com/58783823/93847345-52bb0800-fcc4-11ea-8167-afed0e1b7c86.png">
<img width="1440" alt="Screenshot 2020-09-22 at 11 10 23 AM" src="https://user-images.githubusercontent.com/58783823/93847346-53ec3500-fcc4-11ea-9521-c3267d1ab815.png">
<img width="1440" alt="Screenshot 2020-09-22 at 11 10 30 AM" src="https://user-images.githubusercontent.com/58783823/93847347-5484cb80-fcc4-11ea-976d-d637b3d8b4dd.png">

**Comment by crazyk07** [comment] 2020-09-22 15:11
Contest https://www.topcoder.com/challenges/30143204 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by luizrrodrigues** [comment] 2020-09-22 15:11
@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup

Submit in 8 hours and PR to

https://github.com/topcoder-platform/community-app/tree/feature-refactor-challengelist
https://github.com/topcoder-platform/topcoder-react-lib/tree/feature-refactor-challengelist

run `npm run` test before PR

**Comment by crazyk07** [comment] 2020-09-23 12:36
Contest https://www.topcoder.com/challenges/30143204 has been updated - it has been assigned to cagdas001.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by cagdas001** [comment] 2020-09-23 12:58
@luizrrodrigues @SathyaJayabal can't reproduce. I shows same challenges with prod. Please check if it's still an issue

| Staging | Prod |
| ---- | ---- |
| ![chrome_2020-09-23_15-55-06](https://user-images.githubusercontent.com/28513447/94015399-790ca080-fdb5-11ea-8e09-58e7f6767443.png) | ![chrome_2020-09-23_15-55-24](https://user-images.githubusercontent.com/28513447/94015434-8590f900-fdb5-11ea-814e-2b22651b3363.png) |

**Comment by SathyaJayabal** [comment] 2020-09-23 14:04
@cagdas001 , please use test env, Staging is in use for another testing.

**Comment by cagdas001** [comment] 2020-09-23 14:08
> @cagdas001 , please use test env, Staging is in use for another testing.

What's the url of test env? I had checked the network tab with staging and it was calling the backend to apply filter, as expected

**Comment by luizrrodrigues** [comment] 2020-09-23 14:17
@cagdas001 https://test-community-app.topcoder-dev.com/

**Comment by cagdas001** [comment] 2020-09-23 14:27
I guess I've been banned: 
![2020-09-23_17-23-21](https://user-images.githubusercontent.com/28513447/94026131-f6d6a900-fdc1-11ea-9b86-6ba6c01fb330.png)

**Comment by luizrrodrigues** [comment] 2020-09-23 14:28
@cagdas001 Try access challenges: https://test-community-app.topcoder-dev.com/challenges

**Comment by cagdas001** [comment] 2020-09-23 14:28
> @cagdas001 Try access challenges: https://test-community-app.topcoder-dev.com/challenges

Yes I can access the test-community-app, but tried to access topcoder-dev.com to compare results

**Comment by luizrrodrigues** [comment] 2020-09-23 14:30
@cagdas001 Ah sorry, no able to access challenges directly? https://www.topcoder-dev.com/challenges

**Comment by cagdas001** [comment] 2020-09-23 14:32
> @cagdas001 Ah sorry, no able to access challenges directly? https://www.topcoder-dev.com/challenges

That wasnt working either, but looks like the issue has gone away now. Its working

**Comment by SathyaJayabal** [comment] 2020-09-23 14:44
@cagdas001 , you can use qa env for comparison
https://qa-community-app.topcoder-dev.com/challenges

**Comment by cagdas001** [comment] 2020-09-24 15:39
@luizrrodrigues 

1. First of all, since you're using the current prod env to compare/validate results, I need to note/clarify this. I'm not sure if even the current prod filtering is correct. The prod currently uses [these functions](https://github.com/topcoder-platform/topcoder-react-lib/blob/5fdf3e2b21f4918afe85904b94ffcf21cdefd417/src/utils/challenge/filter.js#L113-L127) from topcoder-react-lib, for date range filter: 

```js
function filterByStartDate(challenge, state) {
  if (!state.startDate) return true;
  const submissionPhase = (challenge.phases || []).filter(d => d.name === 'Submission')[0];
  const submissionEndDate = submissionPhase ? submissionPhase.scheduledEndDate
    : challenge.submissionEndDate;
  return moment(state.startDate).isBefore(submissionEndDate);
}


function filterByEndDate(challenge, state) {
  if (!state.endDate) return true;
  const registrationPhase = (challenge.phases || []).filter(d => d.name === 'Registration')[0];
  const registrationStartDate = registrationPhase ? registrationPhase.scheduledStartDate
    : challenge.registrationStartDate;
  return moment(state.endDate).isAfter(registrationStartDate);
}
```

For *end date* filter, it checks  if the *end date* is greater than the *registration start date*
For *start date* filter, it checks if the *submission end date* is greater than the *start date*.

Shouldn't it be the opposite?

For *end date* filter, it should check if the *end date* is greater than the *submission end date*
For *start date* filter, it should check if the *registration start date* is greater than the *start date*

2. The current API call for date range filter uses `?startDateStart=...&endDateEnd=...` query parameters. These mean `challenge.startDate` & `challenge.endDate` But, as far as I understand from the previous implementation (above), you're treating the registration start date as `startDate` and submission end date as `endDate`. (which makes sense from the point of view of an end user) So the new API call will use `?registrationStartDateStart=...&submissionEndDateEnd=...` query params instead.
3. As discussed before too, V5 Challenge API has some issues with these date fields. So getting the API fixed before proceeding in this one will be better otherwise QA team won't be able to validate the results as it will return wrong challenges

**Comment by SathyaJayabal** [comment] 2020-09-25 05:40
@cagdas001 the current implementation is correct. If you see, it will return all challenges that were active (and the submission phase was open) during the time period selected.


For end date filter, it checks if the end date is greater than the registration start date - we want to make sure the registration started before the selected end date

For start date filter, it checks if the submission end date is greater than the start date.- make sure submission phase has not ended before the selected start date

**Comment by SathyaJayabal** [comment] 2020-09-25 05:52
@cagdas001 , can you create an issue on the challenge api repo for the dates fields issue, with examples please?

https://github.com/topcoder-platform/challenge-api/issues

**Comment by luizrrodrigues** [comment] 2020-10-02 03:12
@cagdas001 I think this filter will works:

https://api.topcoder-dev.com/v5/challenges/?endDateStart=2020-10-01T00%3A00%3A00Z&startDateEnd=2020-10-03T00%3A00%3A00Z&status=Active&currentPhaseName=Submission

```
endDateStart: 2020-10-01T00:00:00Z
startDateEnd: 2020-10-03T00:00:00Z
status: Active
currentPhaseName: Submission
```

![image](https://user-images.githubusercontent.com/7029641/94884429-d5219580-0443-11eb-9abe-02fe78538ec5.png)

**Comment by cagdas001** [comment] 2020-10-02 10:28
@luizrrodrigues We should use `registrationStartDateStart` and `submissionEndDateEnd` instead of `startDate` and `endDate` See the 2. point of this comment https://github.com/topcoder-platform/community-app/issues/4984#issuecomment-698424334

So I'll implement  & fix this feature with the assumption of API is working properly?

**Comment by cagdas001** [comment] 2020-10-02 22:53
It will now call the endpoint with `?registrationStartDateStart={{DATE_PICKER_START_DATE}}&submissionEndDateEnd={{DATE_PICKER_END_DATE}}` query parameters. If you notice any defect (missing/wrong challenges etc), you first check the endpoint with these params it it's working properly

PR: #5039

**Comment by luizrrodrigues** [comment] 2020-10-07 04:49
@cagdas001 @cagdas001 I think we need to use `endDateStart` and `startDateEnd`

Example: Your solution, If select Oct 7 don't show any challenge.
![image](https://user-images.githubusercontent.com/7029641/95284614-fbc14100-0834-11eb-89a8-865303715092.png)

If we use `endDateStart` and `startDateEnd` will show running challenge:
![image](https://user-images.githubusercontent.com/7029641/95288433-a5f19680-083e-11eb-9f01-55c2148c7db1.png)

v4 (beta env):
![image](https://user-images.githubusercontent.com/7029641/95288486-c91c4600-083e-11eb-8d84-16907bfd2d95.png)

**Comment by luizrrodrigues** [comment] 2020-10-07 05:11
User cases:

1. If select range Jun 1 - Jun 30: I want to know what challenges was active in June

2. If select range Oct 11 - Oct 17: I want to know what challenge will be active in next week

cc @SathyaJayabal

**Comment by SathyaJayabal** [comment] 2020-10-07 05:15
@luizrrodrigues , you are correct. We can follow the prev v4 implementation I think.
https://github.com/topcoder-platform/community-app/issues/4984#issuecomment-698731469

**Comment by cagdas001** [comment] 2020-10-07 08:34
Your request (`startDate` & `endDate`) is not the V4 implementation. The current changes already follow the V4. Please read comments

**Comment by luizrrodrigues** [comment] 2020-10-07 11:56
@cagdas001 I read all comments. What I said here is, your implementation, search results no match with v4 results (please compare your solution with https://beta-community-app.topcoder.com/challenges

**Comment by cagdas001** [comment] 2020-10-07 12:34
Yeah because beta still uses frontend filters while you migrated sorting & filtering to backend with challenge listing revamp. That's what I meant by 

> If you notice any defect (missing/wrong challenges etc), you first check the endpoint with these params it it's working properly

Check the frontend filtering implementation above, you'll see API call uses correct field names

**Comment by luizrrodrigues** [comment] 2020-10-07 13:33
@cagdas001 Please check:
https://github.com/topcoder-platform/community-app/compare/listing-develop-sync...issue-4984?expand=1

**Comment by cagdas001** [comment] 2020-10-08 00:28
Updated the PR as per the discussion with @luizrrodrigues on Slack

**Comment by luizrrodrigues** [comment] 2020-10-08 02:38
@SathyaJayabal Ping me on Slack before QA this one.

**Comment by SathyaJayabal** [comment] 2020-10-08 04:38
verified on staging.
Search results return all challenges that were active within the selected time  period.
<img width="1440" alt="Screenshot 2020-10-08 at 9 54 14 AM" src="https://user-images.githubusercontent.com/58783823/95415542-2b17a100-094e-11eb-8ee9-81087f6808fd.png">

**Comment by luizrrodrigues** [comment] 2020-10-09 07:59
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for luizrrodrigues via Topcoder X```

**Comment by luizrrodrigues** [comment] 2020-10-09 08:00
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30143204<br/><br/>```This is an automated message for luizrrodrigues via Topcoder X```

**Closed** 2020-10-09 08:00 UTC
Labels: Must-fix-before-listing-release, P1, QA Pass in Staging, listing:re-implementation, tcx_Assigned, tcx_FixAccepted
