### ISSUE TITLE
[$30] Member's with special characters in their handle unable to register to any challenge

### ISSUE THREAD

**Issue by shivam-51** [topcoder-platform/community-app#4787] opened 2020-08-20 05:40 UTC
**Describe the bug**
On clicking on Register i get an error message saying "ERROR: Failed to register for challenge"

**To Reproduce**
1. Go to https://www.topcoder.com/challenges/c2a1465d-78cb-42b8-8f88-3d1ae386d3c5?tab=details
2. Click on Register

**Expected behavior**
Getting registered for the challenge without any error

**Screenshots**
![qq](https://user-images.githubusercontent.com/47945055/90720843-0e0f0c00-e2d5-11ea-885a-eb54e06e5006.png)

**Desktop (please complete the following information):**
 - OS: Linux 18.04
 - Browser chrome

**Additional context**
Attached chrome log
[log.txt](https://github.com/topcoder-platform/community-app/files/5100887/log.txt)

**Comment by Oanh-and-only-Oanh** [comment] 2020-08-20 05:43
@lakshmiathreya fyi

**Comment by lakshmiathreya** [comment] 2020-08-20 10:19
@shivam-51 I was able to register successfully with this challenge. Can you try again and let me know.

**Comment by lakshmiathreya** [comment] 2020-08-20 14:58
[screencast 2020-08-20 08-54-08 (1).mp4.zip](https://github.com/topcoder-platform/community-app/files/5103784/screencast.2020-08-20.08-54-08.1.mp4.zip)

**Comment by lakshmiathreya** [comment] 2020-08-20 14:58
cc @Oanh-and-only-Oanh

**Comment by sushilshinde** [comment] 2020-08-20 15:29
@shivam-51 can you share network tab video with actuall API response payload message.

**Comment by shivam-51** [comment] 2020-08-20 15:39
@sushilshinde I was registered for the challenge from back-end. I tried to Unregister and the problem came again.

[SC.mp4.zip](https://github.com/topcoder-platform/community-app/files/5104032/SC.mp4.zip)

**Comment by sushilshinde** [comment] 2020-08-20 15:43
@shivam-51 can you find me Topcoder Community Slack

My handle : Sushil

**Comment by shivam-51** [comment] 2020-08-20 15:47
> @shivam-51 can you find me on Topcoder Community Slack
> 
> My handle : Sushil

Sure

**Comment by mtwomey** [comment] 2020-08-20 16:08
@shivam-51 - if you are willing, could you please grab the specific request that's erroring in the Chrome debugger and the response? That would really help us:

![image](https://user-images.githubusercontent.com/7715262/90796767-5af2e280-e2d5-11ea-96d9-55bd516c1ea7.png)

![image](https://user-images.githubusercontent.com/7715262/90796829-6c3bef00-e2d5-11ea-95be-dd0fe590531b.png)

**Comment by shivam-51** [comment] 2020-08-21 05:15
My TC handle is shivam{}
![Screenshot from 2020-08-21 10-44-02](https://user-images.githubusercontent.com/47945055/90854723-5bee4780-e39b-11ea-947e-928c57cf69a0.png)

**Comment by sushilshinde** [comment] 2020-08-21 05:28
@mtwomey @rootelement @Oanh-and-only-Oanh @ThomasKranitsas  I had a call with  @shivam-51 this morning. 

The Registration request is passing the auth token properly but he sees the message of insufficient rights.

**Comment by Oanh-and-only-Oanh** [comment] 2020-08-26 18:55
@sushil, can you give update on this issue. Another member is reporting the same https://github.com/topcoder-platform/community-app/issues/4815

**Comment by sushilshinde** [comment] 2020-08-27 11:54
> @sushil, can you give update on this issue. Another member is reporting the same #4815

It is API issue assigned to James and Thomas

**Comment by rootelement** [comment] 2020-08-27 23:45
I believe this is related to the fix made for
https://github.com/topcoder-platform/community-app/issues/4800

Not positive. Please test again. I'm still testing.

**Comment by SathyaJayabal** [comment] 2020-08-28 04:12
@shivam-51 @arnandosimanjuntak , can you please check if you are able to register to challenges?

**Comment by sushil** [comment] 2020-08-28 09:58
Folks. Please stop using @sushil handle here. Its sending me notifications, and not the intended individual. 

<img width="976" alt="handle" src="https://user-images.githubusercontent.com/108484/91548493-707a9480-e8f3-11ea-8d79-d40f75b71a17.png">

**Comment by arnandosimanjuntak** [comment] 2020-08-28 13:14
@SathyaJayabal I have tried it and clear my browser cached, but still can't register and getting the same error message.

![image](https://user-images.githubusercontent.com/30616976/91564506-eec64d80-e96a-11ea-9a3c-024508ad77c6.png)

**Comment by SathyaJayabal** [comment] 2020-08-28 13:18
@arnandosimanjuntak thanks.
@rootelement , looks like this issue is not fixed by #4800

**Comment by SathyaJayabal** [comment] 2020-09-01 13:47
@arnandosimanjuntak , what is your topcoder handle?

**Comment by arnandosimanjuntak** [comment] 2020-09-01 20:27
@SathyaJayabal My handle is ndondo_

**Comment by SathyaJayabal** [comment] 2020-09-02 03:06
@arnandosimanjuntak , thank you. We are still working on this issue and hope to resolve it soon.

**Comment by SathyaJayabal** [comment] 2020-09-02 03:18
@rootelement , reproduced this issue with new test user
picachui_/appirio123
I think the issue is with the special character in the handle `picachui_`
<img width="1440" alt="Screenshot 2020-09-02 at 8 47 38 AM" src="https://user-images.githubusercontent.com/58783823/91928195-0bf77500-ecf9-11ea-8405-dc164dc54509.png">

**Comment by arnandosimanjuntak** [comment] 2020-09-03 03:24
@SathyaJayabal  Does the issue really come from using the special character in the handle?

If yes - I don't mind removing the special character from my handle if it can be a solution and prevent I facing this issue again in the future. I also noticed that the other members who didn't use the special character in their handle didn't face this issue.

**Comment by SathyaJayabal** [comment] 2020-09-03 04:08
@arnandosimanjuntak , yes, it is because of the special character in the handle. We will try  and fix this issue so that you can continue using your handle.

**Comment by tmalbonph** [comment] 2020-09-03 04:18
@SathyaJayabal I think this is a DNS issue - it happen to me all the time because I am getting the IP address of most of the topcoder IP address and save it into my /etc/hosts via a script. I rerun that script to update the IP address.

**Comment by SathyaJayabal** [comment] 2020-09-03 04:27
@tmalbonph , thanks. Will ask the dev to look into it.

**Comment by luizrrodrigues** [comment] 2020-09-04 20:56
@SathyaJayabal Use `encodeURI(memberHandle)` before call API works, like @rootelement said in Slack.

I'll check if need changed in more calls and then push to QA.

**Comment by crazyk07** [comment] 2020-09-05 01:05
Contest https://www.topcoder.com/challenges/30140635 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-09-05 01:05
Contest https://www.topcoder.com/challenges/30140635 has been updated - it has been assigned to luizrrodrigues.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by SathyaJayabal** [comment] 2020-09-07 08:35
@luizrrodrigues , still see the issue
<img width="1440" alt="Screenshot 2020-09-07 at 2 04 58 PM" src="https://user-images.githubusercontent.com/58783823/92366757-30958780-f113-11ea-8d42-175dc0fd2c74.png">

user:picachui_/appirio123

**Comment by luizrrodrigues** [comment] 2020-09-07 09:02
Registration allow these special characters: ` - _ . { } [ ] `

I'm was using `encodeURIComponent()`, This function encodes special characters, with the exception of: `* @ - _ + . /`

@rootelement I think API need accept characters not encoded by `encodeURIComponent()`, let me know your thoughts.

**Comment by rootelement** [comment] 2020-09-11 16:27
Open here: https://github.com/topcoder-platform/challenge-api/issues/289

**Comment by luizrrodrigues** [comment] 2020-09-11 16:31
Thanks @rootelement

**Comment by ThomasKranitsas** [comment] 2020-09-14 17:27
@rootelement @sushilshinde @luizrrodrigues @Oanh-and-only-Oanh  I don't see how this is an API issue.

I created a user on dev with the username `thomas{}` and I tried to make the following:

```
curl --location --request POST 'http://api.topcoder-dev.com/v5/resources' \
--header 'Authorization: Bearer <token>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "challengeId": "90b846b6-76d8-4985-b549-0da591991b40",
    "memberHandle": "thomas{}",
    "roleId": "732339e7-8e30-49d7-9198-cccf9451e221"
}'
```

and it worked just fine.
It even worked using the encoded version of the handle (`thomas%7B%7D`).

<img width="1105" alt="Screenshot 2020-09-14 at 7 05 28 PM" src="https://user-images.githubusercontent.com/4612921/93118182-8eecd800-f6c8-11ea-99d2-755a050c0fcc.png">

Please share the cURL of the request you're trying to make and it's failing so we can debug and resolve this if it's an actual issue otherwise this seems to be an invalid request issue and not an issue with the API itself.

**Comment by luizrrodrigues** [comment] 2020-09-14 17:32
@ThomasKranitsas special character like  `{}` was fixed with https://github.com/topcoder-platform/topcoder-react-lib/pull/246

Put `encodeURIComponent()` don't encode `- _ . { } [ ]`

If you try register with `picachui_` will fail.

**Comment by ThomasKranitsas** [comment] 2020-09-14 17:34
Nope. `picachui_` worked just fine.
<img width="1110" alt="Screenshot 2020-09-14 at 8 34 11 PM" src="https://user-images.githubusercontent.com/4612921/93118926-ac6e7180-f6c9-11ea-8990-e5c181f0d03c.png">

**Comment by luizrrodrigues** [comment] 2020-09-14 17:40
@ThomasKranitsas I think this working because you was using m2m token right? 

Can you try using member token?

![image](https://user-images.githubusercontent.com/7029641/93119399-1ff78b00-f698-11ea-814b-b1fc6502b815.png)

![image](https://user-images.githubusercontent.com/7029641/93119415-271e9900-f698-11ea-9e41-3f1710e5e9d0.png)

**Comment by ThomasKranitsas** [comment] 2020-09-14 18:15
@luizrrodrigues I was even able to register on a challenge using my `thomas{}` account just fine.

<img width="1568" alt="Screenshot 2020-09-14 at 9 09 47 PM" src="https://user-images.githubusercontent.com/4612921/93122196-c3fc2900-f6ce-11ea-9683-526606b2d5f4.png">

The error you're seeing is only possible to be thrown when you're trying to create a resource for another member and you don't have full access on the challenge or you're not an admin/m2m.

@rootelement that means that the userId from the decoded token does not match the ID we have either in our dynamo mapping or the one that's coming from the V3 API.

**Comment by luizrrodrigues** [comment] 2020-09-14 19:19
@ThomasKranitsas please try with 'picachui_' (check credentials above) or create a new user with _ in name

**Comment by cagdas001** [comment] 2020-09-14 19:42
@ThomasKranitsas @luizrrodrigues at this line: https://github.com/topcoder-platform/resources-api/blob/dd4044c41f154c5afb4e75ed33c4ffc77258550a/src/common/helper.js#L168

_.lowerCase ignores such characters like `_-` so you'll get `testusername` when you use `_.lowerCase("testusername_")` Ref: https://lodash.com/docs/4.17.15#lowerCase

If you use `_.toLower` I think the issue will be resolved

**Comment by ThomasKranitsas** [comment] 2020-09-14 19:49
@cagdas001 you're right. Indeed, I added some logging and tested on dev with the account `thomas_` and seems like it's fetching the ID for `thomas` instead of `thomas_`. I replaced `lowerCase` with `toLower` and pending deployment. This should be fixed shortly.

**Comment by ThomasKranitsas** [comment] 2020-09-14 19:51
Fixed and verified on dev.
cc @rootelement

**Comment by luizrrodrigues** [comment] 2020-09-14 20:11
Thanks @cagdas001 @ThomasKranitsas

**Comment by luizrrodrigues** [comment] 2020-09-14 20:15
@SathyaJayabal @lakshmiathreya please run QA in Dev.

https://github.com/topcoder-platform/challenge-api/issues/289

**Comment by SathyaJayabal** [comment] 2020-09-15 02:57
verified on dev
Able to register with "picachui_"

**Comment by SathyaJayabal** [comment] 2020-09-15 05:48
verified on prod.
<img width="1440" alt="Screenshot 2020-09-15 at 11 15 38 AM" src="https://user-images.githubusercontent.com/58783823/93170412-d3b65480-f744-11ea-987e-bdeab55d38d2.png">
@arnandosimanjuntak @istkz, you should be able to register to challenges now.

**Comment by crazyk07** [comment] 2020-09-15 05:49
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-09-15 05:52
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30140635<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed** 2020-09-15 05:51 UTC
Labels: P1, Prod Env, QA Pass, V5-Challenge-API-Integration, tcx_Assigned, tcx_FixAccepted, v5-intgration-sub-code, waiting-for-api-fix

**Comment by arnandosimanjuntak** [comment] 2020-09-16 08:25
@SathyaJayabal It works! Thank you guys for fixed this issue
