### ISSUE TITLE
Dark Mode disappears on switching the orientation

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/community-app#2594] opened 2019-06-09 06:59 UTC
**Describe the bug**
Dark Mode should be consistent across the pages in any orientation for mobile users.

**To Reproduce**
1. Open the test URL and log in
2. Click on Work
3. Click on Community
4. Observe the Menu path which shows in Dark Mode
5. Switch the orientation of your mobile to Landscape view.
6. Observe the Menu path under Community. It is in Light Mode.

**Expected behavior**

**Screenshots**
Portrait
![20190609_085337](https://user-images.githubusercontent.com/51492004/59155977-4b062e80-8a94-11e9-834e-c456d28cd4e3.jpg)

Landscape
![20190609_085354](https://user-images.githubusercontent.com/51492004/59155979-4fcae280-8a94-11e9-91d9-a712ff2cf491.jpg)

**Smartphone:**
 - Device: Samsung 
 - OS: Android 8.1.0
 - Browser : Chrome 
 - Version : 74.0.3729.157

**Comment by nithyaasworld** [comment] 2019-06-10 18:27
duplicate of https://github.com/topcoder-platform/community-app/issues/2592

**Closed by nithyaasworld** 2019-06-10 18:27 UTC
Labels: Bug Hunt, Functional, Navigation, P2

**Comment by satkanhub** [comment] 2019-06-11 08:25
@nithyaasworld I have checked the duplicate ticket. The issue in 2592 is different to the one I highlighted here. Dark mode is disappearing while changing the view on mobile. This issue is not highlighted in 2592. Could you please check and reopen.

**Comment by nithyaasworld** [comment] 2019-06-12 08:48
Application is set to only Light mode. So displaying dark mode in mobile is incorrect, which would be addressed in #2592
