### ISSUE TITLE
[$50] Community options Turned OFF again when user; turn ON the next item while the popup is there

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/community-app#1378] opened 2018-09-14 01:08 UTC
## Steps to Reproduce

1. Open the Application and Login as a valid user
2. Go to Settings > Profile > Community
3. Turn OFF both the items and wait sometime
4. Now Turn On one item
5. When the popup is displayed; turn On the other one and observe
6. Repeat step 4-5 few times

## Actual Result(s)

- Community options Turned OFF again when user; turn ON the next item while the popup is there

## Expected Result(s)

- Must turn ON when user tap on it

## Frequency

- 5/5

## Environment Details

- **Device(s):** iPad Air 2
- **Operating System:** iOS 11.4.1
- **Size:** 9.7 inches (~71.6% screen-to-body ratio)
- **Resolution:** 1536 x 2048 pixels (~264 ppi pixel density)
- **Browser(s):** Safari 11

## Image(s)/Video(s)/Console Log/Crash Log

> If attachment(s) is/are not here, Please check the comments section 

## Ref:

@ThomasKranitsas

**Comment by sdgun** [comment] 2018-09-14 14:43
In Desktop also

https://www.screencast.com/t/uVd5x2Xq

**Comment by ThomasKranitsas** [comment] 2018-10-19 17:20
Contest https://www.topcoder.com/challenges/30072958 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-10-19 17:20
Contest https://www.topcoder.com/challenges/30072958 has been updated - the new changes has been updated for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment] 2018-10-19 17:22
@topcoder-platform/topcodercompetitors this is open for pickup

**Comment by gets0ul** [comment] 2018-10-19 21:36
@ThomasKranitsas Is this still valid? Are you able to reproduce it?

**Comment by ThomasKranitsas** [comment] 2018-10-19 21:55
Yes, I was able to reproduce it today. I’ll attach a screen recording as soon as I can.

**Comment by gets0ul** [comment] 2018-10-19 21:59
Thanks

**Comment by gets0ul** [comment] 2018-10-20 18:51
I'm unable to reproduce it so I'm releasing this back to open.

**Comment by ThomasKranitsas** [comment] 2018-10-20 18:54
Contest https://www.topcoder.com/challenges/30072958 has been updated - it has been assigned to daga_sumit.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by sumitdaga** [comment] 2018-10-21 07:40
@ThomasKranitsas 
i can't see any popup as of now when user toggles on any community!

**Comment by ThomasKranitsas** [comment] 2018-10-21 08:38
Contest https://www.topcoder.com/challenges/30072958 has been updated - it has been assigned to gurmeetb.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by gurmeetb** [comment] 2018-10-21 08:39
@ThomasKranitsas let me give a shot and update in few hrs

**Comment by gurmeetb** [comment] 2018-10-21 14:48
@ThomasKranitsas I see the problem. It is all because we are delaying the click handler by 1000 ms, so what happens is when we first switch off first one, and then by the time we do second one, the control has reached back componentWillReceiveProps(), which refreshes it. 

I did a test with removing the delay and it worked fine. Tried several times - didn't see issue then. 

But before I push the fix with disabling delay in update, I wanted to understand what was the idea behind setting a delay of 1000 ms or was it mistakenly done by the developer ?

**Comment by ThomasKranitsas** [comment] 2018-10-21 15:10
@gurmeetb if removing the delay doesn't affect anything, then this approach is acceptable.

I don't recall right now why we added that.

**Comment by ThomasKranitsas** [comment] 2018-10-21 15:20
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30072958<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Closed** 2018-10-21 15:19 UTC
Labels: Minor, New Settings Page, tcx_Assigned, tcx_FixAccepted, tcx_ReadyForReview
