### ISSUE TITLE
ADD IMAGE VALIDATION - PD - Member - Migration - MINOR

### ISSUE THREAD

**Issue by psharneja** [topcoder-platform/community-app#1023] opened 2018-06-10 18:48 UTC
@ThomasKranitsas 

ADD IMAGE in user profile is allowing any kind of file to be uploaded.

**Comment by ThomasKranitsas** [comment] 2018-06-13 22:09
duplicate of https://github.com/topcoder-platform/community-app/issues/1005

**Closed by ThomasKranitsas** 2018-06-13 22:09 UTC
Labels: Minor, PD - Member - Migration
