### ISSUE TITLE
Community Nav and Site Structure

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/community-app#3336] opened 2019-09-26 16:26 UTC
Prototype: <https://tc-unified-nav.herokuapp.com/light>

<p></p>

Refactored community navigation structure to improve the community user experience and better leverage a lot of the content that we have, but it's easy to find.  This will be combined with a restructure of the overall nav that brings our website, customer, and member experience together in terms of the overall framework of the nav.

<p></p>

<https://docs.google.com/spreadsheets/d/1zihwe7fDfB1s8LaSd-dH0I_kAZ2FsR9yBAzb5rKr10o/edit?ts=5bcde79f>

<p></p>

Some initial designs:  <https://marvelapp.com/5210jd8/screen/49556954>

<p></p>

---

**User story:** As a user, I want to be able to select a side of the Topcoder platform (Business vs Work) to explore so I can access relevant content.

<p></p>

The navigation view is based on the primary profile. 

## **Acceptance Criteria**

**Scenario #1**: navigating Topcoder.com as visitor (logged out experience)

**Given**: I am not signed in (logged out)

**When**: I log into Topcoder.com

**Then:** Display the Business top bar navigation below

<p></p>

![](https://productboard-files.s3.amazonaws.com/production/attachments/92774fdffc949d14593e9d6c149f863fdba942a987827f293cc2e8dfff43fe3e/image.png)

**Scenario #2**: switching to Work view on Topcoder.com as visitor (logged out experience)

**Given**: I am not signed in (logged out)

**When**: I select "Work" (it's currently labelled as "Community" but will change to "Work")

**Then**: Display the Work top bar navigation below

<p></p>

![](https://productboard-files.s3.amazonaws.com/production/attachments/6b7566be017254eab459e1363c338a8b41b762e87239f24110ba7a2227d07d60/image.png)

<p></p>

**Scenario #3:** Login as Member

**Given**: I am not signed in (logged out)

**When**: I log into Topcoder.com

**If:** I am a community member (competitor),

**Then**: Display community logged-in state and hide the “BUSINESS” portion. See top bar navigation below.

<p></p>

![](https://productboard-files.s3.amazonaws.com/production/attachments/40b8a31268b9da308cb59c3b132f4933dcc62912212a9ad213376e7c755ac48f/image.png)

<p></p>

<p></p>

**Login as Business**

**Given**: I am not signed in (logged out)

**When**: I login Topcoder.com

**If:** User is a business customer (Business),

**Then**: Display the Connect link and hide the “COMMUNITY/WORK” portion of the navigation. See top bar navigation below.

<p></p>

![](https://productboard-files.s3.amazonaws.com/production/attachments/729c44fad05b1facd952c3284048fbd6e79f6bc2d80cc4078d67faa298775a3c/image.png)

<p></p>

**Switch between Business and Work views**

**Given**: I am a registered user with login credentials

**When**: I login Topcoder.com

**If:** I have access to both Work and Business sides (such as a role of copilots and admins), 

**Then**: the user drop-down menu would provide a convenient “context switch”. See below.

<p></p>

![](https://productboard-files.s3.amazonaws.com/production/attachments/c0c4ca4687bbf93a99cf3af85586fb26f6c7da5b71bc5bdb5197fb89d3467e19/image.png)

**Mobile Navigation**

<https://marvelapp.com/1dgiejg6/screen/54473669>

<p></p>

<p></p>

---

**NOTES**:

The structure of the navigation would change and user flows would be formalized later, and implemented by different systems. The mechanics of the navigation is represented in this prototype (click around to see how it works): <https://marvelapp.com/f9b88ee>

**Comment by ajefts** [comment] 2019-09-26 16:26
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1302965

**Comment by Oanh-and-only-Oanh** [comment] 2019-11-04 15:52
Reference ticket https://github.com/topcoder-platform/community-app/issues/3422

**Comment by lakshmiathreya** [comment] 2019-11-07 13:35
@nithyaasworld for your reference ...

**Comment by lakshmiathreya** [comment] 2019-12-16 08:11
cc @picachui

**Comment by luizrrodrigues** [comment] 2020-01-17 17:33
Duplicate of #3422

**Closed** 2020-01-17 17:33 UTC
Labels: Beta Env, New feature, QA Pass
