### ISSUE TITLE
should display successful challenges

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/community-app#982] opened 2018-06-09 02:42 UTC
### Reported URL ###
https://www.topcoder-dev.com/members/standlove/details/?track=DEVELOP&subTrack=ARCHITECTURE&tab=challenges

### Reproduction Steps ###

1. login as pshah_manager

2. open https://www.topcoder-dev.com/members/standlove/details/?track=DEVELOP&subTrack=ARCHITECTURE&tab=challenges

3. observe

### Expected Result ###
Should display successful challenges.

### Actual Result ###

See screenshot

### Screenshots ###
See comment section

### Issue Information ###

Frequency: *Always*

Device: *Mac Book Pro*

OS: *macOS High Sierra Version 10.13.4 (17E199)*

Browser: *Firefox 60.0.1 (64-bit)*

**Comment by winterflame** [comment] 2018-06-09 02:43
<img width="1407" alt="arc" src="https://user-images.githubusercontent.com/4590317/41186919-e6fb3818-6bd1-11e8-8463-0c1978c2f63b.png">

**Comment by winterflame** [comment] 2018-06-11 06:04
@ThomasKranitsas  Labels for this issue:
PD - Member - Migration
Blocker

**Comment by ThomasKranitsas** [comment] 2018-06-13 22:18
Duplicate of #987 the challenges tab is not implemented so it won't show up for any track/subTrack

**Closed by ThomasKranitsas** 2018-06-13 22:18 UTC
