### ISSUE TITLE
[$50]Member Search doesnt return results 

### ISSUE THREAD

**Issue by lakshmiathreya** [topcoder-platform/community-app#4414] opened 2020-05-25 11:29 UTC
Go to https://test-community-app.topcoder-dev.com/members/search/?q=cori_copilot - this returns no results although this user has Info available. 
Search works correctly for the same user in Dev (v4) environment. 
Please see screenshots - 
<img width="1674" alt="Screenshot 2020-05-25 at 4 53 28 PM" src="https://user-images.githubusercontent.com/51733042/82809158-14921100-9ea9-11ea-971e-a295ac5f3bdd.png">
<img width="1667" alt="Screenshot 2020-05-25 at 4 53 12 PM" src="https://user-images.githubusercontent.com/51733042/82809179-1eb40f80-9ea9-11ea-9d26-ff6541c08976.png">

**Comment by SathyaJayabal** [comment] 2020-05-25 13:19
@lakshmiathreya , i too see the issue, but seems to happen in both  the V4 and V5 environments occasionally. I sometimes get the error "Could not determine if search term is a tag"

<img width="1440" alt="Screenshot 2020-05-25 at 6 47 19 PM" src="https://user-images.githubusercontent.com/58783823/82816195-4fe80c00-9eb8-11ea-972d-fa578b65c21b.png">

<img width="1440" alt="Screenshot 2020-05-25 at 6 45 22 PM" src="https://user-images.githubusercontent.com/58783823/82816169-45c60d80-9eb8-11ea-81a1-7196416b9359.png">

<img width="1440" alt="Screenshot 2020-05-25 at 6 45 54 PM" src="https://user-images.githubusercontent.com/58783823/82816181-49f22b00-9eb8-11ea-8c06-12bdd83887f6.png">

<img width="1440" alt="Screenshot 2020-05-25 at 6 47 16 PM" src="https://user-images.githubusercontent.com/58783823/82816189-4ced1b80-9eb8-11ea-82a7-9f51d9231ee2.png">

<img width="1440" alt="Screenshot 2020-05-25 at 6 45 14 PM" src="https://user-images.githubusercontent.com/58783823/82816131-38108800-9eb8-11ea-8b8c-3a39ee4481a4.png">

**Comment by sushilshinde** [comment] 2020-05-26 11:23
@topcoder-platform/topcodercompetitors @topcoder-platform/tcxcommunity this is open for pickup

PR to

https://github.com/topcoder-platform/community-app/tree/integration-v5-challenge-api
https://github.com/topcoder-platform/topcoder-react-lib/tree/integration-v5-challenge-api

**Comment by crazyk07** [comment] 2020-05-26 11:25
Contest https://www.topcoder.com/challenges/30126714 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-05-26 11:49
Contest https://www.topcoder.com/challenges/30126714 has been updated - it has been assigned to Narekvar90.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by narekcat** [comment] 2020-05-26 13:19
@lakshmiathreya @SathyaJayabal @sushilshinde - The problem is with URL. When you go to https://test-community-app.topcoder-dev.com/members/search/?q=cori_copilot, you land to member page with name "search" and part of URL `?q=cori_copilot` is ignored. But when you go to https://test-community-app.topcoder-dev.com/search/members/?q=cori_copilot, you land to search result page. There are user with name "search"
![search_member_issue](https://user-images.githubusercontent.com/11549629/82905270-b5013780-9f74-11ea-80fb-f1ca4ed638a0.png)

I think here is no issue, you just need to use `search/members?q=cori_copilot` for searching user with handle `cori_copilot` and use `members/search` or `members/cori_copilot` for opening `search` or `cori_copilot` user page.

**Comment by sushilshinde** [comment] 2020-05-27 06:57
@SathyaJayabal @lakshmiathreya 

https://qa-community-app.topcoder-dev.com/members/search/?q=cori_copilot

this is not also working, which has a current develop branch

**Comment by SathyaJayabal** [comment] 2020-05-27 07:34
@lakshmiathreya @sushilshinde , the  url used here is incorrect
https://qa-community-app.topcoder-dev.com/members/search/?q=cori_copilot or
https://test-community-app.topcoder-dev.com/members/search/?q=cori_copilot

the correct url is
https://test-community-app.topcoder-dev.com/search/members?q=cori_copilot
https://qa-community-app.topcoder-dev.com/search/members?q=cori_copilot

Closing this as it works as expected

**Comment by crazyk07** [comment] 2020-05-27 07:34
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by sushilshinde** [comment] 2020-05-27 08:15
@narekcat is it possible to fix url on frontend?

**Comment by crazyk07** [comment] 2020-05-27 08:17
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed by crazyk07** 2020-05-27 08:17 UTC
Labels: Member Search, P1, Test Env, tcx_Assigned, tcx_ReadyForReview, v5-intgration-sub-code

**Comment by narekcat** [comment] 2020-05-27 13:12
@sushilshinde @SathyaJayabal @lakshmiathreya - Will you give me compensation for my efforts?

**Comment by sushilshinde** [comment] 2020-05-28 11:03
@narekcat $50 was for the full fix

**Comment by narekcat** [comment] 2020-05-28 11:31
@sushilshinde Ok
