### ISSUE TITLE
New Nav - "Challenges" navigation not working from Profile Page

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#2401] opened 2019-06-03 18:24 UTC
Describe the bug

"Challenges" navigation not working from any of the member profile or settings pages

To Reproduce

Go to https://test-community-app.topcoder-dev.com/members/TonyJ
Click on WORK > Compete > All Challenges
Challenge page doesn't load, this is an issue is consistent for most of the navigation links present on the page
![image](https://user-images.githubusercontent.com/47536078/58824921-1dcc0300-85f2-11e9-9aef-f2ac91e3b805.png)

Expected behavior
The respective target page should be loaded.

Desktop:

OS: Mac
Chrome

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by luizrrodrigues** [comment] 2019-06-07 17:37
@Oanh-and-only-Oanh This is Duplicate of #2395

**Comment by luizrrodrigues** [comment] 2019-06-07 17:38
Duplicate of #2395

**Closed** 2019-06-07 17:53 UTC
Labels: Navigation, P2
