### ISSUE TITLE
New Nav- "Settings" page not working 

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/community-app#2402] opened 2019-06-03 19:15 UTC
**Describe the bug**
"Settings" navigation not working from member profile dropdown menu

**To Reproduce**
1. Go to https://test-community-app.topcoder-dev.com/members/TonyJ
2. Click on "settings"
![image](https://user-images.githubusercontent.com/47536078/58827940-1cea9f80-85f9-11e9-9de5-16d3ef12d049.png)
3. See error. Settings page doesn't load, this is an issue is consistent for most of the navigation links present on the page

**Expected behavior**
The respective target page should be loaded.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by luizrrodrigues** [comment] 2019-06-07 17:21
@Oanh-and-only-Oanh 
This is related to #2401

**Comment by luizrrodrigues** [comment] 2019-06-07 17:53
Duplicate of #2395

**Closed by luizrrodrigues** 2019-06-07 17:53 UTC
Labels: Navigation, P2
