### ISSUE TITLE
Can't open Payments page

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/community-app#2425] opened 2019-06-07 17:53 UTC
### Reproduction Steps: ###

1. Open https://test-community-app.topcoder-dev.com/challenges
2. Login with account: dan_developer/dantopcoder123
3. Try to click on arrow beside avatar 
4. Click on Payments item and observe result

### Expected Result: ###
Direct to Payments page without any Error.

### Actual Result: ###
Show error page with message "502 error occurred"

### Screenshots or screencast: ###

See comment

### Browser Information: ###

Google Chrome 74.0 on Windows 10

**Comment by HongHT** [comment] 2019-06-07 18:42
![2](https://user-images.githubusercontent.com/26895101/59126204-abab4380-898e-11e9-8adf-5ec8f7a94305.png)

**Comment by nithyaasworld** [comment] 2019-06-09 19:10
Duplicate of https://github.com/topcoder-platform/community-app/issues/2425

**Closed by nithyaasworld** 2019-06-09 19:10 UTC
Labels: Bug Hunt, Navigation
