### ISSUE TITLE
number of submissions tab only display for PAST challenges?

### ISSUE THREAD

**Issue by iversonLv** [topcoder-platform/community-app#411] opened 2017-08-29 21:03 UTC
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges/30058983/?type=develop
(check live website: http://community-app.topcoder.com/challenges/30058983/?type=develop)

Actual Result(s)
-----------------------------------------------------------------
- There is no submission tab display for ongoing challenge
but display for past challenge (e.g. http://community-app.topcoder.com/challenges/30059069/?type=develop)

Expected Result(s)
-----------------------------------------------------------------
- No matter what phases challenge, should display submission tab
Is it new feature for topcoder website?

Environment
-----------------------------------------------------------------
- **Device(s):** Desktop PC
- **Operating System:** Windows 10 64bit
- **Browser(s):** Version 60.0.3112.113 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![image](https://user-images.githubusercontent.com/4952611/29844006-6e1bbb04-8d40-11e7-857e-385f72128caf.png)

**Comment by birdofpreyru** [comment] 2017-09-06 15:28
@ajefts Here I see an inconsistency in the backend, at least in case of active F2F challenges:
- `numSubmissions` field in `v3` api response counts all submissions (including those that have not been reviewed yet);
- `submissions` array in `v2` response seems to include only those submissions that have been reviewed already.

These should be update to behave consistently, depending on whether we want to show / hide details about submissions that have not been reviewed yet.

**Comment by ajefts** [comment] 2017-09-08 15:02
@birdofpreyru We should be showing the full count of submissions regardless of if they have been reviewed or not yet. I checked a couple challenges on prod and v3 seems like it's right.  Do you see a current challenge that has a discrepancy?

**Comment by birdofpreyru** [comment] 2017-09-08 15:27
@ajefts Yes, e.g. http://local.topcoder.com/challenges/30059106

**Comment by birdofpreyru** [comment] 2018-01-06 21:06
UPD: The issue is not visible anymore in prod, as it was leveraged with data from v2 api, but the api issue, preventing the correct fix with only v3 api, is still there.

**Comment by nithyaasworld** [comment] 2019-06-12 17:01
Its not an issue anymore. Hence closing this.

**Closed by nithyaasworld** 2019-06-12 17:01 UTC
Labels: API-related, Challenge Details
