### ISSUE TITLE
Work menu display the sub-menus of Compete, Tracks or Community

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/community-app#2535] opened 2019-06-07 23:22 UTC
https://www.screencast.com/t/UsLrr9LBqrZ3

1. Open the application https://test-community-app.topcoder-dev.com/challenges
2. Login as dan_developer (Landscape)
3. Tap Menu > Work > Tracks (You can see sub items Competitive programming, Data Science, Design, Development and QA)
4. Go to Portrait view
5. Tap Menu

**Actual:** Work menu display the sub-menus of Compete, Tracks or Community

**Expected:** Should not display the sub-menus of Compete, Tracks or Community

**Reproducibility Rate:** 3/3

**Environment:** iPad Air 2, iOS 12.2

**Browser:** Safari 12

**Comment by nithyaasworld** [comment] 2019-06-10 11:30
duplicate of #2530

**Closed by nithyaasworld** 2019-06-10 11:30 UTC
Labels: Bug Hunt, Functional, Navigation, P2, nav_BugAccepted
