### ISSUE TITLE
[$50] Stalled challenge issue

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/community-app#4161] opened 2020-04-02 10:51 UTC
https://www.topcoder.com/challenges/30117605 is not stalled 

but listing https://www.topcoder.com/challenges

shows it as Stalled 

![Topcoder Challenges 2020-04-02 16-17-46](https://user-images.githubusercontent.com/683231/78241141-8ed39400-74fd-11ea-9860-b430dd9d7116.png)

Please fix and PR to the `listing-fix` branch, this is P0 please submit in 4 hours.

https://github.com/topcoder-platform/community-app/tree/listing-fix

**Comment by sushilshinde** [comment] 2020-04-02 10:53
@topcoder-platform/topcodercompetitors

**Comment by crazyk07** [comment] 2020-04-02 10:55
Contest https://www.topcoder.com/challenges/30121580 has been created for this ticket.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-04-02 10:56
Contest https://www.topcoder.com/challenges/30121580 has been updated - it has been assigned to rashmi73.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by sushilshinde** [comment] 2020-04-02 14:46
@rashmi73 any solution? 4 hours over

**Comment by rashmi73** [comment] 2020-04-02 14:51
@sushilshinde sometime actively on it, mainly its a backend side issues, where phases are being on details page and not on listing page

**Comment by sushilshinde** [comment] 2020-04-02 14:56
https://api.topcoder.com/v4/challenges/?filter=id%3D30117605

this is returning the phases, which is a listing call not details

**Comment by rashmi73** [comment] 2020-04-02 14:58
@sushilshinde solved

**Comment by sushilshinde** [comment] 2020-04-02 14:59
@LieutenantRoger please review

**Comment by LieutenantRoger** [comment] 2020-04-02 15:02
Hi @rashmi73  where's the PR ?

**Comment by rashmi73** [comment] 2020-04-02 15:02
@LieutenantRoger raising just 2 minutes

**Comment by rashmi73** [comment] 2020-04-02 15:06
@LieutenantRoger PR https://github.com/topcoder-platform/community-app/pull/4163

**Comment by LieutenantRoger** [comment] 2020-04-02 15:54
![image](https://user-images.githubusercontent.com/2875203/78270341-48058e80-753d-11ea-96f1-f96c9748f14e.png)

Thanks, the issue is not presented now.

**Comment by sandhiyakavi** [comment] 2020-04-03 04:34
Verified in Beta as well in Prod,working as Expected in both Environment.

<img width="953" alt="challenge_stalled_check" src="https://user-images.githubusercontent.com/55895538/78324397-3dc1af80-7592-11ea-9e77-dd9715bfea09.PNG">

Prod Environment:

<img width="945" alt="challenge_stalled_prod" src="https://user-images.githubusercontent.com/55895538/78324406-43b79080-7592-11ea-917a-c918fc703728.PNG">

**Comment by SathyaJayabal** [comment] 2020-04-10 04:15
verified on beta
<img width="1440" alt="Screenshot 2020-04-10 at 9 45 07 AM" src="https://user-images.githubusercontent.com/58783823/78961715-0ada6700-7b10-11ea-91cd-a188f9c1b2e9.png">

**Comment by Jobee1** [comment] 2020-04-13 15:27
**Verified on Beta Environment:**
![4161_beta](https://user-images.githubusercontent.com/48575864/79133297-81ef5400-7dcb-11ea-9dd8-3d40a51b886e.png)

**Comment by Jobee1** [comment] 2020-04-13 15:28
**Verified on Production environment:**
![4161_production](https://user-images.githubusercontent.com/48575864/79133325-903d7000-7dcb-11ea-9831-0dbc32d476ff.png)

**Comment by crazyk07** [comment] 2020-04-13 15:34
Payment failed: [500]: Failed to get billing detail for the project.<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-04-13 15:36
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Comment by crazyk07** [comment] 2020-04-15 13:30
This ticket was not processed for payment. If you would like to process it for payment, please reopen it, add the ```tcx_FixAccepted``` label, and then close it again<br/><br/>```This is an automated message for crazyk via Topcoder X```

**Closed by crazyk07** 2020-04-15 13:30 UTC

**Comment by rashmi73** [comment] 2020-06-17 01:29
@sushilshinde @crazyk07 I am unable to see this in pacts yet, can you please check it? sorry for reminding after 2 months
