### ISSUE TITLE
Unable to open Challenge - Conceptualise and Design the Data pipeline using spark

### ISSUE THREAD

**Issue by vasanthkumar22** [topcoder-platform/community-app#591] opened 2017-11-15 15:43 UTC
Unable to open Challenge - Conceptualise and Design the Data pipeline using spark

**Comment by guamacherox** [comment] 2017-11-15 16:08
Having the same problem with a Logo Design Challenge #30060376 
It says it doesn't exist!.

Taking a look into the chrome developer console i get this error message:

> Failed to load https://api.topcoder.com/v2/design/challenges/checkpoint/30060376: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.topcoder.com' is therefore not allowed access. The response had HTTP status code 502. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Steps to Repdroduce: 

- Login to your TC Account.
- Select any of your current active challenges.

This still happening if you access the challenge via URL.

**Comment by birdofpreyru** [comment] 2017-11-23 14:46
I believe, it was a temporary problem, caused by instability of the backend API, and should not be an issue anymore; thus closing this ticket for now.

**Closed by birdofpreyru** 2017-11-23 14:46 UTC
