### ISSUE TITLE
Sometimes landing on the zurich.topcoder.com/challenges page show no results

### ISSUE THREAD

**Issue by mtwomey** [topcoder-platform/community-app#3332] opened 2019-09-25 15:32 UTC
**Describe the bug**
Sometimes landing on the zurich.topcoder.com/challenges page show no results (when it should)

**To Reproduce**
1. Go to 'zurich.topcoder.com/challenges '

**Expected behavior**
See all the expected challenges

**Screenshots**
![screen_shot_2019-09-24_at_9 49 09_pm](https://user-images.githubusercontent.com/7715262/65615864-a85cb780-df7f-11e9-826f-2a0017b2d210.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Brave / Chrome / Safari
 - Latest

**Comment by sushilshinde** [comment] 2019-09-26 08:39
@mtwomey I couldn't replicate it

**Comment by mtwomey** [comment] 2019-09-26 14:12
@sushilshinde What do you think the best next step to fix it is?

**Comment by sushilshinde** [comment] 2019-09-26 16:54
I have asked @anonymousjaggu to look into on his end who already working on the other issue #3331, I will check with him tomorrow. It might be related to the same issue.

**Comment by nithyaasworld** [comment] 2019-10-03 10:17
@sushilshinde @mtwomey Tested on both production and beta env (where the fix of 3331 is deployed currently). I am not able to reproduce in both environments.

**Comment by sushilshinde** [comment] 2019-10-09 15:12
@nithyaasworld it was API issue now fixed 

https://github.com/appirio-tech/ap-challenge-microservice/issues/521

Please test on dev

**Comment by lakshmiathreya** [comment] 2019-10-13 02:00
The issue seems to be seen even now - needs multiple refreshes before the Zurich challenge is seen. Verified on Prod with multiple browsers. Please clarify if the fix has been moved to Prod yet.

**Comment by nithyaasworld** [comment] 2019-10-13 15:15
Yes, it's available on Production. For me, the challenges are just loading fine. 

Can you please try in a new incognito window and see if you are able to reproduce still?

For me, it was reproducible, when I accessed the Zurich challenges page after being idle for some hours(put the system for sleep for hours and then re-accessed).

I will test this scenario and update my results.

**Comment by nithyaasworld** [comment] 2019-10-13 18:39
Steps followed:

1. Logged in www.topcoder.com with my user and then accessed zurich.topcoder.com
2. It showed me 1 challenge
3. Put the computer to sleep for more than an hour **(This is Important step)**
4. When I opened, zurich.topcoder.com, it is stuck with a loading indicator (Screenshot:1)
5. I refreshed it. There was no loading indictor this time but has API failure icon (Screenshot:2)
6. Only on refreshing the third time, it showed me the challenge

![image](https://user-images.githubusercontent.com/5114190/66720146-b1baa080-ee16-11e9-9d39-8b9aed41911c.png)
![image](https://user-images.githubusercontent.com/5114190/66720151-c39c4380-ee16-11e9-8664-22109ebe51a7.png)

**Comment by sushilshinde** [comment] 2019-10-14 05:58
@nithyaasworld please open another issue with the steps that you mentioned because for the simple flow as per original issue desc I'm not able to reproduce issue.

@lakshmiathreya can you help with video or steps.

**Comment by nithyaasworld** [comment] 2019-10-16 13:40
Not able to reproduce by following the steps in the bug description.

Requesting @mtwomey to confirm once, so we can close this issue. Thanks.

https://github.com/topcoder-platform/community-app/issues/3397 has been logged to address the issue with challenge-loading when accessing the page after some idle time.

**Comment by Oanh-and-only-Oanh** [comment] 2019-10-16 16:06
@nithyaasworld, I'm not able to reproduce either. You can close this ticket since you've logged #3397. Thank you.

**Comment by lakshmiathreya** [comment] 2019-10-17 09:39
Verified on Prod and closing this Issue since #3397 has been logged.

**Closed by lakshmiathreya** 2019-10-17 09:39 UTC
Labels: Challenge Listing, Prod QA Pass, Zurich, hot-fix
