### ISSUE TITLE
edit icon is small to compare to delete

### ISSUE THREAD

**Issue by coderhacker** [topcoder-platform/community-app#5836] opened 2021-11-23 08:48 UTC
**Describe the bug**
Go to this url https://www.topcoder.com/settings/profile#hobbies

See edit icon is too small.

**To Reproduce**
1. Go to 'https://www.topcoder.com/settings/profile#hobbies'
2. see edit icon for issue

**Expected behavior**
Edit icon should be as per delete icon

**Screenshots**
![image](https://user-images.githubusercontent.com/62358241/142993973-4ca52475-94ea-443b-a71e-a70127dd2528.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] latest

**Comment by codejamtc** [comment] 2021-11-23 08:55
Duplicate of https://github.com/topcoder-platform/community-app/issues/5335

**Closed** 2021-11-23 08:55 UTC
Labels: UX, Prod Env
