### ISSUE TITLE
Final ranking should not be visible until the `REVIEW` phase is closed for the challenge

### ISSUE THREAD

**Issue by dushyantb** [topcoder-platform/community-app#3269] opened 2019-08-28 05:11 UTC
New `Submission` tab is showing `Final` ranking of the members before the `Review` phase is closed, which should not be the case.
It should be `masked` like we do with the `final score`

<img width="1680" alt="Screenshot 2019-08-28 at 10 37 14 AM" src="https://user-images.githubusercontent.com/1861713/63827297-3bee9880-c980-11e9-9987-0720c0f08c25.png">

**Comment by nithyaasworld** [comment] 2019-09-01 18:42
Verified

![image](https://user-images.githubusercontent.com/5114190/64080254-8e78dd80-cd0f-11e9-875a-ee98b76f1653.png)

**Comment by nithyaasworld** [comment] 2019-09-10 09:11
@ThomasKranitsas @dushyantb @sushilshinde 

Final score is displayed as 0 for this challenge. Can you please check?

(When I checked the same challenges which I previously verified, they have the right score. Seems like the newly updated Final Scores are not updated correctly)

![image](https://user-images.githubusercontent.com/5114190/64600502-dc10dc80-d3d8-11e9-96c3-6128e1b136e4.png)

**Comment by nithyaasworld** [comment] 2019-10-07 01:50
Confirming that this is still an issue

![image](https://user-images.githubusercontent.com/5114190/66280122-df619000-e8d2-11e9-8fe4-cdb52e7225e9.png)

**Comment by codeMinter** [comment] 2019-10-17 06:43
@nithyaasworld @Oanh-and-only-Oanh this also looks like `Not a Bug` - just verified https://www.topcoder.com/challenges/30103195?tab=submissions

**Comment by codeMinter** [comment] 2019-10-22 06:45
@dushyantb did you had chance to check on this, as discussed the other day ? Do we want to move old challenges to new structure ?

**Comment by codeMinter** [comment] 2019-10-24 16:33
@dushyantb moving this to you as we need to take a call on how to handle this - kindly discuss with lazybaer as we talked over slack and feel free to tag me back, if you need my help to get this ahead once we have the decided approach.

**Comment by Oanh-and-only-Oanh** [comment] 2020-01-13 16:08
The visibility issue is fixed. But past challenge scores are not visible.
Awaiting decision on the approach whether we migrate all old challenges to new api response structure of we fix this in UI. Closing this as this issue is tracked by “https://github.com/topcoder-platform/community-app/issues/3392”

**Closed by Oanh-and-only-Oanh** 2020-01-13 16:08 UTC
Labels: P1
