### ISSUE TITLE
Issue in creating new account on Topcoder

### ISSUE THREAD

**Issue by NehaSharma02** [topcoder-platform/community-app#2313] opened 2019-04-16 21:54 UTC
After creating an account the verification link didn't go on the registered email to activate the account which shows the account had not created. 
If going back a step to fill them out again, it will not accept username and the email as the account had already been created. 

Also, please check if it is particularly with the UK region.

cc @ajefts

**Comment by ThomasKranitsas** [comment] 2019-04-17 07:24
@urwithat any idea if this is an issue with the API which isn't publishing the events on kafka or with the processor which isn't sending the emails?

**Comment by nithyaasworld** [comment] 2019-06-17 19:42
I tried to reproduce this using UK VPN. I am not able to reproduce the issue. I am receiving the Account Activation email immediately.

@NehaSharma02 Is this issue reproduce-able always at your side?

**Comment by nithyaasworld** [comment] 2019-06-26 19:26
As no clarification provided for a long time, closing this.

@NehaSharma02 Please feel free to re-open if this is still an issue.

**Closed by nithyaasworld** 2019-06-26 19:26 UTC
Labels: Need clarification
