### ISSUE TITLE
After click on profile arrow arrow, drop down drawer opens and arrow remains download direction

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/community-app#2448] opened 2019-06-07 18:16 UTC
**Describe the bug**

**To Reproduce**
1. Open https://test-community-app.topcoder-dev.com/challenges
2. Login with dan_developer
3. Click on logged in profile arrow i.e top right corner
4. Drawer window opened.
5. Arrow next to profile remains same.

**Expected behavior**
Upon click on profile arrow, after the drawer opens the arrow should change to upward.

**Screenshots**
![1](https://user-images.githubusercontent.com/51490878/59124782-33d51d00-897e-11e9-8b00-1e52e2e00ac7.PNG)

**Desktop (please complete the following information):**
Device: Computer
OS: Windows 10
Browser : Chrome Version 75.0.3770.80 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment] 2019-06-14 14:12
duplicate of https://github.com/topcoder-platform/community-app/issues/2436

**Closed by nithyaasworld** 2019-06-14 14:12 UTC
Labels: Bug Hunt
